### ISSUE TITLE
LaTeX: excessive whitespace since v4.4.0

### ISSUE THREAD

**Issue by rhssk** [sphinx-doc/sphinx#10158]
### Describe the bug

Hi,

I'm using Sphinx together with Breathe and Doxygen to generate LaTeX -> PDF documentation.

Since v4.4.0 I've noticed that undocumented variables/structure members have large amount of whitespace added below them.
Bisecting shows that this is caused by b23036570 (#9941).

HEAD (799385f55):
![4 x_HEAD](https://user-images.githubusercontent.com/14257984/152358894-16d07bf5-fb02-4377-a5d2-e6a9f0f10c2d.png)
With revert:
![4 x_revert_b23036570](https://user-images.githubusercontent.com/14257984/152358912-626f402b-5a8d-46d7-b112-765a27df04cf.png)

### How to Reproduce

Input RST:
```rst
.. cpp:class:: Data

   .. cpp:union:: @data

      .. cpp:var:: int a

      .. cpp:var:: double b
```
[MWE.zip](https://github.com/sphinx-doc/sphinx/files/7995216/MWE.zip)

### Your project

---

### OS

Linux

### Python version

3.10.2

### Sphinx version

v4.4.0

**Comment by jakobandersen** [comment]
It indeed looks excessive, but note that the layout is tuned for when you have documentation of the entities, e.g.,
```rst
.. cpp:class:: Data

   A class that models either this or that.

   .. cpp:union:: @data

      A nested union storing the data different in this and that.

      .. cpp:var:: int a

         If it models a this, then this member is valid.

      .. cpp:var:: double b

         If it models a that, then this member is valid.
```

@jfbu may be able to provide at bit more details in what is going on with the whitespace and may be doable.

**Comment by jfbu** [comment]
Hi thanks for report. In fact the problem caused by the commit you identified (#9941) had already been fixed at #10087 which I have now merged into 4.x, so whitespace will be better at 4.5.0:
![Capture d’écran 2022-02-14 à 20 58 39](https://user-images.githubusercontent.com/2589111/153937162-82e0df3c-eeaf-4d8a-9146-f3cdc7303809.png)

**Comment by jfbu** [comment]
Fixed at 6768577bd96053afd744ea1f229edbb287fd32d9

**Comment by rhssk** [comment]
Hi. I've applied the fix locally and it indeed improves the spacing issues but does not completely bring spacing back to the pre-v4.4.0 state.

Here's a comparison of v4.4.0, current HEAD (b8789b4) and the revert of b230365 (left-to-right):
![screenshot-2022-02-15_12-51-46](https://user-images.githubusercontent.com/14257984/154048077-9ddbc41f-4165-470b-973a-aba0b73378b8.png)

Nevertheless, this is good enough for me, so thanks for the fix.

**Comment by jfbu** [comment]
Thanks for the feedback and nice visual diff! Yes indeed the merge of #10087 is not a revert of https://github.com/sphinx-doc/sphinx/commit/b23036570c839337b90f86735da006b00ddb6731, and deliberately injects some more spacing for better grouping, see https://github.com/sphinx-doc/sphinx/pull/10087#issuecomment-1013695605.

Although there is no way to reproduce exactly former behaviour (which had quite a few issues, and the LaTeX code has been changed significantly), it might be that adding this to conf.py 
```
latex_elements = {
    'preamble': r'\setlength{\sphinxsignaturesep}{0pt}',
}
```
will mimick close enough. The default setting `\smallskipamount` rather than `0pt` is responsible for some extra vertical whitespace. It is very difficult to provide a customizable interface because Sphinx sticks to legacy situation that object descriptions are rendered using LaTeX `list/\item` syntax which in hindsight is not adapted for such things, in particular to get multiple such "labels" share a common description, which is what #10087 in particular is about.
