### ISSUE TITLE
importlib.metadata vs importlib-metadata

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#10157]
### Describe the bug

Commit 6c5c66bbb19cb2dcfdc25da97d4d839eec139db7 by @takluyver removed the dependency on _pkg_resources_. It prefers the third-party _importlib-metadata_ package over the stdlib _importlib.metadata_ module, even if the Python version provides the latter (which is the case since 3.8). The Sphinx `setup.py` specifies _importlib-metadata_ as a dependency for Python 3.10.

This poses a problem when using Sphinx 4.4.0 with the rinoh builder. rinohtype only [falls back to using _importlib-metadata_ if _importlib.metadata_ is not available](https://github.com/brechtm/rinohtype/blob/744a3b76777257114df93d2d3a1c441552f17bc0/src/rinoh/resource.py#L13-L16). So, when using Python 3.8 or 3.9, rinohtype will create a _DynamicRinohDistribution_ instance which inherits from _importlib.metadata.Distribution_, while Sphinx will be using _importlib-metadata_, which expects _Distribution_ instances to have a __normalized_name_ attribute and this crashes on encountering the _DynamicRinohDistribution_ ([test log](https://github.com/brechtm/rinohtype/runs/4898691532?check_suite_focus=true)).

Is there any particular reason Sphinx does not prefer to use the _importlib.metadata_ included with Python? If that is the case, can you suggest an approach to fix this issue. Personally, I don't see one yet.

Thanks!

### How to Reproduce

```
$ git clone https://github.com/brechtm/rinohtype.git
$ cd rinohtype
$ poetry install
$ nox -s "unit_sphinx(sphinx='4.4.0')"
```

### Your project

https://github.com/brechtm/rinohtype

### OS

any

### Python version

3.9.9

### Sphinx version

4.4.0

### Sphinx extensions

rinohtype

**Comment by astrojuanlu** [comment]
If I understand correctly, the solution would be to switch

https://github.com/sphinx-doc/sphinx/blob/3b01fbe2adf3077cad5c2cf345c6d000d429d7ac/sphinx/registry.py#L25-L28

for

```python
try:
    from importlib.metadata import entry_points
except ImportError:  # Python < 3.10 (backport)
    from importlib_metadata import entry_points
```

?

**Comment by brechtm** [comment]
@astrojuanlu Yes, that would be a solution. I feel it makes sense to use the Python-provided module if it's available and only use _importlib-metadata_ as a fallback. However, perhaps @takluyver had a good reason to not do that.

**Comment by takluyver** [comment]
The `importlib.metadata` API changed in 3.10 (see [*compatibility note* in the docs](https://docs.python.org/3/library/importlib.metadata.html#entry-points)). I used the new API, because it seems fairly clear from the docs and the deprecation warnings that the intent is to get rid of the old way in a couple of Python versions. But using the new API means the backport has to be used for Python 3.8 & 3.9.

So if you want to change the preference around in Sphinx, you'll also have to port the code loading the entry points back to the deprecated API, and then at some point in a couple of years someone will have to switch it back again. It's pretty trivial to actually make either change, though.

**Comment by brechtm** [comment]
@takluyver That makes sense as well, of course. I'd prefer not to make the Sphinx code less future-proof of course.

I hope you don't mind me pinging you, @jaraco. But perhaps you have an idea on how to best handle this issue:
* one package defaults to using _importlib.metadata_, and subclasses its Distribution class (which doesn't yet have the `_normalized_name` attribute)
* another package defaults to using a recent _importlib-metadata_ which expects a `_normalized_name` attribute in the _Distribution_ instance

I know it's not a proper solution, but I'm considering just adding the `_normalized_name` property myself as a quick fix.

EDIT: I guess what matters here is whether _importlib.metadata_ and _importlib-metadata_ are backwards or forwards compatible. If older versions are happy with _Distribution_ instances from newer versions (the other way around is obviously not working), perhaps I can use just _importlib-metadata_ (when available)?

**Comment by brechtm** [comment]
My first basic tests with importing _importlib-metadata_ if it's available seem to indicate that it's _Distribution_ class is backwards compatible. i.e. the instance of my subclass is happily accepted by Python 3.9's _importlib.metadata_'s _distributions_ and _entry_points_.

I'll change rinohtype to import _importlib-metadata_ if it's available.

**Comment by jaraco** [comment]
If you have a choice between using the older entry points API and the new one, I'd definitely recommend going with the new one where possible. I'm okay with a custom Distribution supplying its own `_normalized_name` to satisfy the interface for forward compatibility. I don't know if rinohtype could consider unconditionally requiring `importlib_metadata; python_version<"3.9"`, but if so that should most simply provide compatibility. It sounds like you have  pretty good handle on the issue and have good options moving forward. Sorry for the inconvenience.

**Comment by brechtm** [comment]
@jaraco Supplying my own `_normalized_name` turned out not to be an option because other things were missing as well. The current approach of making use of _importlib-metadata_ when it's available seems to working well so far.

The importlib-metadata docs currently say "_Users are encouraged to use the Python standard library where suitable and fall back to this library for future compatibility_". My experience seems to suggest that this might not be the best approach. I couldn't find any other information about backwards/forwards compatibility. Please consider adding some information regarding this.
