### ISSUE TITLE
Add ability to suppress warning log messages from extensions

### ISSUE THREAD

**Issue by jantman** [sphinx-doc/sphinx#10219]
**Is your feature request related to a problem? Please describe.**

I'm using https://github.com/tox-dev/sphinx-autodoc-typehints in one of my builds. Because of an issue in third-party code outside of my control, it's unable to resolve a single forward reference in my code, and [logs a warning message](https://github.com/tox-dev/sphinx-autodoc-typehints/blob/aa345ca0475dbe8f4da7f4c7c56832c8d8e6884a/src/sphinx_autodoc_typehints/__init__.py#L354) to that effect:

    Cannot resolve forward reference in type annotations of "myapp.main.app": name 'FlaskClient' is not defined

This message is logged by the extension via the ``.warning()`` method of a ``SphinxLoggerAdapter`` (as per the Sphinx Logging API docs).

I usually run my build with ``-W`` to convert warnings to errors. However, I can't find any way to suppress this one warning, so the only way to get my build to work is by removing the (very helpful) ``-W`` option.

**Describe the solution you'd like**

I'd like some way to suppress warning log messages, based on something like a regex of the message and/or arguments.

**Describe alternatives you've considered**

At the moment, I'm working around this by adding a very ugly snippet to ``conf.py`` that iterates over the logging handlers, removes ``WarningIsErrorFilter`` from them if present, injects a filter to ignore this specific log message, and then adds back the ``WarningIsErrorFilter`` if it was present.

**Comment by tk0miya** [comment]
Our logging module has already provided `type` and `subtype` arguments for extensions to suppress arbitrary warnings by users.
https://www.sphinx-doc.org/en/master/extdev/logging.html#sphinx.util.logging.SphinxLoggerAdapter.warning

So it would be better to give `type` and `subtype` to the warning on sphinx-autodoc-typehints side.

**Comment by jantman** [comment]
That certainly may be the case, and I can open an issue or PR against that extension, but as it stands right now there's no way for a end-user to suppress warnings like this until the upstream plugin authors add type and subtype...

**Comment by picnixz** [comment]
There is one way to do it (and this is how I do it):

- List the extensions you want to suppress the warnings of. 
- Create a `logging.Filter` object filtering the messages you want to filter.
- Create an extension which is loaded *after* the extension to be silenced. This extension does the following:
  - For all extensions to be filtered, extract the extension module exposed by `app.extensions[name].module`.
  - Find instances of `SphinxLoggerAdapter` using `inspect.getmembers` and add the filter object to the underlying logger via `adapter.logger.addFilter`.

I can make a PR adding this feature since I have most of the things already done.

**Comment by chrisjsewell** [comment]
Closing this,
since there is already the [suppress_warnings](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings) feature for this,
plus I also added [show_warning_types](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-show_warning_types), to make this even easier for users to identify warning types,
and improved typing for the warning method, to make it easier for extension developers (#12154)

> as it stands right now there's no way for a end-user to suppress warnings like this until the upstream plugin authors add type and subtype

yes, I think should be the encouraged way;
if users start monkey-patching extensions to "make them work properly", rather than pushing for the extensions to be fixed, I don't think that is helpful
