### ISSUE TITLE
Doc: Indicate outdated version

### ISSUE THREAD

**Issue by buhtz** [sphinx-doc/sphinx#10229]
https://www.sphinx-doc.org should indicate that the shown page is outdated when using an earlier sphinx version.

Example:
I found that piece of docu via DuckDuckGo.com
https://www.sphinx-doc.org/en/1.5.1/tutorial.html

For new users it is unclear that 1.5.1 is outdated.

I would recommend a colored box on top of each page showing a version different from current stable/release.

**Comment by tk0miya** [comment]
Agreed. It's better to show it. Please let me know the way to indicate it.

**Comment by SilverRainZ** [comment]
Now (2023) it seems that sphinx documentation [only has the master version](https://readthedocs.org/projects/sphinx/), and this issue may no longer be valid?

**Comment by picnixz** [comment]
@SilverRainZ thank you for pointing this (there are so many issues that are under the radar so I'm really glad that someone is willing to check those like you). 

Since we don't support older versions, I'll close this issue. If you want to improve our doc to say that we only support the latest versions (I'm not sure we explicitly state it), feel free to open a PR for that.
