### ISSUE TITLE
Setting short titles (list entry) in LaTeX `\caption[short title]` output to be picked up by `\listoffigures` or `\listoftables`

### ISSUE THREAD

**Issue by michaelosthege** [sphinx-doc/sphinx#10540]
# Problem

I'm trying to include a **list of figures** and a **list of tables** in my dissertation built with the JupyterBook/MyST/Sphinx/LaTeX toolchain.

The list can be generated with the `\listoffigures` raw LaTeX command, but it takes the full caption content.

With the current versions of MyST and Sphinx it looks like there's no way to set the `\caption[Short title]{...}` which would be picked up by `\listoffigures`.

See [`\caption` documentation](https://mirror.clientvps.com/CTAN/macros/latex/contrib/caption/caption.pdf), see Chapter 3.1. and [documentation of the MyST/RST figure directive](https://jupyterbook.org/en/stable/content/figures.html#figure-parameters).

# Desired solution
A keyword parameter that is passed from figure/table/code directives to the final generation of the TeX sources.

# Implementation
I found a [relevant comment](https://github.com/sphinx-doc/sphinx/pull/5630/files#r233339740) by @jfbu in a Sphinx PR from 2018 which mentions `\listoffigures` in the context of captions.

I'm having trouble to find the line of code on current `master` where a change would be needed.

Generally, the route of information flow from the MyST figure directive through the Sphinx AST into the generated TeX code is still a mystery for me.

**It would be great if someone could point me to lines of code** in the relevant projects (Sphinx and MyST parser?) where I could add support for a `short_title` or `list_entry` kwarg.

# Alternatives
* Post-processing the TeX output with a `re.sub` find & replace. __Where could I hook something like that into the build process??__
* Replacing all my MyST figure, table and code-block directives with raw LaTeX 😬

**Comment by jfbu** [comment]
Here is what Sphinx LaTeX writer does on visiting a `caption` node:
https://github.com/sphinx-doc/sphinx/blob/c40bb7281ec26c833aa7e0f792f063b2d2254ec7/sphinx/writers/latex.py#L1323-L1332
There is no provision for `\caption[short]{long}` syntax, as it stands currently.

So, this might be a feature request first at MyST to add an option to their figure directive. Sphinx could perhaps support the new type of node, but it might more be the job of an extension if this is purely LaTeX rendering oriented and has no equivalent in other builders. And probably it could be envisioned only if [DocUtils reStructuredText](https://docutils.sourceforge.io/docs/ref/rst/directives.html) had it too.  Not sure if MyST does things not already supported in DocUtils reStructuredText.

One (very) hacky way from the Python side, if using DocUtils reStructuredText [figure directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure) would be to exploit its notion of a `legend`.  An extension would then overwriter the Sphinx own handling of `caption` and `legend` in order to convert the `legend` (counter-intuitively as it may be multi-paragraph contents) into the "short caption".  Or perhaps use `caption` as the short one and `legend` as the real one.  But this is admittedly convoluted, no idea if this is feasible via the MyST.

The optional argument "short caption"  to LaTeX `\caption` is only optional.  If there is a way in MyST to pass raw LaTeX then a pure LaTeX way is possible.  Assuming that it is possible to customize the LaTeX preamble from MyST as it is with Sphinx (I don't know).  The raw LaTeX would convey the message via a dedicated macro "hey, next time use `bla bla bla` as short caption" and the `\caption` macro would have been redefined to check if such a thing happened and then set the short caption accordingly.  In a Sphinx project this is feasible with suitable LaTeX configuration in [`latex_elements`](https://www.sphinx-doc.org/en/master/latex.html#the-latex-elements-configuration-setting)`['preamble']` from `conf.py`.

**Comment by michaelosthege** [comment]
Thank you for the response! This makes is a little clearer at the Sphinx end.

However, I didn't find a corresponding place in MyST-parser Python code where the caption node is created. Maybe @chrisjsewell can point me to a line of code?

I'd gladly make PRs in docutils, Sphinx, MyST-parser once I can get something to work locally. Heck even an extension if need be.
At this point I just don't have a clue where to place my cursor.

**Comment by jfbu** [comment]
Proof of concept:
![Capture d’écran 2022-06-19 à 17 12 23](https://user-images.githubusercontent.com/2589111/174487965-cac7c68d-36bb-4f2e-a8a3-2b9f8dda334d.png)

In `conf.py`:
```
latex_elements = {
    'tableofcontents': r"""
\sphinxtableofcontents
\listoffigures
""",
    'preamble' : r"""
\AtBeginDocument{% delay for maximal safety
    \newcommand\originalcaption{}% make sure  name does not exist
    \let\originalcaption\caption
    \let\caption\myhackedcaption
}%
\newcommand\myhackedcaption{}% make sure  name does not exist
\newcommand\setupshortcaption{}%       idem
\newcommand\singleusageshortcaption{}% idem
\newcommand\myshortcaptiontrue{}%      idem
%
% define the apparatus to replace \caption
%
\newif\ifmyshortcaption
\def\setupshortcaption#1{\def\singleusageshortcaption{#1}%
                             \global\myshortcaptiontrue}%
\makeatletter
\def\myhackedcaption{% replacement for \caption
    \ifmyshortcaption\global\myshortcaptionfalse\expandafter
    \@firstoftwo\else\expandafter\@secondoftwo\fi
    {\originalcaption[\singleusageshortcaption]}%
    {\originalcaption}%
}%
\makeatother
""",
}
```

Also I am using
```
latex_theme = 'howto'
```
else the LaTeX `\chapter` commands insert mandatory hardcoded extra vertical space in the list of figures, the figure number is reset at each chapter, but there is no "chapter <N>" in the list of figures, of course people in LaTeX world have tons of package to influence that, but I never cared much so I don't know off hand.

Then the mark-up is like this:

`````
```{raw} latex
\setupshortcaption{I am a short caption}
```
`````

`````
```{figure} img/fun-fish.png
:alt: fishy
:class: bg-primary
:width: 200px
:align: center

I am the caption of this image
```
`````

In fact I am using here the MyST syntax, but the approach is not at all MyST related it works generally speaking in Sphinx as long as you have some syntax to insert raw LaTeX code at the right place in the document.

Project:
[testMyST.zip](https://github.com/sphinx-doc/sphinx/files/8935822/testMyST.zip)

**Comment by michaelosthege** [comment]
Thanks a lot @jfbu!
I would never have come up with this LaTeX hack myself, but reading this (on the phone, in the train) I think I understand what it does.
This will definitely help me (and probably also @schmoelder) to get our theses over the finish line!

In the interest of sustainability I would follow up with a proper feature implementation in MyST/docutils/Sphinx -- once I hopefully/eventually understand where to contribute such changes.

**Comment by jfbu** [comment]
@michaelosthege In LaTeX the notion of short caption is not limited to tables and figures.  It also applies to sectioning titles.  As far as I can see neither Markdown (of course, as its original flavor as well as CommonMark do not even have the support of captions for figures to start with) nor [DocUtils reStructuredText](https://docutils.sourceforge.io/rst.html) have a support for "short captions", be it for sectioning titles or for tables or for figures or for code-blocks.  The logical way seems to be to raise this at [DocUtils](https://sourceforge.net/projects/docutils/).  Notice that [DocUtils tools command line options](https://docutils.sourceforge.io/docs/user/config.html#configuration-file-sections-entries)  do not even mention "lists of figures", only "tables of contents";  same for [the rst directives reference](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents).

**Comment by jfbu** [comment]
I expect it is not priority of Sphinx to provide builder-specific enhancements.  Even things requiring somewhat substantial effort on LaTeX side, such as indices compatible with Unicode are motivated by existing mark-up (the ``:index:`` role and ``.. index::`` directive) which influences as well HTML builds at least.  So this should be implemented by way of an extension.  I will wait a while but plan on closing this as "wontfix" (as long as DocUtils stays as it is in this regard).

**Comment by jfbu** [comment]
For the record the method at https://github.com/sphinx-doc/sphinx/issues/10540#issuecomment-1159757219 is not officialy endorsed nor coming with any support... In particular Sphinx manages to authorize captioned figures in table cells and when the table is using `tabulary` a special `\sphinxfigcaption` is used 

https://github.com/sphinx-doc/sphinx/blob/1786e989ca16cac8f9d8a966a481d983d3b23f9c/sphinx/texinputs/sphinxlatexgraphics.sty#L114-L117

and there `\spx@originalcaption`  will refer to the `\caption` before the preamble hack from above cited comment, because `sphinx` issues `\AtBeginDocument` first, before the user hack. So I guess (untested) `\def\spx@originalcaption{\myhackedcaption}` should be added in the "at begin document".  There might be a few other corner cases, cf

https://github.com/sphinx-doc/sphinx/blob/1786e989ca16cac8f9d8a966a481d983d3b23f9c/sphinx/writers/latex.py#L1323-L1332
 
for mark-up.  And also the table templates.

Most of the above ultimately (like `\captionof`) uses `\caption`, so it might work generally speaking for things with captions, however this is untested and it would require me some time to go through all cases.
