### ISSUE TITLE
docutils language importer warning

### ISSUE THREAD

**Issue by kazanzhy** [sphinx-doc/sphinx#10669]
### Describe the bug

Related to #10179

My sphinx-build complains:
`xxx.rst:: WARNING: rST localisation for language "uk" not found.`

Also it doesn't work for `uk_UA`

### How to Reproduce

```
$ git clone git@github.com/python/cpython.git
$ git clone git@github.com:python/python-docs-uk.git
$ cd cpython/Doc
$ make venv
$ mkdir -p locales/uk/LC_MESSAGES
$ cp -r ../../python-docs-uk/* locales/uk/LC_MESSAGES
$ make -e SPHINXOPTS="-D language='uk' -D gettext_compact=0 -W --keep-going" html
```

### Your project

https://github.com/python/python-docs-uk

### OS

Linux

### Python version

3.10

### Sphinx version

sphinx==4.5.0

**Comment by AA-Turner** [comment]
Hi @kazanzhy -- this isn't actually a bug, the Docutils project contains no localisation file for Ukranian. We would very much welcome one though -- if you're a native speaker, please would you be able to translate the file and submit it to https://sourceforge.net/p/docutils/patches/ ?

There are two places to translate:

- https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/languages/
- https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/parsers/rst/languages/

Thanks! I'm closing the issue here, but please do get in touch on the Docutils issue tracker.

A

**Comment by kazanzhy** [comment]
I already did the translation. Would you like to help me to move these changes to Sourceforge?
https://github.com/kazanzhy/docutils/pull/1

**Comment by AA-Turner** [comment]
Amazing, thank you! I'll pick this up.

A
