### ISSUE TITLE
New version of sphinx makes troubles in openTURNS doc

### ISSUE THREAD

**Issue by m-balesdent** [sphinx-doc/sphinx#10918]
### Describe the bug

Hi, 

We added the newest version of sphinx in openTURNS. After the compilation, it causes several troubles in the indentation of the methods (see screenshots, or [here](https://openturns.github.io/openturns/latest/user_manual/integration.html) ).

Maybe there is something to configure to use this  new version (5.2.3) ?

Thanks for your help!

Mathieu

### How to Reproduce

see openTURNS [github page](https://github.com/openturns/openturns)

### Your project

openTURNS

### Screenshots

![image](https://user-images.githubusercontent.com/26813843/195789295-2da7cc0b-860b-44ed-92cb-6eff0cafa206.png)

### OS

linux

### Python version

3.10

### Sphinx version

latest (5.2.3)

**Comment by jschueller** [comment]
looks like this started to appear since sphinx 5.0.x, and 4.5.0 is good

**Comment by jfbu** [comment]
Hi, afaict the indentation is in fact a CSS centering due to `table.align-default` being present in the css class mark-up (from file basic.css):
```
table.align-default {
    margin-left: auto;
    margin-right: auto;
}
```
This seems to not have been modified for last 4 years (see #6341), what was your last Sphinx version without this?

You can [override the CSS styling](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html). If i use the Firefox CSS inspector to remove the above `margin-left` setting all tables end-up left aligned.

But of course it would better to understand what changed..
Perhaps the explanation is that all rows were part of a single table in html output and now multiple tables are used?

**Comment by jschueller** [comment]
it might be just that: the classes in the same toctree have the same indent
