### ISSUE TITLE
Broken link - anchor not found

### ISSUE THREAD

**Issue by simonwright-jbarisk** [sphinx-doc/sphinx#10985]
### Describe the bug

I'm trying to use an external URL in some documentation:

```
into it using the `FillBurn <https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#fillburn>`_ method.
```

However, when I use linkcheck to check the external links are working I'm getting the following error:

```
WARNING: broken link: https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#fillburn (Anchor 'fillburn' not found)
```

Is this a bug or is there a workaround available?

### Environment Information

Sphinx                        3.5.4 sphinx-argparse               0.3.1 sphinx-rtd-theme              1.0.0 sphinxcontrib-applehelp       1.0.2 sphinxcontrib-devhelp         1.0.2 sphinxcontrib-htmlhelp        2.0.0 sphinxcontrib-jsmath          1.0.1 sphinxcontrib-programoutput   0.17 sphinxcontrib-qthelp          1.0.3 sphinxcontrib-serializinghtml 1.1.5sphinxcontrib-websupport      1.2.4

**Comment by francoisfreitag** [comment]
I get the following output:
```
(           index: line    6) ok        https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#fillburn
build succeeded.
```

with:
```
alabaster==0.7.12
Babel==2.11.0
certifi==2022.9.24
charset-normalizer==2.1.1
docutils==0.16
idna==3.4
imagesize==1.4.1
Jinja2==2.11.3
MarkupSafe==1.1.1
packaging==21.3
Pygments==2.13.0
pyparsing==3.0.9
pytz==2022.6
requests==2.28.1
snowballstemmer==2.2.0
Sphinx==3.5.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
urllib3==1.26.12
```

Is the build still broken for you?

**Comment by simonwright-jbarisk** [comment]
Hi.

I'm using Python 3.8.8 and have the following differences in my installed packages:

Babel==2.9.1
imagesize==1.3.0
Junja2=3.0.3
MarkupSafe==2.1.1
Pygments==2.13.0

And the URL isn't currently causing a broken link error.  But I have noticed it being an intermittent error.



Best wishes, Simon.

**Comment by francoisfreitag** [comment]
> And the URL isn't currently causing a broken link error. But I have noticed it being an intermittent error.

I believe that’s not something Sphinx can handle. It is possible the web server serves a different page that does not contain the anchor (maybe on deploy of a new version, maybe because of rate limiting, could be many reasons). Sphinx linkcheck only reports what it sees.

If the issue does not last long, you can try configuring [`linkcheck_retries`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_retries). If it’s longer, maybe try capuring the page that is served with a script that repeatedly fetches the page, check if the anchor is present and stop when it’s not. Otherwise, you can try getting in touch with the editor whiteboxgeo.com to see if they are aware of the issue, and maybe they can solve it.

**Comment by simonwright-jbarisk** [comment]
No problem.  Many thanks.
