### ISSUE TITLE
CI IS FAILING

### ISSUE THREAD

**Issue by danieleades** [sphinx-doc/sphinx#11034]
the continuous integration jobs are failing, which means PRs don't have proper feedback

#10995 goes some of the way to fixing these, but there are other issues.

How are CI-breaking changes being introduced? is a maintainer committing directly to `master` without creating a PR first?

**Comment by jfbu** [comment]
> the continuous integration jobs are failing, which means PRs don't have proper feedback

Yes

> 
> #10995 goes some of the way to fixing these, but there are other issues.
> 

I tried to use #10995 and deactivate the Python-3.12-dev at [my fork](https://github.com/jfbu/sphinx/tree/nopythondevCI) but encountered a CI issue with node.js, which is beyond my knowledge range. 

> How are CI-breaking changes being introduced? is a maintainer committing directly to `master` without creating a PR first?

You can check commits [there](https://github.com/sphinx-doc/sphinx/commits/master). There has been only two since the first commit to master with failing CI.

CI had started failing on all PRs due to issues your #10995 adressed, but resolved only partially.  It looks as if cd3f2e435000835dd98a11497440bc16a79ec31c was pushed to master directly but all new PRs were failing before, and old PRs would fail CI if tested now I think.

I deliberately merged the last two commits from PRs with failed CIs as I can't guarantee being active in maintenance and the PRs were about documentation and the CI failures were unrelated.

**Comment by jfbu** [comment]
> > #10995 goes some of the way to fixing these, but there are other issues.
> 
> I tried to use #10995 and deactivate the Python-3.12-dev at [my fork](https://github.com/jfbu/sphinx/tree/nopythondevCI) but encountered a CI issue with node.js, which is beyond my knowledge range.

Running the failed job now [succeeds](https://github.com/jfbu/sphinx/actions/runs/3586002772).

I triggered running all jobs again from merging 'master', and `du-latest` fail due to

> ERROR: git+https://repo.or.cz/docutils.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

It appears tox does not take into account the subdirectory setting from
https://github.com/sphinx-doc/sphinx/blob/d8977d3e5785b02adca5ee001b0d9cdcd6a22ef0/tox.ini#L26

When commit 33d65fbdaf0349530e4a6ae4eabcfdeab58bb51f was merged the testing (with tox `3.27.0`) then [succeeded](https://github.com/sphinx-doc/sphinx/actions/runs/3335941531/jobs/5520497007) with
```
du-latest create: /home/runner/work/sphinx/sphinx/.tox/du-latest
du-latest installdeps: git+https://repo.or.cz/docutils.git#subdirectory=docutils
```
in the test log, but at my branch [failed test](https://github.com/jfbu/sphinx/actions/runs/3712273463/jobs/6293625597) analogous log (with tox `4.0.11`) looks like
```
du-latest: install_deps> python -I -m pip install git+https://repo.or.cz/docutils.git
```
the subdirectory is not there.

**Comment by jfbu** [comment]
ah well, yes  `tox 4` parses `tox.ini` [differently](https://tox.wiki/en/latest/faq.html)

> The hash sign (#) now always acts as comment within tox.ini or setup.cfg tox configuration file. Where you need to pass on a # character you will need to escape it in form of \# so tox does not handle everything right of the # character as a comment.

**Comment by jfbu** [comment]
The #11035 was merged and now CI jobs complete, as #11035 incorporates #10995, fixes the `tox 4` `#` issue and **(provisorily) deactivates Python 3.12-dev** testing.

**Comment by jfbu** [comment]
Keeping this open until Python 3.12-dev testing issues get fixed.

**Comment by danieleades** [comment]
@jfbu it looks like a `.pre-commit-config.yaml` snuck in there in those last few commits.
#11033 would change that to something more useful

**Comment by jfbu** [comment]
> @jfbu it looks like a `.pre-commit-config.yaml` snuck in there in those last few commits. #11033 would change that to something more useful

Merged, thanks!

**Comment by jayaddison** [comment]
Linking #10989 as relevant for this (some `enum`-related test failures under Py3.12).  Hoping to take another look at that in the not-too-distant future (it may be a quick fix).
