### ISSUE TITLE
Documentation: favicon and logo variables not documented properly with 6.0.0 release

### ISSUE THREAD

**Issue by ViktorHaag** [sphinx-doc/sphinx#11062]
### Describe the bug

The [Deprecated APIs](https://www.sphinx-doc.org/en/master/extdev/deprecated.html#dev-deprecated-apis) documentation page still lists the removal of `favico` and `logo` variables in HTML templates as "TBD". However, they appear to have been removed for the 6.0.0 release as of PR #10562.

### How to Reproduce

Build docs with a template that has a conditional inclusion of the form:
```
        {%- if logo -%}
        . . .
        {%- endif -%}
```
With 5.3.0 this would still include the content in HTML output; with 6.0.0, the content is no longer included.

Switching the conditional inclusion to `{%- if logo_url -%}` with 6.0.0  makes the build correctly include the content in the output again.

### Environment Information

```text Platform:              darwin; (macOS-13.1-x86_64-i386-64bit) Python version:        3.11.1 (main, Dec  8 2022, 10:20:55) [Clang 14.0.0 (clang-1400.0.29.202)]) Python implementation: CPython Sphinx version:        6.0.0 Docutils version:      0.19 Jinja2 version:        3.1.2 ```

### Additional context

Deprecated APIs page needs an update to note that now `logo` and `favicon` have been removed in favour of `logo_url` and `favicon_url` as of 6.0.0.

**Comment by choldgraf** [comment]
Is there any chance we can go through a deprecation cycle for this? It would be helpful if there were a check for `html_logo` and `html_favicon` and throw a warning rather than just error in the HTML template.

**Comment by AA-Turner** [comment]
> Is there any chance we can go through a deprecation cycle for this? It would be helpful if there were a check for `html_logo` and `html_favicon` and throw a warning rather than just error in the HTML template.

Hi Chris, this was deprecated in Sphinx 4 (https://github.com/sphinx-doc/sphinx/pull/8737) and removed in Sphinx 6 -- this is the standard 2 release deprecation period for Sphinx.

A

**Comment by choldgraf** [comment]
Huh - I never noticed a warning in any of my builds. Maybe i just missed it.

**Comment by AA-Turner** [comment]
> I am also a bit confused - it's called logo_url but in my experience most people use a direct path instead of a URL. Is only a URL allowed now?
> 
> Edit: note to self / others: looks from the docs that the functionality is the exact same, just had URL in the variable name now

The better name perhaps would've been `logo_path` or `logo_uri`, but the change was to allow internet URLs to be specified as the logo / favicon, in addition to (rather than instead of) local relative paths.

A

**Comment by choldgraf** [comment]
Yeah - this is why I was confused. The deprecated name (html_logo) was more generic than the new name (html_logo_url) which is why I assumed the functionality had become more specific to URLs.

**Comment by 2bndy5** [comment]
> Huh - I never noticed a warning in any of my builds. Maybe i just missed it.

Same here, but I wouldn't have missed it since I use the switches `-E -W` to highlight these kind of discrepancies in my CI. Finding out that the name changed after the fact (deprecation warning never witnessed) is quite offsetting/inconvenient (wasted almost a half hour trying to track this down and address it downstream).

**Comment by jp-larose** [comment]
I just encountered this, specifically when using the *haiku* theme.  I haven't yet looked at other themes.

**Comment by 2bndy5** [comment]
>I just encountered this, specifically when using the haiku theme. I haven't yet looked at other themes.

@jp-larose Can you be more specific in what exactly you encountered? TBH, I think this should be a separate bug report.

The haiku theme uses `logo_url` in the layout.html template, although it does not get properly used because it checks the existence of the deprecated `logo` var or a theme-specific `theme_full_logo` var:
https://github.com/sphinx-doc/sphinx/blob/b88713e68e1f68b2f0add3a9bed9c4ddf3482e09/sphinx/themes/haiku/layout.html#L37-L44

The haiku theme also inherits from the basic theme layout.html which uses `favicon_url` as expected. https://github.com/sphinx-doc/sphinx/blob/b88713e68e1f68b2f0add3a9bed9c4ddf3482e09/sphinx/themes/basic/layout.html#L139-L141

**Comment by photoniker** [comment]
Dear all, 

is this bug releated to this issue? I define a html_logo = "_static/itomlogo.png". After the build you see such difference in the index.html file: 
![image](https://github.com/sphinx-doc/sphinx/assets/17592823/3a9e90ac-bc68-467d-b4ef-5754a645626e)

This *.png is missing in the website: 
![image](https://github.com/sphinx-doc/sphinx/assets/17592823/c8403a3a-94a3-45c1-a77c-b4c4ea42bc5f)
Which is at the to of the sidebar when build with Sphinx 5.
![image](https://github.com/sphinx-doc/sphinx/assets/17592823/875daf2f-58f2-4b6d-8e7d-6bf14b0a1704)

**Comment by 2bndy5** [comment]
@photoniker It may be related but probably more specific to whatever theme you're using. Contact the theme administrators to inquire about compensation for Sphinx' change from `logo` to `logo_url` in the theme's HTML template(s).

**Comment by photoniker** [comment]
@2bndy5 the MDL_theme is used here.

**Comment by 2bndy5** [comment]
@photoniker ok, but again you should take it up with the theme authors. I can't find that theme by googling "MDL_theme"...

**Comment by photoniker** [comment]
> @photoniker ok, but again you should take it up with the theme authors. I can't find that theme by googling "MDL_theme"...

FYI https://getmdl.io/
I will contact theme.

**Comment by AA-Turner** [comment]
> FYI [getmdl.io](https://getmdl.io/)
> I will contact theme.

This seems to be a link to Google's Material Design Lite overview page -- do you have a link to the Sphinx theme you're using?

A

**Comment by AA-Turner** [comment]
I can't see your `conf.py` or `theme.conf` files -- could you post a link to the directory with those and the documentation sources, please?

A

**Comment by photoniker** [comment]
> @photoniker the MDL that you keep calling a theme is not a sphinx theme. In fact, MDL is a CSS framework that is no longer maintained. What did you set `html_theme` in your conf.py file? I understand that itom-project/itom is a private repo.

@2bndy5 the itom project is a public repo which wwe currently move from bitbucket to GitHub. We used Sphinx for the whole Website that time. Since the last build Sphinx changed 2 major versions... And yes I also realized MDL is not maintained anymore. 
However I wanted to understand If that bug is Sphinx related. Anyway we have to change the Framework for the website. Acutally the doch itself is build by Sphinx and works well using the pydata theme.

**Comment by 2bndy5** [comment]
It is Sphinx _related_, but the bug is with the `html_theme` that you were using because it's HTML templates need updating...

**Comment by photoniker** [comment]
> It is Sphinx _related_, but the bug is with the `html_theme` that you were using because it's HTML templates need updating...

Whould you recommend the sphinx-material theme?

**Comment by 2bndy5** [comment]
Personally, no. I work on the [sphinx-immaterial theme](https://github.com/jbms/sphinx-immaterial/), so I'm rather biased. However, the [pydata theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) is ok for general usage. Many have turned to [furo](https://pradyunsg.me/furo/#) as a more modern theme instead of the [readthedocs theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/).
