### ISSUE TITLE
LaTeX: reST label before a ``module`` (or ``automodule``) sphinx.ext.autodoc directive causes pdf build to report multiply defined reference

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#11093]
### Describe the bug

As said in the title, the PDF build reports multiply-defined references.

### How to Reproduce

Use 
```
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

extensions = ['sphinx.ext.autodoc']
```

in `conf.py`

file `index.rst`:
```rest
Welcome to FOO's documentation!
===============================

.. toctree::

   testfile
```

file `testfile.rst`:
```rest
.. _somelabel:

.. module:: testmodule

Some title
==========

Some text.

.. autofunction:: foo
```

file `testmodule.py`
```python
"""not much here
"""

def foo():
    "I do not do much and simply return ``None``"

    return None

```
(the  autofunction part is not part of the problem).

Then run `make latexpdf`.

Console output ends with
```
Latexmk: ====List of undefined refs and citations:
  Label `testfile:somelabel' multiply defined
```

This is not a serious problem (meaning it does not cause build failure).

But it happens in real life, see https://github.com/numpy/numpy/issues/22930#issuecomment-1371989684 and the 
```
LaTeX Warning: Label `reference/maskedarray.generic:maskedarray-generic' multip
ly defined.
```
is an instance of the present issue.  I have not yet checked but expect the others reported there as well.

### Environment Information

```text
Platform:              darwin
Python version:        3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)])
Python implementation: CPython
Sphinx version:        6.2.0+/6e6b9ad45
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

### Sphinx extensions

```python
``["sphinx.ext.autodoc"]``
```

Edit: all NumPy instances from building their `numpy-ref.pdf` are of this nature: https://github.com/numpy/numpy/issues/22930#issuecomment-1372520387

**Comment by picnixz** [comment]
I investigated and probably located the issue in the `visit_target` method of the LaTeX builder:

https://github.com/sphinx-doc/sphinx/blob/b6e6805f80ad530231cf841e689498005cf2bb96/sphinx/writers/latex.py#L1495-L1503

With your example, the document is:

```xml
<document source="/home/picnix/any/sphinx/doc/testfile.rst">
    <target refid="somelabel">
    <target ids="module-testmodule somelabel" ismod="True" names="somelabel">
    <index entries="('pair',\ 'module;\ testmodule',\ 'module-testmodule',\ '',\ None)">
    <section docname="testfile" ids="some-title :doc" names="some\ title">
        <title>
            Some title
        <paragraph>
            Some text.
        <index entries="('single',\ 'foo()\ (in\ module\ testmodule)',\ 'testmodule.foo',\ '',\ None)">
        <desc classes="py function" desctype="function" domain="py" nocontentsentry="False" noindex="False" noindexentry="False" objtype="function">
            <desc_signature _toc_name="foo()" _toc_parts="('testmodule', 'foo')" class="" classes="sig sig-object sig sig-object py" fullname="foo" ids="testmodule.foo" module="testmodule">
                <desc_addname classes="sig-prename descclassname sig-prename descclassname" xml:space="preserve">
                    testmodule.
                <desc_name classes="sig-name descname sig-name descname" xml:space="preserve">
                    foo
                <desc_parameterlist xml:space="preserve">
            <desc_content>
                <paragraph>
                    I do not do much and simply return 
                    <literal>
                        None
```

The only nodes that are of interest are: 

```xml
<target refid="somelabel">
<target ids="module-testmodule somelabel" ismod="True" names="somelabel">
```

Those nodes are visited by `visit_target` but here is the issue:

- The first node branches on `node.get('refid')` and ignores the for-loop. The `add_target` then calls `hypertarget(id, ...)` which is the function that will add some `\phantomsection\label{...}`.
- The second node does not branch in `node.get('refid')`. However, all names in *ids* are used to create new `\phantomsection\label{...}` blocks. And this is the issue: because the second node also has `somelabel` in `ids`, then we re-add `\phantomsection\label{...}`. In particular, we end up with something like:
  
  ```latex
  %%% visiting: <target refid="somelabel">
  \phantomsection\label{\detokenize{testfile:somelabel}}
  %%%
  %%% visiting: <target ids="module-testmodule somelabel" ismod="True" names="somelabel"> 
  \phantomsection\label{\detokenize{testfile:module-testmodule}}
  \phantomsection\label{\detokenize{testfile:somelabel}} % <- the issue is here
  %%%
  ```

I don't know whether this could affect other labels or not, but I think that we could add the following check:

```python
if node.get('refid'):
    prev_node = get_prev_node(node)
    if isinstance(prev_node, nodes.reference) and node['refid'] == prev_node['refid']:
        # a target for a hyperlink reference having alias
        pass
    else:
        add_target(node['refid'])

if node.get('ismod', False):
    # detect if the previous node is target label in which case, 
    # node['ids'] contains the name of the label in addition to the 
    # label for the module name
    prev_node = get_prev_node(node)
    if isinstance(prev_node, nodes.target) and prev_node.get('refid') in node['ids']:
      ids = node['ids'][:] # copy to avoid side-effects
      ids.remove(prev_node['refid'])
else:
    ids = iter(node['ids']) # read-only iterator

for id in ids:
    add_target(id)
```

By tracing back all the code, I managed to find this:

- When parsing `_somelabel`, a `nodes.target` node with `ids='somelabel'` and `names='somelabel'` is created.
- If `.. module` follows just after, the Sphinx `PyModule` directive creates a `nodes.target` node with `ids='module-testmodule'` and `ismod=True`. 
- In [`docutils.transforms.references`](https://github.com/docutils/docutils/blob/755357e66c2f8b0ee83a14f29035bccb4110ad11/docutils/docutils/transforms/references.py#L58-L60), we have:  
  
  ```python
   next_node['ids'].extend(target['ids'])
   next_node['names'].extend(target['names'])
   ```

In particular, if a target follows another target node, then the previous target names ids and names are merged together (and this is why we end up with the module target node having `somelabel` as a valid ids.

So, one way to fix this behaviour is to *avoid* using `nodes.target` in `PyModule`:

https://github.com/sphinx-doc/sphinx/blob/b6e6805f80ad530231cf841e689498005cf2bb96/sphinx/domains/python.py#L1044-L1049

That way, we will not have this "merge" from docutils. Otherwise, we could use the fact that `ismod=True` in order to handle this case in the LaTeX writer as I did (although I am not sure that it covers all corner cases).

**Comment by jfbu** [comment]
@picnixz Thanks for this very useful analysis.  In the case of `html(5)` it seems Sphinx on visiting target node simply uses  original [`docutils.writers._html_base.visit_target()`](https://github.com/docutils/docutils/blob/755357e66c2f8b0ee83a14f29035bccb4110ad11/docutils/docutils/writers/_html_base.py#L1586-L1593) which will ignore those having a `'refid'` attribute, but the target is not lost from the mechanism you explained which transferred the label name to the node created by the module directive.  The Sphinx texinfo writer has its own [`visit_target`](https://github.com/sphinx-doc/sphinx/blob/b6e6805f80ad530231cf841e689498005cf2bb96/sphinx/writers/texinfo.py#L656) and your analysis applies to it as well, but `sphinx.writers.texinfo.TexinfoTranslator.add_anchor()` filters out already encountered anchors:
https://github.com/sphinx-doc/sphinx/blob/b6e6805f80ad530231cf841e689498005cf2bb96/sphinx/writers/texinfo.py#L529-L538
and there is no duplicate from a module directive following a label in source.

Your (first) work-around using `ismod = True` looks to me as it solves this issue (at least as it showed at numpy where I encountered it and in the minimal reproducer I am playing with) using  a prudent approach minimizing potential changes.  If you convert it into a PR, I think we can merge it for 6.2.0.  The other approach looks good to but I need for this to analyse more, and as I (will) explain in replying to your [other comment](https://github.com/sphinx-doc/sphinx/issues/11268#issuecomment-1510178916) I will be mostly unavailable until mid-May (and should already have been for some weeks, but...)
