### ISSUE TITLE
html_file_suffix defaults to None not ".html"?

### ISSUE THREAD

**Issue by jdillard** [sphinx-doc/sphinx#11141]
### Describe the bug

Unless I'm misunderstanding [this line](https://github.com/sphinx-doc/sphinx/blob/e17f39e7b535f4849754d46f2cd2e411df8aa535/sphinx/builders/html/__init__.py#L1362), it looks like [html_file_suffix](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_file_suffix) defaults to `None` and not `.html` like the docs say, but instead looks like it picks up `.html` [from here](https://github.com/sphinx-doc/sphinx/blob/e17f39e7b535f4849754d46f2cd2e411df8aa535/sphinx/builders/html/__init__.py#L198). It seems like the default should be fixed, or if that isn't possible then update the docs.

### How to Reproduce

I'm not sure the best way to reproduce, but it came up in this PR: https://github.com/jdillard/sphinx-sitemap/pull/57

### Environment Information

```text
Platform:              linux; (Linux-5.4.0-135-generic-x86_64-with-glibc2.31)
Python version:        3.9.16 (main, Dec 25 2022, 18:26:15) 
[GCC 9.4.0])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

**Comment by jfbu** [comment]
The relevant commit seems to be 2b29038d0 from `Sphinx 1.0`... and the wording in the documentation appears to have been somewhat confusing ever since, the Change log entry from this commit providing the more precise https://github.com/sphinx-doc/sphinx/blob/e17f39e7b535f4849754d46f2cd2e411df8aa535/CHANGES#L7272-L7274
