### ISSUE TITLE
LaTeX defines a ``\sphinxemail`` but it is used nowhere

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#11240]
### Describe the bug

The line
https://github.com/sphinx-doc/sphinx/blob/ee3c720cfa6d8fcbfbe01c52bbe78a6ba0e8ed49/sphinx/texinputs/sphinxlatexstyletext.sty#L13

replaced some years ago at 1.4.5 (commit 5510653d6) a definition of a command ``\email`` dating back to very first commit with ancestor of the LaTeX sty files (it was called ``texinputs/python.sty``): 3d74adea2.   But the ``\email`` was used in a header template from the then Sphinx LaTeX writer which has disappeared.

So ``\sphinxemail`` should be removed.  Currently an email will end up using ``\sphinxhref``,  not ``\sphinxemail``.  Or one would have to add some complications to ``\sphinxhref`` to check if there is a ``mailto:`` at start of its first argument if one wanted for ``\sphinxemail`` to be of any use.

### How to Reproduce

No reproduces only some unneeded definition.

### Environment Information

```text
not relevant here
```

**Comment by picnixz** [comment]
I searched on github to see whether ``\sphinxemail`` is used somewhere and.. it seems the case (https://github.com/search?q=%5Csphinxemail&type=code). More importantly, Python is using it directly: https://github.com/python/cpython/blob/85c7bf5bcec07beea6064976e6199195cd34329d/Doc/conf.py#L172.

I *think* it is not safe to remove it without warning the users that it will be deprecated. If users generate documentation with old configurations but with a very new version of Sphinx, then those configurations would likely fail because we would have removed the macro ! So, for those old configurations, we should warn them (maybe at the LaTeX level? although the warning could be lost in the huge traceback..., so maybe at the builder level but it requires to know whether ``\sphinxemail`` was provided by the user of it is using our own implementation).

**Comment by jfbu** [comment]
Thanks @picnixz. Definitely my ``So \sphinxemail should be removed.`` was careless. Thanks for looking at this, I will now close as not planned!
