### ISSUE TITLE
Autodoc: failed to import module 

### ISSUE THREAD

**Issue by mloureiro-ilof** [sphinx-doc/sphinx#11261]
### Describe the bug

I have a module with several python scripts within it and an ``__init__.py`` script that imports all of them. I am trying to create sphinx documentation for this package and every time I run `./make html` I get the same error for each python script:

```
WARNING: autodoc: failed to import module 'deep_features_mil' from module 'iloflib'; the following exception was raised:
No module named 'iloflib'
```

From what I understood, this happens because each `.rst` file imports the python script as `iloflib.deep_features_mil` and not `deep_features_mil` directly. If I remove the `__init__.py` file, this stops happening and the files import `deep_features_mil` directly. (The example is `deep_features_mil` but it happens for all of them).

When `__init__.py` file exists, these files are created:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/87646763/226985391-5cf7a4d0-319a-4c3f-aff3-1334a3c9a490.png">
When building the HTML files, these errors appear:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/87646763/226985527-5a589638-8389-4b3a-be2a-178206634070.png">

If I delete the `__init__.py` file, these files are created:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/87646763/226986311-772d267b-0465-49a5-bcb6-d51f460837e4.png">
In this case, the HTML files are successfully created!

I've tried changing the path in the conf.py script, but without any good results. I've tried changing the import in the `__init__.py` file, without any success. If I have an empty `__init__.py` file, the problem reappears.

### How to Reproduce

I have a module created with several python scripts within it and an `__init__.py` script that imports all of them:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/87646763/226982972-f10233b2-a231-45d6-b895-a765a6cb5c8e.png">
Imports within `__init__.py`:

```python
from iloflib import io
from iloflib import feature_extraction
from iloflib import deeplearning
from iloflib import deep_features_mil
from iloflib import performance
from iloflib import photosignal
from iloflib import validation`
```

My `conf.py` file is:
```python
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join("..", "..", "iloflib")))

project = "iloflib"
copyright = "2023, ilof"
author = "ilof"
release = "1.0.4"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["sphinx.ext.autodoc", "sphinx.ext.viewcode", "sphinx.ext.napoleon"]

templates_path = ["_templates"]
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "alabaster"
html_static_path = ["_static"]
```

An example of the .rst files created (when they return the error):
```restructuredtext
iloflib.validation module
=========================

.. automodule:: iloflib.validation
   :members:
   :undoc-members:
   :show-inheritance:
```

When they work, this is an example:

```restructuredtext
validation module
=================

.. automodule:: validation
   :members:
   :undoc-members:
   :show-inheritance:
```

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.22621-SP0)
Python version:        3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.13.0
```

### Sphinx extensions

```python
extensions = ["sphinx.ext.autodoc", "sphinx.ext.viewcode", "sphinx.ext.napoleon"]
```

**Comment by x12hengyu** [comment]
I am having the same issue right now on linux. Did you resolve this problem? Thanks!

**Comment by picnixz** [comment]
`conf.py` sees `from iloflib import [...]`, but by adding the absolute path of `iloflib`, the modules and packages found *inside* can be imported. Instead, try

```python
sys.path.insert(0, os.path.abspath(os.path.join("..", "..")))
```

That way, the `iflolib` module is properly visible. Note that if you simply print `sys.path`, you'll probably have something like `/usr/lib/python/site-packages` meaning that all packages inside `/usr/lib/python/site-packages` can be imported. If you print `sys.path` after your `sys.path.insert`, you'll see that you only added `/abs/path/to/iloflib` and thus, you'll only be able to import packages that are *inside* (e.g., `deeplearning`). 

You can try this by creating some Python script at the same level of your `conf.py`, e.g.:

```python
import os
import sys

try:
  import iloflib
except ImportError:
  print("oh no 1")

sys.path.insert(0, os.path.abspath(os.path.join("..", "..", "iloflib")))

try:
  import iloflib
except ImportError:
  print("oh no 2")

import deeplearning  # does not fail

sys.path.insert(0, os.path.abspath(os.path.join("..", "..")))

import iloflib  # does not fail anymore
```

**Comment by Carolmeloc** [comment]
Hi, how did you solve your problem? I'm facing the same but I don't know what to do anymore

**Comment by x12hengyu** [comment]
`pip install -e .` is the solution.

**Comment by picnixz** [comment]
(Using `pip install -e .` 'solves' the issue because your package is now discoverable by the native importer, although I wouldn't recommend doing it and rather check if your configuration file has correct paths).

I'll close this issue since it's not directly to Sphinx core but rather how your import system was configured. For people coming on this issue in the future:

- Check first on StackOverflow if other people have similar issues.
- Please provide a minimal working example (**not** your entire project) if you believe that your issue is Sphinx related. We cannot help you or investigate if we don't have anything to validate.
- `conf.py` is a Python file, so you can always add an `import myproject` at the very end and run it normally. In general, if your path is correctly configured, then you won't have import errors (see [my previous comment](https://github.com/sphinx-doc/sphinx/issues/11261#issuecomment-1501124616)).

**Comment by chrisjsewell** [comment]
> Using `pip install -e .` 'solves' the issue because your package is now discoverable by the native importer, although I wouldn't recommend doing it and rather check if your configuration file has correct paths

Out of in interest @picnixz, why do you say this?
Because I always advise the opposite 😅  i.e. specifically against modifying `sys.path` where possible and instead using `pip install -e .`, since the package may have special install semantics (e.g. setting entry points)

**Comment by picnixz** [comment]
>  Because I always advise the opposite 😅 i.e. specifically against modifying sys.path where possible and instead using pip install -e ., since the package may have special install semantics (e.g. setting entry points)

Because when you git clone something, you don't necessarily want to have everything installed in your local installation (if you are in a venv, forget what I said). 

Now, I'd say:

- If you can solve your issue without tempering your site-packages because you don't know why it works but it somehow work by installing everything, do it.
- If your package has special semantics, then yes, install it first to be discoverable correctly. But that's not generally the issue for those import errors (at least not for the issues I encountered).

**Comment by chrisjsewell** [comment]
> If your package has special semantics

Oh and also don't forget about dependencies and dependency resolution 😏
so yes, if you have a very simple package or script, with no dependencies, etc, sure use `sys.path`,
but in general I personally feel installing is the "safer" option

**Comment by picnixz** [comment]
> Oh and also don't forget about dependencies and dependency resolution 😏

Well... technically, those dependencies are already installed in your Python environment (otherwise they wouldn't event work with to start with). To summarize, I think it's just better to first create a virtual environment and then pip install inside that environment. But not pip install using your local installation (because you might temper with other projects for instance).

**Comment by chrisjsewell** [comment]
> But not pip install using your local installation 

Oh of course! We're agreed there 😄
