### ISSUE TITLE
Bad computation of enum superclass in `sphinx.ext.autodoc.importer.get_class_members()`

### ISSUE THREAD

**Issue by alxroyer** [sphinx-doc/sphinx#11353]
### Describe the bug

The computation for the super-class in [`sphinx.ext.autodoc.importer.get_class_members()`](https://github.com/sphinx-doc/sphinx/blob/v6.1.3/sphinx/ext/autodoc/importer.py#L227) is:
```python
superclass = subject.__mro__[1]
```

The version above does not check the super-class taken into account is actually the expected base enum type.

As a consequence, when the super-class is wrong:
- the method does not filter out a couple of members it's used to filter-out for enums: `_generate_next_value_`, `__weakref__`, `_member_names_`, `_member_map_`, `_member_type_`, `_value2member_map_`
- the method filters out other members it should not: `__str__()` for instance.

The computation below fixes the thing:
```python
superclass = list(filter(sphinx.util.inspect.isenumclass, subject.__mro__))[1]
```

### How to Reproduce

```bash
git clone https://github.com/alxroyer/scenario/
cd scenario/
python -m sphinx -T -E -b html -D language=en ./tools/conf/sphinx/ ./doc/html/
```

The problem occurs for the [`StrEnum`](https://github.com/alxroyer/scenario/blob/v0.2.2/src/scenario/enumutils.py#L25) class.

### Environment Information

```text
Sphinx version in use: 5.3.0, but the wrong line is still the same with 6.1.3.
```

### Sphinx extensions

```python
Base `sphinx.ext.autodoc` should be enough.
```

**Comment by AA-Turner** [comment]
Please provide a minimal reproducer, ideally a single module file, a single ``index.rst`` file, and a single ``conf.py`` file.

A

**Comment by alxroyer** [comment]
3 files, in the same directory:
- 'conf.py':
  ```python
  extensions = ["sphinx.ext.autodoc"]
  ```
- 'index.rst':
  ```rst
  .. automodule:: strenum
     :members:
     :undoc-members:
     :private-members:
  ```
- strenum.py
  ```python
  import enum


  class RegularEnum(enum.Enum):
      """
      Regular enum.

      ``enum.Enum`` inherited attributes are filtered-out.
      """


  class StrEnum(str, enum.Enum):
      """
      Inspired from ``enum.IntEnum``.

      ``enum.Enum`` inherited attributes are not filtered-out.
      """
      def __str__(self):
          return self.value
  ```

Build command, from the same directory:
```bash
python -m sphinx -b html . out/html
```

Output:
![image](https://user-images.githubusercontent.com/41943581/235267047-2a2814a9-77fc-4898-afc5-9fee34925c62.png)

Hope that helps. Let me know.

**Comment by picnixz** [comment]
> The computation below fixes the thing:
> ```superclass = list(filter(sphinx.util.inspect.isenumclass, subject.__mro__))[1]```

An enumeration is instantiated as[^1]:

```
EnumName([mixin_type, ...] [data_type,] enum_type)`
```

Instead, it is better to use ``superclass = subject.__mro__[-2]`` because this would always target the correct enumeration type. Also, enumerations cannot be extended with other enumerations, *unless* the enumeration super class has *no* members:[^2]

```python
class EnumMixin(enum.Enum):
    pass

class MyEnum(EnumMixin, Enum):
    a = 1

class Invalid(MyEnum, Enum):  # failure
    b = 1 
```


The reason why ``__str__`` is not included is because it is first a *special* member. I agree that there *is* an issue. This is not due to https://github.com/sphinx-doc/sphinx/blob/776d01eb6229f5d5384da17fc15df9d50fa8e87a/sphinx/ext/autodoc/importer.py#L228-L231 but due to https://github.com/sphinx-doc/sphinx/blob/776d01eb6229f5d5384da17fc15df9d50fa8e87a/sphinx/ext/autodoc/importer.py#L245-L259

Enumerations override [``__dir__``](https://docs.python.org/3/library/enum.html#enum.EnumType.__dir__) and * return public members and some pre-defined special methods. In particular, ``__str__`` is *not* part of the public API for enumerations and Sphinx will never be able to find it. This is not the case for regular classes since ``__str__`` *will* be found when using `dir(subject)`.

As such, I suggest one of the following:

- Either you document the behaviour of what ``__str__`` in the enumeration docstring directly (which would probably be more readable in general).
- Or we entirely change the logic of finding members for an enumeration (this would also affect https://github.com/sphinx-doc/sphinx/blob/776d01eb6229f5d5384da17fc15df9d50fa8e87a/sphinx/ext/autodoc/importer.py#L146-L153 where enumerations are handled differently as well.

---- 

[^1]: https://github.com/python/cpython/blob/9fbb614c4ed0b9181db1c1b858dfb93587662d6b/Lib/enum.py#L955-L957
[^2]: https://github.com/python/cpython/blob/9fbb614c4ed0b9181db1c1b858dfb93587662d6b/Lib/enum.py#L929-L937

**Comment by alxroyer** [comment]
Thanks a lot @picnixz for the explanation.
