### ISSUE TITLE
Directive index option name not working

### ISSUE THREAD

**Issue by generationext** [sphinx-doc/sphinx#11416]
### Describe the bug

From documentation
directives.html#directive-index

options
  :name: a label for hyperlink (text)

Define implicit target name that can be [ref]. For example:

    .. index:: Python
       :name: py-index

I tried:
:ref:`py-index`

Failed to create a cross reference. A title or caption not found

### How to Reproduce

.. index:: Python
    :name: py-index

try:
:ref:`py-index`

### Environment Information

```text
Sphinx v6.2.1
```

**Comment by picnixz** [comment]
The ``index`` directive is meant to create a cross-reference for a specific location in the source. However, the directive block itself is not considered as a valid anchor so you need a real anchor point:

> Since index directives generate cross-reference targets at their location in the source, it makes sense to put them before the thing they refer to – e.g. a heading.

For instance,

```rst
.. index:: My Section
   :name: my-section-label

My Section
----------
Pouet

(lots of lines)

My Other Section
----------------
Go to :ref:`my-section-label`
```

**Comment by picnixz** [comment]
They should because it is mentioned on the [official documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-index).

**Comment by picnixz** [comment]
Whenever you create a label, be it using the ``.. index::`` directive or a simple label `_my-label:`, you usually put them before a heading (section) or a caption. That way, you can simply write <code>:ref:\`py-index\`</code>. However, when you are using a standalone index or label, you need to add a title in the reference role, namely <code>:ref:\`My Title \<py-index\>\`</code>.

**Comment by picnixz** [comment]
> In order to refer to a word in a sentence, you need to use the following syntax:

Well you told me "And I can refer to this word using the <code>:ref:\`word\`</code> role"... Also, the reason why it works is because <code>_\`word\`</code> is what we call an "inline internal label". But this is part of docutils and not sphinx per se (see https://docutils.sourceforge.io/docs/user/rst/quickref.html). 

>  If you want to use the index directive without a header, you must include an explicit header when creating the link!

Again, this is something that should be known. Any directive or any construction creating a cross-reference must either be followed by something with a title or must be referred to via an explicit title. This is explained [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role):

> Labels that aren’t placed before a section title can still be referenced, but you must give the link an explicit title, using this syntax: :ref:\`Link title \<label-name\>\`.

And the index directive says:

> Define implicit target name that can be referenced by using [ref](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-ref).

**Comment by picnixz** [comment]
> because I can access them from the Index page but not through the :ref: role

This is not the same. The `:ref:` role is meant to be used for cross-referencing locations but not for objects created within specific domains. For instance, you cannot use <code>:ref:\`myfunction\`</code> if you had previoulsy documented `foo` using `.. py:function:: foo` because `foo` was actually documented by the Python `py` domain.

As explained [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-rst-dir), you don't refer to directives using <code>:ref:\`MyDirective\`</code> but using <code>:rst:dir:\`MyDirective\`</code>. The reason is simply because when you document a directive via `.. rst:directive:: MyDirective`, you are using the RST domain.

**Comment by picnixz** [comment]
> (which is not displayed correctly, without a dot)

If you want to render something with a dot, do not use <code>:data:\`.mydata\`</code> because the leading dot has a special meaning. Please carefully read this [section](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-obj). 


> How can I apply styles to the above roles without using a css file?

With *native* sphinx, I don't know a way to do it easily (unless you write your own extension). I think you can render things like that because of `myst_parser` and `sphinx_design`, so ask your questions on stackoverflow & co or submit an issue / feature request directly on their repository. 

Since the original issue is no more relevant (AFAICT the index directive *does* work as intented), I will not answer off-topic questions anymore (unless there is a real issue).

**Comment by picnixz** [comment]
> how are links generated on pages generated by Sphinx without a dot.

References are gathered and resolved. But the real process is much more complex so if you want to know more you need to dive into the code yourself. 

> I also wonder how it was possible to create most of the link elements in the block

Links point either to external pages or internal nodes which are marked during the process. I am closing the issue since the discussion is becoming off-topic.
