### ISSUE TITLE
Change relative path resolution for file calling ..include:: directive (also applies to .. figure::)

### ISSUE THREAD

**Issue by PedroAlfNeto** [sphinx-doc/sphinx#11454]
The relative path is being resolved from the index.rst file, instead of the file calling the directive!

This approach sacrifices not only reusability of content, having no clear way to work around this, but it goes against the specification for the reference (unless I'm interpreting it wrong):

![image](https://github.com/sphinx-doc/sphinx/assets/17347870/b7161403-9e08-45b1-af93-c637c3bbc262)
[[source](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include)](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include)

I've verified that this path definition error also applies to directives of ".. figure::"

Please consider changing this implementation to always handle relative paths from the file calling the directive.
This handling of path is a deal breaking for my project documentation system.

(Using sphinx-build 3.4.3)

**Comment by picnixz** [comment]
Please, give us a minimal reproducible example, together with the directory structure (which is important), the configuration script and the sources. If you are using `autodoc`, keep in mind that the document being generated (which is the endpoint to which the path is is not necessarily the (physical) document where the directive is written (e.g., a Python file). 

For instance, assume that you have the following structure:
```
.
├── doc
│   ├── pages
│   │   └── a.rst
│   └── index.rst
└── src
    ├── a.py
    └── a.txt
```

```python
# ./src/a.py

"""
Some text.

.. include:: a.txt
"""

pass
```

```rst
.. ./doc/pages/a.rst

Title
-----

.. automodule:: src.a
```

```rst
.. ./doc/index.rst

.. toctree::

   pages/a
```

Then, when you build the documentation, the `doc/pages/a.rst` becomes equivalent to

```rst

.. module:: src.a
   
   Some text.

   .. include:: a.txt
```

An obviously, `doc/pages/a.txt` does not exist. As such, this is an expected behaviour. In general, `.. include` directives do not play well with autodoc unless you specify an absolute path (i.e., `/a.txt`) which will be resolved *relative to root directory* (in our case `./doc`), that is, it becomes `.. include:: doc/a.txt`

**Comment by PedroAlfNeto** [comment]
Hi @picnixz, thank you for your example, i'm not using any autodoc and will ignore. Hope this next example highlights my issues with the existing approach.

## Example project
### Directory structure:
      . 
      ├── general_doc
      │   ├── Intro.rst
      │   └── HW_overview.rst
      │
      │
      ├── docA
      │   ├── index.rst
      │   ├── conf.py
      │  ...
      │     
      ├── proj
      │     ├──docB_proj
      │    ... ├── index.rst
      │        └── conf.py
     ...

### File to reused
``` restructuredText
    # ./projA/doc_projA/index.rst - Document A which reuses intro
    
    Intro
    =============
    My intro to the project


    .. Relative path to index, existing implementation - only works for doc_projA

    .. include:: ../general_doc/HW_overview.rst  



    .. Relative path to index, existing implementation - only works for doc_projA    

    .. include:: ../../general_doc/HW_overview.rst



    .. Relative path file calling the directive (wont work!!) - ideal approach would work for both:

    .. include:: ./HW_overview  

```

### Document A which reuses intro

``` restructuredText
    # ./docA/index.rst - 

    #####
    Doc A
    #####

    .. include:: ../../general_doc/Intro.rst
    
```
### Document B which reuses intro (diferent directory level to DocA)

``` restructuredText
  # ./proj/docB_proj/index.rst - Document B which reuses intro

  #####
  Doc B
  #####
  
  .. include:: ../../general_doc/Intro.rst

```

In the above example it is not possible with the given project directories to reuse "intro" documentation in both Doc A and Doc B.
I cannot see the advantages of resolving realtive paths from the index file... would only result in hidden logic and greatly limit reusability.

## Problem statement
The core issue here is that relative paths provided to directives (include, figure etc) are defined by the documentation source (start path at index.rst), and IMHO should be resolved from the file calling the directive, due to the arguments provided above.

**Comment by picnixz** [comment]
First of all, you have `./projA/doc_projA/index.rst` which I don't see in your tree structure. So I cannot know where the file actually lies. Secondly, I don't see how this can be done: 

```rst
    .. Relative path file calling the directive (wont work!!) - ideal approach would work for both:

    .. include:: ./HW_overview  
```

The only case where this would make sense (independently of Sphinx) is if you are currently in some directory containing `HW_overview`, namely the above can only be relevant if the file is `./general_doc/index.rst`. 

> I cannot see the advantages of resolving realtive paths from the index file...

In general, `.. include::` (or `.. literalinclude::`) is used for including independent pieces of codes (e.g., JSON schemas). The same is true for `.. figure::` which includes an independent image. You don't really use it for avoiding duplicated texts, unless it's really an independent piece of text (e.g., a licence or a general comment). I think that having *duplicated* pieces of text for each project is fine because each project should be introduced differently. There are probably extensions that can do what you actually want to do, but for the core library, we probably won't change it. Also, note that the `.. include::` directive is a `docutils` directive so you should submit this feature request to [docutils.sourceforge.io/](docutils.sourceforge.io/). Here, we would only consider changing the implementation of `.. literalinclude::` but since it follows the same considerations as `.. include::`, we would only act if it changes upstream.

I will conclude with the following observations:

- The `.. include::` directive should be used carefully because it presents a security hole in general. 
- If you include a file which itself includes another file, which includes itself another file, etc, you need to dynamically resolve the included files, possibly ending up having circular inclusions.

**Comment by PedroAlfNeto** [comment]
Thank you for you clarification and hints @picnixz.
I'll look into extensions and docutils.
As for the the security holes and infinite recursion, i disagree and think you're tailoring to specific applications.
And this "having duplicated pieces of text" is a clear DRY violation and when projects scale so does exponentially scale maintenance and unwanted forking.
