### ISSUE TITLE
doxygen breathe.file_state_cache.MTimeError:Cannot find file: source/user_doxygen_out/xml/index.xml

### ISSUE THREAD

**Issue by ramkikannan** [sphinx-doc/sphinx#11470]
### Describe the bug

I am producing the documentation for ramkikannan.com/planc-api. It had been running fine. Recently I swapped my laptop and was setting up breathe, sphinx, doxygen on the laptop and getting the following problem. 

```
Exception occurred:
  File "/Users/xxxxxxxxx/xxxxxx/virtualenv/doxygen/lib/python3.9/site-packages/breathe/file_state_cache.py", line 27, in _getmtime
    raise MTimeError("Cannot find file: %s" % os.path.realpath(filename))
breathe.file_state_cache.MTimeError: Cannot find file: /Users/xxxxx/xxxxxx/research/breathe-nmflibrary/source/user_doxygen_out/xml/index.xml
The full traceback has been saved in /var/folders/5f/w01788w52p5fh5_5x71ff21mnvh04x/T/sphinx-err-7488mcq4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

I am generating the documentation on my Macbook M1 pro. I have setup the following

 1. brew install doxygen
 1. brew install graphviz
 1. Create a virtualenvironment
 1. pip install sphinx sphinx-mt-theme
 1. pip install breathe

Please let me know if you are looking for additional details

### How to Reproduce

I ran ```sphinx ./source ./build``` and got the above error. 

### Environment Information

```text
The following are the python package versions.

breathe==4.35.0
Sphinx==6.2.1
sphinx-rtd-theme==1.2.2
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
```
```


### Sphinx extensions

```python
No special extensions.
```

### Additional context

No other tools were used.

**Comment by picnixz** [comment]
- It is an issue with breathe which is looking for a cached file that doesn't exist (because you switched your laptop).
- Try to invoke sphinx with `-E` option. It should wipe out any cached directory (if it still doesn't work, wipe the output directory yourself and try again).
- I don't know whether `/Users/xxxxx/xxxxxx/research/breathe-nmflibrary/source/user_doxygen_out/xml/index.xml` is autogenerated or if it should exist or not. I never used breathe so I cannot tell. If the issue persists, I would advise asking directly the breathe community instead.
