### ISSUE TITLE
Enum values inside `typing.Literal` render weirdly

### ISSUE THREAD

**Issue by ItsDrike** [sphinx-doc/sphinx#11473]
### Describe the bug

While `typing.Literal` is picked up properly by autodoc when it just contains a string, when the contained value is an enum variant, the output is very messy.

For some reason, it shows `~typing.Literal`, rather than just `Literal`, and the enum variant seems to just be the output of  `repr(SomeEnum.X)`, which includes the value of that enum, which isn't something we'd generally need to see. It also doesn't produce a clickable reference to the specific variant (or at least to the enum class).

While using `repr` works well when the Literal just contains strings, it looks very weird for enum variants, and clearly seems to be a bug.

Here's how the documentation would look from the minimal reproducable example below:

![image](https://github.com/sphinx-doc/sphinx/assets/20902250/e266ac72-9436-44cd-b586-4025519104d4)

<details>
<summary>
And here's another screenshot of how this might look from an actual project, to demonstrate how "cluttery" this can get:
</summary>

![image](https://github.com/sphinx-doc/sphinx/assets/20902250/29f51050-37d9-433a-af96-ae9724ad6c8b)
</details>

### How to Reproduce

```bash
python -m venv .venv
emulate bash -c '. .venv/bin/activate'
pip install sphinx
mkdir src
cat > src/example.py <<EOF
from typing import Literal
from enum import Enum

def works_great(x: Literal["foo"]) -> None:
    """Does stuff"""

class SomeEnum(str, Enum):
    X = "x"
    Y = "y"
    Z = "z"

def problematic_func(x: Literal[SomeEnum.X]) -> None:
    """Also does stuff"""
EOF
cat > src/conf.py <<EOF
import os, sys

sys.path.insert(0, os.path.abspath("."))

extensions = ["sphinx.ext.autodoc"]
EOF
cat > src/index.rst <<EOF
API reference
=============

.. automodule:: example
    :members:
    :undoc-members:
EOF
sphinx-build -b html src _build
xdg-open _build/index.html
```

### Environment Information

```text
Platform:              linux; (Linux-6.3.7-arch1-1-x86_64-with-glibc2.37)
Python version:        3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429])
Python implementation: CPython
Sphinx version:        7.0.1
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

### Sphinx extensions

```python
["sphinx.ext.autodoc"]
```

**Comment by ItsDrike** [comment]
After doing some quick inspection of the sphinx code-base, I think the place where this should be fixed is in the `stringify_annotation` function in `sphinx.util.typing`:

https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/util/typing.py#L213

Currently, since the enum class is also a string subclass, the function returns here:

https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/util/typing.py#L253

This is a clear bug, as it actually returns back the annotation as-is, meaning the enum variant is returned directly. This is because of the `isinstance(annotation, str)` check, rather than `type(annotation) is str` check, causing subclasses of string to also fall here, which clearly shouldn't be happening.

Though even if this was just a simple `Enum`, rather than a `str, Enum`, it would just go to the unknown type branch, returning a repr representation of the annotation here:

https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/util/typing.py#L319

To fix this, this check should be changed from `isinstance` to an explicit `type` check, to prevent subclasses from passing, and there should be a branch for handling enums explicitly, checking `isinstance(annotation, enum.Enum)`, which returns a more friendly looking annotation, so for example something like: `annotation.__class__.__name__ + "." + annotation.name`, whcih would render as `SomeEnum.X` for variant X here.

I'm not particularly comfortable with all of the nuances of Sphinx codebase, so I don't feel very comfortable making a PR myself, but to anyone more experienced here, it should hopefully be an easy fix, following these instructions.

**Comment by picnixz** [comment]
I am travelling now but I will have a look  when I return because I fixed this locally. It should be easy to make it a PR out of it but it will not be up until late July

**Comment by ItsDrike** [comment]
I see @picnixz, I could attempt a PR myself, basically just doing what I've described above, and just leave it to reviews to point out any mistakes (which I'm pretty sure there will be). But I'm not absolutely certain that this is indeed the place this should be fixed in, and whether it's the only place this change needs to be made. Do you think the solution I proposed is the right one, or should I look elsewhere?

**Comment by picnixz** [comment]
I don't remember exactly, but I think the stringify\_annotation function is the one to change. There is also the restify function somewhere to change iirc. Sorry, but since I have no access to my local projects currently, I cannot tell you more about it

**Comment by picnixz** [comment]
I drafted a PR, but I'm not entirely happy with how it renders. Should it render:

- `Literal[SomeEnum.x]`,
- `Literal["x"]`,
- or `Literal[module.SomeEnum.x]` ?

Depending on the rendering mode, I would say:

- In `mode = 'fully-qualified-except-typing'`, I want something like `~typing.Literal[module.SomeEnum.x]`, which then renders on the HTML page as `Literal[module.SomeEnum.x]`.
- In `mode = 'fully-qualified'`, I want `typing.Literal[module.SomeEnum.x]` (which renders similarly on the HTML page).
- In `mode = 'smart'`, I think `Literal[SomeEnum.x]` is better than `Literal["x"]`. But then the content won't be "clickable" since no reference is created when stringifying annotations.

**Comment by picnixz** [comment]
@ItsDrike 

> So, to fix this, first, the literal handling should make recursive calls for any of the type arguments to literal, rather than just calling a repr on them.

Technically, `Literal` should only accept ... literal arguments. And the only literal types valid in Python are literal ints, byte and unicode strings, bools, Enum values and `None`. So having a recursive call is not needed. We only need to handle values that have a non-trivial `repr`, namely enumeration values.

**Comment by ItsDrike** [comment]
I think `Literal["X"]` is a really bad choice, since it could imply a string "X" literal, not an enum variant. Either `Literal[X]` or `Literal[EnumClass.X]` or `Literal[module.EnumClass.X]`. The distinction of when to show `module.` is fairly clear, if the mode is fully-qualified/fully-qualified-except-typing it should be there. As to picking from just `Literal[X]` vs `Literal[EnumClass.X]`, I'd say the class should almost always be included, as there might be more enum classes with the same variant names. The only place where this might not be as amazing is if the enum class also contains functions that take in those variants, where the shorter `Literal[X]` might make more sense. However I'd say it's pretty clear that generally, the class should be included, and even in the internal fucntions it's fine if it's included IMO.

**Comment by picnixz** [comment]
Actually, when I said "I'm not happy", it's probably because I wanted to have a clickable thing. But for stringified annotations, I don't think I should expect more than that, so I'm no more unhappy. Actually, I don't know whether 'smart' should output `~typing.Literal[~module.SomeEnum.x]` or directly `Literal[SomeEnum.x]` (I'll need to check where it is actually used). For regular values, it outputs `~typing.Literal[value]`, so I would say that I need to output `~typing.Literal[~module.SomeEnum.x]`, but again I'm not sure whether the fact that I have `~module.SomeEnum.x` is important or not when rendering (the reason why we had the original issue is because we had `<...>` so I suspect that the content of `[...]` is the culprit).

> I'd say the class should almost always be included,

Yes, that's what I thought would be the most relevant.  

> (perhaps this can be done with when mode=smart?).

If you mean "detect that your are inside the function", then no. The `smart` mode means that you don't want the module name to be printed.

**Comment by electric-coder** [comment]
> I'm not sure whether the fact that I have `~module.SomeEnum.x` is important or not when rendering (the reason why we had the original issue is because we had `<...>` so I suspect that the content of `[...]` is the culprit).

Possibly a legacy issue predating #9272 because Enum's are special cased `<EnumClass.EnumMember: Enum value>` instead of using fully qualified names like other objects. The fact that Enum is special cased like this caused a number of internal issues with Sphinx.

**Comment by picnixz** [comment]
Actually, `__repr__` does not necessarily need to use fully qualified names. According to the specifications, the content of `<...>` should be "...some useful description...". The issue is more because of the symbols `<` and `>` that are badly parsed.

For instance, with `autodoc_typehints_format = 'short'`, documenting

```python
from enum import Enum
from typing import Literal

class SomeEnum(Enum):
    X = "x"

def bar(x: Literal[1234]) -> None: pass
def foo(x: Literal[SomeEnum.X]) -> None: pass
```

renders as 

![Screenshot_20230726_101415](https://github.com/sphinx-doc/sphinx/assets/10796600/3b248643-8386-4c95-838c-3b5d1a976562)

I now understand why it fails. Actually, when creating the signature of the function being documented, the list of arguments (together with its annotations) is parsed. In the first case, what we parse is `x: ~typing.Literal[1234]` (the `~typing.Literal` comes from the fact that we have first stringified the annotation). The output is 

```xml
<desc_parameterlist multi_line_parameter_list="False" xml:space="preserve">
  <desc_parameter xml:space="preserve">
    <desc_sig_name classes="n">
      x
    <desc_sig_punctuation classes="p">
      :
    <desc_sig_space classes="w">
       
    <desc_sig_name classes="n">
      <pending_xref py:class="True" py:module="testfoo" refdomain="py" refspecific="False" reftarget="typing.Literal" reftype="obj">
        Literal
      <desc_sig_punctuation classes="p">
        [
      <desc_sig_literal_number classes="m">
        1234
      <desc_sig_punctuation classes="p">
        ]
```

For `x: Literal[SomeEnum.X]`, what we actually parse is `x: ~typing.Literal[<SomeEnum.X: 'x'>]`. **However, this fails** and the current strategy is to actually ignore the failure and assume that `~typing.Literal[<SomeEnum.X: 'x'>]` denotes a type itself. The reason is essentially because `<SomeEnum.X: 'x'>` cannot be parsed correctly. What we actually do is create a signature object by parsing the following fake Python functions:

```python
def func(x: ~typing.Literal[1234]): pass
def func(x: ~typing.Literal[<SomeEnum.X: 'x'>]): pass
```

From an AST point of view, the first definition is correct (although it does not work at runtime). However, the second definition is not correct because `[<SomeEnum.X: 'x'>]` is illegal. This causes the signature node to be 

```xml
<desc_signature class="" classes="sig sig-object" fullname="foo" module="testfoo">
  <desc_addname classes="sig-prename descclassname" xml:space="preserve">
    testfoo.
  <desc_name classes="sig-name descname" xml:space="preserve">
    foo
  <desc_parameterlist xml:space="preserve">
    <desc_parameter xml:space="preserve">
      x: ~typing.Literal[<SomeEnum.X: 'x'>]
```

And this is why we have `~typing.Literal` even though we are in a 'short' (smart) mode. Note that changing the AST parser is not possible (unless we preprocess the string that is to be parsed to avoid syntax errors, but that would be a herculean task to achieve, or use a token-based approach but I don't want to do it again).
