### ISSUE TITLE
Floating Graphviz Output

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1149]
I'd like to be able to float an image generated by sphinx.ext.graphviz so text can flow around it.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1149
- Originally reported by: [Odd_Bloke](https://bitbucket.org/Odd_Bloke)
- Originally created at: 2013-04-16T15:03:50.642

**Comment by tk0miya** [comment]
In my short investigation:
Since version 1.1, `sphinx.ext.graphviz` allows `:inline:` option. So we can put it into text as floated image in LaTeX output.

But, In HTML, it does not work fine. For example, I tested by simple code::

```
hello

.. graphviz::
   :inline:

   digraph { A -> B }

world
```

It works fine in LaTeX builder, but in HTML builder, we got following result::

```
<p>hello</p>
<span class="graphviz">
<img src="_images/graphviz-a3131b2d7b2e1afc7c2dcf3e5e4daa6b76801e4d.png" alt="digraph { A -&gt; B }" />
</span>
<p>world</p>
</div>
```

You can see that texts placed before and after are treated as a paragraph.

BTW, we have _substitution syntax_ for embedding inline directives into text.
but it does not support `sphinx.ext.graphviz`. because the `graphviz` node is not instance of `nodes.Inline`.

To resolve this, we should change type of `graphviz` node to `nodes.Inline`.
