### ISSUE TITLE
consider inverting ruff lint list

### ISSUE THREAD

**Issue by danieleades** [sphinx-doc/sphinx#11579]
this repo currently uses an approach of enforcing *all* ruff lints, and then selectively turning off lints which aren't wanted. I propose doing the opposite.

The main reason is that the current approach is extremely brittle to new lints being added to Ruff. This causes a lot of breakages.

**Comment by picnixz** [comment]
For me it's a +0:

* We might end up with a *LOT* of rules to enable (I don't know how many are actually enabled with the current set but the file will likely become larger and larger). 
* We need to keep track of the new rules that are added (maybe some of them are important, or maybe we are not aware of them and only discover them when we do some weird stuff). 
* On the other hand, I would agree if someone would be kind enough to actually keep the list of rules up-to-date with a good rationale of why such rule has been selected (or excluded).
* Personally, I prefer enabling everything so that I also discover new rules or know that when I disable one explicitly, it's for a good reason.

**Comment by danieleades** [comment]
> For me it's a +0:
> 
> * We might end up with a *LOT* of rules to enable (I don't know how many are actually enabled with the current set but the file will likely become larger and larger).

The rules can be globbed by only including the prefix, so in practice this isn't too annoying 

> * We need to keep track of the new rules that are added (maybe some of them are important, or maybe we are not aware of them and only discover them when we do some weird stuff).

That's true, it means they are added on a case by case basis and the merits of each judged in the corresponding PR. I find the inverted logic of getting all the lints without warning and having to unbreak things after the fact *much* messier

> * On the other hand, I would agree if someone would be kind enough to actually keep the list of rules up-to-date with a good rationale of why such rule has been selected (or excluded).

Yeah you're right, relies on maintainers taking an active interest in this.


> * Personally, I prefer enabling everything so that I also discover new rules or know that when I disable one explicitly, it's for a good reason.

Doing this in a local build periodically would be a great way to discover new lints. But doing it in the remote just leads to unstable CI

**Comment by danieleades** [comment]
can we please take another look at this? Every time i come back to this repo the linting is in a completely broken state and it creates a really bad developer experience.

- many of the lints are now behind a `--preview` flag so i'm getting spammed with warnings
- if i update to the latest version of ruff there are hundreds of errors
- the version of ruff is not pinned in the dependencies so different users will see different errors
- PRs are filled with lint errors that are not related to the changes being made
- the list of disabled lints is now very long. I don't think the argument that this is less verbose than inverting the logic holds at all

**Comment by AA-Turner** [comment]
This has been done.
