### ISSUE TITLE
Attribute Error when running the docs

### ISSUE THREAD

**Issue by rohanbabbar04** [sphinx-doc/sphinx#11604]
### Describe the bug

Thanks for this great project, I have been using it a lot..
Recently switching to `sphinx==7.2.0`, I am getting an `AttributeError` which was not there in the earlier version(

```
Theme error:
An error happened in rendering the page adding.
Reason: AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")
```
Expecting a quick reply from you all...

### How to Reproduce

These are some of the files that may be required: 
- [conf.py](https://github.com/PyLops/pylops-mpi/blob/main/docs/source/conf.py)
- [index.rst](https://github.com/PyLops/pylops-mpi/blob/main/docs/source/index.rst)
- [adding.rst](https://github.com/PyLops/pylops-mpi/blob/main/docs/source/adding.rst)

### Environment Information

```text
Platform:              linux; (Linux-6.2.0-26-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.0
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

**Comment by RobPasMue** [comment]
Yes, also seeing this issue in other repositories!

For example: 
- Repo: https://github.com/ansys/pyansys
- PR: https://github.com/ansys/pyansys/pull/335
- Workflow: https://github.com/ansys/pyansys/actions/runs/5888045275/job/15968512476?pr=335

**Comment by picnixz** [comment]
We refactored the TocTree adapter here https://github.com/sphinx-doc/sphinx/pull/11565 (which also caused some other issues e.g., https://github.com/pydata/pydata-sphinx-theme/issues/1404). However, TocTree is not meant to be a public API (there is no external documentation provided), so such internal changes should not considered as breaking changes (see https://github.com/pydata/pydata-sphinx-theme/issues/1404#issuecomment-1673713452 and https://github.com/pydata/pydata-sphinx-theme/issues/1404#issuecomment-1674070013).

Now, in order to fix this, either `pydata` fixes it upstream or we could re-expose `Toctree.get_toctree_ancestors` as:

```python
def get_toctree_ancestors(self, docname: str) -> set[str]:
    return _get_toctree_ancestors(self.env.toctree_includes, docname)
```

What do you think @AA-Turner

**Comment by sr-murthy** [comment]
Had the same error with the docs stage in one of my CI pipelines - I was leaving Sphinx unpinned, so it installed 7.2. When I switched back to 7.1.2 the error went away. I thought this was a theme error so I posted in the pydata Sphinx theme project

https://github.com/pydata/pydata-sphinx-theme/issues/1412

**Comment by AA-Turner** [comment]
Please test with [Sphinx 7.2.1](https://pypi.org/project/Sphinx/7.2.1/).
