### ISSUE TITLE
heading with :manpage: role results in failed build

### ISSUE THREAD

**Issue by dviererbe** [sphinx-doc/sphinx#11673]
### Describe the bug

When using `:manpage:` in a heading in `reStructuredText`, the manpage properties for the node does not get parsed.

### How to Reproduce

I created a repository with a minimal example: https://github.com/dviererbe/sphinx-manpage-heading-bug.

Just run `make install && make run`.

### Environment Information

```text
Platform:              linux; (Linux-6.2.0-31-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Additional context

Attaching a debugger showed that the manpage node attributes were not parsed:

```
> /path/to/project/docs/.sphinx/venv/lib/python3.10/site-packages/sphinx/writers/html5.py(751)visit_manpage()
-> node['refuri'] = self.manpages_url.format(**node.attributes)
(Pdb) node
<manpage: <#text: 'ls(1)'>>
(Pdb) node.attributes
{'ids': [], 'classes': ['manpage'], 'names': [], 'dupnames': [], 'backrefs': [], 'xml:space': 'preserve'}
```

**Comment by picnixz** [comment]
I don't know who's the maintainer for the manpage so I don't know if there was anything new since 5.x. Can you test with the latest Sphinx version?

Also, can you do it without third-party extensions? w

**Comment by dviererbe** [comment]
Take your time, it's a low priority bug ;)

**Comment by picnixz** [comment]
After investigation, it appears that the reason is because of some weird documents that are created *during* the writing phase. More precisely,

* At the very early stage of the build, titles are gathered and nodes are created from those titles. These nodes are stored in the environment. 
* Then transformations are applied. Those transformations are applied on the doctree. **However**, if a transformation modified some node which was contained in one of the nodes stored in the environment, then only the former will be affected and not the latter. 
* During the writing phase, we first write the "title". However, to write the title, what we do is restoring the nodes that were stored and use them as "fake" nodes. In particular, these nodes will *not* contain the changes that were made when a transformation passed over it. More precisely, if attributes were added after they were stored, these attributes won't be found !

**Comment by picnixz** [comment]
So, after https://github.com/sphinx-doc/sphinx/pull/11825, it appears that my PR is no more needed. I'll close the issue for now since the tests I implemented seem to pass, but feel free to re-open if *your* specific issue still occurs.
