### ISSUE TITLE
Can't allow access to my documentation for a few people.

### ISSUE THREAD

**Issue by Tuxman2** [sphinx-doc/sphinx#11726]
### Describe the bug

Hello,

I created a Linux server on which sphinx-doc is installed. My documentation created under sphinx-doc can be visible to everyone on my network. I would like a limited number of people to only have access to my documentation, but sphinx-doc does not allow this by default. How to solve this problem ?

Thanks.

### How to Reproduce

None

### Environment Information

```text
none
```

**Comment by picnixz** [comment]
Hi, this repository is only for core development. Please ask your question on Stackoverflow since it is something related to serving files. Sphinx only generates them and is not meant to know about how the files will be served later. 

Btw, if you want to only allow some people, you could setup some .htaccess to put your files behind a password. Alternatively you could make these files accessible from a vpn but you'll need to configure your server as well.
