### ISSUE TITLE
Failed to create the reference node within the custom directive

### ISSUE THREAD

**Issue by Phantom1003** [sphinx-doc/sphinx#11731]
### Describe the bug

Hi, I want to create a custom Sphinx directive that renders a Github permalink. The directive grammar is as follows:

```
.. remotecode:: <local temperary file>
  :url: https://github.com/<user>/<repo>/blob/<commit hash>/<file name>#L9-L19
```

To clarify, the above directive  will result in the generation of a block as shown below:

```
  Source code from <href to :url:>:
  ┌───────────────────────────────────────────┐
  │                                           │
  │               Github Code                 │
  │                                           │
  └───────────────────────────────────────────┘
```

So, my plan is to extend the existing LiteralInclude class to implement the required extension. I intend to define a custom directive that will return a literal_block node and a reference node. Unfortunately, while the code block is generated successfully, the reference node fails to generate.

![image](https://github.com/sphinx-doc/sphinx/assets/39120057/48698691-65a8-4a38-ba5b-5e9155cb9f0f)

I noticed that the `[source]` element is being displayed as plain text instead of a hyperlink. To figure it out, I tried hooking the visit_reference function and discovered that the generated reference node is not handled by the function. It seems like the node is eliminated before the HTML generation. I am not sure if this is due to my misunderstanding of the internal implementation or a bug. Could you please help me understand why this is happening? Thanks!

### How to Reproduce

The buggy code is at:

https://github.com/Phantom1003/rss_doc/blob/78416ce7a1c5b84f0b52f976247b9beea749388d/docs/_ext/remotecode.py#L69

You can run the extension by executing `make` under the `docs` directory.

You should get the same result, by adding the following code in the `docs/index.rst`:

```
.. remotecode:: _static/tmp/test.md
  :url: https://github.com/Phantom1003/riscv-isa-manual/blob/301d4a9f6b569f53c48094d30ab38494b705a1b6/README.md?plain=1#L9-L13
  :type: github-permalink
  :language: markdown
  :lineno-match:
  :lines: 9-15
```

### Environment Information

```text
sphinx==7.2.6
```

**Comment by picnixz** [comment]
You are incorrectly using the LiteralInclude directive. It should be used as follows:

```python
ret = super().run()[0]
if isinstance(ret[0], nodes.system_message):
   return ret

ref = nodes.reference('', _('[source]'), internal=False, refuri=url)
return [nodes.paragraph('', '', *ret, ref)]
```

That way, you have two separate nodes: one containing the code, followed by the one containing the reference. Otherwise, you reference is transformed into a 'simple' text node since it's a standalone reference.

I don't remember why it's like that but it's probably something from docutils. However, docutils doesn't explain that...

By the way, those questions must be asked on SO first since here is for core-development. I answered this question because it's related to the lack of documentation on our side. Feel free to reopen if my patch doesn't work.
