### ISSUE TITLE
Crufty code in search.html layout?

### ISSUE THREAD

**Issue by jdillard** [sphinx-doc/sphinx#11753]
### Describe the bug

I could be wrong, but it looks like the following code blocks are no longer used and could be removed since that functionality is carried out in [searchtools.js](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/searchtools.js)?

https://github.com/sphinx-doc/sphinx/blob/bb74aec2b6aa1179868d83134013450c9ff9d4d6/sphinx/themes/basic/search.html#L48-L53

https://github.com/sphinx-doc/sphinx/blob/bb74aec2b6aa1179868d83134013450c9ff9d4d6/sphinx/themes/basic/search.html#L55-L63

### How to Reproduce

Removing those blocks and using the `html` builder seem to have no negative impact, but something else I can't find could be using that template logic.

### Environment Information

```text
Links are from the `master` branch
```

**Comment by picnixz** [comment]
If we remove it, we should plan it for 8.x.

In other words, we should warn people (especially those with probably old extensions) that using custom js + custom theme extending the search layout may result in a breaking change. 

But otherwise, I agree we can remove it. Just be sure that 'search_performed' and 'search_results' are no more injected variables.

**Comment by AA-Turner** [comment]
Done in a6b0dbc5b95130d6c124bd171838c6ee431786db, thanks @jdillard!

These were used in ``websupport`` before it was split off into ``sphinxcontrib-websupport``.

A
