### ISSUE TITLE
Index and target node order changed in 7.2.0

### ISSUE THREAD

**Issue by wRAR** [sphinx-doc/sphinx#11797]
### Describe the bug

Our project (Scrapy) uses custom directives and a custom extension to handle them, and for the following text:

```rst
.. setting:: S1
.. setting:: S2

S1/S2
-----
```

the contents of `doctree.children` is different on 7.2.0 which breaks some expectations of our code. Namely, it's `index,index,target,target,section` while it was `index,target,index,target,section` before 7.2.0 (specifically before #10478).

Our code is quite old and it's possible that it does something that isn't recommended but as this is a recent undocumented behavior change I deciced to file a bug report, feel free to close this if suitable.

The code of the extension is https://github.com/scrapy/scrapy/blob/master/docs/_ext/scrapydocs.py , `collect_scrapy_settings_refs()` is called for `doctree-read` and `get_setting_target()` matches target nodes to index nodes assuming they are next to each other.

### How to Reproduce

index.rst:

```rst
.. setting:: S1
.. setting:: S2

S1/S2
-----
```

_ext/scrapydocs.py:

```python
def collect_scrapy_settings_refs(app, doctree):
    # look at doctree.children
    pass

def setup(app):
    app.add_crossref_type(
        directivename="setting",
        rolename="setting",
        indextemplate="pair: %s; setting",
    )
    app.connect("doctree-read", collect_scrapy_settings_refs)
```

### Environment Information

```text
Platform:              linux; (Linux-6.5.0-4-amd64-x86_64-with-glibc2.37)
Python version:        3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.17.2
```

**Comment by picnixz** [comment]
I agree that it's at both time an issue for us and for you.

- For us: we changed something that *could* have been a precondition for some extensions that we are not aware of. 
- For you: you likely need to change your extension and we are sorry for you. 

However, it was purposely designed as such to avoid transformations messing them up. So I don't think we should change how it's now done. I'm closing the issue because I don't think we'll revert this behaviour (I would say the pros outweight the cons in this case; you can still rely on the new structure to match what should need to be matched (like, you know now that a set of `<target>` is preceeded by a set of at most as many `<index>`).

Btw, if our current implementation does not allow you to match the `<index>` and `<target>` together, then feel free to reopen (but it should be like that I think?)

**Comment by wRAR** [comment]
Sure, thanks for your time!
