### ISSUE TITLE
Dutch Translation "Note" not "Notitie" but " Opmerking?

### ISSUE THREAD

**Issue by 3dhype** [sphinx-doc/sphinx#11968]
### Describe the bug

I'm working on the Dutch Blender Manual translation, and I'm quite positive that "Note" in most of the cases should be translated to "Opmerking" instead of "Notitie".

[#: sphinx/locale/__init__.py:227
msgid "Note"
msgstr "Notitie"
](https://github.com/sphinx-doc/sphinx/blob/e976059fd6ab49b1c2784445d7095c9287897724/sphinx/locale/nl/LC_MESSAGES/sphinx.po#L3174C1-L3177C1)

### How to Reproduce

There is no other info needed I think

### Environment Information

```text
Nothing special here.
```

**Comment by picnixz** [comment]
I don't speak Dutch, but the German translation uses "Bemerkung" which is closer to "Remark/Comment" rather than "Note/Notice". Since "Opmerking" is probably the Dutch's equivalent, I think it would be fine.

**Comment by mgeier** [comment]
I can't say anything about Dutch, but for German, I feel that "Hinweis" would be better than "Anmerkung", which would still be better than "Bemerkung".

Since "Hinweis" is already taken for "hint" (which is a very good match), probably "Anmerkung" would be the best choice here.

"Notiz" would be etymologically closer to "note" (and I guess to the Dutch "Notitie"?), but it doesn't feel appropriate to me.

**Comment by AA-Turner** [comment]
Please submit an improved translation via Transifex.

A
