### ISSUE TITLE
[task] benchmark Sphinx on Python 3.13

### ISSUE THREAD

**Issue by picnixz** [sphinx-doc/sphinx#12181]
I'm opening an issue following #12174 so that we can track how incremental GC affects Sphinx from a memory usage (docutils is strongly affected by it as shown by https://github.com/python/cpython/pull/117120#issuecomment-2015622114 and https://github.com/faster-cpython/ideas/issues/668, so I would expect the same holds for Sphinx). 

I personally won't have time to play and do the benchmarks in the next weeks so I'm leaving it to anyone who wants to do it. Otherwise I'll do it when I've got time.

### References

- https://github.com/faster-cpython/benchmarking-public

**Comment by picnixz** [comment]
Err @AA-Turner, I assume that you don't want to benchmark it? :( (or you think this issue will stay opened for a too long time)

**Comment by AA-Turner** [comment]
I was doing some quick triage this morning & it seems the GC issues for Sphinx (Docutils) have been resolved in Python. 

Benchmarking will be valuable, but (a) should be for all versions, and (b) will be difficult as we need to avoid IO in benchmarks, and Sphinx doesn't have a no-IO mode.

I do admit closure is also partially due to that we have 1000+ open issues, which I am embarrassed about...

A

**Comment by picnixz** [comment]
Ah don't worry about it! Actually, I was more interested in the new GC mechanics and how it could affect Sphinx but at least it should be lowerbounded by docutils perfs.
