### ISSUE TITLE
Enable navigation_with_keys by default in themes with responsive design

### ISSUE THREAD

**Issue by C0rn3j** [sphinx-doc/sphinx#12227]
**Is your feature request related to a problem? Please describe.**
The documentation isn't very keyboard-accessible by default.  
This is solved by an [opt-in theme feature](https://github.com/sphinx-doc/sphinx/pull/2064), which I believe should be enabled where it doesn't break the theme.  
This feature makes documentation much nicer to read with just the keyboard.

I have sent pull requests to a few projects, some of them internal, and they all decided to let the feature be turned on (or haven't responded yet). The link-throughs from people sending PRs to enable this in various project also seem to be all positively accepted.

*A single example of my PR - https://github.com/kdave/btrfs-progs/pull/754*

**Describe the solution you'd like**

Set `navigation_with_keys = True` by default in themes where it does not break sideways scrolling, for example the basic theme:

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/theme.conf#L12

**Describe alternatives you've considered**

Constantly sending PRs whenever I press arrow keys and nothing happens til eternity.

**Additional context**

At the time almost a decade ago, some of the maintainers/contributors voiced reasons against enabling this by default:

* *Navigation feature is bothering me because it is not intuitive to me*
  * Undiscovered feature is better than no feature.

* *It may be really annoying for those that are not used to it and accidentally hits left/right.*  
  * I believe encountering such accident would help discoverability, and it shouldn't confuse people too much to see things happen when they press keys

* *It breaks the normal sideways scrolling behaviour.*
  * The current default theme design is always responsive and never sideways scrolling. People using themes which do not follow this expectation, can keep this setting off.

**Comment by C0rn3j** [comment]
> Can you compile the projects that were interested in? If there are large projects, I would be willing to consider the proposal.

[btrfs](https://github.com/kdave/btrfs-progs/pull/754) and [OpenMW](https://gitlab.com/OpenMW/openmw/-/merge_requests/3930) 

There may be more that I am forgetting / unable to find, but those two are examples of bigger projects.

> How do we tell them that so that we don't break their themes once we change the default value ? did we actually say that the basic them is responsive-friendly and non-responsive features (such as navigation_with_keys) should be explicitly disabled?

I am not too familiar with the project, so this is best answered by someone else, however it could(should?) be marked as a potential breaking change mentioned along a new version release and resolved that way.

> I personally think that the basic theme should remain basic, without any additional feature and it should be up to theme authors to customize it.

While I get the sentiment, I believe the feature is fairly essential.

Try visiting [this](https://btrfs.readthedocs.io/en/latest/CHANGES.html) page and going to the next page with just the keyboard.

Now try going back and forth a few times with the arrow keys instead, which are already enabled there.

It's genuinely frustrating to me to read the documentation pages without this feature enabled, that page I linked requires me to hold TAB for solid 3 seconds to just scroll past the sections.

I am sure people who physically can't reasonably use the mouse would welcome this even more, I am just someone who has a KB+M setup but prefers using the keyboard.

**Comment by picnixz** [comment]
> There may be more that I am forgetting / unable to find, but those two are examples of bigger projects.

An alternative suggestion is that this behaviour could be enabled on RTD only, and on demand since many docs are hosted out there. What are your thoughts about it @humitos ? Let's also ask some theme and docs maintainers: Furo's @pradyunsg, PyData's @trallard and @hugovk ? If I were to ignore other's opinion, I'd say "no for the change, it's less work for us, less risk and go for PRs" (while there are projects that could require that option, most of them should be fine if you use a mouse or even a touchboard IMO).

> I am not too familiar with the project, so this is best answered by someone else, however it could(should?) be marked as a potential breaking change mentioned along a new version release and resolved that way.

There was a discussion about how we should avoid breaking themes (https://github.com/sphinx-doc/sphinx/issues/11931). A simple suggestion is to wait for 8.x for that change to land and we're done (major version, so we can break things (there should be more major versions!!))

> Try visiting [this](https://btrfs.readthedocs.io/en/latest/CHANGES.html) page and going to the next page with just the keyboard.

I can understand but at the same time I personally am not used to that, though I'm used to use arrows for reading EPUBs but not when I'm browsing around. Personally, I tend to use my down/up arrows for navigating but then if I accidently hit my left/right it's a bit annoying for me.

**Comment by trallard** [comment]
Thanks for the ping! While I can see where @C0rn3j is coming from, I believe setting the `navigation_with_keys=True` is rather opinionated and could have considerable implications for no-mouse users, which include keyboard users as well as those using other types of accessible tech, such as screen readers.

> The current default theme design is always responsive and never sideways scrolling. People using themes which do not follow this expectation, can keep this setting off.

This is not entirely accurate, for example, from the examples provided (https://btrfs.readthedocs.io/en/latest/Subvolumes.html) and in many other documentation sites, items like code blocks, tables, maps, data frames, etc. can and consistently trigger `x-scrolling` at specific breakpoints. 

See on a laptop:

![image](https://github.com/sphinx-doc/sphinx/assets/23552331/a3b641e6-2af7-4135-8d57-001b32cbb655)

vs. on a tablet where the code block now has a horizontal scroll bar (sorry if this is not visible on the image, but you can see how the block itself is overflowing)

![image](https://github.com/sphinx-doc/sphinx/assets/23552331/811a60cd-fcbd-4245-a835-5e5b57a5297c)

for these elements, `x-scroll` and `y-scroll` are essential for navigation and information access, which would be superseded by the arrow keys used to navigate across pages.

> The documentation isn't very keyboard-accessible by default.

I agree that many documentation themes and sites could be more keyboard-friendly and usable. However, per https://webaim.org/techniques/keyboard/, the arrow keys are most commonly used for scrolling (outside components like tabs and menus), especially within the context of keyboard navigation. So, adopting an opinionated pattern that differs from what most sites and apps do could introduce new friction to how many users interact with documentation sites (and cause issues with users' accessibility settings). So, I am worried that this default would defeat the original intention of making the theme more usable for disabled people.

The theme also already has `Previous` and `Next` buttons for page navigation, and I understand that perhaps reaching these with the keyboard only means a lot of `tabbing`, but the primary sidebar can also be used to navigate the documentation, and that is easier to reach per the keyboard navigation order.

Last, having this setting by default would impact several themes and maintainers, and breaking changes has been a struggle. Web accessibility and keyboard navigation are not as widely spread skills as others, so I would prefer theme maintainers and downstream dependencies to have good essential accessibility affordances by default and opinionated settings like this one being an `opt-in` configuration.

**Comment by C0rn3j** [comment]
> items like code blocks, tables, maps, data frames, etc. can and consistently trigger x-scrolling at specific breakpoints.

> on a tablet where the code block now has a horizontal scroll bar

Actually I can reproduce that on my desktop too with the tab size being just right.  
I was not aware you can trigger x-scroll on the default theme.

> and I understand that perhaps reaching these with the keyboard only means a lot of tabbing, but the primary sidebar can also be used to navigate the documentation, and that is easier to reach per the keyboard navigation order.

Both options are very unwieldy to use on certain pages, see the earlier [example](https://btrfs.readthedocs.io/en/latest/CHANGES.html) and try going forwards with either menu entries or the Next button, it's literal seconds of holding TAB either way.

> So, I am worried that this default would defeat the original intention of making the theme more usable for disabled people.

I am not sure if this would make sense for Sphinx, but would user-configurable settings make sense if this turns out to hamper accessibility?

In the case it would make sense, adding a user-configurable ON/OFF for keyboard navigation, and possibly allowing customized keybinds too would solve this, enabling easy keyboard navigation for everyone, while at the same time allowing for disabling it in case someone had some sort of a special/accessibility setup which relied on arrow keys.

RTD already has an expandable menu where this could be possibly added in without visually changing the main view, if adding a cogwheel somewhere were undesirable:

![image](https://github.com/sphinx-doc/sphinx/assets/1641362/5f5ffc7a-8dc7-41b2-8770-b72bbd04a329)

**Comment by trallard** [comment]
> I am not sure if this would make sense for Sphinx, but would user-configurable settings make sense if this turns out to hamper accessibility?

> In the case it would make sense, adding a user-configurable ON/OFF for keyboard navigation, and possibly allowing customized keybinds too would solve this, enabling easy keyboard navigation for everyone, while at the same time allowing for disabling it in case someone had some sort of a special/accessibility setup which relied on arrow keys.

Do you mean at the end-user level configurations? As in, I want to use arrows, so I remap arrows? 
I am not sure how this would work or how much work it would be, but my initial gut feeling is that it might be worth more effort than it is worth. Perhaps having this as a plugin would make more sense. 

Also I would like to be really careful about wording per 

> adding a user-configurable ON/OFF for keyboard navigation, and possibly allowing customized keybinds too would solve this,

As this _would_ only relate to "navigating pages with arrow keys" keyboard navigation (`TAB`, `Shift + TAB`, `arrows`) should _always_ be possible by default and not obscured/disabled in the expectation that users have to enable this. 

> Both options are very unwieldy to use on certain pages, see the earlier [example](https://btrfs.readthedocs.io/en/latest/CHANGES.html) and try going forwards with either menu entries or the Next button, it's literal seconds of holding TAB either way.

I manually checked the navigation order and keyboard navigation before when checking the scrolling behaviour. Yes, it is seconds of holding TAB, but that is often the only way users can navigate the web and access information. Having all those keyboard-focusable elements across all the docs sections makes it possible for disabled and fully-abled users alike to use the theme so I am personally not bothered if I have to TAB (I do this all the time as I work on accessibility-related things and also sometimes cannot use a mouse or pointing device because reasons).

**Comment by picnixz** [comment]
> I am not sure if this would make sense for Sphinx, but would user-configurable settings make sense if this turns out to hamper accessibility?

At this stage, I honestly think it's for an extension/plugin and not Sphinx core anymore. Sphinx does not really care about *how* the documentation is served and is solely responsible to *generate* it (that's why I suggested having this feature on RTD instead; if you configure your project with some "yes/no", then the generated conf.py would be updated accordingly).  

> Last, having this setting by default would impact several themes and maintainers, and breaking changes has been a struggle.

I remember 7.2 (sorry again). I also stick to my argument that the basic theme should be basic. Not just because it's named as such, but also because it can be used for unit-testing where you don't have features by default.

---

Having thought about it, I vote against this change (for now, I'll leave the issue open for discussion). Nonetheless, having the possibililty to change this setting on RTD with a simple button would be good (it could be stored as a simple cookie and your browser would rememeber your choice).

**Comment by trallard** [comment]
> I remember 7.2 (sorry again). I also stick to my argument that the basic theme should be basic. 

No shade here at all. We all have loads on our plate and y'all were super prompt at dealing with this and it was noted and appreciated.

**Comment by C0rn3j** [comment]
Thanks to the both of you for providing context and additional information, I've opened [an issue](https://github.com/readthedocs/readthedocs.org/issues/11266) downstream on RTD about this.

> As this would only relate to "navigating pages with arrow keys" keyboard navigation (TAB, Shift + TAB, arrows) should always be possible by default and not obscured/disabled in the expectation that users have to enable this.

My only suggestion is to modify the the page flipping feature and its associated LeftArrow/RightArrow keys, WITH the additional possibility to possibly override those arrow keys with something else, so fast page flips are still possible, but perhaps not by conflicting with x-scroll keys.

**Comment by pradyunsg** [comment]
I realise I was mentioned to ask for inputs -- I don't have much to add on top of what @trallard has already mentioned here.

If you're looking for opinions: I'd prefer that this stay opt-in. To be honest, I wish themes could just straight up remove not have option inherited from the basic theme (since I would like to do that in Furo) but, oh well, that's a separate discussion that we can defer. :)

**Comment by picnixz** [comment]
> I'm maintaining [python/python-docs-theme](https://github.com/python/python-docs-theme) rather than PyData

Ah, sorry for the misunderstanding! I should have added a comma before the 'and'.

Considering the above opinions, I am closing this issue as "not planned". Thank you everyone for the discussion (feel free to open separate issues for the other topics that were raised).

**Comment by humitos** [comment]
I just saw that I was mentioned in this issue. I feel represented by what @trallard said in her comments as well and I don't have too much to add here.

_However_, regarding Read the Docs, **we are moving away from modifying project's behavior behind the scenes** (like manipulating the `docs/conf.py` file to change a setting). We already started this process for MkDocs and its `mkdocs.yml` file (see https://about.readthedocs.com/blog/2024/03/mkdocs-yaml-manipulation/) and we plan to start the same process for Sphinx soon. There are many reason behind this decision, but the most clear and easy one to explain is "parity with local build" 😄 

So, we won't add `navigation_with_keys = True` to the project documentation's `conf.py` file and we will leave this decision to the documentation authors as mentioned on this issue as well. They should be the responsible about enabling/disabling this setting.

On the other hand, we have been talking internally about "readers features" and we've implemented some of these ideas as addons (https://github.com/readthedocs/addons), I think we can continue discussing the "per-user configuration" idea you raised here instead of "per-project configuration" --but there are a bunch of things to consider here, starting by the user is not logged in into the documentation domain.

Oh, by the way, we already have an addons that's called `hotkeys.js` 😄 that we can expand if we find a clear way to move forward with this proposal. I will continue this conversation in the issue that you open on Read the Docs 👍🏼
