### ISSUE TITLE
Remove the recommendation about the bundled package

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#12318]
> I think we should just remove the recommendation about the bundled package and rather suggest using `pip` in the first place.

_Originally posted by @picnixz in https://github.com/sphinx-doc/sphinx/issues/12239#issuecomment-2058509129_

**Comment by picnixz** [comment]
I personally think we should recommend virtualenv + pip in the first place; at least, we won't have any surprises (or there should be none!) @n-peugnet do you follow me for that call?

**Comment by n-peugnet** [comment]
IMO virtualenv + pip is a safe and portable default that would work as expected everywhere. The virtualenv part should be mandatory in the install instructions [instead of recommended afterwards currently](https://www.sphinx-doc.org/en/master/usage/installation.html#using-virtual-environments).
The [README](https://github.com/sphinx-doc/sphinx?tab=readme-ov-file#installation) should also be updated, maybe as a link to the installation page?

Another possibility would be to recommend [pipx](https://pipx.pypa.io/stable/) as suggested in [the pip install warning](https://veronneau.org/python-311-pip-and-breaking-system-packages.html). I'm not used to this tool but is seems like a fine way to install python CLI tools with dependency isolation.

I don't think the recommendation to use system packages should be removed. For most of the people this is probably the easiest way to install Sphinx, but maybe a warning should be added that mixing user installed pip and system packages can cause issues?

**Comment by timhoffm** [comment]
Is this sufficiently addressed through #12458?

**Comment by chrisjsewell** [comment]
Let's say yes cheers, and can always re-open if necessary
