### ISSUE TITLE
ext.napoleon to work with ext.todo

### ISSUE THREAD

**Issue by raybellwaves** [sphinx-doc/sphinx#12343]
**Is your feature request related to a problem? Please describe.**
I would like to use the todo extension with the napoleon extension

**Describe the solution you'd like**
I can use the todo extension with the napoleon extension

**Describe alternatives you've considered**
I'm not sure how to write a todo plugin for the napoleon extension

**Additional context**
There was an issue previously but it was closed due to lack of interest https://github.com/sphinx-doc/sphinx/issues/1837

**Comment by electric-coder** [comment]
Using [`sphinx.ext.todo`](https://www.sphinx-doc.org/en/master/usage/extensions/todo.html#module-sphinx.ext.todo) while using napoleon works. You can also use the [`Todo` docstring section](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections). Can you give an example of what isn't working?

**Comment by picnixz** [comment]
I see that you actually opened a discussion for that but since we did not have time for that we probably forgot about it (Adam and I are really busy these past weeks and I personally don't look much at the discussion tab). I'm closing the issue so people who have time to help should answer here: https://github.com/orgs/sphinx-doc/discussions/12306
