### ISSUE TITLE
sphinx raises an exception when trying to build python 3.13 doc with devhelp

### ISSUE THREAD

**Issue by danigm** [sphinx-doc/sphinx#12416]
### Describe the bug

Sphinx raises an exception when trying to build the Python 3.13 documentation:

```sh
$ cd Doc
$ sphinx-build -a -b devhelp . build/devhelp
...
dumping devhelp index...
 
Exception occurred:
File "/usr/lib/python3.11/site-packages/sphinx/environment/__init__.py", line 603, in get_doctree
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/Python-3.13.0b2/Doc/build/devhelp/.doctrees/index.doctree'
```

This is due to the removal of `master_doc = 'contents'` in the `conf.py` file done in this PR: https://github.com/python/cpython/pull/117853

I've reported this in cpython project: https://github.com/python/cpython/issues/120150, but maybe the problem is in sphinx or sphinxcontrib-devhelp project.

### How to Reproduce

Download python 3.13 beta code and try to build the doc:

```
$ cd Doc
$ sphinx-build -a -b devhelp . build/devhelp
```

### Environment Information

```text
Platform:              linux; (Linux-6.9.1-1-default-x86_64-with-glibc2.39)
Python version:        3.11.9 (main, Apr 08 2024, 06:18:15) [GCC])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.4
Pygments version:      2.18.0

OS:                    **openSUSE Tumbleweed**
sphinxcontrib-devhelp: **1.0.6**
```

### Sphinx extensions

```python
extensions = [
    'asdl_highlight',
    'c_annotations',
    'escape4chm',
    'glossary_search',
    'peg_highlight',
    'pyspecific',
    'sphinx.ext.coverage',
    'sphinx.ext.doctest',
    'sphinx.ext.extlinks',
]
```

**Comment by picnixz** [comment]
First of all, the docs are very slow to build on my side but I don't know whether the issue is because of Sphinx, CPython or me. Second, have you tried wiping out a possible existing `build` folder? and thirdly, when is the exception occurring: is during the read or the write phase? because I have no issue in the reading phase and the writing phase starts correctly (though it's still ongoing..).

**Comment by picnixz** [comment]
So the docs are finally done and indeed there is an issue (I've got the same as you). Mmh, I don't know what happened. I'll try investigating.

**Comment by picnixz** [comment]
Ok, the `devhelp` build is ASTRONOMICALLY slow. What's the reason? I don't know. I don't have an issue with building the files for Sphinx but Python is hanging for some reason. So it should not be my disk. 

Anyway, I understood what happens. We have:

```python
	'master_doc': _Opt('index', 'env', ()),
	'root_doc': _Opt(lambda config: config.master_doc, 'env', ()),
```

meaning that, by default, `master_doc` is set to 'index' and that `root_doc` is set to `master_doc`. If you set `root_doc`, then `master_doc` will *not* be correctly reflected, so you'll end-up with an invalid value. 

The issue is that `sphinxcontrib-devhelp` is using `self.config.master_doc` instead of `root_doc` so I'll change that on the other repo. Note that I don't have permissions to publish on pypi =/
