### ISSUE TITLE
Linkcheck reports broken Anchor not found

### ISSUE THREAD

**Issue by madmiraal** [sphinx-doc/sphinx#12688]
### Describe the bug

This was previously reported in #10985, which was closed, because it was considered an intermittent failure attributed to the destination website. However, I get this error consistently when pointing to an anchor on GitHub for example https://github.com/sphinx-doc/sphinx#features; so I'm opening a new issue.

### How to Reproduce

`index.rst`:
```
https://github.com/sphinx-doc/sphinx#features
```
`conf.py`: empty
Link check:
```
sphinx-build -b linkcheck . _linkcheck
```

### Environment Information

```text
Platform:              linux; (Linux-6.1.0-23-amd64-x86_64-with-glibc2.36)
Python version:        3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

```python
None
```

**Comment by jfbu** [comment]
I know nothing about all this but fwiw I found
```
<a id="user-content-features" class="anchor" aria-label="Permalink: Features" href="#features">
```
inside the `response.text` from the Response object in `found = contains_anchor(response, anchor)` used by linkcheck.py.

and indeed using
```
    parser = AnchorCheckParser('user-content-' + anchor)
```
as a test in `contains_anchor()` coerced the output to be positive.

**Comment by jayaddison** [comment]
@madmiraal thank you for the bugreport!

I can't seem to locate an HTML element with an `id` of `features` on the page initially, based on a `jQuery` query in the browser console:

```javascript
// https://github.com/sphinx-doc/sphinx#features
$('#features')
null
```

...and as a result of that, I suspect that this is another instance of https://github.com/sphinx-doc/sphinx/issues/9016 - for which a fix was previously implemented but had to be reverted.

If the description of that issue seems to fit, you could try uncommenting this event handler to check whether the anchor is reported as found:

https://github.com/sphinx-doc/sphinx/blob/0d912c85fd3ec385432fe707f6a0678425d1e841/sphinx/builders/linkcheck.py#L727-L729

The handler adjusts some page fragments to insert the `user-content-` prefix that @jfbu alluded to -- that element _does_ exist on the page:

```javascript
$('#user-content-features')
<a id="user-content-features" class="anchor" aria-label="Permalink: Features" href="#features">
```

...however, it is known to introduce regressions (#9435) related to other HTML anchors on GitHub, and does not seem to be a generalizable fix in its current form.
