### ISSUE TITLE
py:attribute

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1282]
Hello,
I want to document class variables via autodoc. For this task I use ":attribute name: some text" syntax, but the rendering is not really nice. 

It renders as:

```
#!text

 <purple box start>Attribute name:<purple box end>Some text
```

and not like function parameters as:

```
#!text

 <purple box start>Parameters:<purple box end>name - Some text
    next_one - Some more text
```

The problem with the current rendering is that with longer attribute names the box takes the whole width. And that a group of attribute descriptions look ugly, so I would be happy if the rendering could be changed like for parameters.

Regards

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1282
- Originally reported by: Anonymous
- Originally created at: 2013-10-03T16:33:26.922

**Comment by tk0miya** [comment]
This image is attached on original issue:
![bad](https://user-images.githubusercontent.com/748828/37156276-f978713c-2328-11e8-9ebb-e4facdbaf159.png)

**Comment by tk0miya** [comment]
With latest Sphinx (v2.0.1), the class is rendered as following:

**alabaster theme**
![スクリーンショット 2019-06-02 12 29 40](https://user-images.githubusercontent.com/748828/58756357-44c30000-8532-11e9-82b2-280066fea6a5.png)

**classic theme**
![スクリーンショット 2019-06-02 12 30 14](https://user-images.githubusercontent.com/748828/58756359-4bea0e00-8532-11e9-9fc5-4b9111c2fc43.png)

It seems this problem has been already resolved. So closing this now.

Input:
```
.. py:class:: Page(namespace, tile)
   :module: database

   :attribute id: Primary key of the page. Immutable.
   :attribute namespace: The namespace (group of pages, often with special functions) of the page.
   :attribute title: The system title of the page without namespace prefix. Can change.
```

Note: it would be better to use `.. py:attribute`` directive to describe attributes instead of field lists.
