### ISSUE TITLE
Module omitted from index can be linked in Sphinx 8.0.2, fails in 8.1.3

### ISSUE THREAD

**Issue by nedbat** [sphinx-doc/sphinx#13059]
### Describe the bug

In the coverage.py docs, I use `.. module:: coverage` in a few places.  They all have `:no-index:` on them.  Sphinx 8.0.2 let me use ":mod:\`coverage\`" to refer to the module.  Upgrading to Sphinx 8.1.3 causes a warning:
```
/Users/ned/coverage/trunk/doc/api.rst:12: WARNING: py:mod reference target not found: coverage [ref.mod]
```
If I remove `:no-index:` from one of the directives, then the link is made correctly.

### How to Reproduce

To reproduce, clone the [coverage.py repo](https://github.com/nedbat/coveragepy/) and run `tox -e doc`.   Three commits of interest:

- [5369f8ad](https://github.com/nedbat/coveragepy/commit/5369f8ad811aaf86771a77b8598ef21fd97a1c16): Sphinx 8.0.2 with the docs building correctly
- [13a52255](https://github.com/nedbat/coveragepy/commit/13a52255303676fdd05bebaeaf791d6a85f72e55): Upgrade to Sphinx 8.1.3, generates a warning, no link created
- [c179fb2f](https://github.com/nedbat/coveragepy/commit/c179fb2f568888d83d9625039e729ed3e1efbcc4): Removed `:no-index:`, all builds properly.

### Environment Information

```text
Platform:              darwin; (macOS-14.7-arm64-arm-64bit)
Python version:        3.11.10 (main, Oct 20 2024, 13:53:59) [Clang 16.0.0 (clang-1600.0.26.3)])
Python implementation: CPython
Sphinx version:        8.1.3
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

**Comment by AA-Turner** [comment]
I think that this is related to #12844, but I’m not able to check at the moment.

**Comment by electric-coder** [comment]
> [c179fb2f](https://github.com/nedbat/coveragepy/commit/c179fb2f568888d83d9625039e729ed3e1efbcc4): Removed `:no-index:`, all builds properly.

I read the code containing `.. module:: coverage` and it's used once without `:no-index:` in [`api_module.rst`][1] and twice with `:no-index:` in [`api_coverage.rst`][2] and [`api_coveragedata.rst`][3]... There's no instance of [`.. automodule:: coverage`][4]

> If I remove :no-index: from one of the directives, then the link is made correctly.

This is expected behavior..! Those reST directives are declarations, so at least one of them has to be inserted into the index in order for the cross-reference ```:mod:`coverage` ``` to have a valid target. I'm not sure if I'm following but I'm pretty certain that's always been the Sphinx behavior since at least Sphinx 5.

[1]: [api_module.rst](https://raw.githubusercontent.com/nedbat/coveragepy/c179fb2f568888d83d9625039e729ed3e1efbcc4/doc/api_module.rst)
[2]: https://raw.githubusercontent.com/nedbat/coveragepy/c179fb2f568888d83d9625039e729ed3e1efbcc4/doc/api_coverage.rst
[3]: https://raw.githubusercontent.com/nedbat/coveragepy/c179fb2f568888d83d9625039e729ed3e1efbcc4/doc/api_coveragedata.rst
[4]: https://github.com/search?q=repo%3Anedbat%2Fcoveragepy%20..automodule%3A%3A%20coverage&type=code
