### ISSUE TITLE
autodoc private-members doesn't work for class attributes

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1362]
Documenter.filter_members should take a look at attr_docs in case of private_members.

special-members seems to have the same problem.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1362
- Originally reported by: Anonymous
- Originally created at: 2014-01-27T07:09:45.822

**Comment by bitprophet** [comment]
I can confirm this in 1.3b3.

Example docs `rst` file:

```
.. autoclass:: mymodule.MyClass
    :members:
    :private-members:
```

When `mymodule` looks like this, the `defaults` attribute appears in rendered docs:

``` python
class MyClass(object):
    def __init__(self):
        #: These are the defaults!
        defaults = "whatever"
```

Simply change it to this, however, and `defaults` disappears, and is not replaced by `_defaults` in the docs:

``` python
class MyClass(object):
    def __init__(self):
        #: These are the defaults!
        _defaults = "whatever"
```

**Comment by TheMagSec** [comment]
This issue is still there!
I had the issue when I wanted to create an in-house developer documentation.
Therefore I also wanted the private-protected variables and class constants be documented.

## Example:

``` python
class Foo(object):
    #: foo is a list for ...
    __foo = []
    __bar = None
    """
    bar stores ...
    """
    # [...]
```

## Solution:

in `sphinx.util.inspect` change the function `safe_getattr`:

``` python
def safe_getattr(obj, name, *defargs):
    """A getattr() that turns all exceptions into AttributeErrors."""
    try:
        if name.startswith("__") and not name.endswith("__"): # <-+ these lines
            obj_name = obj.__name__                           #   | have to be
            if "_%s%s"%(obj_name,name) in obj.__dict__:       #   | added
                name = "_%s%s"%(obj_name,name)                # <-+ 
        return getattr(obj, name, *defargs)
    except Exception as error:
        # this is a catch-all for all the weird things that some modules do
        # with attribute access
        if defargs:
            return defargs[0]
        raise AttributeError(name)     
```

this will remove the error.
To remove the internal namespace, of protected class constants in the generated docs, change the function `filter_members` inside `sphinx.ext.autodoc`:

``` python
def filter_members(self, members, want_all):
    # [...] 
    for (membername, member) in members:
        # [...]
        elif want_all and membername.startswith('_'):
            # ignore members whose name starts with _ by default
            keep = self.options.private_members and \
                            not membername.startswith('_'+namespace) and\  # <- ADD THIS LINE
                            (has_doc or self.options.undoc_members)    
        # [...]
```

**Comment by Foodyborris** [comment]
Hi,

I've been having this issue with sphinx (1.4.6). I've tried the above suggestion from MagSec-Arts  but not had any luck. I've learnt about (again?) about name mangling, which helps me understand what the code is trying to do. But the mangled entries just don't exist in the object's **dict** when sphinx looks. If I instanced once of the troublesome classes and then print it's **dict**, the symbol is present. I guess this is due to sphinx trying to work from just the module import. My python is 3.4.2 (wish there was a stable 3.5 package for debian jessie by now!).

Has anyone made the above patch work? If so, what version of sphinx and python did you use please?

Any pointers would be much appreciated - at present it feels like this has never worked, but I can't believe that!

**Comment by Foodyborris** [comment]
Ah, I am asking for something different. I am wanting to document instance attributes set in **init**.
