### ISSUE TITLE
Adding CSS and javascript files from extensions

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1379]
It does not seem possible (let alone trivial) to inject CSS or JS content from a sphinx extension, not without serious contorsions anyway:
- It's easy to do for the project owner by editing `conf.py`
- It's specifically supported for theme authors using `css_files` and `script_files`

For an extension however I have not found it, the only hook I've managed to dig is connecting to `html-page-context` and injecting stuff inline in `context['metatags']`, which feels like a hack and a misuse of the hook. On top of that, it forces the content inline and prevent minimization by sphinx (not that sphinx does minification at the moment, as far as I know) or styles and scripts being injected only where relevant (that is, on documents where the directive or role they're working with was used).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1379
- Originally reported by: [masklinn](https://bitbucket.org/masklinn)
- Originally created at: 2014-02-05T18:42:21.068

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-02-05 17:55:01+00:00_

Could you just use the extension's [setup(app)](http://sphinx-doc.org/extdev/tutorial.html#the-setup-function) method to call [app.add_javascript](http://sphinx-doc.org/extdev/appapi.html#sphinx.application.Sphinx.add_javascript) and [app.add_stylesheet](http://sphinx-doc.org/extdev/appapi.html#sphinx.application.Sphinx.add_stylesheet)?

**Comment by shimizukawa** [comment]
_From [masklinn](https://bitbucket.org/masklinn) on 2014-02-15 17:49:47+00:00_

Not sufficient, these methods only add the provided file paths (prefixed with `_static`) to the generated pages, they don't publish the files themselves to `_static`. So the user of the extension would also have to add the file paths to his `html_static_path`, and thus the extension also has to provide a way to get these paths (and pray it is not a zip/an egg).

**Comment by shimizukawa** [comment]
_From [masklinn](https://bitbucket.org/masklinn) on 2014-02-19 07:55:04+00:00_

So worked around the issue thus: add a sub-directory of the package to the config's `html_static_path` on the fly and use `add_javascript` and `add_stylesheet` to inject those into the document:

```
#!python
env.config.html_static_path.append(
    os.path.join(os.path.dirname(__file__)),
    'static')
env.app.add_stylesheet(stylesheet)
env.app.add_javascript(script)
```

This works-ish but:
- depending on the names picked for the static files, it may collide with theme or user-provided file names. It may be possible to alleviate that issue a bit by creating a sub-directory named after the extension
- it will absolutely definitely not work with zipped modules, since it needs an actual filesystem directory

**Comment by svenevs** [comment]
For clarification for those reading this, the following statement is **crucial**:

> - it will absolutely definitely not work with zipped modules, since it needs an actual filesystem directory

Specifically, assuming you are using `setuptools` / have a `setup.py` for installing your extension, you **must** be setting `zip_safe=False` (more info [here](http://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=zip_safe#setting-the-zip-safe-flag)).

There's a lot more going on in terms of making sure those static files actually get installed (lookup `MANIFEST.in` for examples), but I wanted to link to how to make sure you don't end up with a zipped module :wink:

**Comment by shimizukawa** [comment]
Now a day, `.egg` package is deprecated and `.whl` package is always extracted and installed. So, I think this problem will no longer occur.

If such a problem still occurs, please don't use `zip_safe=True` option for such sphinx extension packages that include CSS or JavaScript, and also theme package.

**Comment by AmatanHead** [comment]
@shimizukawa So this issue is closed but as far as I can see there's still no way to add css from extensions. The proposed workaround doesn't work if called from extension's `setup()` function because user can overwrite `'html_static_path'` in `conf.py`.

The only way that I've found to make this work is fiddling with `app.config._raw_config`:

```python
def setup(app):
    app.config._raw_config.setdefault('html_static_path', []).append(
        os.path.join(os.path.dirname(__file__), '_static')
    )

    app.add_stylesheet('my_plugin.css')

    return {
        'version': '1.0.0',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }
```

This seems ugly and unsafe but at least it works... Is there any better way of doing this?

**Comment by svenevs** [comment]
@AmatanHead yes that is unsafe :wink: that prevents the user from having custom css / javascript.

Instead of `app.config._raw_config.setdefault` you can just `append` a string (or multiple) to `app.config.html_static_path` list.

I'm linking you to the (somewhat chaotic) code [I am currently using to do this stuff](https://github.com/svenevs/exhale/blob/c61b32e59b34c11ed1a468f0a0e342037a43d8a4/exhale/configs.py#L1783-L1808).

As long as you `append` the right path you should be good to go. Please let me know if that doesn't solve it for you!

**Edit**: also, the original clarification I made was talking about making sure you do `zip_safe=False` in the `setup.py`, **not** in the Sphinx `setup(app)` method. What you are asking about here (appending to `html_static_path`) is the second part of the puzzle :slightly_smiling_face:

**Comment by AmatanHead** [comment]
@svenevs hmm I'm experiencing quite the opposite. Appending to `app.config.html_static_path` only works if user have no `html_static_path` in theirs `conf.py` (because what you essentially do is appending to the default value). Appending to `app.config._raw_config.setdefault` accounts for that case. I still think we should add an official API for this (a hook, maybe?).

**Comment by AmatanHead** [comment]
Also, it seems that you have to insert new static paths to the beginning of array instead of appending. This way users can override default css files by adding files with same names to their own static directory.

**Comment by shimizukawa** [comment]
IMO you should not modify `app.config.html_static_path` from extension.
Extension can use `app.add_css_file` (that renamed from `app.add_stylesheet` since 1.8).
http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file

BTW This issue is too old to discuss.
Please use mailing list instead https://groups.google.com/forum/#!forum/sphinx-users
Thanks

**Comment by AmatanHead** [comment]
Posted a thread on the mailing list: https://groups.google.com/d/msg/sphinx-users/Z-wcktOhIAc/pGDWO0yVBQAJ

**Comment by smheidrich** [comment]
Just copying @tk0miya's very useful answer from that mailing list thread here so people don't have to click back and forth:

-----

>I guess your goal is copying CSS files properly, not modifying config
object. Hence it is better to provide a way to copy them easily.
Is this right?

>At present, you can do it with following code: 

```python
from sphinx.util.fileutil import copy_asset

def copy_asset_files(app, exc):
  asset_files = [...]
  if exc is None: # build succeeded
    for path in asset_files:
      copy_asset(path, os.path.join(app.outdir, '_static'))

def setup(app):
  app.connect('build-finished', copy_asset_files)
``` 

> I think this code is enough simple. What do you think? Would you like to add another API to do that? 

-----

Note from myself: Personally, I think it would be great if this was in the docs somewhere, because "add custom JS/CSS file" seems like it'd come up a lot in extension development, and when looking for examples in existing sphinxcontrib extensions, the solutions I found were a bit meh. E.g. [findanything does this](https://github.com/sphinx-contrib/findanything/blob/3ee1369ffd58a2fa32683275d540172ad73c5f2c/sphinxcontrib/findanything/__init__.py#L180-L202) using the same "modify config then use `add_js_file` (then called `add_javascript`)" hack that was rightly discouraged here.

EDIT: I guess it's already kind of documented in the docs on theming: https://www.sphinx-doc.org/en/master/development/theming.html#add-your-own-static-files-to-the-build-assets
