### ISSUE TITLE
apidoc: module names with trailing underscore must be escaped in the section title

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1451]
For instance, if my module is named "mymodule_" then apidoc will generate:

``` rst
mypackage.mymodule_ module
--------------------------

.. automodule:: mypackage.mymodule_
    :members:
    :undoc-members:
    :show-inheritance:
```

Unfortunately the underscore in the section title will be considered as markup, so it need to be escaped (but everything is fine in the automodule directive)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1451
- Originally reported by: Pierre Augeard
- Originally created at: 2014-04-11T10:36:43.291

**Comment by ijmorlan** [comment]
I'm running into the same problem. This is not as weird as one might initially assume as one technique that is sometimes used to make a Python identifier that is essentially but not identical to a Python keyword is to append an underscore.

For example, in at least one HTML generation library, HTML attributes become keyword parameters. A common attribute is "class" for specifying CSS classes. But "class" is a Python keyword. So the keyword parameter is called "class_".

Similarly, I have a module which can reasonably be called "print" (within a containing package), so the actual name is "print_". As a result this bug is manifested when using sphinx-apidoc for all packages contained within the print_ package.

I verified that escaping the underscore in the title by inserting a backslash silences the error message and makes the output page look right.

**Comment by eric-wieser** [comment]
Related to #519, and #1462?
