### ISSUE TITLE
namedtuple subclasses do not render appropriate docstrings

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1484]
Documenting a subclass of a `namedtuple` will render without errors but will not display the appropriate docstrings. See this example:

https://github.com/biocore/scikit-bio/blob/69c69a287d382a10fe6f0d609cb0d1207af41022/skbio/math/stats/ordination/base.py

Which yields the following page:

![Screen Shot 2014-06-09 at 6.37.09 PM.png](https://bitbucket.org/repo/7zgG/images/1103170020-Screen&#37;20Shot&#37;202014-06-09&#37;20at&#37;206.37.09&#37;20PM.png)

http://scikit-bio.org/generated/skbio.math.stats.ordination.OrdinationResults.html#skbio.math.stats.ordination.OrdinationResults

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1484
- Originally reported by: Yoshiki Vazquez-Baeza
- Originally created at: 2014-06-10T02:37:59.664

**Comment by RobRuana** [comment]
This appears to be a deep issue with namedtuple that other people have also had problems with – see [here](http://bugs.python.org/issue19931) and [here](http://bugs.python.org/issue16669).

It looks like the example was built using the numpydoc extension, which has been updated to compensate for this issue since it was originally filed.

For what it's worth, I've added some tests to the napoleon extension which verify it handles the given example and uses the class level docstring `Attributes` to override the default namedtuple property docstrings.
