### ISSUE TITLE
ifconfig parsing false condition?

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1635]
Hi,
it seems to me that a block encapsulated in a ifconfig block is parsed no matter if the condition is false or not. Is it intended to do so? It may improve performance skip such a block....

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1635
- Originally reported by: Andrea Cassioli
- Originally created at: 2014-12-01T12:47:13.649

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-12-01 13:34:52+00:00_

The reason is dependent on the processing stages of the Sphinx.
http://sphinx-doc.org/extdev/tutorial.html#build-phases
- On phase 1 (Reading), all reST sources will be converted into node tree format and will be stored on the disk. `ifconfig` directive will convert the child block into ifconfig node too.
- On phase 4 (Writing), doctrees will be converted into output format (html, latex, ..). ifconfig node will also be converted if expression of ifconfig node is True.

Therefore, I must say it's a specification.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-12-01 15:47:18+00:00_

Well, the condition could also be evaluated when reading, except for the "builder" key that's also added, this one is only known at writing time.

**Comment by andreacassioli** [comment]
What about two different keyword to distinguish or an option like

```
.. ifconfig: standard condition


.. ifconfig-writer: another condition:

```

To avoid confusion I would suggest to have an official if-statement'  for excluding blocks as

```
.. if-block: a condition

   ...

```

and possibly a role like

```
bla bla :if-cond:`bla`

Of course one can achieve this writing extensions and the like, but the docs lose readibility. 
```

**Comment by Cilyan** [comment]
I'm faced with the same kind of problem, where substitutions are not always defined. The ifconfig was supposed to protect these, but as it runs after, I still get the warnings.

I was wondering why the ifconfig post-processing is hooked to the event `doctree-resolved` instead of using a (possibly high-priority) transform? Is it just historical? (I noticed that when the extension was created, transforms were not in place in Sphinx, and the extension was not modified in its inner working since.) Or is there a reason?

The idea behind, would be to remove the parts of the tree as early as possible at the beginning of phase 3, so that it limits the number of issues the "to-be-removed-anyway" nodes may raise. I understand why the removal is not done at phase 1 (caching of doctree), but am I misunderstanding something when I suggest that this could be moved at the beginning of phase 3 instead of at the end of it?

**Comment by tk0miya** [comment]
AFAIK, there is no reason not to run ifconfig-processing on early of doctree-resolved phase. I don't opposite to change it.

**Comment by Cilyan** [comment]
Thanks for the answer.

This is my go at creating such a directive (renamed so that it can act as an extension and not conflict with the original ifconfig). It works for my use-cases, I did not test it extensively yet.
https://gist.github.com/Cilyan/f6d3e5ba1c446ac765d349ad4167936b

Do you think it is worth that I propose a PR to change the original sphinx.ext.ifconfig and start a discussion?

**Comment by tk0miya** [comment]
Hmm? It seems your code goes removal of ifearly nodes on the reading phase (phase1), not the beginning of the resolving phase (phase 3). As you said above, it should not be done at that phase. So I can't accept your change.

**Comment by Cilyan** [comment]
Oh... does it? From reading the code, I understood that the transforms are called after reading (or loading from doctree) and after check_consistency... Did I mistake this with post transforms? I need to have a deeper look then...

**Comment by Cilyan** [comment]
Okay, I better understood when the transforms are called. I did not see that the reading phase called the entirety of docutils' publish with a DummyWriter, I thought this was the other way round especially as looking roughly at what was pickled in the doctree, I thought that the substitutions were done also after the pickle file had been loaded back.

So it seems that our needs do not align. For my case, I need to make the decision before substitutions occur, and I want them (substitution values and conditions) to be correlated. So if the cached files already contains the substitution values, then there is no reason to cache branch content, as if a value is changed I will want the tree to be rebuilt also.

Now I understand better why the ifconfig is not implemented as a Transform. Thanks for the help, this will simplify my implementation, but clearly it has its place as an extension and cannot replace the original ifconfig, they both have different goals.

**Comment by tk0miya** [comment]
Yes, standard transforms are called during the reading phase. The substitution is one of them. The overview of sphinx core events illustrates how Sphinx processes document internally.
https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events

Now ifconfig processing (filtering) has been invoked at `doctree-resolved` event. And the comment "I don't opposite to change it" means moving it to "13. apply post-transforms". It seems that change does not help your case. So let's keep as is.

**Comment by tk0miya** [comment]
BTW, there is nothing to do for this issue because the conditions should be evaluated in the resolving phase to go incremental builds. So I'm closing this now.
