### ISSUE TITLE
exclude_patterns not used for static files copied from the theme

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1644]
See the description of issue #540

The bug has been closed without a fix for some reason but the issue may be legitimate.

I have the issue with sphinx 1.1.3.
My theme contains .svn directories and these are copied despite the configuration of the exclude_patterns option.

I have tried 2 config:

```
#!python

#exclude_dirnames = ['.svn']
exclude_patterns = ['**/.svn']
```

and 

```
#!python

exclude_dirnames = ['.svn']
exclude_patterns = ['**/.svn']
```

None works. If one looks at the code quoted in issue #540, one can see that the static files copied from the theme are not filtered, neither by exclude_patterns nor by exclude_dirnames.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1644
- Originally reported by: Jean-Michel Pichavant
- Originally created at: 2014-12-04T18:10:14.525

**Comment by tk0miya** [comment]
Now `exclude_patterns` does not effect to templates directory.
http://www.sphinx-doc.org/en/1.4.9/config.html#confval-exclude_patterns

But, at this moment, Sphinx does not copy dotfiles on template directory.
So I believe this issue is already resolved.

So I close this issue.
Please reopen if you have another problem.

Thanks,
