### ISSUE TITLE
Latex writer should not translate Greek unicode, but use textgreek package

### ISSUE THREAD

**Issue by callegar** [sphinx-doc/sphinx#1682]
The current behavior in the latex writer is to translate all Greek letters in latex math. For instance, a Greek Δ becomes `\(\Delta\)`.

This creates issues when Greek text appears in a section title, because hyperref has trouble in creating bookmarks including math.  Furthermore, it breaks formatting because it make it impossible to have the Greek test follow the current text style with respect to things like italics, bold, etc.  Most important, it is completely unnecessary, since pdftext supports unicode just fine given that you are using a unicode `\textinput`. To this aim it is only necessary to load the `\textgreek` package with a suitable font... e.g. `\usepackage[artemisia]{textgreek}` and to pass the `unicode` option to `hyperref`.

**Comment by jfbu** [comment]
Thanks for report and suggestion, and sorry for long delay before actually doing something... I think this has now been fixed in #5645 for future Sphinx 2.0. See also http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_elements, the discussion of ``'fontpkg'``, ``'fontenc'``, and ``'textgreek'`` key.

Closing now.
