### ISSUE TITLE
tooltips for internal links (reference/doc)

### ISSUE THREAD

**Issue by rom2014** [sphinx-doc/sphinx#1762]
Hi, currently I see no way to add customized tooltips to internal links, this would for example help to visualize the target of the reference as the title itself might not always be too self-explaining (if you have several similar or same titles within different parts of the documentation) and reduce the information of the link itself (if you provide the full path in the link text, it might be not well to read in texts, especially if you document a calculation).

Is there a possibility to do so?

**Comment by shimizukawa** [comment]
There is no way to do it from sphinx side because there is no syntax to provide 'title' information for internal links.

For example, some of reference that is generated by sphinx role (i.e. `:ref:` role with intersphinx extension) will generate `<a>` tag with `title` attribute. In this way, although you can let the extended notation output the title attribute, it will be difficult to add the information to the standard (internal link) notation.

For now, Sphinx does not plan to make its own changes to the standard reST notation.
If it were to be implemented, I think that we will introduce new roles like:
```rst
:link:`section title [tooltip information] <link-target>`
```
This can be realized without changing the reST syntax and you can implement it as Sphinx extension, so please try it ;)
