### ISSUE TITLE
Napoleon and Todo (meeting in the middle)

### ISSUE THREAD

**Issue by jakirkham** [sphinx-doc/sphinx#1837]
It is really great to have napoleon. Also, I find it useful to add todos in my docstrings. Somehow I am unable to get the two to work together. I have tried using `.. todo::` in my Google style docstrings, but have the feeling that this isn't permitted and it isn't exactly desirable. However, `Todo` isn't supported under napoleon. Here are my two questions?
1. What could I do to get napoleon and todos to play nicely at present?
2. Is it possible/foreseeable that some better interaction of the latter type (i.e. `Todo`) would be supported?

**Comment by RobRuana** [comment]
Using `.. todo::` just like that is 100% permitted. You can use mix Google style and standard reStructuredText without problem.

In fact, I'd argue that the `.. todo::` style is actually beneficial, because it helps the Todo item stand out when you are skimming the source code.

I'll leave this issue open for awhile, and if there's enough interest, I'll add support for the directives from the [sphinx.ext.todo](http://sphinx-doc.org/ext/todo.html) extension.

**Comment by jakirkham** [comment]
That's a good point. I suppose it persuades one to complete them so as not to look at them any more. :)

I guess I really like what you did with making docstrings more readable and was hoping now that it is integrated in main we could leverage some more interoperability between included extensions.

Certainly, let's see what other people say.

**Comment by RobRuana** [comment]
Okay, I'm going to close this issue as _won't fix_, because I haven't heard from anyone else requesting this. However, if you really want this functionality, feel free to reopen it and submit a pull request :)

**Comment by rtaib** [comment]
I'm also very grateful for all your work on Napoleon, and while I get your point about having `rst` todos stand out more, I think I'd rather see them supported similarly to warnings or notes.
