### ISSUE TITLE
LaTeX Error: Too deeply nested. (although pdf was built)

### ISSUE THREAD

**Issue by bialix** [sphinx-doc/sphinx#1846]
Trying to publish docs to my intelhex project on readthedocs.org. Pdf builds always failed although somehow pdf is available.

Here is what readthedocs build failed page says:
https://readthedocs.org/builds/python-intelhex/2568305/

My docs sources are here: https://github.com/bialix/intelhex/tree/master/docs/manual

Here is pdf: https://media.readthedocs.org/pdf/python-intelhex/latest/python-intelhex.pdf
(strange situation, build failed but pdf exists)

**Comment by bialix** [comment]
My docs sources are here: https://github.com/bialix/intelhex/tree/master/docs/manual

**Comment by bialix** [comment]
Here is pdf: https://media.readthedocs.org/pdf/python-intelhex/latest/python-intelhex.pdf

**Comment by jfbu** [comment]
@bialix I have `git clone`'d  your project and tested it with master branch of future Sphinx 1.5 (the beta will be released soon).

I can confirm the error you got on PDF build. But adding this:

```
latex_elements = { 
    'maxlistdepth' : '6',
}
```

to the `conf.py`,  the PDF builds without error report and the output looks ok (the problem came from the nested lists in Appendix A).

I am thus closing the issue, please re-open if the above does not work for you when Sphinx 1.5 is released. The feature was added at #3096.

**Comment by bialix** [comment]
@jfbu I hope your new release will be used on readthedocs web site, cause I did not convert to pdf directly on my machine. Thanks anyway.

**Comment by jfbu** [comment]
@bialix 

When Sphinx 1.5 will be released via the usual channels, you should add a readthedocs.yml file to your project (if it does not already contain one) with a line like this one

```
requirements_file: requirements/docs.txt
```

and the file "requirements/doc.txt" should contain

```
Sphinx>=1.5
```

At least that's the kind of settings which worked for me in my single experience with readthedocs.

And your conf.py should contain the 

```
latex_elements = { 
    'maxlistdepth' : '6',
}
```
