### ISSUE TITLE
generated doc contains non-ascii characters, causing syntax error if copy-pasted into comments

### ISSUE THREAD

**Issue by eflister** [sphinx-doc/sphinx#1915]
copy pasting into comments in one's code causes a syntax error because of the non-ascii characters. doc that can be copy/pasted into comments is most useful -- shouldn't have to declare an encoding (figure out which to use, syntax, worry it conflicts with choice made for other reasons, etc).

```
SyntaxError: Non-ASCII character '\xe2' ..., but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

examples: 
http://www.losonczylab.org/sima/1.2/api/sequence.html#sima.Sequence.create
single quotes in description for dim_order
http://www.losonczylab.org/sima/1.2/api/segment.html#sima.segment.STICA
dash between parameter names and descriptions

**Comment by birkenfeld** [comment]
Actually I think every source file should have an explicit encoding (in Python 2 - Python 3 has a sensible default of UTF-8); otherwise you're running into problems whenever you happen to need a non-ASCII char.

But you are right, there shouldn't be "pretty" quotes in the type string. I'll fix that.

**Comment by eflister** [comment]
what about the dash (2nd linked example in OP)?
