### ISSUE TITLE
Convert unicode to latex equivalents

### ISSUE THREAD

**Issue by mtreinish** [sphinx-doc/sphinx#1959]
A lot of unicode symbol characters, like ✓, have built-in equivalents in latex symbols packages. So instead of adding the unicode to the document text you would use \checkmark and the appropriate package that provides it. The sphinx output generation should probably try to detect the usage of these characters (or a subset of them) in the rst and convert them to the latex equivalents. 

If you try to use these symbol characters now the latex build will fail and you'll have to manually add the symbol package usage and find and replace all the unicode chars with the latex equivalents.

**Comment by uchida** [comment]
sphinx uses `inputenc` package with `utf8` option, so latex could treats input of characters like ✓.
However, to output these characters, use correct font encodings with `\usepackage[font encoding here]{fontenc}` is required.

If you simply want to replace ✓ with `\checkmark`, inserting the following will work:

```
\usepackage{newunicodechar}
\newunicodechar{✓}{\checkmark}
```

And use XeLaTeX and unicode supported fonts instead of LaTeX also could be an option.

**Comment by birkenfeld** [comment]
The mapping of Unicode to LaTeX is maintained in sphinx/util/texescape.py - please feel free to add some symbols you need there and send a pull request.
