### ISSUE TITLE
Make it possible to ignore output from doctest setup code

### ISSUE THREAD

**Issue by LeoHuckvale** [sphinx-doc/sphinx#1981]
I'm trying to structure a doctest as follows:

```
.. testsetup::
    from package import setup_the_thing, do_the_thing
    setup_the_thing()

.. testcode::
    do_the_thing()

.. testoutput::
    'some output'
```

However, my setup code emits some output I don't care about (e.g. logging messages), and when I run doctests, I get:

```
File "some_file_containing_doctest.rst", line 2, in default (setup code)
Failed example:
    from package import setup_the_thing, do_the_thing
    setup_the_thing()
Expected nothing
Got:
    WARN: Some example logging output
```

The doctest fails on the setup and never reaches the `testcode` directive. It would be useful here to be able to ignore _all_ of the output from the setup code.

I've trawled through the sphinx documentation but can't find how to do this, otherwise. Any help would be much appreciated!

**Comment by lehmannro** [comment]
Mmmmh, yeah, the culprit seems to be [sphinx.ext.doctest:363-380](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/doctest.py#L363-L380) which runs setup/cleanup like ordinary doctests with no expected output.

I think a simple solution would be adding `...` (`doctest.ELLIPSIS_MARKER` instead of `''` in line 366) as an expected output, maybe only if requested by a directive option to retain backwards-compatibility.  (OTOH I'm not sure this behaviour was ever sensible, because then you could just have had a `.. testcode: :hide:` block.)
