### ISSUE TITLE
Image indexing

### ISSUE THREAD

**Issue by NoralK** [sphinx-doc/sphinx#1985]
If I add a figure and try to index it like this:

```
.. index:: :numref:`oaktree`

.. figure:: oaktree.png
    :name: oaktree

        Oak Tree
```

it does not get listed in the index properly but it is linkable and does take you to the image. The URL is incorrect and it is listed in the Index as `:numref:`oaktree``.  I would expect to see the caption "Oak Tree" or the figure's name.

The correct URL, from another :numref:, is - file:///E:/Projects/Combined/_build/html/Test.html#oaktree
The incorrect URL, from the index, is - file:///E:/Projects/Combined/_build/html/Test.html#index-4

**Comment by NoralK** [comment]
_Ping_

**Comment by tk0miya** [comment]
The `index` directive does not expand inline markups (cf. roles, emphasis, and so on).
so `:numref:` role is ignored and put it on listing indecies as raw text.

In addition, `:numref:` will be replaced by figure number (cf. `Figure. 1`).
You should use `:ref:` role instead of `:numref:` to get caption text (but `index` directive ignores it too).

I think there is no simple way to put caption of figures to index.

**Comment by NoralK** [comment]
Is this a Sphinx issue or reStructuredText issue?

**Comment by shimizukawa** [comment]
IMO, it's a specification of Sphinx.

**Comment by shimizukawa** [comment]
Now I'll close this issue.
