### ISSUE TITLE
Title in PDF Output

### ISSUE THREAD

**Issue by NoralK** [sphinx-doc/sphinx#1986]
In my `conf.py` I am using `'fncychap': '\\usepackage[Sonny]{fncychap}'` for generating my PDFs.

My chapters are generating correctly:
![chapter](https://cloud.githubusercontent.com/assets/13447087/9159925/f767a3c8-3ee6-11e5-880f-dfdb12513de5.png)

However the index font is much smaller than the chapter:
![index](https://cloud.githubusercontent.com/assets/13447087/9159927/faabeb20-3ee6-11e5-891c-f1bcc3da810a.png)

How can this be fixed?

**Comment by NoralK** [comment]
This also happens if I remove and use the default fncychap.

**Comment by NoralK** [comment]
Also the table of contents is the same way.

![untitled](https://cloud.githubusercontent.com/assets/13447087/9183805/6767cb74-3f66-11e5-806e-52dba2a752d8.png)

**Comment by NoralK** [comment]
_Ping_

**Comment by tk0miya** [comment]
It caused by Sphinx. Sphnx redefines style parameters for fncychap on `sphinx.sty`::

```
% This sets up the fancy chapter headings that make the documents look
% at least a little better than the usual LaTeX output.
%
\@ifundefined{ChTitleVar}{}{
  \ChNameVar{\raggedleft\normalsize\py@HeaderFamily}
  \ChNumVar{\raggedleft \bfseries\Large\py@HeaderFamily}
  \ChTitleVar{\raggedleft \textrm{\Huge\py@HeaderFamily}}
  % This creates chapter heads without the leading \vspace*{}:
  \def\@makechapterhead#1{%
    {\parindent \z@ \raggedright \normalfont
      \ifnum \c@secnumdepth >\m@ne
        \DOCH
      \fi
      \interlinepenalty\@M
      \DOTI{#1}
    }
  }
}
```

`sphinx.sty` is generated automatically on every time you run `make latex`.
We need to patch to Sphinx that does not redefine these parameters by default.

MEMO:
This style came from the Python documentation (3d74adea2595f35994093091410bc8607bd49f74)

**Comment by liminkai520520** [comment]
and how to change the font(such as  chapter,index,contents ) size and color??

**Comment by liminkai520520** [comment]
@tk0miya  how to change the font(such as chapter,index,contents ) size and color??

**Comment by jfbu** [comment]
In my short investigation:
1. the `\ChNameVar` and `\ChNumVar` decides how the word "chapter" and its numbered are rendered on the first page of the chapter. 
2. the `\ChTitleVar` decides the chapter name itself. But its use in `sphinx.sty`:
   
   ```
   \ChTitleVar{\raggedleft \textrm{\Huge\py@HeaderFamily}}
   ```
   
   is completely buggy as `\Huge` is without effect, being served as argument of `\textrm`. 
   Furthermore I have tested that changes in `\ChNumVar` "spill" over or "contaminate" the
   rendering of the chapter title. The reason why these titles are `\Large` is because
   the `\Large` is from `\ChNumVar` which one would have supposed should have modified
   only the way the number of the chapter is rendered (IMHO this is a
   bug of fncychap).

Regarding the `Contents:`, there is no use made of the `\ChNumVar` setting (it seems to be associated to an unnumbered chapter) hence it is done in normal font, due to buggy use of `\ChTitleVar` as described above. If we however change it to the correct:

```
   \ChTitleVar{\raggedleft \rmfamily\Huge\py@HeaderFamily}
```

or better

```
   \ChTitleVar{\raggedleft \Huge\py@HeaderFamily }
```

then suddenly all chapter titles in Sphinx produced documents will be `\Huge` !! perhaps they were a long long time ago... 

The `\py@HeaderFamily` is customizable by user by `\sphinxSetHeaderFamily{new definition}`. Its default is `\sffamily\bfseries`. But it is used in many places, hence it is not "fine" enough for styling.

Finally the change to 

``` latex
  \def\@makechapterhead#1{%
    {\parindent \z@ \raggedright \normalfont
      \ifnum \c@secnumdepth >\m@ne
        \DOCH
      \fi
      \interlinepenalty\@M
      \DOTI{#1}
    }
```

is buggy too as it lacks a `%` after `\DOTI{#1}`; furthermore it is incomplete as there is another macro for non-numbered chapters `\@makeschapterhead` which could also be customized (its definition in `fncychap` starts with  `\vspace*{50\p@}`, but perhaps we actually want to keep that, it shifts down possibly the `Contents:` (untested)).

@liminkai520520 You can use the `\ChTitleVar` in your `conf.py` in this way, for example.

``` python
latex_elements = {
     # The paper size ('letterpaper' or 'a4paper').
     #
     # 'papersize': 'letterpaper',
     # The font size ('10pt', '11pt' or '12pt').
     #
     # 'pointsize': '10pt',

     # Additional stuff for the LaTeX preamble.
     #
     'preamble': '''\
\\ChTitleVar{\\color{red}\\normalfont\\Huge\\ttfamily}''',

     # Latex figure (float) alignment
     #
     # 'figure_align': 'htbp',
}
```

But it does not discriminate between contents, chapters, indices and tables, all three treated the same (currently).

@tk0miya we should fix the use of `\ChTitleVar` in `sphinx.sty` as the latex makes no sense.

The edit removes references in this message to the "header" because actually the page header are not the matter here.

**Comment by liminkai520520** [comment]
thanks @jfbu .your are right. I want to ask you a question , How do you know the `\ChTitleVar` directive. I want to know more directives like this , for instance : I want to definecolour with my tableheader. How can I do?

**Comment by jfbu** [comment]
@liminkai520520 regarding `\ChTitleVar` I checked the documentation of package `fncychap` via the command `texdoc fncychap`. It was already indicated in this thread by @tk0miya that `\ChTitleVar` was a command of package `fnchchap`.

Regarding generally speaking styling LaTeX with Sphinx, it is improved on master branch. On the specific question of table headers there will  be in release `1.5` `\sphinxstylethead` replacing the hard-coded `\textsf`. This was discussed at #2686. 

But styling in LaTeX is very difficult, and even more so if we want to maintain compatibility with older TeX installations (for example Ubuntu 12.04 only has TeXLive 2009) and backwards compatibility with extensions using the old LaTeX code in Sphinx.

**Comment by liminkai520520** [comment]
OK, @jfbu excuse me sir , Now I find a new problem, in my documention, I set my font via `'fontpkg':'\\usepackage{YaHei Consolas Hybrid}',`But I hope englisn and number in the text  use `Arial` font ,such as `chapter 1` `contents` and others in the text, And the chinese in the text use `YaHei Consolas Hybrid` font ,How can I set?
