### ISSUE TITLE
Feed generation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#2]
Add some directive that automatically generates an RSS feed for its items.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/2
- Originally reported by: Georg Brandl
- Originally created at: 2008-11-02T22:13:48.195

**Comment by shimizukawa** [comment]
_From Éric Araujo on 2010-10-29 00:13:42+00:00_

I don’t get what the entries of the feed would be.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-10-29 05:43:56+00:00_

Basically, the content of the directive, formatted as some list.  But it's all a bit vague, and that's why this hasn't been implemented yet :)

**Comment by shimizukawa** [comment]
_From Anonymous on 2010-10-29 07:13:53+00:00_

I think it should just provide the list of the new pages in a reverse chronological order (most recent at the top), with the full content of the article as description.

Personnaly, I do not like when content is limited in a feed.

**Comment by shimizukawa** [comment]
_From [glenfant](https://bitbucket.org/glenfant) on 2010-11-12 12:31:05+00:00_

Hmmm

Adding a new markup for this...
{{{
.. syndication-feed:: [a title or keep title of the page]
   :description: An optional description of the feed
}}}
This markup should be unique in a file.

In "conf.py"
{{{
feed_format = None # default
feed_format = "rss"
feed_format = "atom"

# Think we should know from the conf the publication URL to build this static feed (?)

}}}

This would require some changes in templates too. So it would not be that easy to make this in an extension IMHO. Would love to have time to make such an extension.

**Comment by tk0miya** [comment]
Now, we have three extensions to generate RSS feed.
- sphinxcontrib-newsfeed https://pypi.python.org/pypi/sphinxcontrib-newsfeed
- sphinxfeed https://pypi.python.org/pypi/sphinxfeed
- sphinx-contrib/feed https://bitbucket.org/birkenfeld/sphinx-contrib

I think main purpose of this issue is resolved by them.
So I close this issue.

Thans,

**Comment by martin-ueding** [comment]
Neither extension has been ported to Python 3, so if you want to use Sphinx with Python 3, you are out of luck. One can move to [Tinkerer](http://tinkerer.me/), though that seems like a major change to me.

- I have tried to port `sphinx-contrib/feed` to Python 3, but the feed that is generated does not seem to be a valid RSS feed. At least Akregator and W3C do not like it.

- `sphinxfeed` depends on `feedformatter` and that is not available for Python 3 either.

So either I downgrade to Python 2 again for Sphinx, switch to one of the [million other static site generators](http://staticgen.com/), or just forget about the RSS feed. All options are not quite satisfying.

**Comment by TormodLandet** [comment]
For those that find this issue on Google and think RSS feed blogs / news / release lists are not supported by Sphinx, you should know that the [sphinxcontrib-newsfeed](https://pypi.org/project/sphinxcontrib-newsfeed/) extension mentioned above has supported Python 3 since 2013 and works perfectly. There has not been a release since 2015, but the Sphinx API is stable and the extension still works as it is supposed to, so there is probably no need for any changes at the moment. 

An example from one of my packages: News-blog https://trlandet.bitbucket.io/ocellaris/blog/  has RSS feed https://trlandet.bitbucket.io/ocellaris/index.rss

PS: this functionality is so useful and stable that it could be promoted a bit more, by inclusion in the main repo or by a link in the documentation perhaps?

**Comment by TimKam** [comment]
As `sphinxcontrib-newsfeed` is loading 3rd party scripts from disqus.com, I'd say it shouldn't be part of the sphinx core--IMHO 3rd party integration extensions are too volatile for this. However, I suggest we can move the repo to the [sphinx-contrib](https://github.com/sphinx-contrib/) organization, **if** the Sphinx maintainers and the `sphinxcontrib-newsfeed` author(@xitology) agree. This would add visibility to the extension and makes it easier to maintain in case the original author does not have time. I think we can also link to the extension from the FAQ, if it is moved to the `sphinx-contrib` organization.

**Comment by tk0miya** [comment]
AFAIK, sphinx-contrib organization is mere a collection of repositories. There are no special rules. So nothing will be changed even if moved. Sphinx-core team does not have any permissions for repo, and also can't release a new version.

BTW, we can add a hyperlink to official docs without moving. +1 for adding!

**Comment by lsaffre** [comment]
I now ported my fork of sphinxfeed to Python 3: https://github.com/lsaffre/sphinxfeed
