### ISSUE TITLE
Extensions in virtual environment not found

### ISSUE THREAD

**Issue by jluttine** [sphinx-doc/sphinx#2005]
I have Sphinx=1.3.1 installed as a system package and some extensions (e.g., numpydoc) in my virtual environment (which also uses the system packages). Sphinx is not able to find the extensions that are in the virtual environment. However, if I installed Sphinx to the virtual environment, then it works. Also, importing the extensions in Python shell works.

The error I got:

```
sphinx-build -b latex -d build/doctrees  -v source build/latex
Running Sphinx v1.3.1
Original exception:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 429, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
ImportError: No module named 'numpydoc'


Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 429, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
ImportError: No module named 'numpydoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.4/site-packages/sphinx/application.py", line 433, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension numpydoc (exception: No module named 'numpydoc')

Extension error:
Could not import extension numpydoc (exception: No module named 'numpydoc')
```

**Comment by shimizukawa** [comment]
That is the correct behavior of the `virtualenv`.
`sphinx-build` command is invoked by System Python interpreter instead of virtual environment.

In such case, you can use alternative way.

`sphinx-quickstart` -> `python -m sphinx.quickstart`
`sphinx-build` ->  `python -m sphinx`

Please try it.

**Comment by jluttine** [comment]
I think this could be fixed by replacing the shebang in `sphinx-build`:

```
#!/usr/bin/python
```

with:

```
#!/usr/bin/env python
```

I tried this and it works. Why to force using System Python?

And thanks for your suggestion, that should also work nicely.

**Comment by shimizukawa** [comment]
> I tried this and it works. Why to force using System Python?

Because you installed Sphinx by using system python.
`sphinx-build` script is generated by `pip` (or `easy_install`) instead of Sphinx.
So, there is nothing to do from Sphinx side.

IMO, if shebang is set as `#!/usr/bin/env python`, we can't invoke `/path/to/virtualenv/bin/sphinx-build` without virtualenv activation. Invocation scripts should bind to environment.
Unfortunately, I can't find any articles/mails to confirm my opinion straitly. 
Please ask your question to https://mail.python.org/mailman/listinfo/distutils-sig ML.

Refs:
- https://mail.python.org/pipermail/distutils-sig/2013-July/022001.html
- http://pythonhosted.org/distlib/tutorial.html
- https://bitbucket.org/pypa/distlib/src/931436ce5/distlib/scripts.py

**Comment by jluttine** [comment]
Ok, thanks!
