### ISSUE TITLE
Search result entries don't HTML escape names?

### ISSUE THREAD

**Issue by waywardmonkeys** [sphinx-doc/sphinx#2019]
When we do a search in our docs, things that contain `<>&` aren't HTML escaped as far as I can tell. I ended up doing this temporarily in our domain's `get_objects` method, but I'm not sure that that is the correct fix for this.

**Comment by tk0miya** [comment]
Fixed at d5a2073a07ef40f63607ba2edc0e493015fd8ea7.
This issue is caused from any domain objects are not escaped. Other entries (like section titles) are surely escaped.
So I escape them on building index.

It will be released in next stable release; v1.3.6

Thank you for reporting and sending pull request!
