### ISSUE TITLE
Enable passing options to pygments

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#207]
Hi,

Related to issue 175 (and discussed on #python-docs), it would be nice to have a way of passing options to pygments.

This is essential for small snippets of PHP (the :startsinline: option) - there are probably other cases too.

Default options might go in conf.py, with sourcecode block options allowed.

Thanks

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/207
- Originally reported by: Paul Biggar
- Originally created at: 2009-06-23T19:02:39.208

**Comment by shimizukawa** [comment]
_From Konstantin Molchanov on 2012-12-11 17:30:16+00:00_

Vital feature, please add!

**Comment by tk0miya** [comment]
Note: #175

**Comment by tk0miya** [comment]
Now we provides a config variable `highlight_options` to pass options to pygments since v1.3. I think it can resolve this case. Please let me know if you'd like to apply options to an arbitrary code-block.

BTW, the `highlight_options` are only applied to the language that is specified to `highlight_language`. It means we can't pass the options to pygments when using two or more languages. It should be improved before closing this.
