### ISSUE TITLE
numref not working with download in only block

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2143]
Hi,
I am trying to show code blocks with a link to the file for download in the block caption. The link should only appears in html. So I do

```
.. only:: html

   .. literalinclude:: my_file
      :caption: title :download:`click<filelink>`
      :name: code

.. only:: latex

   .. literalinclude:: my_file
      :caption: title
      :name: code

```

The code and the download link are displayed correctly, but  if I try to refer to the block with

```

:numref:`code`

```

the link is broken. Any clue?

**Comment by andreacassioli** [comment]
OK, it seems not to be related with download, so I close the issue and make a new one.

**Comment by tk0miya** [comment]
In this case, you'd got a following warning on building docs:

```
WARNING: Duplicate explicit target name: "code".
```

The message was raised at second `literalinclude`.
because the `only` directive did not remove first `literalinclude` block. but It made the block invisible (still exists).

so the `:numref:` role refers the invisible one and the generated document looks like broken.
It seems a little strange, but it is a current specification. (see also #1717, #1488)
