### ISSUE TITLE
litralinclude code in latex does not break in pages!

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2147]
Hi,
it seems that if I use literinclude to insert a piece of code that will span more than one page in PDF, then the code block is not split and it is rendered (wrongly) only in the first page. 

To be more precise:

1- the code is displayed in the next page respect to the position that it should have in the text

2- the code goes "out of the page" with no breaks

3- the latex code looks OK except that it is a single literal-block, that in my understanding is not breakable.

I guess this is related to the fact that the writer uses literal-block.

Actually it seems that the problem comes out when I set a caption for the literalinclude. Is that something that changes the way the latex writer generates the output?

**Comment by takaakiaoki** [comment]
I also met same problem several weeks ago. This issue due to the fact that
when literalinclude (or code-block) is used with :caption: option, the latex builder encloses 
the contents with float environment named as literal-block, where page break is not available.

I wrote some extension to replace float by newfloat and add small modification, shown in 
  https://github.com/takaakiaoki/sphinx_latexnewfloat

I think there must be better solution than this extension. Indeed, I do not have enough skill how to contribute this finding to the main stream. I appreciate your comments and suggestions.

**Comment by tk0miya** [comment]
@takaakiaoki Good extension!
Could you remake it as pull request?
We'll merge your extension into the Sphinx.

I can support you in Japanese :-)

**Comment by takaakiaoki** [comment]
@tk0miya -san,

I appreciate your offer and accept any operation on my code to solve this issue.
Thanks,

**Comment by andreacassioli** [comment]
Hi guys,
thank you for the quick turn around!  Any guess on when the pull will be merged in stable?

**Comment by tk0miya** [comment]
The pull request is merged into stable now.
Please try it now :-)
