### ISSUE TITLE
faulty \ifx in sphinx.sty (latex issue)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#2165]
File `sphinx.sty` for `latex` output contains:

``` latex
% use pdfoutput for pTeX and dvipdfmx
\ifx\kanjiskip\undefined\else
  \ifx\Gin@driver{dvipdfmx.def}\undefined\else
    \newcount\pdfoutput\pdfoutput=0
  \fi
\fi
```

The second `\ifx` test is not correct `TeX`: `\ifx` will compare `\Gin@driver` token to `{` token. Thus this conditional always evaluates to false, hence always 

``` latex
 \newcount\pdfoutput\pdfoutput=0
```

is executed if `\kanjiskip` is defined, i.e. if `platex` is used. Besides `\Gin@driver` is only defined by package `graphicx` which is loaded later (I quickly checked that was true with `platex` too).

**Comment by uchida** [comment]
I have pushed this changes to evade errors due to `\include{pdfcolor}` line, which includes 
`$TEXMF-dist/tex/generic/pdftex/pdfcolor.tex`.
This file is distributed with `pdftex` package and `platex` cannot handle this file.
Therefore if `\kanjiskip` is defined, `\newcount\pdfoutput\pdfoutput=0` should be executed and second `\ifx` conditional is unnecessary.

Sorry to write faulty conditonal and @jfbu thank you to report.
