### ISSUE TITLE
porterstemmer causes `make json` to fail

### ISSUE THREAD

**Issue by bnaul** [sphinx-doc/sphinx#2183]
Create an example project:

```
$ sphinx-quickstart
...
Creating file ./conf.py.
Creating file ./index.rst.
Creating file ./Makefile.
Creating file ./make.bat.

Finished: An initial directory structure has been created.
```

Try compiling with `porterstemmer` available and the build will fail:

```
$ pip install porterstemmer
Collecting porterstemmer
Installing collected packages: porterstemmer
Successfully installed porterstemmer-0.5

$ make json
Exception occurred:
  File "/Users/brettnaul/anaconda/envs/mltsp3k/lib/python3.5/site-packages/sphinx/search/en.py", line 235, in init
    class Stemmer(CStemmer):
TypeError: type 'porterstemmer.Stemmer' is not an acceptable base type
```

Try again without `porterstemmer` and all's good:

```
$ pip uninstall porterstemmer
Successfully uninstalled PorterStemmer-0.5

$ make json
...
build succeeded.

Build finished; now you can process the JSON files.
```

**Comment by tk0miya** [comment]
In my short investigation:
It is caused from PorterStemmer-0.5. With PorterStemmer-0.4, it works fine.

**Comment by shibukawa** [comment]
@tk0miya, @shimizukawa, porterstemmer author(methane) and I discussed about this issue:
- Old Sphinx supported only English for search words.
- porterstemmer option was introduced in this age for acceleration.
- Then Sphinx supported 14 languages for search words by using [snowballstemmer](https://github.com/shibukawa/snowball_py) (I made)
- snowballstemmer uses PyStemmer for acceleration if available and PyStemmer supports 14 languages too.

My recommendation is using PyStemmer instead of porterstemmer and removing porterstemmer support from Sphinx (to keep Sphinx Pythonic).

@bnaul how about this idea?

**Comment by bnaul** [comment]
:+1:

**Comment by tk0miya** [comment]
Fixed at f1518c5.

@bnaul Sorry, I did not noticed your pull request and I fixed this at local.
Thank you for reporting!

@shibukawa Thank you for organizing issue. It's very helpful for me :-)

**Comment by tk0miya** [comment]
At first, I fixed this at stable branch.
but I moved it into master branch just now (4234c88). because it is breaking change.

Thanks,

**Comment by bnaul** [comment]
Perfect! Just saw that the issue was still open then so I figured I'd try it myself. Thanks for your help!
