### ISSUE TITLE
No warning is given for unknown options

### ISSUE THREAD

**Issue by RobertoBagnara** [sphinx-doc/sphinx#2229]
Please consider applying (a suitable modification of) the attached patch.
[unknown_option_warning_patch.txt](https://github.com/sphinx-doc/sphinx/files/83676/unknown_option_warning_patch.txt)

**Comment by tk0miya** [comment]
Thanks, I'll take a look.

**Comment by RobertoBagnara** [comment]
I am using the patched version right now: it works great for me (we had so many mistyped option references and we did not notice before).

**Comment by tk0miya** [comment]
I applied your patch at bba3f38 (arranged a little).
Thank you for contribution!

**Comment by frougon** [comment]
Hello,

Warning about unknown options is very nice, but how is one supposed to mention options of other software that are not defined in the document one is writing (where "defined" means having an "option" directive)? My library had a nice documentation, but now the build generates tons of warnings because the doc mentions options of an external program in many places. What am I supposed to do?

More details here: https://groups.google.com/forum/#!topic/sphinx-users/6F_EJUEA2f8

Maybe the new warning should only be printed when a new, specific option is passed to sphinx-build?

Thanks

**Comment by tk0miya** [comment]
Sorry for inconvinience.
I reverted this feature from stable release (1.3.x).
And I will reimplement it for next major release. of course it will support warnings supression.

**Comment by frougon** [comment]
Apart from the fact that commit messages and documentation use the incorrect spelling "supress" instead of "suppress", I think what you implemented here should solve the problem I reported. Thank you!

**Comment by tk0miya** [comment]
Thanks, I fixed the typos :-)
After the reviewing, it will be merged. Please wait a moment.
