### ISSUE TITLE
 miss code-block lineno-start option in sphinx/doc/markup/code.rst

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2307]
There is no mention of "lineno-start" in the code-block examples.

It could be here :

.. code-block:: python
   :caption: this.py
   :name: this-py
   :lineno-start: 42

   print 'Explicit is better than implicit.'

**Comment by jfbu** [comment]
I am not sure if it is intentional in file `doc/markup/code.rst` that there is no `::` after the sentence ending as  _automatically activated as well._

``` rst
The first line number can be selected with the ``lineno-start`` option.  If
present, ``linenos`` is automatically activated as well.

   .. code-block:: ruby
      :lineno-start: 10

      Some more Ruby code, with line numbering starting at 10.
```

Other examples have it. This one doesn't and as a result the thing is evaluated, not displayed as source (http://www.sphinx-doc.org/en/stable/markup/code.html#line-numbers)

**Comment by ghost** [comment]
jfbu is right more than I was, this should be explicitly show after the sentence ending "as automatically activated as well."

**Comment by tk0miya** [comment]
Updated.
Thank you for reporting!
