### ISSUE TITLE
'article' documentclass doesn't have blue titlepage

### ISSUE THREAD

**Issue by samwilson** [sphinx-doc/sphinx#2327]
When using the `article` documentclass (as the 5th argument to the `latex_documents` config variable), the title, author, and date lines are not rendered in the same blue sans-serif font as subsequent headers in the document body.

For example:
https://media.readthedocs.org/pdf/assetmanager/latest/assetmanager.pdf

Does anyone know how I might fix this?

(This issue previously raised as https://github.com/rtfd/readthedocs.org/issues/1974.)

**Comment by jfbu** [comment]
Could you try adding this to `conf.py` and report aftereffects:

``` python
# Additional stuff for the LaTeX preamble.
'preamble': """\\let\\oldmaketitle\\maketitle
\\makeatletter
\\def\\maketitle{\\py@TitleColor\\py@HeaderFamily\\oldmaketitle}
\\makeatother""",
```

By the way, when I tried `article` as fifth element of `latex_documents` I noticed the problem that `make latex` still produces a file with `\chapter` commands. I am curious how you configured Sphinx to produce `\section`'s rather than `\chapter`'s as top level sectioning units, can you explain? (I am still new to Sphinx).

**Comment by jfbu** [comment]
Ah sorry, there is a better way, customize not `'preamble'` but `'maketitle'` key from `latex_elements` dictionary in `conf.py`.

``` python
'maketitle' : """\\makeatletter
\\py@TitleColor\\py@HeaderFamily\\maketitle
\\makeatother""",
```

does this work for you? Perhaps one shoud also add `\\normalfont` after that, but anyhow the Table of contents will reset the font, and the first sectioning unit too.

**Comment by samwilson** [comment]
Yep, that's fixed the title colour.... but now the whole document is blue! E.g. https://media.readthedocs.org/pdf/tabulate/master/tabulate.pdf

And the top-level headings _are_ still `\chapter{}`; not sure why they're formatted to look like normal sections... maybe something to do with `\def\sphinxdocclass{report}`?

I must admit, despite being reasonably familiar with normal LaTeX the code generated by Sphinx is confusing me mightily! :) I'm glad you're here.

**Comment by jfbu** [comment]
I am not much familiar with it either :-) 

The expected thing if you want sections as top level is to use `howto` as fifth argument to `latex_documents`. Using `article` does not seem to be the expected thing...

If the produced `tex` source has `\chapter` commands, and the class is `article`, then `\chapter` is like  `\relax`, it does nothing: the headings will be typeset as is. No entry will appear in table of contents.

About your colour problem, ah ok, I should have tested ... the issue is that I didn't want to put the `\maketitle` inside a braced group, and I was expecting next heading would reset colour and font. 
But your `\chapter=\relax` does not create headings...

``` python
'maketitle' : """\\makeatletter
\\py@TitleColor\\py@HeaderFamily\\maketitle
\\makeatother\\normalfont\\normalcolor""",
```

should work.

**Comment by tk0miya** [comment]
Now, Sphinx provides the following ways to change the sectioning unit:
(1) Specify `howto` to docclass; the fifth argument of `latex_documents`, then `section` is used
(2) Use `latex_use_parts=True` to use `part`

There is no way to change the sectioning unit arbitrarily in current Sphinx.
So I'll add a new config value named `latex_toplevel_sectioning`.
In details, please see #2349. It's under reviewing.
