### ISSUE TITLE
Possible regression with sphinx==1.4a1

### ISSUE THREAD

**Issue by xavfernandez** [sphinx-doc/sphinx#2330]
Hello,

we had failing docs build on the pip project with sphinx==1.4a1:

```
$ tox -e docs
GLOB sdist-make: /home/xfernandez/other_dev/pip/setup.py
docs create: /home/xfernandez/other_dev/pip/.tox/docs
docs installdeps: sphinx
docs inst: /home/xfernandez/other_dev/pip/.tox/dist/pip-8.1.0.dev0.zip
docs installed: -f /home/xfernandez/.pip/wheelhouse/,alabaster==0.7.7,Babel==2.2.0,docutils==0.12,imagesize==0.7.0,Jinja2==2.8,MarkupSafe==0.23,Pygments==2.1.1,pytz==2015.7,six==1.10.0,snowballstemmer==1.2.1,Sphinx==1.4a1,wheel==0.24.0
docs runtests: PYTHONHASHSEED='2955190628'
docs runtests: commands[0] | sphinx-build -W -b html -d /home/xfernandez/other_dev/pip/.tox/docs/tmp/doctrees docs docs/_build/html
Running Sphinx v1.4a1
loading pickled environment... not yet created
loading intersphinx inventory from https://packaging.python.org/en/latest/objects.inv...
loading intersphinx inventory from https://www.pypa.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 21 source files that are out of date
updating environment: 21 added, 0 changed, 0 removed
reading sources... [  4%] configuration
reading sources... [  9%] cookbook
reading sources... [ 14%] development
reading sources... [ 19%] index
reading sources... [ 23%] installing
reading sources... [ 28%] logic
reading sources... [ 33%] news
reading sources... [ 38%] quickstart
reading sources... [ 42%] reference/index
reading sources... [ 47%] reference/pip
reading sources... [ 52%] reference/pip_download
reading sources... [ 57%] reference/pip_freeze
reading sources... [ 61%] reference/pip_hash
reading sources... [ 66%] reference/pip_install
reading sources... [ 71%] reference/pip_list
reading sources... [ 76%] reference/pip_search
reading sources... [ 80%] reference/pip_show
reading sources... [ 85%] reference/pip_uninstall
reading sources... [ 90%] reference/pip_wheel
reading sources... [ 95%] usage
reading sources... [100%] user_guide

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  4%] configuration
writing output... [  9%] cookbook
writing output... [ 14%] development

Warning, treated as error:
/home/xfernandez/other_dev/pip/docs/development.rst:18: WARNING: Could not lex literal_block as "python3". Highlighting skipped.

ERROR: InvocationError: '/home/xfernandez/other_dev/pip/.tox/docs/bin/sphinx-build -W -b html -d /home/xfernandez/other_dev/pip/.tox/docs/tmp/doctrees docs docs/_build/html'
```

Pinning sphinx to 1.3.5 (or in our case, removing `--pre` option to disable prereleases) fixed it for us.

To reproduce:

```
git clone git@github.com:pypa/pip.git
# e0db87c is current develop
git checkout e0db87c
tox -e docs
```

**Comment by birkenfeld** [comment]
Well, as you can see this is a new warning in 1.4 that indicates that a code block is likely not Python code and therefore should not use Python highlighting.

I wouldn't call it a regression; the warning was added because it's preferable to know beforehand that highlighting of a block will be wonky.

**Comment by xavfernandez** [comment]
Mmmh ok, but I don't think we wish for any highlighting here.
https://raw.githubusercontent.com/pypa/pip/develop/docs/development.rst corresponds to https://pip.pypa.io/en/stable/development/

Why does it think it is python3 code ?

**Comment by birkenfeld** [comment]
The default highlighting language is (and has always been) Python.

You can either set different highlighting for the entire docs in conf.py (`highlight_language = "xxx"`), or in individual documents (`.. highlight:: xxx`), or in individual code blocks (`.. code-block:: xxx` instead of just `::`). `none` works for no highlighting.

**Comment by tk0miya** [comment]
This problem came from the difference between each `highlight_language` types.
The `python` (used at Sphinx-1.3.x or older) skips highlighting without any warnings if the code-blocks could not highlight by python2. In other words, it fallbacks `none` to language automatically.
But the `python3` (used at Sphinx-1.4a1) don't do that.

So if you wrote code-blocks without any `highlight_language` settings, Sphinx tries to highlight them as python3 and emits warnings if failed.

Now, I added fallback feature to `python3` at https://github.com/sphinx-doc/sphinx/commit/423bf7b5e3ab744ea32b8c929a81a4e6a11db95a .
So this will be fixed at next alpha release.

Thanks,

**Comment by birkenfeld** [comment]
I'm not too happy with that change, but I'll open a new issue to discuss.

**Comment by xavfernandez** [comment]
Ok, thanks for the clarification.
I'll stick with latest stable and will certainly add `highlight_language = "none"` to `conf.py` if this becomes mandatory.

**Comment by birkenfeld** [comment]
It's a good idea in any case.

For the snippets in the file in question, you might want to try `.. highlight:: console` though.

**Comment by xavfernandez** [comment]
Well I tried it but the result was not that great.
For https://pip.pypa.io/en/stable/development/, in the first block, only `cd` was colored and in the `Running tests` first block, only `test` from `$ python setup.py test  # Using the setuptools test plugin` was highlighted, so `highlight_language = "none"` will certainly have my preference.

**Comment by birkenfeld** [comment]
I understand. Highlighting console sessions is always a bit of a pain :)
