### ISSUE TITLE
Support 'lang_COUNTRY' language codes

### ISSUE THREAD

**Issue by fkrull** [sphinx-doc/sphinx#2345]
Sphinx should better support using 'lang_COUNTRY' language codes (preferably, also even more specific formats) for translations, f.ex. 'de_DE', 'de_AT', 'en_GB' etc.

By way of example, with Sphinx 1.3.5, if you set `language='de_AT'`, the following happens:
- For (most of) its own translated strings and the document text, Sphinx falls back to 'de' (going by `sphinx.locale`, that's a feature of the `gettext` module) as it should.
- `html_search_language`, if not set, defaults back to 'en'; it should be 'de' instead. (More generically, the 'lang' part of 'lang_COUNTRY'.)
- Parts of the search results page -- the dynamic 'Search results', 'Search finished, so-and-so-many results' strings at least -- are in English; they should be German from the 'de' catalog.

(There may be other bits I didn't find.)

**Comment by stephan-gh** [comment]
Any news on this issue? This issue is still present in Sphinx 1.5.2 and is quite difficult to bypass because the locale codes used by Sphinx seem to be rather inconsistent: Most languages use the two letter locale code but others like `nb_NO` or `uk_UA` use the full locale code even though no other variant is supported.

It works fine for the main Sphinx translations but not for the JavaScript search part. It should be quite easy to fix:

- In https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py#L148-L161 it needs to check for translations in the folder with the stripped language code **additionally** (e.g. everything before the underscore, so `de` if `de_AT` is given).
- In https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py#L278-L281 it just needs to strip the country part of the given language before looking it up (all defined search languages  are two letter codes).

**Comment by tk0miya** [comment]
Thank you for comment. But, unfortunately there are no updates.
We always welcome your help. Could you send us pull request (with testcodes if possible) ?

**Comment by tk0miya** [comment]
I noticed this was already fixed in 1.6.5 (see #4169).
So I'm closing this now.
