### ISSUE TITLE
Setting LaTeX tocdepth

### ISSUE THREAD

**Issue by fredrik-johansson** [sphinx-doc/sphinx#2358]
A footnote on the doc page for "The TOC tree" says:

> The maxdepth option does not apply to the LaTeX writer, where the whole table of contents will always be presented at the begin of the document, and its depth is controlled by the tocdepth counter, which you can reset in your latex_preamble config value using e.g. \setcounter{tocdepth}{2}.

This is not correct; Sphinx inserts its own \setcounter{tocdepth} after the preamble. In particular, this overrides the user-defined preamble, which is a problem if the user wants different settings for the LaTeX version.

A further confusing detail is that Sphinx seems to set tocdepth to the index page's toctree maxdepth - 1. In my case, I want the LaTeX tocdepth to be exactly the same as the toctree maxdepth (i.e. I have maxdepth = 2, so Sphinx sets the LaTeX tocdepth to 1, but I want the LaTeX tocdepth to be 2). I figured out that I can work around it by inserting an empty toctree

```
.. toctree::
   :maxdepth: 3
```

at the top of my index.rst, but this seems like an ugly hack.

**Comment by tk0miya** [comment]
Thank you for reporting.
I will move the tocdepth defintion to above of user-defined preambles.

BTW, what docclass do you use; the 5th element of `latex_document`?
If you use `howto` to the docclass, Sphinx uses the value of `maxdepth` to tocdepth.
Otherwise, `maxdepth - 1` is used for the tocdepth. Because Sphinx also uses `chapter` as toplevel sectioning unit if docclass is not `howto` (cf. `manual`).

**Comment by fredrik-johansson** [comment]
The docclass is 'manual'.

**Comment by fredrik-johansson** [comment]
Setting the tocdepth with the preamble works as expected now.

**Comment by tk0miya** [comment]
Glad to hear that.
Thank you for reporting!
