### ISSUE TITLE
Save memory allocated by Text nodes

### ISSUE THREAD

**Issue by lehmannro** [sphinx-doc/sphinx#2426]
Docutils `Text` nodes are taking up roughly 15% of the memory consumed by doctrees, with the bare classes taking up half of that.

Maybe we can save some memory if these became slotted, new-style classes?

**Comment by embray** [comment]
It looks to me that in trunk, anyways, [`Text` nodes](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/nodes.py#l322) are already new-style classes.  But I would be willing to bet some not-insignificant savings could be had by changing `Node` and subclasses thereof to use `__slots__`.  A more interesting question though to me is exactly how many of those objects are in memory at peak usage?  Because with an actual number it would be possible to come up with a pretty accurate estimate of the savings before even doing the work.

**Comment by lehmannro** [comment]
Wohoo, so that just keeps us waiting for a next release.

I don't have the numbers right now, but as I wrote in my [report from Sage Days 77](https://groups.google.com/d/msg/sphinx-dev/gMwnl58Q3zM/3_VPcYtnBQAJ), we can observe significant memory blow-up (pickled files: 200M, in-memory doctrees: 1.8G.)  I think from the memory forensics we did, a significant amount of memory (~15% as I said above) are consumed by Text node objects.

One problem with `__slots__` is that we _might_ be attaching arbitrary attributes to nodes, but I don't remember clearly right now.

**Comment by birkenfeld** [comment]
That should be what the attributes dict is for. In effect it's duplicating the already existing attributes dict, `__dict__`, for slightly cleaner namespacing.

The only problem is that this optimization can't easily be made selectively, or in a monkey-patching fashion (I think).

**Comment by lehmannro** [comment]
Well, we can always monkey patch the _whole_ class in `docutils.nodes`.  I didn't know we could do `__slots__ = ['__dict__', ...]` to allow arbitrary attributes;  that effectively voids my concerns.

**Comment by tk0miya** [comment]
I think doc-sig or docutils-list is a better place for such a discussion. I think there is nothing to do from the Sphinx side. So I'm closing this now.
