### ISSUE TITLE
LaTeX output is not using \usepackage{listings}

### ISSUE THREAD

**Issue by nowox** [sphinx-doc/sphinx#2472]
I am playing the LaTeX output and I am surprised Sphinx is not using the `listings` package for highlighting blocks of code. I feel this should the the correct solution instead of using these unusual `Verbatim` blocks. 

Is there any reason for this?

**Comment by jfbu** [comment]
I don't know the reason, but can only comment from perspective of a newcomer. If you look at the produced TeX file, you will see that it is full of macros `\PYG...` doing the highlighting already, which are produced from Sphinx using the http://pygments.org/ library. There only remains the task of outputting line by line with possible numbering and a framing (and also optionally a background color). The `Verbatim` (from the `fancyvrb` package) although indeed a verbatim environment is configured to allow backslashes and braces with their TeX meanings, hence it will expand the macros `\PYG..` to do their job. The frame is created using `framed` package. Yes, these are old packages, but they are relatively lightweight. It is true that using `framed` is delicate. Possibly for that reason, so far the framing extends the full line-width. Very recently I got interested in this, increased my understanding of the intricacies of `framed.sty` and produced PR #2459 for framing obeying indentation.

I am not much familiar wit `listings` but I gather it does a _lot_ of TeX processing (a bit like the `soul` package, which typesets first in boxes of only `1/65536 pt` width to pick up each glyph one by one and later reconstitutes it with the asked-for underlining or strike-through or whatever).

The approach in Sphinx with python libraries producing a TeX file enriched already with the highlighting mark-up makes for _much less_ TeX processing in the end. And it is quite flexible because one can then imagine changing  on the TeX side the behaviour of the macros. For example I have a PR #2343 which will wrap long code lines. Nevertheless `listings` is probably a viable option ; but it would need quite some re-writing on the Sphinx side to switch to it. As Sphinx has direct access to http://pygments.org/ it looks weird to switch to a TeX tool rather, as TeX is definitely not the tool of choice for manipulating text files, and `listings` achieves it by necessity in a rather heavy mannered way.

There is also `minted`. This one uses the Pygments library: but that means the TeX compilation itself must be allowed general shell access, which people don't like so much for security. And why use the Pygments library from TeX, when we can use it directly from Python rather, which is much much easier to program with ? 

.. my two cents...

**Comment by tk0miya** [comment]
Yes, it comes from the behavior of `pygments`. It only supports `verbatim` environment. It's only reason we does not use `listings` package. I think it's okay to move to other package if it highlights like pygments.

Actually, we still have some troubles with `verbatim` package as @jfbu says. So it would be nice to improve representation of "code blocks" in python side and LaTeX side.

**Comment by nowox** [comment]
Is it possible to get some hints on where (on the codebase) is performed the highlight with pygments? I may spend some time on this these next days.

**Comment by jfbu** [comment]
The ``LatexFormatter`` class is actually from pygments

  https://bitbucket.org/birkenfeld/pygments-main/src/a042025b350cd9c9461f7385d9ba0f13cdb01bb9/pygments/formatters/latex.py?at=default&fileviewer=file-view-default#latex.py-149

It is (ultimately) responsible for inserting in Sphinx latex output the 

```latex
        \begin{Verbatim}[commandchars=\\\{\}]
        \PY{k}{def }\PY{n+nf}{foo}(\PY{n}{bar}):
            \PY{k}{pass}
        \end{Verbatim}
```
type of mark-up. (Sphinx modifies the environment name now to sphinxVerbatim)

(also ``\PY`` is actually ``\PYG`` in Sphinx output, but this is config passed over to pygments formatter I guess)

The class is imported into Sphinx at  https://github.com/sphinx-doc/sphinx/blob/master/sphinx/highlighting.py#L23.

**Comment by nowox** [comment]
Thanks, this is something I can play with.

**Comment by jfbu** [comment]
listings package is not really compatible with Unicode: it requires considerable extra set-up.

minted package calls Pygments and thus requires shell-escape.

**Comment by tk0miya** [comment]
We decided to use customized `verbatim` to represent code-blocks.
So I close this issue now.

Thanks,

**Comment by yves-chevallier** [comment]
I agree, `minted` doesn't offer much, and it requires `shell-escape`. However I don't agree about unicode with `listings`. With a good font it is fine. 

For what it's worth I have created a small yet unstable extension to use listings instead of `SphinxVerbatim`. The example demonstrate that unicode chars plays fine with `lstlistings`.

https://github.com/yves-chevallier/sphinx-listings-test
