### ISSUE TITLE
Crash building latexpdf with javasphinx generated documentation.

### ISSUE THREAD

**Issue by kellpossible** [sphinx-doc/sphinx#2490]
I get this error in latex.py when running make latexpdf with documentation generated by javasphinx added to the toctree.

```
Exception occurred:
  File "/usr/lib/python3.5/site-packages/sphinx/writers/latex.py", line 1565, in visit_index
    for type, string, tid, ismain, key_ in entries:
ValueError: not enough values to unpack (expected 5, got 4)
```

printing out entries yields:
`[('single', 'Assignment1 (package)', 'package-Assignment1', '')]`

The toctree entry is:
`./apis/Assignment_1/packages.rst`

Not really sure if it's a problem with javaspinx or spinx its self.

Changing line 1565 into this appears to fix the problem:

```
for values in entries:
            type = values[0]
            string = values[1]
            tid = values[2]
            ismain = values[3]
```

key_ isn't even used in this visit_index() method.

**Comment by tk0miya** [comment]
Since Sphinx-1.4, we changed internal form of index. It's incompatbile change from 1.3.
Then javasphinx now does not support Sphinx-1.4.

Here is related codes:
https://github.com/bronto/javasphinx/blob/master/javasphinx/domain.py#L190
https://github.com/bronto/javasphinx/blob/master/javasphinx/domain.py#L428

@shimizukawa could you check this please?

**Comment by shimizukawa** [comment]
Now I checked https://github.com/bronto/javasphinx/commit/67e1756d6edcb8c54d89ca5e567cef17db1be453
javasphinx has been modified to support Sphinx-1.4.
Sorry for my late reply.
I think there is nothing to do now.

**Comment by tk0miya** [comment]
It seems new javasphinx has been released.
So this is completely fixed now!
