### ISSUE TITLE
Single page HTML doesn't output toctree

### ISSUE THREAD

**Issue by ericholscher** [sphinx-doc/sphinx#2589]
The singlehtml builder should still generate the top-level TOC Tree, but it should link to the relative headers in the HTML on that single page.

**Comment by davidism** [comment]
The issue appears to be that in order to generate a single file, the builder replaces the toc nodes with the actual pages and renders that. See `SingleFileHtmlBuilder.assemble_doctree()`. The toc is still available in templates as `{{ toc }}`, and the links work correctly as long as all headers have unique ids, but I don't think there's a way to conditionally render that in the middle of a RST page.

A solution could be to render the original toc node above the replaced version. It would be good to put it behind a config, like `singlehtml_body_toc`, so that it can be disabled.

As an alternative, I wanted to display the toc in the sidebar for singlehtml. But it's common for `html_sidebars["index"]` to exclude `localtoc.html`, which affects singlehtml. #5246 suggests a way to configure the sidebars for the singlehtml builder separate from the html builder.

**Comment by tk0miya** [comment]
I'm closing this because of duplicated with #1863
