### ISSUE TITLE
Latexpdf and miktex does not respect :align: right

### ISSUE THREAD

**Issue by nmat** [sphinx-doc/sphinx#2595]
I have a document with:

``` rest
====
Test
====

.. figure:: /images/testimage01.png
  :align: right
  :width: 300px

  Test image

Paragraph here
```

Which would in html align the image on the right but keep text on the left. In the PDF the image is rendered but takes up the whole width. The text is also rendered with the paragraph but is written above the image also being aligned to the left. Creating the affect of image being in the background then having text above the image. So its not following how html would render the image.

Miktex version: pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
Sphinx version: 1.4.2

**Comment by tk0miya** [comment]
I found another bug; `width` option of figure directive does not work if `align` option specified at same time.
Is this related with the bug?
I fixed it at da3d368961f8eb75b28d231718bf4e53194d9c16.

Could you try it if possible.

**Comment by tk0miya** [comment]
In addition, LaTeX does not recognize `px` as a unit of width. Please use `cm`, `em` or other units to express length.

**Comment by nmat** [comment]
Tested with cm on both html and latex. Seems to work just fine now.

**Comment by tk0miya** [comment]
Please close this issue if it's okay.

**Comment by nmat** [comment]
Is fixed now and confirmed.

**Comment by barbara-sfx** [comment]
The fact that LaTeX doesn't recognize px seems like - if not a bug - at least a feature request. So now i have to go through and figure out how to rework all my px entries into cm or em or whatever. Consider this, from https://www.w3.org/Style/Examples/007/units.en.html#units:

In fact, CSS requires that 1px must be exactly 1/96th of an inch in all printed output. CSS considers that printers, unlike screens, do not need to have different sizes for px in order to print sharp lines. In print media, a px thus not only has the same visual appearance from one device to another, but indeed it is measurably the same (just as the cm, pt, mm, in and pc, as explained above).

How would one go about suggesting a fix to LaTeX to honor px settings?

**Comment by jfbu** [comment]
Actually LaTeX does recognize px. Many documentation do not mention it, as it is not part of TeX/LaTeX but implemented by the engine pdftex, and only "recently" (in TeX sense), i.e. since 2005:

> http://docutils.sourceforge.net/docs/user/latex.html#size-of-a-pixel

But the default is 72px=1in (in other terms, this is a "big point", or bp in LaTeX terms). To set the default to 96px=1in (which means 4px=3bp) you can add this to conf.py in `latex_elements`:

```
'preamble': '\\pdfpxdimen=\\dimexpr49336sp\\relax',
```

Unfortunately this makes 96px not exactly 1in, but a tiny bit less. The exact needed value would be `49336.32sp` where `sp` is one TeX scaled point, i.e. one /65536th of 1/72.27 in. There does not seem to be a way to tell pdfTeX to treat `1px = 1/96 in` and then round to nearest multiples to nearest integer multiple of sp, we have to decide what `1px` is once and for all. (I say this because other earlier dimensions in Knuth TeX are treated in the more sophisticated way of ratios which are only rounded -- or perhaps truncated, I forgot -- at very end).

However currently it seems Sphinx ignores lengths specified with px in `:width:` for images, they just disappear from produced LaTeX. Thus the issue is more one of Sphinx than one of LaTeX. Recent PR #2615 which addresses another issue obeys `:figwidth:` if the figure is in a table (on current stable branch this crashes LaTeX writer, bu #2615 aims at fixing this) and there the px specs are not filtered out. I will examine how to have px dimensions go through with default 96px = 1in (as said above this can not be done exactly, but error is 1 part in about 150000 which is negligible).

**Comment by jfbu** [comment]
@barbara-sfx see PR #2618 which tries to allow using px in  `:width:` option of figure and image directives, for LaTeX output too.

**Comment by barbara-sfx** [comment]
Thanks @jfbu. I will look into these options.
