### ISSUE TITLE
Improve tables on LaTeX

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#2620]
At this moment, sphinx uses four types of macros to create tables:
- threeparttable
- longtable
- tabular
- tabulary

To make sphinx simple, it would be nice we move to one or two package to create tables.

**Comment by ghost** [comment]
I'd add a vote for `longtabu`.

**Comment by jfbu** [comment]
[Docutils 0.13](http://docutils.sourceforge.net/RELEASE-NOTES.html) has new ``:align:`` [option for tables](http://docutils.sourceforge.net/docs/ref/rst/directives.html#tables). Is there some plan for Sphinx to support it generally speaking ? currently a table with more than 30 rows will automatically use longtable which centers, but shorter tables are rendered by tabulary + threeparttable and as far as I know there is no official way from rst source to specify alignment although LaTeX would allow it easily.

**Comment by jfbu** [comment]
Also, shouldn't Sphinx LaTeX support natively the  `:widths:`  option, rather than require used of custom ``tabularcolumns`` directive ?

I am asking this because situation with tables on LaTeX side is very complicated with many packages not all compatible and not fully satisfying, with ``tabu`` package unmaintained and its author said next release will break former syntax etc... hence it looks more complicated to try to streamline packages used by Sphinx than it is to actually try now to extend the level of support by Sphinx of current docutils syntax with the already used LaTeX tools.

**Comment by jfbu** [comment]
about ``tabularcolumns`` I understand it allows LaTeX syntax which ``:widths:`` would not accept, but it would be nice if ``:widths:`` can also be understood and obeyed by latex as it is by html.

**Comment by tk0miya** [comment]
>Is there some plan for Sphinx to support it generally speaking ? 

No plans. But it does not means Sphinx never supports the option. Simply, we're too busy to plan new features.
Could you file it please? I will take a look later.

**Comment by jfbu** [comment]
done at #3377. As per ``:widths:`` option I assigned myself #3378 as this is for LaTeX writer specifically.

**Comment by tk0miya** [comment]
This is already refactored at #3377. Finally we use the following table macro-sets:

* tabular (+ threeparttable)
* tabulary (+ threeparttable)
* longtable

Note: #3686 is related with this. It tries to drop threeparttable.
