### ISSUE TITLE
WARNING: 4 column based index found

### ISSUE THREAD

**Issue by tardyp** [sphinx-doc/sphinx#2673]
Since upgrade to 1.4.4, I got a bunch of following error in my docs:
https://travis-ci.org/buildbot/buildbot/jobs/137072146

WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', u'Resource Type; collection', u'rtype-collection', u'rtype-collection')]

Not sure exactly what this error means

**Comment by tk0miya** [comment]
Since Sphinx-1.4, the structure of index has changed to 5 columns based.
This warning means any extensions you use don't support new structure.

As a quick look, BBDomain creates old 4 column based index: https://github.com/buildbot/buildbot/blob/master/master/docs/bbdocs/ext.py#L74

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if there is still any problems.

**Comment by tardyp** [comment]
Can we disable this warning? This is annoying as this requires us to fix
version of Sphinx to <1.4 if we don't fix or≥1.4 if we fix.

Le sam. 2 juil. 2016 09:44, Takeshi KOMIYA notifications@github.com a
écrit :

**Comment by tatsuhiro-t** [comment]
I'm wondering what is the best way to support both Sphinx >= 1.4, and older versions with the same extension code base.  Perhaps, do the branch based on Sphinx version?  I'm not sure it is available in extension API.

**Comment by tatsuhiro-t** [comment]
Right, I figured out how to do this.  sphinx.version_info does the job.
I think 'WARNING: 4 column based index found. It might be a bug of extensions you use:' is completely misguided.  Since this is breaking changes introduced by Sphinx, it should say extension uses older API, and it should be upgraded or something like that.  Actually, something in the comment https://github.com/sphinx-doc/sphinx/issues/2673#issuecomment-226076269 would be much better.
