### ISSUE TITLE
Why don't index directive parameters start with colons?

### ISSUE THREAD

**Issue by mixmastamyk** [sphinx-doc/sphinx#2690]
There seems to be an inconsistency on the way index entries are configured vs rst:
- http://www.sphinx-doc.org/en/stable/markup/misc.html#directive-index
- http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure

Is there a reason for this?

**Comment by tk0miya** [comment]
I don't know the reason. But I think it is to avoid restriction of directive-options.
The options should be unique in a directive definition.
For example, the following definition gets an error:

```
.. toctree::
   :name: hello
   :name: world

   foo
   bar
   baz
```

```
/Users/tkomiya/work/tmp/doc/index.rst:11: ERROR: Error in "toctree" directive:
invalid option data: duplicate option "name".

.. toctree::
   :name: hello
   :name: world

   foo
   bar
   baz
```

The `index` directive defines multiple index entries at once. So it adopts original notation instead of the directive-option syntax.

**Comment by mixmastamyk** [comment]
Nice, makes sense, thanks.
