### ISSUE TITLE
LaTeX error because of \sphinxstyleliteralintitle

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#2694]
This was changed in #2691 and causes the following error:

```
...
Runaway definition?
->\protect Watching for Changes with \protect #I\<def>-command \reserved@a \ETC
.
! TeX capacity exceeded, sorry [main memory size=5000000].
<inserted text> \reserved@
                          a
l.329 ...inxstyleliteralintitle{sphinx-autobuild}}

!  ==> Fatal error occurred, no output PDF file produced!
...
```

Strangely, if I simply replace `\sphinxstyleliteralintitle` with `\texttt` in the Sphinx-generated `.tex` file, it works again ...

**Comment by jfbu** [comment]
Thanks. I am stymied. As error occurs on line 329 of Sphinx-generated tex file, could you if possible post this line say, starting at line 325, and up to line 329, so that I see better what happens. I will try to reproduce this in meantime.

**Comment by jfbu** [comment]
ok I reproduced it immediately no need you bother posting your tex. Strange it wasn't intercepted by `make test`.  I will fix it once I understand my mistake.

**Comment by jfbu** [comment]
The problem can be fixed by 

```
\newcommand{\sphinxstyleliteralintitle}{\texttt}
```

rather than the current `\let\sphinxstyleliteralintitle\texttt`. Obviously this has to do with the mechanism for robust commands by LaTeX, but I thought that the `\let` was ok, because this means that it expands to  `\protect \texttt<space here in macro name>`. Obviously I still have something to understand about LaTeX innards.. 

I will push immediately a commit (and take time after to understand ;-) ) which uses the `\newcommand` (or perhaps `\DeclareRobustCommand` I will decide next) at bottom of sphinx.sty.

Sorry for inconvenience and a thanks a lot for reporting !

**Comment by mgeier** [comment]
No problem, thanks for the incredibly quick fix!

**Comment by jfbu** [comment]
The change had just been committed earlier today, it is great you found the problem immediately !

For the record, the bug is from an interaction with `hyperref`. Removing hyperref (and things depending upon it like `\urlstyle`)  there is no problem. I suppose this is documented somewhere.

**Comment by jfbu** [comment]
for example  this http://tex.stackexchange.com/questions/106346/fragile-error-on-robust-command-using-relsize seems to be an instance of the same phenomenon. The poster had a quite sane `\DeclareRobustCommand` and nevertheless ended up in infinite loop due to hyperref ... there is no detailed explanation of the mechanism there however.

For our case, I suspect hyperref wants to force full expansion for bookmarks, hence it has a means to recognize LaTeX robust commands, perhaps it has a list, but `\sphinxstyleliteralintitle` is not known to hyperref, first expansion replaces it with `\protect \texttt<space in name>`, and somehow then hyperref deactivates the `\protect` does more expansion and this time ends in infinite loop.

The infinite loop is the worst because it sometimes means one does not get exploitable log. Using latex, not pdflatex, often allows to obtain more exploitable log.

My long experience with un-decipherable LaTeX errors did not yet include that case ;-) !

**Comment by jfbu** [comment]
briefly, as this is not so much Sphinx matters, I had forgotten the details, but now I recall that `hyperref` executes a command `\pdfstringdef` on the title of sections (without optional arguments), and this includes dozens of redefinitions including this one:

```
{changing \texttt=macro:->\protect \texttt  }
{into \texttt=\long macro:#1->#1}
```

These redefinitions are done to prepare an expansion done by `\xdef`. This is all explained in section 6.2.2 of the commented source code of hyperref (I can't give direct link, it is complicated to navigate to this from the hyperref.pdf user documentation, it is hidden location). When the `\xdef` is done the `\protect` has meaning `\relax`. Let's imagine we have done earlier  `\let\foo\texttt`, then `\foo` will expand to `\protect \texttt<space>` where the space is part of the macro name. But this `\texttt<space>` is _not_ redefined by hyperref. And thus it causes an expansion. Which is not wanted here. It may lead to infinite loop depending on circumstances (inside the `\xdef` counts are not incremented, definitions not executed, hence typically tests will not act as expected.) To let `\foo` be handled safely by hyperref, one can do things like:

```
\pdfstringdefDisableCommands{\let\foo\relax}
```

As a LaTeX user one is used to `\texorpdfstring` usage inside section titles. When using some generator like Sphinx, one forgets that it may put things into section titles which could need the `\texorpdfstring`. 

With the `\newcommand\foo{\texttt}` there is no problem because of the redefinition of `\texttt` above (which is done among dozens of such redefinitions **each time** hyperref handles a section heading !)
