### ISSUE TITLE
Add a way to suppress warnings caused by default_role = “any”

### ISSUE THREAD

**Issue by Wrzlprmft** [sphinx-doc/sphinx#2709]
I use `any` as the default role, but I have a lot of inline code snippets (marked-up with `) for which there is no target for `any` to find. They are rendered as regular code, which is exactly what I want, but the output is cluttered with warnings for references for which `any` could not find a target. This is obviously annoying as it makes it difficult to find important warnings without filtering Sphinx’s output.

I thus propose to add some way to suppress such warnings, e.g., by making a variant of `any` (say `any_no_warnings`) that does not throw such warnings and is intended for being used as a default role.

**Comment by lehmannro** [comment]
I'm not sure what you're asking for?  The &#96; and &#96;&#96; [markup constructs](http://www.sphinx-doc.org/en/stable/rest.html#inline-markup) are different things, the former being for roles/references and the latter for code.  Default roles consequently only apply to the former.

**Comment by Wrzlprmft** [comment]
If I use `any` as a default role, single backticks (`) default to code formatting (i.e., the same as double backticks) if no reference can be found. Thus, with `any`, I can consistently use single backticks for all code, whether I expect it to be linked or not. This is convenient and makes the docstrings consistent.

**Comment by tk0miya** [comment]
I'm agree with @lehmannro . The single backtick quotes is not a notation for literals. It is only for roles.
http://docutils.sourceforge.net/docs/ref/rst/roles.html

So I'll never add the option to suppress the warnings.

BTW, you can suppress the warnings with following ad-hoc code.

```
def on_missing_reference(app, env, node, contnode):
    if node['reftype'] == 'any':
        return contnode
    else:
        return None


def setup(app):
    app.connect('missing-reference', on_missing_reference)
```

Thanks,

**Comment by Wrzlprmft** [comment]
Okay. Thanks for the work-around.

**Comment by barbara-sfx** [comment]
I know this issue is closed, but I have been meaning to ask why roles/ single backticks default to code format in the first place. I use the any role as links in our glossary and it looks odd to have the links show up in code. Why aren't they just formatted the same as every other link? Is that a known/requested issue?  Can I specify that somewhere? Thanks.

http://docs.signalfx.com/en/latest/reference/glossary/glossary.html

(BTW if you see an Edit on github button there, it might not work yet. I've asked the developer to fix it.)
