### ISSUE TITLE
invalid name: __objclass__ using napoleon

### ISSUE THREAD

**Issue by rmangi** [sphinx-doc/sphinx#2732]
Hi,

We have a bit of legacy code that is erroring out when we enable napoleon. 

The code in question is fairly simple, if not super pythonic :)

``` Python
class Enum(set):
    def __getattr__(self, name):
        if name in self:
            return name
        raise KeyError('invalid name: %s' % name)

    def __getitem__(self, name):
        return self.__getattr__(name)
```

`File "/Users/rick/.pants.d/python-setup/chroots/fd723fde174e04ea2dc167b760aa973b0e6bfd4a/pychartbeat/enum.py", line 15, in __getattr__
    raise KeyError('invalid name: %s' % name)
KeyError: 'invalid name: __objclass__'`

[stacktrace.txt](https://github.com/sphinx-doc/sphinx/files/343774/stacktrace.txt)

**Comment by RobRuana** [comment]
Thanks for the report!

**Comment by RobRuana** [comment]
Ok, I can see where this is happening, but I can't for the life of me replicate the error you're seeing.

The error indicates that Napoleon is trying to call `getattr(obj, '__objclass__')` on an **instance** of `Enum`, rather than on the class itself.

Is `Enum` being used as a metaclass somewhere? Or is there some other python magic happening beyond the code snippet you posted above?

**Comment by RobRuana** [comment]
You may want to consider changing `Enum.__getattr__` to raise an `AttributeError` instead of a `KeyError`. The [python docs](https://docs.python.org/3/reference/datamodel.html#object.__getattr__) for `__getattr__` explicitly say it should raise an `AttributeError` if the value can't be found.

Consider the following:

``` python
e = Enum()
result = getattr(e, 'nonexistent_attr', 'default_value')
```

When `Enum.__getattr__` raises a `KeyError`, the above code will throw an error.

If you change `Enum.__getattr__` to raise an `AttributeError` instead, the above code will run successfully. `result` will end up with a value of `default_value`, which I think is the expected behavior.

Incidentally this should also fix your Napoleon error.

**Comment by rmangi** [comment]
Thanks Rob, I'm on holiday will try this next week. 

Best

**Comment by rmangi** [comment]
That fixed it Rob, thanks a lot!
