### ISSUE TITLE
Link checker doesn't accept gzip content

### ISSUE THREAD

**Issue by nijel** [sphinx-doc/sphinx#2775]
When server is configured to server only compressed content, linkcheck fails. For example this can be seen on https://tcpdf.org/. 

This can be simply fixed by adding `Accept-encoding: gzip` header to the URL opener (at least for HEAD requests, for GET and anchor checking probably more work would be needed).

I can see that master branch has switched to using requests, where this case works just fine. I just would like to see this work in released version as well...

**Comment by tk0miya** [comment]
Are you saying master branch works fine? If true, please wait a next major release. because it seems too hard and meaningless to support it on stable branch.

Until the release, you can download it from https://github.com/sphinx-doc/sphinx/archive/master.zip

Note: master branch is still in develop, so there might be some bugs.

**Comment by nijel** [comment]
Yes, it seems to work fine in master. I just have no clue what is
schedule for releasing it and so whether it's worth fixing in stable
releases before...

Dne 15.7.2016 v 04:55 Takeshi KOMIYA napsal(a):

**Comment by tk0miya** [comment]
The target day for next major release is not planed yet. But, IMO, it might be released in this autumn.

Of course, all contributions are welcome. so it's okay to merge PR to fix this on stable branch.

**Comment by nijel** [comment]
Here comes the PR: https://github.com/sphinx-doc/sphinx/pull/2809

**Comment by tk0miya** [comment]
Merged #2809.
