### ISSUE TITLE
Expand sphinx.ext.mathjax to support KaTeX (including autorender)

### ISSUE THREAD

**Issue by jason-s** [sphinx-doc/sphinx#2839]
Several things are required to support KaTeX with autorendering rather than MathJax:

In the `<head>`:
- use KaTex CSS: `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css">`
- use the KaTeX URL rather than the MathJax URL: `<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>`
- use the KaTeX autorender URL: `<script src="http://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/contrib/auto-render.min.js"></script>`

At the end of the `<body>`:

```
<script>
    renderMathInElement(document.body);
</script>
```

Otherwise the two are very similar, and it seems like it would make sense to add a `katex` option in the `sphinx.ext.mathjax` extension. If I look at the code https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/mathjax.py I get a sense of what's needed to add Javascript to `<head>` , not sure about CSS or how to add something into `<body>`.

**Comment by jason-s** [comment]
relates to #2430

**Comment by jason-s** [comment]
see https://github.com/jason-s/sphinx-ext-mathjax/commit/c343e53fd62dfa840390ba6cbf3cb8b445d99c75 for a sample solution

**Comment by tk0miya** [comment]
You can use `Application.add_javascript()` to add custom java scripts.
http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_javascript

Sphinx also uses jQuery by default. So you can use `$(document).ready({ ... })` to call `renderMathInElement()`.

**Comment by tk0miya** [comment]
Now I close this issue.
If you still have a question on developing extensions, please post it to sphinx-dev forum.
https://groups.google.com/forum/#!forum/sphinx-dev

Thanks,

**Comment by jason-s** [comment]
I don't understand, sphinx.ext.mathjax is part of the standard Sphinx distribution, why can't issues about it be discussed here?

**Comment by tk0miya** [comment]
Did you see my comment at #2430?

**Comment by jfinkels** [comment]
@tk0miya I think the reasoning behind this pull request is that if MathJax is worthy enough to be in sphinx-core, then it seems reasonable that KaTeX might also be worthy, as it is nearly a drop-in replacement for MathJax. Conversely, if KaTeX is not worthy of being in sphinx-core, then why is MathJax worthy?

**Comment by tk0miya** [comment]
Reopened for discussion :-)

Agreed. It looks KaTeX is worthy as you said. But it is not enough to bundle it. There are many worthy extensions and utilities. KaTeX is much worthy than them? Is there any problem to release it as 3rd party package?

In addition, another reason is maintainer problem. we don't have enough time and knowledges to maintain KaTeX module. If bundled, who maintains it?

> Conversely, if KaTeX is not worthy of being in sphinx-core, then why is MathJax worthy?

Both are worthy enough for me. I think it is a historical reason.

It was bundled since Sphinx-1.1.
At that time, the sphinx-core is smaller than now. So the maintainers of those days accepted it.
But nowadays, sphinx-core becomes huge. It's too hard to maintain by few people.
If someone proposed to bundle MathJax NOW, I will discuss as same as this case.

I have plan to unbundle some extensions in future release. We have to slim down sphinx-core to keep sustainable. So we need to discuss that it should be bundled or not.

**Comment by tk0miya** [comment]
Now I close this again.
Thanks,

**Comment by hagenw** [comment]
If someone with the same question ends up here: I have implemented a KaTeX sphinx extension, that can be used instead of mathjax, see https://github.com/hagenw/sphinxcontrib-katex/
