### ISSUE TITLE
The LaTeX builder handles image directive's scale option in a weird way

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#2865]
The LaTeX builder scales images differently depending on whether the (unscaled) image fits within `\textwidth` or not.

```
.. image:: images/image.png
   :scale: 80%
```

If the image fits within the text width, the scale option works as expected; the image is scaled to 80% of its original size.

If the image is wider than the text width, it is first scaled to fit the text width. Subsequently, it is scaled again using the `:scale:` factor. For the example, the image is thus scaled to 80% **of the text width** (instead of the original image's size).

This is confusing. If the user in fact wants to scale the image relative to the text width, (s)he can pass a percentage to the `:width:` option:

```
.. image:: images/image.png
   :width: 80%
```

**Comment by tk0miya** [comment]
Thank you for reporting. You're right.

Current sphinx generates the LaTeX code below.

```
\scalebox{0.800000}{\includegraphics{logo.jpg}}
```

This means the image is resized to 80% of its original size.

Basically, this works fine. But if the image is larger than `\textwidth`, the `\includegraphics` macro resizes it to `\textsize` at first. Because of good layout, Sphinx fits the images to `\textwidth` automatically. After that, `\scalebox` resizes it to 80% of the `\textwidth`, not original size. This combination causes the situation.

It would be better if the scale option works before fitting to `\textwidth`.

**Comment by jfbu** [comment]
I have amended my PR #3059 in order to maintain earlier behaviour in case the `:width:` or `:height:` attribute was used.

in case of merge, the commit message should possibly be amended toread "make latex image inclusion scale ..." as in the one I pushed it is not clear if the sentence refers to what is done or to what is changed.
