### ISSUE TITLE
ROI: copyright statement for latex

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2876]
Copyright statement seems to be available only for HTML and ePub. Would it be possible to have it also for Latex? 

I think it should appears in the bottom or top of the second page, i.e. right after the title page.

**Comment by andreacassioli** [comment]
Any plan for this? Should the copyright setting be just common to all the targets?

**Comment by tk0miya** [comment]
Good idea. But maybe it will be introduced at 1.6 or later version.
If you want it in earlier version, please send pull request.

**Comment by HFriberg-mosek** [comment]
If anyone have a go with this enhancement request, it would also be nice to allow markup in the copyright statement such that external links would work across builders.

**Comment by gerritholl** [comment]
See also [this question on Stack Overflow](https://stackoverflow.com/q/54147210/974555) asking how to achieve this in the absence of this ROI being resolved.

**Comment by jfbu** [comment]
Maybe new since 1.8.3 `\sphinxbackoftitlepage` (see #5850) can help in solving this issue? it can already be used manually but user must define it. We could add the config value `copyright`,  once TeX-escaped, as default contents of `\sphinxbackoftitlepage`, or perhaps better TeX-escape it to some `\sphinxusercopyright` macro which the user may or not use in whatever location, for example as part of a custom `\sphinxbackoftitlepage`.
