### ISSUE TITLE
Sphinx class missing __exit__ ??

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2942]
Hi,
I am trying to use Sphinx from a Python 3 script. Since I need to make some pre/post processing, it would make my job much easier. In particular I want to call Sphinx in a loop with different options.

At first I tried to use `sphinx.build_main`, but since I see that basically reverts to `sphinx.cmd_line.main` I tried the latter. It works, but to my great surprise it seems some global information are not cleaned up on exit! For instance I get multiple reference menu and warnings about extension to be overwritten.

So I decided to dig deeper and directly use the `Sphinx` class. Indeed I manage the options and I exactly know what to pass to it. What I do now is

```
       with Sphinx(srcdir, confdir, outdir, doctreedir, BUILDER,
                    confoverrides, status, warning, freshenv,
                    warningiserror, tags, verbosity, jobs) as app:

            app.build(force_all, filenames)

            res = app.statuscode
```

That to me should help clean up the environment (well possibly...), but to my great surprise it seems that the Sphinx class it is not ready for `with`:

```
AttributeError: __exit__
```

How is that? Any workaround?

**Comment by andreacassioli** [comment]
Of course `__enter__` is missing as well.

**Comment by lehmannro** [comment]
You make it sound like that's some kind of bug in Sphinx, whereas some objects in Python _are_ context managers, and some _aren't._  Sphinx isn't.

There are some issues with using Sphinx as a library (#2799, #2687) but pull requests are always welcome.  I think the previous recommendation has always been multiple processes.  Maybe also have a look at the [test utilities](https://github.com/sphinx-doc/sphinx/blob/master/tests/util.py).

I'm closing this because there's enough tickets tracking this already, and this isn't going to move forward other than by actual patches.
