### ISSUE TITLE
Linkcheck url to linkedin.com

### ISSUE THREAD

**Issue by HFriberg** [sphinx-doc/sphinx#2988]
The following is a valid link:
https://www.linkedin.com/company/mosek-aps
But I get "WARNING: broken link" from sphinx/builders/linkcheck.py? 

Note:
W3C also has issues with this page as seen by https://validator.w3.org/checklink?uri=https://www.linkedin.com/company/mosek-aps which returns::
    Error: 403 Forbidden by robots.txt 

Nevertheless, W3C use the user-agent "W3C-checklink", while Sphinx use the ordinary "Mozilla/5.0" so I am not sure robots.txt is the issue here.

**Comment by hhsprings** [comment]
memo:
- requests.get without user-agent: 999 (Request Denied)
- requests.get with user-agent: 200 OK
- session.get: 200 OK (session has already user-agent header)
- session.head: 404

**Comment by hhsprings** [comment]
workaround:

``` python
                    try:
                        # try a HEAD request, which should be easier on
                        # the server and the network
                        response = self.session.head(req_url, **kwargs)
                        response.raise_for_status()
                    except HTTPError as err:
                        if err.response.status_code not in (403, 404, 405):  # add 404
                            raise
                        # retry with GET if that fails, some servers
                        # don't like HEAD requests and reply with 403 or 404 or 405
                        response = self.session.get(req_url, stream=True, **kwargs)
                        response.raise_for_status()
```

**Comment by hhsprings** [comment]
I noticed similar but different problem. [Practical Programming in Tcl and Tk](http://www.beedub.com/book/) is surely valid link, but linkcheck.py reports it is 403 (`403 Client Error: Forbidden for url:`).

**Comment by hhsprings** [comment]
[Practical Programming in Tcl and Tk](http://www.beedub.com/book/) respond with 403 if user-agent is set, and if not set, 200 OK...?? んなアホな。If it is true, why normal browser can browse?

workaround (updated):

``` python
                    try:
                        # try a HEAD request, which should be easier on
                        # the server and the network
                        response = self.session.head(req_url, **kwargs)
                        response.raise_for_status()
                    except HTTPError as err:
                        if err.response.status_code not in (403, 404, 405):  # add 404
                            raise
                        # retry with GET if that fails, some servers
                        # don't like HEAD requests and reply with 403 or 404 or 405
                        response = self.session.get(req_url, stream=True, **kwargs)
                        if response.status_code == 403:
                            # retry with GET without user-agent header...
                            response = requests.get(req_url, stream=True, **kwargs)
                        response.raise_for_status()
```

**Comment by hhsprings** [comment]
In CPython document, even if above workarounds (and #2992) were applied followings are reported as `broken`:

```
faq/general.rst:271: [broken] http://www.upfrontsystems.co.za/: 500 Server Error: Internal Server Error for url: http://www.upfrontsystems.co.za/
faq/windows.rst:0: [broken] http://showmedo.com/videotutorials/series?name=pythonOzsvaldPyNewbieSeries: HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/series?name=pythonOzsvaldPyNewbieSeries (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000B535C50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
faq/windows.rst:18: [broken] http://showmedo.com/videotutorials/series?name=pythonOzsvaldPyNewbieSeries: HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/series?name=pythonOzsvaldPyNewbieSeries (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000B535128>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
faq/windows.rst:0: [broken] http://showmedo.com/videotutorials/video?name=960000&fromSeriesID=96: HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/video?name=960000&fromSeriesID=96 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000AD52BA8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
faq/windows.rst:18: [broken] http://showmedo.com/videotutorials/video?name=960000&fromSeriesID=96: HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/video?name=960000&fromSeriesID=96 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000AD52048>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
library/hashlib.rst:229: [broken] http://csrc.nist.gov/publications/fips/fips180-2/fips180-2.pdf: ('Connection aborted.', BadStatusLine("''",))
library/mailbox.rst:698: [broken] https://quimby.gnus.org/notes/BABYL: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
library/mailbox.rst:494: [broken] http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/mail-mbox-formats.html: ('Connection aborted.', BadStatusLine("''",))
library/othergui.rst:26: [broken] https://www.commandprompt.com/community/pyqt/: 404 Client Error: NOT FOUND for url: https://www.commandprompt.com/community/pyqt/
library/statistics.rst:229: [broken] https://help.gnome.org/users/gnumeric/stable/gnumeric.html#gnumeric-function-SSMEDIAN: Anchor 'gnumeric-function-SSMEDIAN' not found
library/subprocess.rst:762: [broken] https://msdn.microsoft.com/en-us/library/ms633548(v=vs.85).aspx: ('Connection aborted.', BadStatusLine("''",))
license.rst:22: [broken] http://www.zope.com/: HTTPConnectionPool(host='www.zope.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000B2D03C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))
license.rst:131: [broken] http://www.pythonlabs.com/logos.html: 404 Client Error: Not Found for url: http://www.pythonlabs.com/logos.html
using/windows.rst:788: [broken] https://www.microsoft.com/com/: 503 Server Error: Service Unavailable for url: https://www.microsoft.com/com/default.mspx
using/windows.rst:876: [broken] https://www.microsoft.com/en-us/download/details.aspx?id=48145: 503 Server Error: Service Unavailable for url: https://www.microsoft.com/en-us/download/details.aspx?id=48145
whatsnew/2.1.rst:543: [broken] http://www.vex.net/parnassus/: 404 Client Error: Not Found for url: http://www.vex.net/parnassus/
whatsnew/2.6.rst:174: [broken] http://www.upfrontsystems.co.za/: 500 Server Error: Internal Server Error for url: http://www.upfrontsystems.co.za/
whatsnew/2.6.rst:174: [broken] http://svn.python.org/view/tracker/importer/: 404 Client Error: Not Found for url: http://svn.python.org/view/tracker/importer/
whatsnew/2.6.rst:193: [broken] http://svn.python.org/view/tracker/importer/: 404 Client Error: Not Found for url: http://svn.python.org/view/tracker/importer/
whatsnew/2.6.rst:2366: [broken] http://tipc.sourceforge.net/: ('Connection aborted.', BadStatusLine("''",))
whatsnew/3.2.rst:959: [broken] http://greenteapress.com/semaphores/downey08semaphores.pdf: 404 Client Error: Not Found for url: http://greenteapress.com/semaphores/downey08semaphores.pdf
```

In these, valid links are included. (for example https://www.microsoft.com/com/.)

**Comment by tk0miya** [comment]
Hmm... linkedin returns 404 to our HEAD request. I feel that is very strange. but, in fact, some HTTP servers does not support HEAD request...

```
$ curl -I -X HEAD -H "accept-encoding: identity" -A 'Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0' --url http://www.linkedin.com/company/mosek-aps
HTTP/1.1 404 Not Found
Content-Type: text/html
Server: Play
Content-Length: 6417
X-FS-UUID: 56f5121189317a1420f9471a912b0000
Date: Tue, 04 Oct 2016 01:58:12 GMT
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Li-Fabric: prod-lsg1
Set-Cookie: bcookie="v=2&0848fc2d-44f9-4e16-8bbf-06f3e57afd7a"; domain=.linkedin.com; Path=/; Expires=Thu, 04-Oct-2018 13:35:44 GMT
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache, no-store
Connection: keep-alive
X-Li-Pop: prod-ehk2-highspeed
X-LI-UUID: VvUSEYkxehQg+UcakSsAAA==
Set-Cookie: lidc="b=SGST07:g=1:u=1:i=1475546292:t=1475632692:s=AQE6gBhdlSGA_iQyHX4Yvjs64Hfe7qXn"; Expires=Wed, 05 Oct 2016 01:58:12 GMT; domain=.linkedin.com; Path=/
```

**Comment by tk0miya** [comment]
it seems linkedin publishes invalid cookies.
If we use requests.session, even GET request fails. How much they hates HEAD requests...

```
from sphinx.util.requests import requests, useragent_header

session = requests.Session()
session.headers = dict(useragent_header)

url = 'https://www.linkedin.com/company/mosek-aps'
print "# Using session"
print "HEAD =>", session.head(url)
print "GET =>", session.get(url)

print ""
print "# Not using session"
print "HEAD =>", requests.head(url, headers=dict(useragent_header))
print "GET =>", requests.get(url, headers=dict(useragent_header))
```

```
$ python test.py
# Using session
HEAD => <Response [404]>
GET => <Response [999]>

# Not using session
HEAD => <Response [404]>
GET => <Response [200]>
```

**Comment by tk0miya** [comment]
I fixed this at ce7fea9.
It will be fixed at next major release (v1.5).

With the fix, it seems @hhsprings 's problem is also fixed.
Could you check this please?
If not, please file a new issue.

Thank you for reporting

**Comment by hhsprings** [comment]
Thanks, I'll check it. Please wait.

**Comment by hhsprings** [comment]
With merging my #2992 to your fix, newer linkcheck reports these:
- [x] http://csrc.nist.gov/publications/fips/fips180-2/fips180-2.pdf: `('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`
- [x] http://greenteapress.com/semaphores/downey08semaphores.pdf: `404 Client Error: Not Found for url: http://greenteapress.com/semaphores/downey08semaphores.pdf`
- [x] http://homepage.ntlworld.com/jonathan.deboynepollard/FGA/mail-mbox-formats.html: `('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`
- [x] http://showmedo.com/videotutorials/series?name=pythonOzsvaldPyNewbieSeries: `HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/series?name=pythonOzsvaldPyNewbieSeries (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000717E160>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://showmedo.com/videotutorials/series?name=pythonOzsvaldPyNewbieSeries: `HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/series?name=pythonOzsvaldPyNewbieSeries (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000717EC18>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://showmedo.com/videotutorials/video?name=960000&fromSeriesID=96: `HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/video?name=960000&fromSeriesID=96 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000006ADEC50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://showmedo.com/videotutorials/video?name=960000&fromSeriesID=96: `HTTPConnectionPool(host='showmedo.com', port=80): Max retries exceeded with url: /videotutorials/video?name=960000&fromSeriesID=96 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000717EB38>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://svn.python.org/view/tracker/importer/: `404 Client Error: Not Found for url: http://svn.python.org/view/tracker/importer/`
- [x] http://www.pygtk.org/: `HTTPConnectionPool(host='www.pygtk.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000008C77BE0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://www.pygtk.org/pygtk2tutorial/index.html: `HTTPConnectionPool(host='www.pygtk.org', port=80): Max retries exceeded with url: /pygtk2tutorial/index.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000005147F28>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://www.pygtk.org: `HTTPConnectionPool(host='www.pygtk.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000BCE3668>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [x] http://www.pythonlabs.com/logos.html: `404 Client Error: Not Found for url: http://www.pythonlabs.com/logos.html`
- [x] http://www.vex.net/parnassus/: `404 Client Error: Not Found for url: http://www.vex.net/parnassus/`
- [x] http://www.zope.com/: `HTTPConnectionPool(host='www.zope.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000B607128>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))`
- [ ] https://quimby.gnus.org/notes/BABYL: `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)`
- [x] https://scipy.github.io/devdocs/tutorial/weave.html: `404 Client Error: Not Found for url: https://scipy.github.io/devdocs/tutorial/weave.html`
- [x] https://www.commandprompt.com/community/pyqt/: `404 Client Error: NOT FOUND for url: https://www.commandprompt.com/community/pyqt/`

I'm checking indivisually...Done.

https://quimby.gnus.org/notes/BABYL is the case, but it is another issue, I think.
