### ISSUE TITLE
literal blocks in footnotes are not supported by Latex

### ISSUE THREAD

**Issue by itfanr** [sphinx-doc/sphinx#3003]
During converting rst to tex, I got the error. 

https://github.com/gotgit/gotgithub/issues/24

**Comment by jfbu** [comment]
This issue is part of #2616.

Memo: currently already Sphinx uses package LaTeX `footnote.sty` but not its `footnote` environment which allows verbatim material. However `footnote.sty` is old and has bugs (incompatibility with `xcolor` and unawareness of `hyperref` in particular). Package [footnotehyper](http://www.ctan.org/pkg/footnotehyper) fixes some such issues. It could be shipped with Sphinx taking place of the currently shipped custom `tabulary.sty` which incorporate a change for compatibilty with old package `footnote.sty`.

**Comment by jfbu** [comment]
@tk0miya I have a branch at https://github.com/jfbu/sphinx/tree/improvefootnotes which now allows code-blocks within footnotes. I need to do some testing, it is not mature enough for a PR. Initially the branch was about improving footnotes inside table. It was stale for some months, now I have renamed and revived it. From the point of view of hyperlinks, the problem is that LaTeX's hyperref does not implement them if the code uses `\footnotemark[N]/\footnotetext[N]` syntax, which various parts of Sphinx use in tables. 

As per allowing code-blocks we use environment form of `footnote`. This needs own Sphinx shipped latex package.

**Comment by jfbu** [comment]
I have rebased and updated https://github.com/jfbu/sphinx/tree/improvefootnotes at https://github.com/jfbu/sphinx/commit/b5a96853cbbd4fe15dfc59f877487a73bde82ae7. This version updates the root tests. It allows code-blocks in footnotes, even with captions ! Also hyperlinking of footnotes is improved.

Further needed improvements: modify `latex.py` so that the footnotes will use `\footnotemark[N]` in less cases. Only need in captions and inside `tabulary`. There is no need in longtable cells.

**Comment by itfanr** [comment]
@jfbu  Thank you for your answer.

**Comment by jfbu** [comment]
PR #3022

**Comment by itfanr** [comment]
@jfbu  What I know  about  sphinx is less . I will look into it when I  am free .  Thank you .

**Comment by jfbu** [comment]
fixed at b8e0e93 for 1.5a2 pre-release. Thanks for reporting !

**Comment by itfanr** [comment]
@jfbu Thank you .
