### ISSUE TITLE
Bad rendering of parsed-literals in LaTeX: regression introduced in Sphinx 1.4.4 and still present

### ISSUE THREAD

**Issue by RobertoBagnara** [sphinx-doc/sphinx#3009]
[bug.zip](https://github.com/sphinx-doc/sphinx/files/510217/bug.zip)

$ unzip bug.zip
$ cd bug
$ make latexpdf
$ evince ./_build/latex/bug.pdf

With Sphinx 1.4.x for x = 4, 5, 6, 7, 8, you will see in the last page of the created PDF

  command -opt1=  ARG1 -opt2=  ARG2/@MOD@.ext -opt3

where there are spurious spaces after the two equal signs; moreover, ARG1 and ARG2 are not in italics as they should.

If you retry with Sphinx 1.4.3 you will see that the PDF output is as expected.

**Comment by jfbu** [comment]
You can reproduce the problem directly with this LaTeX file:

``` latex
\documentclass{article}

\usepackage{alltt}

\begin{document}
\begin{alltt}
a\emph{A}\emph{B}\emph{C}\relax
\scantokens{a\emph{A}\emph{B}\emph{C}\relax}
\end{alltt}
\end{document}
```

Compare rendering of first and second line:

![capture d ecran 2016-10-05 a 09 45 53](https://cloud.githubusercontent.com/assets/2589111/19105119/9f2ea110-8ae0-11e6-98d9-45577e338931.png)

Starting with Sphinx 1.4.4, there is a `\scantokens` used inside `\code` (aka `\sphinxcode` macro). Besides Sphinx uses the `alltt` for parsed-literal directive. The bug results from the combination of the two, or the three: `\emph` inside `\scantokens`,  inside `alltt`. It is not immediately obvious to me how it all conspires to produce the bug. Will investigate...

**Comment by jfbu** [comment]
Commit https://github.com/jfbu/sphinx/commit/a55b51f18b800102abf31a8bcb2b90a0544be213 on jfbu/sphinx was based on stable, commit https://github.com/jfbu/sphinx/commit/7af5f5d79a5ae4d59dc3e09bf389f7e542be3405 is based on master. (and moved the `\@noligs` location). This is PR https://github.com/sphinx-doc/sphinx/pull/3010.

**Comment by jfbu** [comment]
The explanation for LaTeX-experts: `\scantokens` works by simulating writing to a file and parsing again. When TeX writes verbatim to a file something like `\write\outstream{\the\toks0}`, the control sequences such as  `\emph{foo}` in `\toks0` are written `\emph<space>{foo}`. Then `\scantokens` parses, but the `alltt` environment has made the space "active". Thus `\emph` does not see the `{foo}`  but rather the `<space>` as its argument (a normal space would be gobbled and `{foo}` would be the macro argument.) This explains why there is a space and why the `{foo}` is not typeset with the italic font.

Thus an alternative to fix at PR #3010 could be do the `\scantokens` after having reset the catcode of space to `10`. But anyway, inside `alltt` there is no need for this `\scantokens` whose rôle is to make sure the quotes end-up straight in the output, in case the earlier the`\@noligs` which changes catcodes was ineffective because the whole thing was grabbed as a macro argument and catcodes are frozen. But `alltt`  does noes appear inside macro arguments and besides it already does the `\@noligs`. Whow....

**Comment by RobertoBagnara** [comment]
On 10/06/2016 07:27 PM, Jean-François B. wrote:

> Closed #3009 https://github.com/sphinx-doc/sphinx/issues/3009 via 44f595a https://github.com/sphinx-doc/sphinx/commit/44f595a63f94e9e83c477125fb4c725a21a6a72c.

Great, thanks!

**Comment by jfbu** [comment]
@RobertoBagnara sorry for inconvenience caused by my commit in Sphinx 1.4.4 which caused this... (I wasn't aware and didn't test that the modified code could end up in an `alltt` LaTeX environment.) hopefully things will be ok now. (the aim in Sphinx 1.4.4 was to let Sphinx use straight quotes in LaTeX rendering of inline code)

**Comment by RobertoBagnara** [comment]
No problem. I look forward to the release of Sphinx 1.4.9. Thanks a lot for your work and support.

**Comment by jfbu** [comment]
@tk0miya I pushed the commit to master branch hence I guess for 1.5 but should have I rather done it on stable branch for 1.4.9 ? (if there will be one ?)
