### ISSUE TITLE
Migrate to TeXLive 2013

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3070]
In next spring, Apr 2017, Ubuntu 12.04LTS reaches its EOL.
So it's time to migrate the support version of TeXLive.

As a quick look, Ubuntu 14.04 LTS has TeXLive-2013.
So I propose Sphinx-1.6 supports TeXLive 2013 or above.

**Comment by shimizukawa** [comment]
+1

**Comment by jfbu** [comment]
according to https://www.tug.org/texlive/debian.html, the versions of TeXLive shipped are

  Ubuntu: hardy: 2007, lucid: 2009, natty: 2009, oneiric: 2009, precise (12.04LTS): 2009, raring (13.04): 2012, saucy (13.10): 2013, trusty (14.04LTS): 2013, utopic, vivia: 2014, wily: 2015, xenial (current stable): 2015, yakkety (dev): 2016.

PR#3064 starts using "fontspec" for XeTeX/LuaLaTeX by default, but "fontspec" started supporting LuaTeX only with (kept up-to-date) TL2010 or TL2011. From the point of view of Travis checking, perhaps it could switch to using TL2012 earlier than 1.6 ? perhaps Sphinx-1.5 supports TeXLive 2012 or above ?

**Comment by jfbu** [comment]
PR #3064 make test succeeds on TeXLive 2013 but not TeXLive 2012 on my Mac. Hence I amend for my previous comment. But could Sphinx-1.5 say: "for LuaLaTeX/XeLaTeX, you need at least TeXLive 2013" without waiting Sphinx-1.6 ?

One would need a test on a pristine TL2013, because mine has all the updates before TL2014 release.

**Comment by tk0miya** [comment]
I have no strong opinion to support precise and TeXLive 2009 at Sphinx-1.5.
I heard this support policy from @birkenfeld when I try to add a LaTeX package which is not belong to precise.
So we can change it if he agreed.

If not, I will revert the default settings for LuaLaTeX from #3064.
It only means Sphinx-1.5 does not give a default settings for LuaLaTeX. Nothing are changed from 1.4.

**Comment by tk0miya** [comment]
Note: The `fontspec` package in TeXLive 2009 does not support LuaTeX. We could not give a good default settings for LuaTeX (ref: #3064).
So we should improve it after migrating to TeXLive 2013.

**Comment by tk0miya** [comment]
Now we are testing with Ubuntu 14.04 on Travis CI. It seems no error now.
Here is what we should do before release:

- check some style files should be still bundled (or use TeXLive 2013's)
- update default settings for LuaLaTeX
- Remove needless `\phantomsection`

```
$ grep -r TeXLive sphinx
sphinx/texinputs/sphinxhowto.cls:% Note: \phantomsection is required for TeXLive 2009
sphinx/texinputs/sphinxmanual.cls:% Note: \phantomsection is required for TeXLive 2009
```

Anything else?

**Comment by tk0miya** [comment]
Now we don't say about the support version of TeX distro.
Through this opportunity, it would be better to make clear it.

**Comment by jfbu** [comment]
``\phantomsection``'s handled at f3e071a

**Comment by jfbu** [comment]
regarding ``sphinx/texinputs/needspace.sty`` it is categorized by TeXLive in ``collection latexextra``. 

```
$ tlmgr info --list collection-latex | wc -l
      40

$ tlmgr info --list collection-latexrecommended | wc -l
      70

$ tlmgr info --list collection-latexextra | wc -l
    1141
```

I am not sure how distros handles things vz TeXLive categorizing, but anyhow ``needspace`` is very small  (35 lines including blank lines and comments) hence I think Sphinx can go on bundling it even if it is included at least since 2010 in TeXLive. I should check which LaTeX style files required by Sphinx are not in TeXLive's ``latexrecommended``.

**Comment by jfbu** [comment]
as a quick look I gathered these as immediate dependencies of Sphinx LaTeX:

    alltt amsmath amssymb amstext babel capt-of cmap color eqparbox fancyhdr fancyvrb float fncychap fontenc fontspec footnote framed geometry graphicx hypcap hyperref inputenc kvoptions longtable makeidx multirow needspace parskip polyglossia tabulary textcomp threeparttable times titlesec upquote wrapfig xcolor 

this does not include sub-dependencies ...

if I got it right all are included in TeXLive's collection ``basic``, ``latex``, ``latexrecommended``, ``fontsrecommended`` except:

```
capt-of
fncychap
framed
needspace
tabulary
threeparttable
titlesec
upquote
wrapfig

eqparbox
multirow
```

which are only listed in ``latex-extra``. It is not easy going because TeXLive "package" is not like LaTeX "package". I put aside ``eqparbox`` and ``multirow`` which are marked for removal if #3435 is merged. The others are well-established old packages (``needspace`` is I presume bundled with Sphinx because it is small and last updated 2010/09/12 after TL2009) but perhaps a note should be made about them being Sphinx dependencies. (I am not listing the document classes for Japanese)

edit: the list above was obtained by grepping in ``latex.py``, ``sphinx.sty``,  classes, templates, thus they are not strict dependencies as it depends on language (Japanese does not use ``babel`` for example) and whether user changes defaults.

update: all the above is not very interesting as on Linux distros one can not install easily individually LaTeX packages, for example [this search](http://packages.ubuntu.com/search?searchon=contents&keywords=capt-of.sty&mode=exactfilename&suite=trusty&arch=any) shows only ``texlive-latex-extra`` contains ``capt-of.sty``.

Anyway I have downloaded the file lists of Ubuntu/trusty and  this script

```console
#!/bin/bash

for i in alltt.sty amsmath.sty amssymb.sty amstext.sty babel.sty capt-of.sty cmap.sty color.sty fancyhdr.sty fancyvrb.sty float.sty fncychap.sty fontenc.sty fontspec.sty framed.sty geometry.sty graphicx.sty hypcap.sty hyperref.sty inputenc.sty kvoptions.sty longtable.sty makeidx.sty needspace.sty parskip.sty polyglossia.sty tabulary.sty textcomp.sty threeparttable.sty times.sty titlesec.sty upquote.sty wrapfig.sty xcolor.sty eqparbox.sty multirow.sty
do
    grep -q $i trusty-texlive-base.txt || \
    grep -q $i trusty-texlive-latex-base.txt || \
    grep -q $i trusty-texlive-latex-recommended.txt || \
    (echo -n "$i not found so far" ; \
    grep -q $i trusty-texlive-latex-extra.txt && echo " OK" \
	    || echo -e " \033[1;31mNOT FOUND\033[0m")
done

exit
```

confirms the above listed packages (and polyglossia) require ``texlive-latex-extra`` and the fact that ``xcolor.sty`` needs separate install if using Ubuntu/trusty.

**Comment by jfbu** [comment]
The ``xcolor`` being in ``latex-recommended``  the test for existence in ``sphinx.sty`` should presumably be dropped and ``xcolor`` always loaded rather than simply ``color``.

edit: no this is wrong, cf https://github.com/sphinx-doc/sphinx/issues/3070#issuecomment-282547501.

``xcolor`` is indeed in TeXLive 2013's ``latexrecommended`` collection but not in the ``texlive-latex-recommended`` of Ubuntu which is much smaller selection.

In fact https://github.com/sphinx-doc/sphinx/issues/3070#issuecomment-282481678 ``xcolor`` is not even in ``texlive-latex-extra``  of Ubuntu/trusty, but requires its own ``latex-xcolor`` package. All this is surely well-known to Ubuntu users, sorry, but recording it for memo.

``xcolor.sty`` is in Ubuntu 16.04's [texlive-latex-recommended](http://packages.ubuntu.com/xenial/all/texlive-latex-recommended/filelist) and needs there no separate install.

**Comment by jfbu** [comment]
updated docs at dbf9608

I wonder however if this this best place for it.

@tk0miya maybe it is not Debian, but Ubuntu which should be mentioned. Not owning a Linux box I am a bit lost with wheezy, jessie, stretch versus saucy, trusty, etc...

ah ok Ubuntu uses I think basically Debian packaging of TeXLive but has its own release dates thus for example trusty has [texlive-luatex (2013.20140215-1)](http://packages.ubuntu.com/trusty/texlive-luatex). This date of `20140215` indicates it is not initial TeXLive 2013. Hence I think the docs should not say TeXLive 2013, because there is possibility that things pass on the Ubuntu Trusty but not on the initial TeXLive 2013. Indeed I don't know for sure if #3466 would pass on initial TeXLive 2013, it fails on last update to TeXLive 2012. But it passes on Ubuntu/trusty.

**Comment by jfbu** [comment]
I have updated LaTeX builder docs at 7f1b9c0, reverting dbf9608 which used config.rst rather than builders.rst location in the documentation.

Again updated at ff700ae.

Ubuntu packaging does not correspond one to one to TeXLive similar named collections. For example trusty's [texlive-latex-recommended](http://packages.ubuntu.com/trusty/all/texlive-latex-recommended/filelist) is much smaller than TeXLive's latexrecommended.

Hence for clarity I used fuller packaging names at ff700ae.

**Comment by jfbu** [comment]
@tk0miya shouldn't we add ``latex-xcolor`` as new requirement for travis, because ``xcolor.sty`` is neither in [texlive-latex-recommended](http://packages.ubuntu.com/trusty/texlive-latex-recommended) nor in [texlive-latex-extra](http://packages.ubuntu.com/trusty/texlive-latex-extra) of Ubuntu/trusty ? But most users of LaTeX presumably have ``xcolor``. Although not those perhaps which don't use LaTeX directly.

The context here is that `sphinx.sty` loads `xcolor.sty` only if present. But `xcolor` makes LaTeX macro ``\fbox`` for framing fragile, as following test files proves:
```
\documentclass{article}

\usepackage{color}
%\usepackage{xcolor}

\begin{document}
\section{\fbox{A}}

\end{document}
```
Uncomment the xcolor the line and compilation fails. Thus it appears more cautious to test with xcolor than without.

Ah actually the above bug of `xcolor`  is automatically patched by `hyperref` package: it loads automatically package [hycolor](http://www.ctan.org/pkg/hycolor) which contains patch for this `xcolor` bug. Arrgghh... software is so time-consuming. No actually `hyperref` is not able to fix document above. (although documentation of ``hycolor`` contains a subsection related to such problems). Perhaps I have found another xcolor bug, or the patch of xcolor by hyperref is buggy. (I tried on TeXLive2013 also) [reported here](https://github.com/ho-tex/oberdiek/issues/21)

**Comment by tk0miya** [comment]
Sorry for late response. I'm checking the comments from above since now.

About `needspace.sty`:
Basically, I prefer to lessen bundled packages. Because we'll have to check updates of them if bundled.
I understand bundling package will bring us stable library. But, at same time, pinning the version also brings stagnation to the software. I believe we should follow the newest packages and interface as possible.

Get back to `needspace.sty`, it is a very small package, and it is not updated since 2010. So only in this package, it's okay to keep bundled.

About base version of TeXLive:
Thank you for investigation. I'd like to re-target this to "Migrate to Ubuntu/trusty". And we can say to migrate TeXLive 2012 of above at least.

**Comment by tk0miya** [comment]
About `xcolor`:
+1 for adding!

**Comment by tk0miya** [comment]
As conclusion, we are already finished this issue. I feel it was almost your work, thanks @jfbu !
Is there any remaining work?
If none, I'll close this.

**Comment by jfbu** [comment]
Your patience with my intertwined comments above need to have been great! I was verbose as usual but here because my perspective was purely TeXLive one at first. But Ubuntu Debian packaging uses latex-recommended not in same sense as TeXLive latexrecommended.

- about avoiding to bundle packages, I fully agree. Regarding needspace I wrote my comments at time I had not yet clear view of Debian latex-recommended versus latex-extra. Now, I think there is no clearcut reason to make an exception and to bundle needspace with Sphinx. I am for not bundling it.

- about xcolor, the issue being that it makes more fragile some macros and that in practice users should have it installed, I think we should test with it. It is too much complications to test both with xcolor and without. We can hope that somethings break more easily with than without xcolor.

I don't see any remaining work apart from removing needspace and adding xcolor Travis requirement via latex-xcolor Ubuntu/trusty package.

**Comment by tk0miya** [comment]
Thank you for quick response.
Okay, I'll do them tomorrow.

In Japan, it's night (at 3 AM), so I'm going to bed from now. Good night :-)

**Comment by jfbu** [comment]
@tk0miya I should have done earlier, I took care of it now (crossing fingers I don't cause again failed Travis test of master ...). Sleep is most important for brain !

**Comment by jfbu** [comment]
memo: find some perhaps more satisfying font configuration for xelatex/lualatex.

**Comment by tk0miya** [comment]
Can I close this?

**Comment by jfbu** [comment]
+1 for close. Basic migration is done. Choosing defaults fonts for xelatex/lualatex is further matter.

**Comment by tk0miya** [comment]
Okay, now I close this :-)
I feel LaTeX writer is much improved in 1.6. Thank you for all your work!
