### ISSUE TITLE
Link to custom module index?

### ISSUE THREAD

**Issue by HFriberg-mosek** [sphinx-doc/sphinx#3106]
I am using the Domain API and generate a custom index using:
http://www.sphinx-doc.org/en/1.4.8/extdev/domainapi.html#sphinx.domains.Index.generate

1)
:ref:`modindex` seems hardcoded to "py-modindex.html" whether or not this page exists or not..

2)
A custom Domain (name='msk') and Index (name='mskindex') does not seem to create a label. I have not inspected the rather huge doctree, but simply tried :ref:`mskindex`, :ref:`msk-mskindex` and :ref:`msk-modindex` among others..

Am I missing something or am suppose to add the target my self? In http://www.sphinx-doc.org/en/1.4.8/extdev/domainapi.html#sphinx.domains.Index.generate I tried::

    tnode = nodes.target('', '', ids=['msk-mskindex'])
    self.state.document.note_explicit_target(tnode)
    content.insert(0, tnode)

but I could not find a reference to state from from the Index object.

As work-around I am using an explicit html link given that the location is known..

**Comment by gertvdijk** [comment]
I'm running into the same wall here. Confirming that this is still an issue for 1.8.x

**Comment by tk0miya** [comment]
Unfortunately, there are no proper way to do that. We need to add new API for this purpose.

As a workaround, you can hack `StandardDomain` class manually.
https://github.com/ofosos/sphinxrecipes/blob/cffd1f93a2f6b411e24faeef7f23435d9cbc3984/sphinxrecipes/sphinxrecipes.py#L207-L215
(refs: https://opensource.com/article/18/11/building-custom-workflows-sphinx)

But I don't recommend this way because this accesses internal data structure of the domain directly. That's too fragile.

**Comment by bdice** [comment]
@tk0miya Thanks for the helpful answer - I was having a lot of trouble with figuring out how to create the index after reading this guide: https://www.sphinx-doc.org/en/master/development/tutorials/recipe.html

The repo you linked (https://github.com/ofosos/sphinxrecipes/) has a working example that is more up-to-date than that guide.

**Comment by tk0miya** [comment]
If you'd like to an official API to do that, please file an issue. I'll try to add it in future release.
