### ISSUE TITLE
Issues building against TexLive 2016 in Fedora Rawhide

### ISSUE THREAD

**Issue by avylove** [sphinx-doc/sphinx#3109]
I'm trying to update the RPM packages for Fedora, but TexLive was updated in Fedora Rawhide to 2016. I had a number of problems and was able to work through most of them, but I still have two tests failing. It could be a missing dependency or a problem with the new TexLive packages, but I don't know enough about Tex to figure it out.

The test output is attached. Any ideas what I should try?

[Rawhide_Errors.txt](https://github.com/sphinx-doc/sphinx/files/564214/Rawhide_Errors.txt)

**Comment by jfbu** [comment]
Most probably you are lacking the `luatex85` package. With the luatex of TL2016 the package is needed to have some `\pdf...` named control sequences, and is automatically loaded by the `sphinxmanual`  class, but only if it is found.

There is curious bit of  legacy code in `sphinx.sty` which results in `\py@NormalColor`  and `\py@TitleColor` remaining undefined if `\pdfoutput` itself is undefined. Try adding [luatex85](http://www.ctan.org/pkg/luatex85)  package to your TeX installation.

**Comment by jfbu** [comment]
@tk0miya maybe in sphinxmanual.cls : 

``` latex
\ifx\directlua\undefined\else
% if compiling with lualatex 0.85 or later load compatibility patch issued by
% the LaTeX team for older packages relying on \pdf<name> named primitives.
    \IfFileExists{luatex85.sty}{\RequirePackage{luatex85}}{}
\fi
```

we should test the `luatex` version in the false branch and if it is something like 0.85 or higher we should issue a message of the sort 

```
luatex85 package missing and luatex recent, expect the worst !
```

;-)

More seriously: I think the luatex85 thing must be done also from sphinx.sty itself, in case the document class is special, or better, add it to the tex template at very start of produced LaTeX file, rather than having it in the sphinx document class. (I was not familiar with Sphinx LaTeX innards when doing the commit with addition of luatex85 use)

**Comment by jfbu** [comment]
ref: 5c823a770ce9807abc769b074ed09329099f5277, 5833dfc60fe347ee6f6dda3fdb070ad06822149f

**Comment by avylove** [comment]
That was exactly the problem. Added tex(luatex85.sty) as a dependency, new package built fine, and I pushed it out to rawhide.

**Comment by jfbu** [comment]
@tk0miya now that `latex_engine` exists for 1.5 since #2513 I propose to move the check and loading of latex package `luatex85` to a new template variable which will be inserted into build tex document only if `latex_engine`  is `lualatex`. Also, if it doesn't find file `luatex85.sty` it should write some informative message to the latex log. Will do PR tomorrow.

**Comment by jfbu** [comment]
@avylove thanks for your report and feedback !

**Comment by tk0miya** [comment]
Okay, I will review ASAP :-)

**Comment by jfbu** [comment]
@avylove, thanks for report, now closing.

Many documents break with the lualatex of TL2016 if they don't load `luatex85`. Hence no TeX distribution of TL2016 should be without `luatex85`, this is vital dependency. Sphinx had anticipated this and tex documents it produces do require `luatex85` if compiled with lualatex. Now that 1.5 will have `latex_engine` config variable, the whole conditional for `luatex85` loading will only get executed if `latex_engine` was set to  `'lualatex'`.  
Furthermore, in case the package is not found, the latex build will stop immediately with a clearer message than just letting it go and end up in the problems due to `lualatex` engine having made breaking changes in TL2016.

From the Sphinx point of view I think there is a unique primitive `\pdfoutput` which is problematic, but anyhow, packages it loads like `geometry`  or `hyperref` may have their own issues and require `luatex85`.
