### ISSUE TITLE
Broken latex image scale in Sphinx 1.5.0

### ISSUE THREAD

**Issue by djhoese** [sphinx-doc/sphinx#3202]
I was trying to help a coworker build our documentation PDF and when testing a fresh build environment found that image scaling no longer works. I'm using conda with python 2.7 and installed sphinx via pip and I'm using my mac. In a subpage of my documentation I have:

    .. image:: my_image.jpg
        :scale: 50%
        :align: center
        :alt: my_image.jpg

When running `make latexpdf` I see messages like this in the output where the image filename is referenced and the images are not resized (they may be resized to textwidth):

    Overfull \vbox (166.22621pt too high) has occurred while \output is active

If I then run `pip install sphinx==1.4.5`, `make clean`, and `make latexpdf` I don't see the above message and the images are scaled properly. No other dependencies were changed between these two runs. The difference in latex seems to be:

    # version 1.4.5
    < \noindent{\hspace*{\fill}\scalebox{0.500000}{\sphinxincludegraphics{{my_image}.jpg}}\hspace*{\fill}}
    ---
    # version 1.5
    > \noindent{\hspace*{\fill}\sphinxincludegraphics[scale=0.5]{{my_image}.jpg}\hspace*{\fill}}

**Comment by jfbu** [comment]
Thanks for report. I can reproduce, but actually with both of 1.4.5 and 1.5.

**edit:** please jump directly to later comments because the thing discussed here is another issue.

<strike>
In my testing it is with 1.4.5 that one gets `\scalebox{0.500000}{...}` and with 1.5 that one gets `[scale=0.5]` syntax. But the problem is not related with this, it happens with pure pristine LaTeX `\includegraphics` with no options.

The following post seems relevant http://smallideasforabigworld.blogspot.fr/2013/08/latex-jpg-dimension-too-large.html, my test case also failed due to a jpg having a setting of 1 pixel per inch ! (I obtained the jpg from old 6.8.3 version of ImageMagick convert utility applied to a png inside Sphinx own doc, and Preview.app on the Mac tells me it has this 1dpi setting. If I use the png original image directly, rather than the jpg image, I experience no issue with Sphinx be it 1.4.5 or 1.5)

Can you open jpg in some image editor and check its dpi setting ? But maybe your issue is something else as you don't experience it on 1.4.5.
</strike>

**Comment by jfbu** [comment]
Hmm sorry. I did not read your post closely enough. Your issue is something else. You don't experience compilation error but overfull vbox warnings. Sorry for misunderstanding. Will check.

**Comment by jfbu** [comment]
Well, sorry again for wrong hint (I am not deleting my post as it may serve in future), but your problem is likely caused by the fact that Sphinx now scales first the image (here by a ratio 0.5) then if it is oversized it fits it to textwidth. Formerly in absence of height or width option, it first scaled oversized image to textwidth then in a second step applied the scaling (via `\scalebox` which you see in 1.4.5 output). Thus the image in your case ended up having half the width, hence half the height.

To fix your issue you can use directly `width` option.

Jump straight to next comment.

<strike>
If you are on letter paper, 11in times 8.5in, knowing that Sphinx by default applies left and right margins of 1in, you have textwidth of 6.5in, hence try

```
.. image:: my_image.jpg
    :width: 3.25in
    :align: center
    :alt: my_image.jpg
```

For a4paper which has 21cm paper width, Sphinx still applies 1in=2.54cm margins, hence textwidth is 15.92cm, thus try

```
.. image:: my_image.jpg
    :width: 7.96cm
    :align: center
    :alt: my_image.jpg
```
</strike>

**Comment by jfbu** [comment]
Well actually the much simpler thing to do if you want the image to occupy half the text-width is to use this:

```
.. image:: my_image.jpg
    :width: 50%
    :align: center
    :alt: my_image.jpg
```

This was already pointed out in issue report https://github.com/sphinx-doc/sphinx/issues/2865 which triggered change of behavior of Sphinx with scaling over-sized images.

**Comment by djhoese** [comment]
So specifying `width` with a percentage definitely works for the same purpose, but shouldn't the `scale` option still work? I mean, this is still a bug isn't it?

**Comment by jfbu** [comment]
The ``scale`` option does work. Simply, formerly, an oversized image was first rescaled to available width, then ``scale`` option was applied. With 1.5, ``scale`` option is applied first and then if the result is wider than available width it is rescaled to fit this width. This is deliberate change (http://www.sphinx-doc.org/en/stable/changes.html#release-1-5-released-dec-5-2016, in 1.5b1 section).

Consider also this situation:

```
hello

.. tabularcolumns:: CCC

.. csv-table:: Frozen Delights!
   :header: "Treat", "Quantity", "Description"

   |picture|, |picture|, |picture|

.. |picture| image:: my_image.png
    :scale: 20%
    :alt: alternative_text
```

Formerly if ``my_image.png`` was wider than table cell, it would end up occupy ``20%`` of the cell width there. 

Here is an example where I had used ``50%``: (``20%`` would be only more spectacular but I had already taken the screenshot)

![capture d ecran 2016-12-07 a 08 22 17](https://cloud.githubusercontent.com/assets/2589111/20958580/96b5c89a-bc56-11e6-84a0-152a5e4266e6.png)

Notice that this differs from ``html`` target:

![capture d ecran 2016-12-07 a 08 22 40](https://cloud.githubusercontent.com/assets/2589111/20958607/ae97d21e-bc56-11e6-89f1-29c1be70a57b.png)

Now, first the image is scaled to ``20%`` of its natural size, then if it would overflow the table cell width is it rescaled again to fit there.

![capture d ecran 2016-12-07 a 08 23 33](https://cloud.githubusercontent.com/assets/2589111/20958617/bbf6ccee-bc56-11e6-8bb3-c2dfe6e1ec38.png)

Thus it is a bug fix, not a a bug. By the way the html target seems to distort the image, rescaling it differently in x and y direction.

**Comment by jfbu** [comment]
ah ok, html looks was a feature of ``alabaster`` theme here is with classic theme:

![capture d ecran 2016-12-07 a 08 30 22](https://cloud.githubusercontent.com/assets/2589111/20958748/80e0e4ae-bc57-11e6-91ba-9cadd02f9fde.png)

**Comment by djhoese** [comment]
Ah ok. I totally understood the change with regards to first scaling it to cell/text width then applying the scaling specified. However in my test I had done 10% of my image which just happened to still be huge relative to the page size.
