### ISSUE TITLE
Ugly, break csv-table in latexpdf output

### ISSUE THREAD

**Issue by daiger14** [sphinx-doc/sphinx#3361]
Subject: <what happen when you do on which document project>

### Problem
Break, ugly csv-table In pdf file generated with latexpdf from sphinx. Latexpdf doesn't take size, style from rst file. Html version is good.

#### Procedure to reproduce the problem
```
- make html  - to see html is ok
- make latexpdf
```

#### Error logs / results
- https://drive.google.com/open?id=0B7X8TT3BuJ3MaVkzRnFVYUNTQlU

### Reproducible project / your project
- https://drive.google.com/open?id=0B7X8TT3BuJ3MN1dDRW1vTk15dVE

### Environment info
- Python version: 2.7
- Sphinx version: 1.4.8
- texlive full

**Comment by tk0miya** [comment]
At this moment, sphinx fails to separate tables even if it is larger than the page height.
So please give `:class: longtable` option to `csv-table` directive as a hint.
It will allow you to separate the table.

**Comment by tk0miya** [comment]
Note: refs #2620.

**Comment by daiger14** [comment]
Hello! Thank you` :class: longtable` works. But how i can customize table? Cell size? Text orientation? Why sphinx/latex doesn't take html style?

**Comment by tk0miya** [comment]
About cell size (cell width), you can use `:widths:` option to specify the widths manually.
But no way to modify text orientation.

AFAIK, there are no way for HTML builder too.
What did you mean "html style"? If you mean CSS, you can use TeX macros to do that (I'm not good at it...)

**Comment by daiger14** [comment]
I used `:widths:` in table but in latex output like you see doesn't have effect. You can check my example of project.

**Comment by tk0miya** [comment]
Ah, sorry. It's my mistake.
Please use `tabularcolumns` directive instead.
```
.. tabularcolumns:: |p{1.5cm}|p{2.0cm}|p{5.0cm}|
```
http://www.sphinx-doc.org/en/1.5.1/markup/misc.html

**Comment by daiger14** [comment]
Thank you for your help Takeshi!

**Comment by jfbu** [comment]
Sphinx 1.6 will obey ``:widths:`` option to table directives, for LaTeX output (ref #3379, #3381), thus sparing use of ``tabularcolumns`` in simple cases. With current code such tables will always occupy full line width, though, but perhaps some way will be found so that it becomes useful option also for tables which are naturally narrower than linewidth. But currently tables (when they are equipped with  a caption and have less than 30 rows hence do not use automatically longtable) are not even centered in the page.
