### ISSUE TITLE
Unnecessary '{}' for '\item' in latex output

### ISSUE THREAD

**Issue by jbking** [sphinx-doc/sphinx#3437]
### Problem
- The latex builder output of list has unnecessary `{}` just after `\item`. The `\item` doesn't allow `{}` as their attribute.

#### Procedure to reproduce the problem

Source

```
- apple
- beer
- circus

1. 1st
2. 2nd
3. 3rd
```

#### Error logs / results

```
...(brabrabra)...

\begin{itemize}
\item {}
apple

\item {}
beer

\item {}
circus

\end{itemize}
\begin{enumerate}
\item {}
1st

\item {}
2nd

\item {}
3rd

\end{enumerate}

...(brabrabra)...
```

#### Expected results

```
\begin{itemize}
\item apple
\item beer
\item circus
\end{itemize}
\begin{enumerate}
\item 1st
\item 2nd
\item 3rd
\end{enumerate}
```

### Environment info
- OS: Mac
- Python version: 3.5.1
- Sphinx version: f21cfa7117423c78b8345ac1ece49b913f18b1d7

**Comment by jfbu** [comment]
Thanks for reporting. It probably has to do with protecting a ``[`` from regular text from being mis-interpreted as ``\item`` 's optional argument. The ``{}`` does not create a change in output (the end of line space is swallowed because it will be a space at start of a line). Does this cause a problem in your Sphinx builds ?

**Comment by jbking** [comment]
(Indeed, this is a minor case and just compiled rubbish can be ignored by latex itself technically)

In my sphinx builds, No. But in our related project, Yes.
It cause a problem with application using the latex build output as source. Our case is Omega-T. This latex importer parsing source well.
So translate source becomes `{} apple` (editable `{}` as apart of that).
My opinion is **use gettext** instead for this special case.

However such latex output can make collaboration applications confused.

**Comment by jfbu** [comment]
Sometimes ``{}`` can be used for quite legitimate LaTeX purposes and we can not a priori restrict Sphinx LaTeX syntax because of external application. In this special case the code path is there from very beginnings 3d74ade, with this comment:

```
    def visit_list_item(self, node):
        # Append "{}" in case the next character is "[", which would break
        # LaTeX's list environment (no numbering and the "[" is not printed).
        self.body.append(r'\item {} ')
```

but next commit https://github.com/sphinx-doc/sphinx/commit/c5580ebd9115dc8dd1e76a8ac25cea95bc3db2ce#diff-c524933be923016c87a9da437a0e7537R576 added general escaping mechanism  to replace  ``[ ``'s by ``{[}``'s.

Thus possibly the ``{} `` here is superfluous, but complete confirmation needs more time before modifing ten years old codeline. It could be replaced by ``\relax ``.

**Comment by jfbu** [comment]
as a possible workaround for your project you might do this monkey-patching
in ``conf.py``:

```
import sphinx.writers.latex

class LaTeXTranslator(sphinx.writers.latex.LaTeXTranslator):

    def visit_list_item(self, node):
        self.body.append(r'\item ')

sphinx.writers.latex.LaTeXTranslator = LaTeXTranslator

```

but it may break extensions or other things and might be frowned upon by the
Python authorities (I am the LaTeX consultant here ;-) )

**Comment by tk0miya** [comment]
Our primary target is latex compilers. It would be much better if we can also support third party tools. But, if it is hard to support them, it is not necessary.
Is there any worries or side effects to use `\relax`? If none, I agree to move it (of course, Omega-T also supports it).

**Comment by jfbu** [comment]
Replacing `{}` by `\relax` has no side effect. One only has to be careful to leave space after `\relax<space>` in case by anychange some letter comes immediately (but I think most of the time the list item will have an initial `\n`  from Docutils node processing). It if makes Omega-T happy, I have no objection. On the other hand there are circumstances where a `\relax` would make things more complicated: when I was working on table merged cells I had at some point a macro with two arguments one of them either ``{}`` or ``{\vline}``. Using ``\relax`` would have really complicated things because then some other code branch would have needed to be careful not to insert it into the TeX token stream.

**Comment by tk0miya** [comment]
Hmm... surely complex tables might cause some problems.
I'd like to avoid to be complicated the implementation (especially around tables) if possible.

@jbking can you use the workaround which @jfbu describes?

**Comment by jbking** [comment]
The patch seems to be enough for us.
And I didn't know this has very old history...

I will ask my team and trying to apply it. Thanks. (and sorry for late)

**Comment by jfbu** [comment]
@jbking I am glad the patch works for you.

In https://github.com/sphinx-doc/sphinx/issues/3437#issuecomment-283068521 I was unclear and induced @tk0miya into thinking I was still making reference to this specific issue while I was in fact making a general comment that it is not always convenient to avoid ``{}`` in LaTeX output by replacing it by ``\relax``. For your issue, we could do the replacement.  You can simulate that by modifying [patch](https://github.com/sphinx-doc/sphinx/issues/3437#issuecomment-283001106) above into

    def visit_list_item(self, node):
        self.body.append(r'\item\relax ')

The issue is kept open because it may well be that we can drop ``{}`` entirely as you initially suggested and not even use a ``\relax ``, but as I said this is modifying 10 years old codebase, hence doing this requires cautiousness. A priori, Sphinx arranges for ``[`` in reST source to end-up as ``{[}``  in LaTeX, but it has be to be made certain there are no other scenario. And for example one can imagine theoretically some extension inserted naked ``[`` and if core Sphinx drops the ``{}`` then the extension starts breaking lists without having changed itself !

**Comment by jfbu** [comment]
I am sorry that my comments here were a bit verbose. To sum up I think it is perfectly fine to replace the `{}` by a `\relax` (with space after it). @jbking are you still interested into this?

**Comment by tk0miya** [comment]
On my understanding, the braces are important to avoid error caused by brackets.
IMO, to replace by `\relax` is not meaningful for everybody. So either is okay to me.
In addition, adding empty braces is standard technique of LaTeX to me. So I don't think the replace is needed.

Of course, I'm also okay if you choose `\item\relax`.

Anyway, this is bikeshed issue. So it's time to close.

**Comment by jbking** [comment]
Sorry for late response. I didn't interest this anymore.
