### ISSUE TITLE
Regression: wrong quotes in latex output for productionlist directive

### ISSUE THREAD

**Issue by bfrk** [sphinx-doc/sphinx#3507]
To give an example, the keyword "entry" in

```
.. productionlist::
   entry: "entry" `block`
```

gets rendered as

```
``entry''
```

in the latex output. I am seeing this with version 1.5.2, whereas the output generated by version 1.3 is fine.

**Comment by jfbu** [comment]
Thanks for this !

First bad commit is 82758b1 (PR #2627, Sphinx 1.4.4). This commit already got a number of follow-ups... I will look, thanks. In a way it may be (sort of) intended because rendering of curly double quotes is font dependent (mono space font here for inline literal).

(what is going on is that the commit prevents the formation of the ```` `` ```` and ``''`` ligatures in the TeX font).

**Comment by jfbu** [comment]
Classifying this as a bug, because the intent of PR #2627 (and needed subsequent commits) was to obtain in inline literals same as in literal blocks regarding quotes. This does not happen for double quotes which are Pygmentized in literal blocks, hence immune to the standard LaTeX verbatim set-up applied there and which PR #2627 transferred to inline literals. But in inline literals double quotes have already been converted by Sphinx into ```` ``''```` pairs and then the 82758b1 and descendants prevents TeX ligatures.

memo: actually in a literal-block ``"entry"`` is not rendered with directional double quotes like TeX produces on ligatures ```` `` ```` and ``''``.

**Comment by bfrk** [comment]
Thanks for looking into this. (Note this is not critical for me, I guess most of my users look only at the html).

**Comment by jfbu** [comment]
fixed at 94e9d3e (#3527) for upcoming 1.5.4. Thanks for reporting.
