### ISSUE TITLE
Consider switching py:function and py:method to supporting different function types using options instead of directives?

### ISSUE THREAD

**Issue by njsmith** [sphinx-doc/sphinx#3743]
One source of frustration I've run into when using Sphinx to document Python projects is this: out-of-the-box, Sphinx's `py` domain has directives for `function`, `method`, `staticmethod`, `classmethod`, `decorator`, and `decoratormethod`. But this leaves a bunch of common Python types that it doesn't support: async functions/methods, abstract functions/methods, context managers, async context managers, generators, async generators, and combinations of the above.

This is particularly annoying for new projects using async/await, since this is a critical part of function signatures in the language now, and Sphinx has no standard way to handle it. But what makes it extra tricky is that the async/not-async distinction is orthogonal to other distinctions like regular method/staticmethod/classmethod. Recently I found myself trying to document an abstract async classmethod, which drove home the limitations of the current system :-).

My solution was to write [sphinxcontrib-trio](https://sphinxcontrib-trio.readthedocs.io), which is an extension that – instead of trying to add a dozen+ new directives for every possible method type – replaces the standard `py:function` and `py:method` with new versions that take *options* describing the different attributes of the function/method. So that abstract async classmethod is just:
```rst
.. method::
   :abstractmethod:
   :async:
   :classmethod:
```

Doing this via an extension is convenient because it makes the functionality available immediately. But as far as I can tell, this approach is a 100% backwards compatible extension that makes the `py` domain much more usable for modern Python projects. So I'm wondering: is there any interest in building this functionality into Sphinx itself?

**Comment by Rapptz** [comment]
There is e.g. [`sphinxcontrib-asyncio`](http://pythonhosted.org/sphinxcontrib-asyncio/) which does something similar. One problem I've encountered when using it is that it doesn't work very well with Sphinx's autodoc module but I suspect with proper support in the module it'd be a non-issue.

**Comment by njsmith** [comment]
Re: sphinxcontrib-asyncio: [I'm aware](https://sphinxcontrib-trio.readthedocs.io/en/latest/#acknowledgements) :-). (And I don't know what problems you had with sphinxcontrib-asyncio, but as far as I know sphinxcontrib-trio integrates nicely with autodoc; if you run into any problems then I'd certainly like to know.)

**Comment by tk0miya** [comment]
That sounds good. Indeed, the decorations of functions, methods and so on is orthogonal. I feel your approach is better than current way.
I don't know what way is best solution, but +1 for improving. We need many helps for improving and maintaining.

**Comment by tk0miya** [comment]
We've got #6138 for abstract options. It uses `:abstract:` option for abstract methods instead of `:abstractmethod:`.
@njsmith Do you have any opinion?

**Comment by lukasjuhrich** [comment]
First of all, I wasn't aware of this issue or `sphinxcontrib-trio`.

To give my rationale for implementing it with `:abstract:` instead of `:abstractmethod:`, consider [this
minimal example](https://github.com/sphinx-doc/sphinx/pull/6138/files#diff-f34713b6edbea2ba3ac26b57f4a4c852R140) taken from the autodoc tests I've added:

```python
class AbstractBase(metaclass=ABCMeta):
    @property
    @abstractmethod
    def value(self):
        """Some value"""
        pass

    @staticmethod
    @abstractmethod
    def statmeth():
        """Some static method"""
        pass

    # etc...
```
In that case, autodoc is supposed to generate the following ReST content:
```ReST
.. py:class:: AbstractBase
   :module: target

   
   .. py:attribute:: AbstractBase.value
      :module: target
      :abstract:
   
      Some value
      
   
   .. py:staticmethod:: AbstractBase.statmeth()
      :module: target
      :abstract:
   
      Some static method
   .. etc...
```
In the python source, one can see that `AbstractBase.value` is implemented as a method, hence the `@abstractmethod` decorator. However, on the *documentation level* the property is represented as an `attribute::`, so naming the ReST directive option `:abstractmethod:` feels quite misleading to me. It suggests that it can be applied to methods only, when IMO the correct abstraction (pun not intended) is that abstractness is a property of *class members*, which of course subsumes methods. A newcomer to sphinx may be spending some time to look for an `:abstractattribute:` option only to find that `:abstractmethod:` does the job he/she wanted.

This being the reasons I would be perfectly fine with adding an `:abstractmethod:` option which acts as an alias to `:abstract:` if it is desired – this would have the obvious benefit that the wording coincides with the used decorator, so we make a common guess work out-of-the-box without need to consult documentation. The cons are redundancy.

Also, I just realized that @njsmith seems to be aware of this, judging by the [bugs and limitations section](https://sphinxcontrib-trio.readthedocs.io/en/latest/#bugs-and-limitations) for `sphinxcontrib-trio`.

@tk0miya what is your stance on this?

**Comment by tk0miya** [comment]
I've never used these abstraction and abc module so far. So I don't have strong opinion for this. My main concern is which is easy to understand to both readers and writers of document. Personally, it would be better to use same keyword in python and Sphinx if no conflicts.

BTW, if your worry is only property, we can add PropertyDocumenter for this feature. Does it resolve the worry?

**Comment by njsmith** [comment]
It's true that when writing sphinxcontrib-trio, I didn't think too hard about abstract properties, because I've never used them or seen them used :-). And I was adding a bunch of attributes like `:staticmethod:`, `:classmethod:`, etc., so `:abstractmethod:` fit in with those. I don't have a strong opinion about which is objectively better.

One thing we might want to think about: I guess adding #6138 will probably break sphinxcontrib-trio. Which is fine, that's how it works for sphinx extensions and we can cope. But maybe we should also consider possible paths for merging sphinxcontrib-trio into sphinx proper (i.e. what this bug is about)? Merging it into sphinx would be a more general solution to these issues. OTOH, it would also make it more interesting to keep supporting `:abstractmethod:`, to make it easier for existing projects to migrate :-). @lukasjuhrich do you have any interest in working on this, or do you just want to get `:abstract:` in and be done with it?

**Comment by lukasjuhrich** [comment]
@njsmith I have no problem with adding `:abstractmethod:` as well, I think imposing an adaption effort for other people is not justified in this case. I'll change #6138 shortly.

> I guess adding #6138 will probably break sphinxcontrib-trio. 

Are there other things besides `:abstractmethod:` that my PR does different? I am not aware of the feature set of `sphinxcontrib-trio`.

Considering a possible merge: #6138 was kinda fun, so I'd love to help out :-). However, I can't make any promises (semester is about to start), so having incremental steps which can be finished independently would be important.

**Comment by lukasjuhrich** [comment]
@njsmith I modified #6138 such that classmethod-ness and static-ness are “detected” via the `:static:` and `:classmethod:` flags, and ensured backwards-compatability to the `staticmethod::` and `classmethod::` directives by making them aliases which automagically set the right flags and act as tough they would be `method::`s.

This should lay the groundwork for the additions you implemented in `sphinxcontrib-trio`, since nothing concerning the “flavor” of a method is deduced by the directive type anymore. Concerning `function::`, afaik there are no other directive types to worry about.

Am I correct that the only observable change options like `:async:` should cause is the prefix in the signature?

I just hope this is not too much of a hack in the eyes of @tk0miya.

**Comment by tk0miya** [comment]
I feel very strange for `:static:` option. As I commented above, I'd like to use same keyword as python's. I suspect document authors would know syntax of python. So that is familiar for them. I worry about using another keyword confuses them.
So -1 for using `:abstract:` and `:static:`.

**Comment by tk0miya** [comment]
Since 2.1.0, we've switched declaration style to options based one. So I think this was already done.
I'm closing this now.
Thank you for your comments :-)
