### ISSUE TITLE
Doc in decorated function not generated

### ISSUE THREAD

**Issue by yvn11** [sphinx-doc/sphinx#3783]
### Problem
- Function below, doc isn't generated in with parameters HTML, only function signature is generated.

#### Procedure to reproduce the problem
```
@some_decorator
def some_func(param1, param2):
     """An awesome function
     :param param1: a param
     :param param2: another param
     """
     do_something
```

#### Error logs / results
```
some_func(param1, param2)
```

#### Expected results
```
some_func(param1, param2)
  An awesome function
  Parameters: param1 a param
              param2 another param
```
### Environment info
- OS: Mac
- Python version: 2.7.13
- Sphinx version: 1.6.1

**Comment by bskinn** [comment]
It's a known side-effect that decorators 'mask' the docstrings of the wrapped functions. This interferes with Sphinx's ability to discover documentation there.

The first workaround to try is to use the [`functools.wraps` decorator](https://docs.python.org/3/library/functools.html#functools.wraps), one action of which is to 'replicate' the docstring of the decorated function into the final, wrapped object.  I've used this approach in one of my projects; e.g., the function [`opan.utils.vector.ortho_basis`](https://github.com/bskinn/opan/blob/0b1b21662df6abc971407a9386db21a8796fbfe5/opan/utils/vector.py#L49-L99) is wrapped by my custom decorator [`opan.utils.decorate.arraysqueeze`](https://github.com/bskinn/opan/blob/0b1b21662df6abc971407a9386db21a8796fbfe5/opan/utils/decorate.py#L36-L88).  I used `functools.wraps` on line 87 for exactly this purpose of docstring replication. As you can see, the docstring is parsed properly by Sphinx in the [generated documentation](http://opan.readthedocs.io/en/latest/api/utils/vector.html#opan.utils.vector.ortho_basis).

One thing that `wraps` can't (or couldn't previously) do, though, is report the correct function signature to, e.g., `.. autofunction::`.  I had to [enter the function signature manually](https://github.com/bskinn/opan/blob/0b1b21662df6abc971407a9386db21a8796fbfe5/opan/utils/vector.py#L30) when I composed the module-level docstring.

**Comment by yvn11** [comment]
I see,Thanks @bskinn, it works.

**Comment by tk0miya** [comment]
autodoc module simply refers the docstrings of the targets. in this case, `functools.wraps` helps you.
I think this is not a bug. Can I close this?

**Comment by yvn11** [comment]
Yes @tk0miya, please close it.

**Comment by duetosymmetry** [comment]
I know this issue has been closed, but I think it would be very useful for sphinx to be able to inspect numba-decorated functions. Would it be acceptable to add code (an extension?) which does something like: if an object `obj` has type `numba.targets.registry.CPUDispatcher`, then recognize it as a function (autodoc currently does not); and then instead document `obj.py_func`, which is the original undecorated python function?

**Comment by duetosymmetry** [comment]
PS Part of this can be implemented using the `autodoc-process-signature` trigger. Here is an example for what to add to `conf.py` so that numba-decorated functions have their correct signatures emitted: https://github.com/duetosymmetry/qnm/blob/d286cad616a4abe5ff3b4e05adbfb4b0e305583e/docs/conf.py#L71-L93 (please note that I should have named the function `process_numba_signature` instead of `process_numba_docstring`)

**Comment by tk0miya** [comment]
@duetosymmetry I think Sphinx should not be add special code for 3rd party libraries. So it should be better to handle in an extension. And it seems you've already handled it on `autodoc-process-signature`. Is there something needed else?
If so, please file a new issue. This is different topic from this issue.

**Comment by duetosymmetry** [comment]
@tk0miya I think the only thing missing is that autosummary does not recognize decorated functions as functions, since it sees them as objects. This makes autodoc less automatic—my workaround is I have to include a list of decorated functions in `docs/_autosummary/modulename.rst`. I could not find a trigger that allows me to assign `what='function'` for the relevant decorated functions. Perhaps this is the actual issue (and needs to be opened separately, if it is useful for others).

**Comment by schipiga** [comment]
When 4 years we had met this problem we fixed with monkey-patching:
in `conf.py`:

```python
def setup(app):
    """Customize function args retrieving to get args under decorator."""
    from functools import partial
    from sphinx.ext import autodoc
    from stepler.third_party.utils import get_unwrapped_func

    orig_getargspec = autodoc.getargspec

    def patched_getargspec(func):
        if type(func) is not partial:
            func = get_unwrapped_func(func)
        return orig_getargspec(func)

    autodoc.getargspec = patched_getargspec
```

where `get_unwrapped_func`:

```python
def get_unwrapped_func(func):
    """Get original function under decorator.
    Decorator hides original function inside itself. But in some cases it's
    important to get access to original function, for ex: for documentation.
    Args:
        func (function): function that can be potentially a decorator which
            hides original function
    Returns:
        function: unwrapped function or the same function
    """
    if not inspect.isfunction(func) and not inspect.ismethod(func):
        return func

    if func.__name__ != six.get_function_code(func).co_name:
        for cell in six.get_function_closure(func):
            obj = cell.cell_contents
            if inspect.isfunction(obj):
                if func.__name__ == six.get_function_code(obj).co_name:
                    return obj
                else:
                    return get_unwrapped_func(obj)
    return func
```

Code is 4 years old, can't say is it working now. Original example is in https://github.com/Mirantis/stepler/blob/master/doc/source/conf.py#L450

```

**Comment by jluttine** [comment]
I encountered this issue as well so I thought I'd share my workaround in case someone comes here via a search engine like me looking for a solution.

In my case, I can't use `functools.wraps`, because the result of the decoration needs to be an object of a particular class. It's callable and it's kind of like a function but it really isn't. But in the documentation I want it to be treated similarly to a normal function.

So, let's say my decorator class is `Decorator`. My solution was to monkeypatch `inspect.isfunction`:

```python
def setup(app):
    import inspect
    isfunction = inspect.isfunction
    inspect.isfunction = lambda f: isfunction(f) or isinstance(f, Decorator)
    return {}
```

In order for this to work, `Decorator` needs to set a few attributes that are expected from functions. So, here's a minimal definition of the decorator and how to use it:

```python
class Decorator():

    def __init__(self, f):
        self.f = f
        self.__code__ = f.__code__
        self.__name__ = f.__name__
        self.__doc__ = f.__doc__
        self.__annotations__ = f.__annotations__
        self.__defaults__ = f.__defaults__
        self.__kwdefaults__ = f.__kwdefaults__

    def __call__(self, *args, **kwargs):
        return self.f(*args, **kwargs)


@Decorator
def foo(a, b=42):
    """Foo a and b

    Lorem ipsum

    """
    return a + b
```

If I now use it in `autosummary`, it gets treated as a normal function and the subpage is created correctly:

```rest
.. autosummary::
   :toctree:

   foo
```
