### ISSUE TITLE
How does autodoc_mock_imports handle REAL modules?

### ISSUE THREAD

**Issue by weaverba137** [sphinx-doc/sphinx#3920]
Subject: How does autodoc_mock_imports handle REAL modules?

### Problem
- When `autodoc_mock_imports` is set in a Sphinx configuration file, does Sphinx *always* mock the modules listed, or does it prefer real modules if it can find them in the build environment?

**Comment by tk0miya** [comment]
autodoc mocks up if the target modules is not imported. So you can use REAL modules by importing them manually before mocking.

**Comment by weaverba137** [comment]
OK, so based on that, one could add code like this to the Sphinx `conf.py` file:

```python
autodoc_mock_imports = []
try:
    import astropy
except ImportError:
    autodoc_mock_imports.append('astropy')
# and so on...
```

But just to be absolutely clear, 

1. I have astropy in my build environment.
2. I just have `autodock_mock_imports = ['astropy']` in my `conf.py` file; I haven't manually tried to import astropy like in the example above.
3. Sphinx parses a module that does `import astropy`.
4. Sphinx uses the mock module instead of the real module, because I haven't manually imported astropy *before* Sphinx imports my own module.

**Comment by tk0miya** [comment]
What did you mean? Are you saying sphinx imports astropy automatically?
I can't answer to your question because I don't know your document.

**Comment by weaverba137** [comment]
Here is an example scenario.

1. I am working in an environment that has astropy installed.
2. My `conf.py` file contains `autodoc_mock_imports = ['astropy']`.
3. I have a Python module file, let's call it `mypackage/util.py`.  It contains:
   ```python
   """
   mypackage.util
   ==============
   
   Miscellaneous utilities.
   """
   import astropy
   ```
4. I have a top-level Sphinx document, let's call it `api.rst` that contains `.. automodule:: mypackage.util`.
5. Now I build the Sphinx documentation (via `sphinx-build` or `python setup.py build_sphinx`).

Given the above scenario, when Sphinx imports `mypackage.util` and hits the `import astropy` statement, which astropy is imported, the actual module or the mock module?

**Comment by djhoese** [comment]
I'm experience an issue related to this, but I'm seeing the opposite behavior from what @weaverba137 is seeing. In my case I have some submodules that use `h5py` and some modules that import `h5netcdf` which uses some of the h5py shared libraries in cython modules (I think) of `h5py`. I get a segmentation fault when sphinx starts importing these modules even when I list both `h5py` and `h5netcdf` in `autodoc_mock_imports`. I have both packages in my environment and I think what is happening is that sphinx is mocking all of the submodules of `h5py` including the shared libraries, then when `h5netcdf` is processed is seg faults because it is getting a mocked module when it should be getting a shared library.

I'm using sphinx 1.6.5 from conda-forge on OSX. If I make the mock importer the first importer by changing the equivalent of this line `https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/importer.py#L92` in my local environment then I don't get a seg fault. To me this is happening because all the modules are mocked without analyzing the actual installed modules structure.

Edit: Just did `pip install git+https://github.com/sphinx-doc/sphinx.git` and I still get this segmentation fault.

**Comment by weaverba137** [comment]
I've had a chance to run a few tests on this.  This is with Sphinx 1.6.3.  Here's a dummy Python module in a package:

```python
"""
==============
testsphinx.foo
==============

Contains dummy functions.
"""
import yaml
import foobar

if yaml.__version__ == '3.12':
    print("yaml == 3.12")

if foobar.__version__ == '1.2.3':
    print("foobar == 1.2.3")

def bar():
    """A dummy function.
    """
    return 0
```
The module gets imported by Sphinx via:
```rst
.. automodule:: testsphinx.foo
   :members:
```
and the conf.py file contains:
```python
autodoc_mock_imports = ['yaml', 'foobar']
```
When I build the documentation, Sphinx uses the real yaml module installed in my environment (*i.e.* `yaml == 3.12` is actually printed), and the `foobar` module is mocked up (*i.e.* importing `testsphinx.foo` does not throw `ImportError`).  The documentation builds successfully with no warnings.

**However**, if I replace every instance of `yaml` with `astropy` (which is also installed in the same environment), and try to to build the documentation, I get a warning of an exception thrown by astropy.

I *think* this is because astropy does a lot of self-introspection (to find configuration files and helper packages, etc.) when it is imported, and somehow the `autodoc_mock_imports` mechanism is interfering with that.  When I ran `build-sphinx` in debug mode, I found this line:
```
[autodoc] adding a mock module astropy.extern.six.moves!
```

So I think the answer is that Sphinx prefers to use real modules when it can, but some packages may be really complex and screw around with their own import system, and therefore not play well with `autodoc_mock_imports`.
