### ISSUE TITLE
Typo in sphinx.sty

### ISSUE THREAD

**Issue by tititiou36** [sphinx-doc/sphinx#3946]
Subject: Typo in sphinx.sty

### Problem
There seems to be a typo in sphinx.sty, around line 1137.
sphinimportantBgColor should be sphinximportantBgColor (missing x at the end of sphinx) to be consistent with the other sphinx[...]BgColor

### Environment info
- Sphinx version: 1.6.3

**Comment by tititiou36** [comment]
I'm also wondering if the 4 lines:
   \definecolor{sphinx<smthg>BgColor}{rgb}{1,1,1}
around line 1137 have any use? 
The ones which seem to have an effect are around line 320 and look like:
    \sphinxDeclareSphinxColorOption{<smthg>BgColor}{{rgb}{1,1,1}}

**Comment by jfbu** [comment]
Good catch, thanks. The typo is fixed at https://github.com/sphinx-doc/sphinx/commit/621eca38bec307a0b33e3c5c837906a11eabf4f0 (I will update CHANGES)

In fact, as indicated in comments around line https://github.com/sphinx-doc/sphinx/blob/stable/sphinx/texinputs/sphinx.sty#L1133 these colour definitions have no direct usage, because they are supposed to serve background colours for "light" admonitions (note, hint, important, tip), but the LaTeX macros for these admonitions have no support for this. They are supposedly needed however for the ``\sphinxcolorlet`` at https://github.com/sphinx-doc/sphinx/blob/stable/sphinx/texinputs/sphinx.sty#L1211, which is common code for the "light" and "heavy" admonitions.

No crash was caused by the typo because the typo caused some LaTeX colour macro to be made an alias to `\relax`, but the default code for ``important`` type notices had no mention of the background colour, and the `\relax` was never actually encountered in code dealing with colours. It would have caused crash in user customization attempting to use the colour for whatever purposes though.

The code comments at https://github.com/sphinx-doc/sphinx/blob/stable/sphinx/texinputs/sphinx.sty#L1133 explain why you don't see corresponding option handling code around line 320 as you observed.
