### ISSUE TITLE
The 'conf.py' generated by 'sphinx-quickstart' has too much noise

### ISSUE THREAD

**Issue by stephenfin** [sphinx-doc/sphinx#4256]
The default `conf.py` file generated by Sphinx is far too complicated for its own good, containing a lot of stuff that really isn't necessary. We should come up with a plan to simplify this.

This was noted in the discussion for #4174

**Comment by stephenfin** [comment]
This is the opposite side of #4148.

**Comment by tk0miya** [comment]
I don't think so. I believe we can adopt both together.
I think there are only a few commonly used (changed) settings. So we can reduce it.

IMO, giving better default setting also goes to simplify conf.py.
For example, the default value of `master_doc` is `contents`, but many people might use `index` for it. because quickstart generated it as by default. I think this is very stupid behavior.

**Comment by timhoffm** [comment]
There are two different philosophies for a config file:

1. **Short:** Make it really short and include only the most common options. The advantage is that the user can easily see the active options. On the downside, it's more difficult to add options because you have to look them up in the manual. This heavily relies on the html documentation as an additional resource. I've attached a possible config file in a really stripped down version below.

2. **Complete:** Add a full list of options including descriptions. The config file can stand for itself, you can probably do most stuff without going to the manual. Jupyter notebook does it this way. They have a special formatting to distinguish between commented out (i.e. inactive) options and their preceeding desription. See below.

The current version has the differences of both worlds. It's quite verbose but you still need the docs because its not complete. That said, IMO both directions are viable ways for improvement and I have no clear preference. 

### Appendix

#### Excerpt from jupyter_notebook_config.py
~~~
#------------------------------------------------------------------------------
# NotebookApp(JupyterApp) configuration
#------------------------------------------------------------------------------

## Set the Access-Control-Allow-Credentials: true header
#c.NotebookApp.allow_credentials = False

## Set the Access-Control-Allow-Origin header
#  
#  Use '*' to allow any origin to access your server.
#  
#  Takes precedence over allow_origin_pat.
#c.NotebookApp.allow_origin = ''
~~~

#### Possible config file in a really stripped down version

~~~
# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup -----------------------------------------------------------

# -- Project information --------------------------------------------------

project = 'Flaboo'
copyright = '2018, Tim Hoffmann'
author = 'Tim Hoffmann'
version = ''
release = '1.0'

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
]

# -- Options for HTML output ----------------------------------------------

html_theme = 'alabaster'
html_theme_options = {}

# -- Options for HTMLHelp output ------------------------------------------

# -- Options for LaTeX output ---------------------------------------------

# -- Options for manual page output ---------------------------------------

# -- Options for Texinfo output -------------------------------------------

# -- Extension configuration ----------------------------------------------

# -- Options for intersphinx extension ------------------------------------

intersphinx_mapping = {
    'https://docs.python.org/': None
}

# -- Options for todo extension -------------------------------------------

todo_include_todos = True
~~~

**Comment by tk0miya** [comment]
Sphinx has a lot of options. So I think shorter one is better for our docs instead completeness.
http://www.sphinx-doc.org/en/latest/config.html

**Comment by timhoffm** [comment]
Just FYI, jupyter notebook has a similar amount of options and they have decided for the complete approach. Their config is 600+ lines.

Given that options may change over time, I now slightly tend towards the short approach. A previously generated complete file might not be complete (or even correct) for later versions of Sphinx.

**Comment by tk0miya** [comment]
At present, `conf.py` becomes much slim. So I'm closing this now.
Please post another issue if you have idea yet.

Thanks,
