### ISSUE TITLE
Tests fail due to mock import with Python 3

### ISSUE THREAD

**Issue by funkyfuture** [sphinx-doc/sphinx#4284]
i'm a little irritated that i have to add the `mock` module to the test requirements for tests on a Python 3 interpreter (e.g. `tox -e py36`). i mean it makes sense that it fixes the `ImportError`s from `import mock` in the test modules as the stdlib's located at `unittest.mock`. what irritates me that no one else seems to have experienced that yet.

@stephenfin do you have any idea?

**Comment by stephenfin** [comment]
Ah, good spot. This happens because the native mock in Python 3 is actually `unittest.mock` and not `mock`. We need to either remove the Python 2-only modifier on the requirement or switch between importing `mock` or `unittest.mock` depending on the version of Python we're running against. I'd probably opt for the latter because it's one less dependency and we'll surely drop Python 2.7 support at some point in the next year or two, but either approach is fine.

I can do this tomorrow, but if you want to submit a patch to do it then I'd be happy to review :smile:

**Comment by funkyfuture** [comment]
i wouldn't mind that one dependency for tests. actually, using `mock` from the cheeseshop would ensure that all tests use the identical version of it.

**Comment by funkyfuture** [comment]
> we'll surely drop Python 2.7

interesting, but shouldn't `docutils` be reimplemented then? ;-)

**Comment by stephenfin** [comment]
`docutils` 0.6 is Python 3 compatible, no?


we'll surely drop Python 2.7
interesting, but shouldn't docutils be reimplemented then? ;-)

**Comment by tk0miya** [comment]
At once, I'd discussed with @shimizukawa about dropping py2 support. And we agreed with we can do it in Sphinx-2.0. But we don't know when it comes...
So I prefer to switch the mock module by running python version at present.

**Comment by tk0miya** [comment]
Fixed by #4297.
