### ISSUE TITLE
Automatically add html class in output to elements inside an `only` directive 

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#4374]
### Problem
With the following content:
```

My title
========

Some normal text

.. only:: internal

   Some internal text

Some normal text
```

#### Expected results

The HTML output is:

```
<div class="section" id="my-title">
  <h1>My title<a class="headerlink" href="#my-title" title="Permalink to this headline">¶</a></h1>
  <p>Some normal text</p>
  <p>Some internal text</p>
  <p>Some normal text</p>
</div>
```

If the output contained some indication that the text had a tag, that would be great:

```
<div class="section" id="my-title">
  <h1>My title<a class="headerlink" href="#my-title" title="Permalink to this headline">¶</a></h1>
  <p>Some normal text</p>
  <p only="internal">Some internal text</p>
  <p>Some normal text</p>
</div>
```

Simply adding it to all the elements contained in the directive would be a nice step forward for conditional outputting and formatting.

### Environment info
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment]
-1; I think this is not a common feature. Please implement your idea as an extension. Sphinx provides extension point and APIs.

**Comment by ArtFlag** [comment]
Hi again,
Since I really need this, it is the opportunity for me to learn how to write extension, but since the docs are pretty slim about this topic for people with no experience with docutils, may I ask for some pointers?

What would be the starting point to modify the behaviour of an **existing** directive?

Thanks

**Comment by tk0miya** [comment]
I think `Transform` module is better for this case. It is used to modify doctree (intermediate representation format for documents).
http://docutils.sourceforge.net/docs/ref/transforms.html

Sphinx provides `Sphinx.add_transform()` API to install transform module from extensions:
http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_transform

Anyway, you need to learn how docutils works to create extension. Because Sphinx is based on docutils platform. So I recommend you to read the document of docutils.

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for your proposal.
