### ISSUE TITLE
stable/master 1.7.1/1.6.8+

### ISSUE THREAD

**Issue by dilyanpalauzov** [sphinx-doc/sphinx#4744]
According to https://github.com/sphinx-doc/sphinx/blob/master/CONTRIBUTING.rst#id32 there are two branches: master and major.minor (=stable).

The git repository has indeed only two branches.

The online documentation is available at:
* http://www.sphinx-doc.org/en/master/ - showing in the title 1.8.0+, and
* http://www.sphinx-doc.org/en/stable/ - showing in the title 1.6.8+

In particular, 

www.sphinx-doc.org/en/stable/ext/autodoc.html doesn't mention `autodoc_inherit_docstrings`, which is part of 1.7, while http://www.sphinx-doc.org/en/master/ext/autodoc.html mentions it.

If 1.7.1 is the stable version, please replace all occurrences at /en/stable with the documentation for 1.7, otherwise clarify, that 1.6.8 is the stable version.

**Comment by tk0miya** [comment]
Since 1.7, we started to use MINOR.MAJOR branch (and tags) to maintain old releases.
Related with the change, the URL of docs are also changed.
Now, `/en/stable` was obsoleted and `/en/1.7` was started to use.
So please refer http://www.sphinx-doc.org/en/1.7/ instead.

About `autodoc_inherit_docstrings` is written in here:
http://www.sphinx-doc.org/en/1.7/ext/autodoc.html#confval-autodoc_inherit_docstrings

**Comment by dilyanpalauzov** [comment]
When pip offers update 1.6.7 -> 1.7.0 one wants to determine, if 1.7.0 is stable.

The <title> of http://www.sphinx-doc.org/en/stable/ suggests, that 1.6.8+ is stable.

The <title> of http://www.sphinx-doc.org/en/master/, taking into account CONTRIBUTING.rst suggests, that this is unstable.

But is it not possible to find out, what status (stable/unstable/intermediate) 1.7 have, neither reading http://www.sphinx-doc.org/en/1.7/ nor CONTRIBUTING.rst .

**Comment by tk0miya** [comment]
http://www.sphinx-doc.org/en/stable/ is not maintained now. So I'd like to drop from search engines.
AFAIK, there are no links and mentions from our repository.
It is only used for keeping old URLs for external websites.

**Comment by dilyanpalauzov** [comment]
Why don't you make a HTTP redirect from /en/stable to /en/1.7 or write at /en/stable (e.g. in the title) that this is not maintained , and /en/1.7 shall be used.

**Comment by tk0miya** [comment]
It seems there are no configuration to do that in readthedocs.org.
@shimizukawa do you have any idea?

**Comment by shimizukawa** [comment]
RTD has a redirect setting.
http://docs.readthedocs.io/en/latest/user-defined-redirects.html
However, it is not possible to redirect access to a specific PATH (`/en/stable`) to another path (`/en/1.7` or something else). I think we have several choices.

The first way: display the information 'Please refer to the new document' when accessing `/en/stable` pages. For this, we need to create a new `stable` branch in the Sphinx repository and embed the message in all `doc/*.rst` files. Once we build the document with RTD, we can delete the new stable branch of Sphinx.

The second way: display the Permission Denied page of RTD when accessing `en/stable` pages. In this case, redirection is not done. Users will not be able to browse the old `en/stable` pages.

The third way: Keep it as it is.
If users access `en/stable`, they will see the red colored version number on the bottom right, which means the non-public version of the document. Unkind, but it seems to be a hint.

**Comment by dilyanpalauzov** [comment]
At best read-the-docs is asked to provide possibility for the /stable/ -> /1.7/ redirect, either for everybody or installing it manually.

Fourth option: create a branch `stable` that is identical to branch `1.7`.  Upload the documentation, delete branch stable.  Do the same procedure from time to time.  This way visitors of /stable/ will see the documentation of the 1.7 version or what is most recent.

**Comment by tk0miya** [comment]
I have another option. It is adding canonical URL to old documents (including stable).
It will clear old pages from web searches. If cleared, we can remove the stable page from our site.

**Comment by shimizukawa** [comment]
> At best read-the-docs is asked to provide possibility for the /stable/ -> /1.7/ redirect, either for everybody or installing it manually.

I agree. Let's vote the featureto RTD tracker :)
https://github.com/rtfd/readthedocs.org/issues/2444


For now, +1 for canonical URL.

**Comment by dilyanpalauzov** [comment]
I opened this ticket, as there was no means to determine if 1.7 is a stable version, considering that the addresses http://www.sphinx-doc.org/en/master/, http://www.sphinx-doc.org/en/stable/ and http://www.sphinx-doc.org/en/1.7/ co-exists, which are three distinct addresses, `pip` offers update to 1.7 and CONTRIBUTING.md speaks about two branches only.  Moreover, Linux used to use even versions for stable and odd versions for unstable.  By coincidence 1.6 is even and stable, 1.8 will be stable one day and 1.7 is odd and is not mentioned under /en/stable.

How can somebody, without reading this ticket, making the aforementioned observations, determine whether 1.7 is stable version?

**Comment by tk0miya** [comment]
Ah, sorry. The closing is not my intention. Reopened.

>How can somebody, without reading this ticket, making the aforementioned observations, determine whether 1.7 is stable version?

Why do you want to know the stable version?
At present, http://www.sphinx-doc.org/ is redirect to `/en/master`. And you can move to documents for each versions by pop up menu at right bottom. So you don't need to know about stable version.

Note: `/en/stable` is not linked from anywhere at present. Only google and search engines indexes it. And it will be cleared soon.

**Comment by dilyanpalauzov** [comment]
Because I want to know, whether the upgrade 1.6 -> 1.7 shall be skipped or performed, providing that I want to have a stable version.

**Comment by tk0miya** [comment]
Sphinx only supports latest release. In other word, last release is always stable version.

**Comment by dilyanpalauzov** [comment]
As long as /en/stable exists and shows "1.6.8" is stable, users cannot know, whether 1.7 is stable.

It is irrespective, whether in addition to the above fact Sphinx supports only the latest release.

**Comment by mgeier** [comment]
Sixth option: Set the last released version (a.k.a. "stable") instead of "master" as default version on RTD. This would have to be changed at each release.

This way you could use the normal [prefix redirect](https://docs.readthedocs.io/en/latest/user-defined-redirects.html#prefix-redirects) to redirect from `/$lang/stable` to the default version.

Also, IMHO it doesn't make too much sense to show the "master" version by default, because the huge majority of visitors will use a released version of Sphinx, so the website will show the wrong version for them.

**Comment by shimizukawa** [comment]
> This way you could use the normal prefix redirect to redirect from /$lang/stable to the default version.

Unfortunately, `/$lang/stable` prefix redirection doesn't work as we expected. It will be just 404 Not Found.

**Comment by shimizukawa** [comment]
> Moreover, Linux used to use even versions for stable and odd versions for unstable. 

It is Linux. Not a Sphinx.

**Comment by shimizukawa** [comment]
The reason for the opinion "I do not know which stable version is" is because the explicit document version name 'stable' disappears.I think that there is not much choice of document version names we can take.

Previous version name:

* Not released: `master`
* Released latest: `stable`
* Released: `1.7.1`,` 1.6.5`, `1.5.2`
* default redirect to: `stable`

Previously, every time we released sphinx, we needed to change the visible document on RTD like `1.7.1` ->` 1.7.2`.
Also, when major releases were made, work was needed to ensure consistency between `stable` and the translation project on transifex. Currently these tasks are no longer needed, so the necessary steps at release are shortened.

I believe that we can not restore "stable" in order to keep release and operation procedures simpler and maintain on a continuous basis. Also, due to the constraints of RTD, it is not possible to redirect access to `/<lang>/stable/` to the released latest version.
(We can redirect `/stable/` to `/en/1.7/` if we do not consider languages ​​other than English)

Current version name:

* Not released: `master`
* Released: `1.7`,` 1.6`, `1.5`
* default redirect to: `master

Among the current situation, I think the following two changes are possible.

* Change the name of an unreleased version to `develop` or just remove/private `master` document.
* Default redirect to `1.7`

**Comment by tk0miya** [comment]
Thank you for proposal.
Finally, we decided not to change this.

Thanks,

**Comment by mgeier** [comment]
Are you planning to add *any* way to provide links to the docs of the latest release that keep pointing to the latest release after a new release?

**Comment by tk0miya** [comment]
You can see the latest documention for Sphinx at http://www.sphinx-doc.org/ .

**Comment by mgeier** [comment]
@tk0miya Thanks for your answer and sorry if I've been unclear ...

If you say "latest documentation", you mean "the documentation created from the most recent commit in the `master` branch", right?

That means this documentation contains features that are not yet available in (or may have changed since) the latest official release on PyPI (which most users *should* be using, right?).

I think it would be more helpful (and I think most "normal" users would agree) to have an URL to the "latest PyPI release". This currently 1.7.5 but it will at some point become 1.7.6 and 1.8.0 and so on.

My question was: is there such an URL?

**Comment by tk0miya** [comment]
>I think it would be more helpful (and I think most "normal" users would agree) to have an URL to the "latest PyPI release". This currently 1.7.5 but it will at some point become 1.7.6 and 1.8.0 and so on.
>
>My question was: is there such an URL?

No.

Do you think `html_css_files` entry is confusable for normal users? This was added in 1.8. So it is not available in current release. Personally, I don't think so.
http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files

**Comment by mgeier** [comment]
Yes, this would be one example where people could get confused.
Of course it's not a huge problem, because an attentive reader will quickly find the note "New in version 1.8" in the documentation of `html_css_files`.

If you don't mind the mismatch between the latest release and `master`, that's OK for me.
I just wanted to make sure I didn't overlook anything.

Thanks again for your help!

**Comment by tk0miya** [comment]
TBH, I don't have strong opinion for this topic. If you're interested in to change our documenation, please join maintainers and become release manager.
It is strongly related with branch model, translations, release operation and so on (see #4398 and @shimizukawa's work). it is a bit tough work to change the model to me...

**Comment by mgeier** [comment]
It's not a big deal. I don't have time to contribute more to Sphinx, but I guess I'll continue to submit occasional issues and pull requests.

Thanks to the whole Sphinx team for all your hard work!

**Comment by tk0miya** [comment]
:-) Thank you always!
