### ISSUE TITLE
code-block looks smooshed in Chrome

### ISSUE THREAD

**Issue by abaybektursun** [sphinx-doc/sphinx#5057]
### Problem
code-block with python syntax looks smooshed in Chrome but looks fine in Firefox. 

#### Procedure to reproduce the problem
```python
.. code-block:: python
    
    import Datasets
    
    # Example with XES file
    xes_file_path = 'file_data/file.xes'
    xes_dataset   = Datasets.XES(xes_file_path)

    # Field name for the optimization target
    optimize_field_name = 'AMOUNT_REQ'
    # One hot encoding
    train_set, test_set = xes_dataset.hot(optimize_field_name)

    sample_size = 20
    train_sample = train_set.sample(sample_size)
```
This will be rendered like this in Chrome:

![screenshot_from_2018_06_07_19_36_36](https://user-images.githubusercontent.com/2589111/41145936-f8378634-6b01-11e8-87a7-0497ee6bf27e.png)

But it looks normal in Firefox:

![screenshot_from_2018_06_07_19_36_57](https://user-images.githubusercontent.com/2589111/41145942-ff2e835c-6b01-11e8-9faa-435fe7831ae4.png)

### Environment info
- OS: Ubuntu 18.04
- Python version: 3.6
- Sphinx version: 1.6.7 (with sphinx_rtd_theme)
- Chrome and Firefox

**Comment by tk0miya** [comment]
On my local, it seems fine to me.
![2018-06-09 2 28 08](https://user-images.githubusercontent.com/748828/41171811-cc5742da-6b8c-11e8-93e7-3ff65abc10b6.png)
This screenshot is taken with Chrome 66.0.3359.181 on MacOS.

Do you install custom CSS? How about other themes? Could you share your project or reproducible one?

FYI: sphinx_rtd_theme is not bundled theme. So we can't help you if your trouble is caused by it.

**Comment by abaybektursun** [comment]
No custom CSS, no other themes. I can't share the project since it has private information.
I will try to build html with default theme and see if the problem persists. 
Thanks

**Comment by abaybektursun** [comment]
Ok, I do not know what happened, but now I do not see the issue. I did not change anything
