### ISSUE TITLE
math_role and MathDirective in sphinx 1.8?

### ISSUE THREAD

**Issue by paugier** [sphinx-doc/sphinx#5463]
I use 

```
from sphinx.ext.mathbase import MathDirective, math_role
```
in https://bitbucket.org/fluiddyn/fluiddyn/src/default/fluiddoc/mathmacro.py

Both names have been removed from the mathbase module in sphinx 1.8.

I managed to find that `MathDirective` is now in `sphinx.directives.patches`.

`math_role` has been removed in https://github.com/sphinx-doc/sphinx/commit/4e04bff4f50bc382251437d5faafff9c34c492cb (by @tk0miya )

I didn't find anything in the documentation on why these class/function have been removed.

Can I still do something like what is done in https://bitbucket.org/fluiddyn/fluiddyn/src/default/fluiddoc/mathmacro.py with sphinx 1.8 ?

**Comment by tk0miya** [comment]
Oh, sorry. It was not intended change. I'll re-add them to keep compatibility.

>I didn't find anything in the documentation on why these class/function have been removed.

As the commit message of 4e04bff, math directive and role are moved to core package. So they were merged to core. The `math` directive was moved `sphinx.directives.patches`. On the other hand, the `math` role was removed because we uses docutils' implementation.

**Comment by tk0miya** [comment]
Fixed by #5464.
But they will be removed in Sphinx-3.0.
So please move to new ones until then.

Thanks,
