### ISSUE TITLE
Spurious spaces in code blocks when translated with Google Translate

### ISSUE THREAD

**Issue by astrofrog** [sphinx-doc/sphinx#5727]
In https://github.com/sphinx-doc/sphinx/pull/4424, Sphinx introduced the ``class='notranslate'`` on code blocks, which is great and works to some extent. However, there is a residual issue that Google Translate appears to introduce spaces between parts of the code:

<img width="710" alt="screen shot 2018-12-05 at 17 56 15" src="https://user-images.githubusercontent.com/314716/49554280-bdfdd500-f8b8-11e8-9139-339fec308a33.png">

which means that copy/pasted code can't actually be used without cleaning it up first. It would be great if this is something that could be prevented on the Sphinx side.

(cc-ing @tk0miya as the author of #4424)

**Comment by tk0miya** [comment]
Unfortunately, I'm not good at google translate. Do you have any good idea?

**Comment by TimKam** [comment]
@astrofrog Could you point to a specific documentation page that is available online and specify the language you are translating to? This does not seem to be a problem that occurs _always_, no matter the type of code block and language.

**Comment by astrofrog** [comment]
@TimKam - here's an example:

English: http://docs.astropy.org/en/latest/constants/index.html

French: https://translate.google.com/translate?sl=en&tl=fr&u=http%3A%2F%2Fdocs.astropy.org%2Fen%2Flatest%2Fconstants%2Findex.html

**Comment by tk0miya** [comment]
Hmm... google translate inserts a space character between `<span>` tags. It makes the code-block sparse.
It seems no options for google translate to control the behavior. If anyone knows it, please let me know.

**Comment by TimKam** [comment]
I also had a look and could not find any straight-forward fix for this. I certainly see this as a problem with Google translate and not with Sphinx. It's probably technically possible to implement work-arounds in Sphinx (e.g.: writing a script that waits some seconds after page load, checks the URL and removes space characters in elements with specific classes), but these would be rather *hacky* and unreliable.
What do you think, @tk0miya? Should we try a work-around or rather conclude that this issue is a) not caused by Sphinx and b) of too little importance?

**Comment by tk0miya** [comment]
I feel this is a problem of Google Translate. So there are nothing to do from sphinx side.

In addition, workaround is fragile and hacky. So I don't think we should not that as sphinx-core.

**Comment by TimKam** [comment]
Makes sense imho. Then I mark it as ``wontfix`` and close it.
