### ISSUE TITLE
sphinx-autodoc with __init__.py (python package)

### ISSUE THREAD

**Issue by jain-sah** [sphinx-doc/sphinx#5916]
Subject: sphinx-autodoc automatically executes __init__.py file

### Problem
My project has a directory in which I have a __init__.py file.
This gets run as soon as I run the sphinx-apidoc and the remaining python files are ignored creating the foldername.rst and modules.rst

#### Procedure to reproduce the problem
1. Have a folder with 4(random number) python files.
2. Include a __init__.py file
3. Run sphinx-apidoc -f -o source/ ../<foldername>
4. 2 files generated foldername.rst and module.rst
5. Remove the __init__.py file and run step 3
6. All the remaining .py file's rst are created

### Environment info
- OS: Mac
- Python version: 2.7
- Sphinx version: 1.8

**Comment by tk0miya** [comment]
apidoc considers a directory having `__init__.py` as a package as python does. `foldername.rst` would contain submodules information. I think it is right behavior of apidoc.
What is problem?

**Comment by jain-sah** [comment]
I have this structure -
test-project
├── code
│   ├── ```__init__.py```
│   ├── hello.py
│   └── hello123.py
├── docs
│   ├── Makefile
│   ├── build
│   ├── make.bat
│   └── source
│       ├── _static
│       ├── _templates
│       ├── conf.py
│       └── index.rst
└── test

I am running this command in the docs directory 
```sphinx-apidoc -f -o source/ ../code/```
I get this - 

```
Creating file source/code.rst.
Creating file source/modules.rst.
```

After running 
```make html```

My page looks like this and I can't click on them - 

![screen shot 2019-01-10 at 11 58 56 am](https://user-images.githubusercontent.com/30559538/50993812-66faa980-14cf-11e9-9df5-b59c748363b7.png)


After removing the ```__init__.py``` file from the "code" folder and running the same steps I get this - 

```
$ sphinx-apidoc -f -o source/ ../code/
Creating file source/hello.rst.
Creating file source/hello123.rst.
Creating file source/modules.rst.
```
and the ```make html``` generated this page which is expected -

![screen shot 2019-01-10 at 12 07 02 pm](https://user-images.githubusercontent.com/30559538/50994132-4e3ec380-14d0-11e9-82ec-2c39789df0a4.png)

**Comment by jain-sah** [comment]
Is there any other place I can ask for help on this topic?

**Comment by tk0miya** [comment]
Sorry for late response.
Could you share a minimal reproducible example? On my local, both case are working fine. So I'd like to reproduce the situation.
Thanks,

**Comment by jain-sah** [comment]
Hi, here is the link that explains the problem and the document structure.
https://github.com/jain-sah/sphinx_test

**Comment by tk0miya** [comment]
It seems `sys.path` settings in `code_with_init/docs/source/conf.py` is wrong.
https://github.com/jain-sah/sphinx_test/blob/0ff1c2bcc03ef0015d5baf82c62ee3c0a4c8528f/code_with_init/docs/source/conf.py#L17

To import `code` package, you need to add `os.path.abspath('../../')` instead.
I guess you'd seen "failed to import module" warning from autodoc.
Please check your project settings.

**Comment by tk0miya** [comment]
I'm closing this now because this would not be a bug of Sphinx.
Thanks,

**Comment by kanishk-varshney** [comment]
I am running into the same issuse. While generating the documentation, code placed inside __init__.py file gets executed and crashes the docstring build. 

There is some global variables assignment happening in global scope( outside any function etc.)
The crash is happening due to exception raised by code execution, which is getting executed by the **_make html_**

![sphinx_issues](https://user-images.githubusercontent.com/4751805/84390672-8b533c00-ac15-11ea-8689-4ffe346145d7.PNG)

@tk0miya 
@jain-sah Did you find any fix for this ?

**Comment by tk0miya** [comment]
@varskann It seems your script tries to assign "None" value to environment variable. I don't know why this happened. But this is a bug of your script. The autodoc extension goes to import the target module on documenting. So you need to ensure your module importable from autodoc.
Anyway, your bug is not related to this issue.
