### ISSUE TITLE
IE Compatibility Mode

### ISSUE THREAD

**Issue by hokorobi** [sphinx-doc/sphinx#6242]
**Describe the bug**
`<meta http-equiv="X-UA-Compatible" content=IE=edge">` is no longer output

**Environment info**
- OS: Win
- Python version: 3.7.3
- Sphinx version: 2.0.0

**Additional context**
Related issue #3537

**Comment by hokorobi** [comment]
It could be displayed without problems by setting `html_context = {'html5_doctype': False}` in `conf.py`.

**Comment by tk0miya** [comment]
The change has been caused that Sphinx move to HTML5 output since 2.0. It seems #3997 does not adds the meta tag on HTML5 output. I don't know what is correct. But this is expected behavior of #3997.

So I propose you to set `html4_writer` to `True` on your conf.py. Then sphinx generates HTML files in HTML4 mode.

**Comment by hokorobi** [comment]
Thank you, that's fine.
Please remove the bug label.
