### ISSUE TITLE
Autodoc attempts to document imports in "optional import" idiom

### ISSUE THREAD

**Issue by rhelmot** [sphinx-doc/sphinx#6451]
Autodoc-ing a module with the following idiom will result in trying to document the third-party OptionalClass. Pretty sure it's because it classifies it as not-imported data because of the assignment. Related to #6447 ?

```python
try:
   from xyz import OptionalClass
except ImportError:
  OptionalClass = None
```

This is happening on 2.1.0 and on the latest master. Let me know if you need more reproduction instructions and I'll put together a small testcase. Right now the very large testcase is in the angr project; error log is [here](https://travis-ci.org/angr/angr-doc/jobs/541906392#L1170), build tree is [here](https://github.com/angr/angr-doc/tree/c0e815b/api-doc) (conf.py is [here](https://github.com/angr/angr-doc/blob/c0e815b/api-doc/source/conf.py), relevant source is [here](https://raw.githubusercontent.com/angr/angr-doc/c0e815b/api-doc/source/angr.rst) (the relevant line is `.. automodule:: angr.engines.concrete`)) and the module source is [here](https://github.com/angr/angr/blob/48a7297/angr/engines/concrete.py#L11).

**Comment by sanscore** [comment]
I'm seeing a similar issue, but in my case, Sphinx is documenting `logging` and `flask`. However, I don't have any `try-except` guards around those imports. I cannot provide thorough documentation unfortunately, but in the case for `logging`, the code looks like this:

```python
import logging
import logging.config

import yaml

with open('logging.yaml') as log_config:
    logging.config.dictConfig(yaml.safe_load(log_config))

log = logging.getLogger(__name__)
```

This started today after upgrading to Sphinx v2.1.0. The issue went away after I downgraded back to v2.0.1.

**Edit:** As for the `flask`, it only generated docs for `blueprints.py`, so this must be from code similar to the following:

```python
from flask import Blueprint

blueprint = Blueprint('foo', __name__, static_folder='../templates/foo/')

@blueprint.route('/bar')
def bar():
    return render_template('bar.html')
```

IMHO, the change is "Working as Expected", but it really shouldn't be doing this. Rather than adding new functionality to `:undoc-members:`, it would be better to add a new directive instead; `:undoc-constants:`.

#6447, #6423, and #1063

**Comment by tk0miya** [comment]
I think there are two problems. First is about optional imports. I believe nobody wants to document it. And another is about documenting global variables. I think first one is a bug. And second one is not a bug, but it should be under controlled by "opt-in" rules (maybe configs or directive options). I'd also like not to document `logger` variable to the document :-p

**Comment by tk0miya** [comment]
Finally, I decided to revert #6423 (refs: #6471).
Thank you for reporting.
