### ISSUE TITLE
Cyclical intersphinx setup

### ISSUE THREAD

**Issue by jan-matejka** [sphinx-doc/sphinx#6489]
Hi, I have two projects with sphinx-doc and using intersphinx to connect them both.

It seems to be working except the build procedure is now:
```
make -C proj_1 html || true
make -C proj_2 html || true
make -C proj_1 html
make -C proj_2 html
```

The first two builds are required only to build the objects inventory file if I understand correctly.

Is there a way to build the inventory objects only?

**Comment by tk0miya** [comment]
There are no way to build inventory.
Thanks,

**Comment by jan-matejka** [comment]
Ok. Maybe turn this into a feature request then?

**Comment by tk0miya** [comment]
I think the feature is not effective. Because almost of Sphinx processes are needed for building inventories. It would not decrease time of build so much.

**Comment by jan-matejka** [comment]
This feautre would not be about speed but about having the process under control. Right now the first two make commands print some errors and their exit code is meaningless. With a command to generate object inventory only I would not need to suppress the output and exit code.

**Comment by tk0miya** [comment]
I don't know why are you suppress output and exit code. Are all of them for outputting HTMLs? If so, inventory builder would be useful. Is this right?

**Comment by jan-matejka** [comment]
Because its producing errors due to the missing objects.inv file so the output and exit code of first two runs is meaningless.

Yes, I'm building into html and inventory builder would be nice.

**Comment by tk0miya** [comment]
Unfortunately, building HTML and inventory is strongly coupled. Because URL of each object entry is changed by kind of HTML builders. For example, standard HTML builder put them into individual pages (files), but single HTML builder put them all to single HTML file. directory based HTML builder (dirhtml) is also different. As a result, building inventory must be processed after almost of HTML building process.

The "inventory builder" what I called above is only not generating HTML files (but calculates internally). It does not help to suppress error messages...
