### ISSUE TITLE
PDF generation requires nonfree software

### ISSUE THREAD

**Issue by alex-tee** [sphinx-doc/sphinx#6505]
**Describe the bug**
On Arch Linux or Parabola GNU/Linux with texlive-most installed it's not possible to generate the PDFs using pdflatex. It gives similar errors to this https://labs.parabola.nu/boards/5/topics/55?r=58. Note that it works if you install the official texlive package from https://tug.org/texlive/.

**To Reproduce**
```

# on Arch-Linux or Parabola GNU/Linux with texlive-most installed:

$ git clone https://git.zrythm.org/zrythm/zrythm-docs
$ cd zrythm-docs
$ make latexpdf
```

**Expected behavior**
It compiles the PDF successfully.

**Your project**
https://git.zrythm.org/zrythm/zrythm-docs

**Environment info**
- OS: Arch-Linux or Parabola GNU/Linux
- Python version: 3.7.3
- Sphinx version: 2.1.1
- Sphinx extensions:  N/A
- Extra tools: tex

**Additional context**
Arch Linux and Parabola GNU/Linux are likely removing non-free components from the official texlive distribution before packaging it. See an example here https://labs.parabola.nu/boards/5/topics/55?r=58.
> It should be noted the much of texlive-* is in the [libre] repo meaning that work had to be done to make it respect your freedom.
Installing from the link above would almost certainly Violate that Freedom and the spirit of Parabola

sphinx-doc should be expected to produce PDFs without requiring the user to install non-free software.

**Comment by jfbu** [comment]
The link you include seems to indicate a problem with fonts. When using pdflatex the default font choice is via `\usepackage{times}`. This times package is part of the [`psnfss` bundle](https://ctan.org/pkg/psnfss), which itself is 

> The bun­dle as a whole is part of the LaTeX ‘re­quired’ set of pack­ages. 

and is described as

> Font def­i­ni­tion files, macros and font met­rics for freely-avail­able Adobe Type 1 fonts. 

This is not the same as the EC encoded Computer Modern (aka Knuth) fonts which ecrm1095 refers to in the thread you linked to.

I don't know the details about why Arch Linux does not include this support (it is described in all LaTeX reference books dating back less than circa 20 years ago I guess) for these so called Type 1 Adobe Fonts.

As alternative you may try to use ``latex_engine = 'xelatex'``. Then make sure the GNU FreeFonts are available on the platform. Indeed this is the default fonts for xelatex Sphinx usage (since release 2.0.0) The math fonts will still be the Knuth default TeX ones. I do not know if they qualify as free fonts in the Arch Linux distro. They probably do as I don't see what could be "freeer" in terms of math fonts in the LaTeX world.

**Comment by alex-tee** [comment]
thanks for the information. it sounds like a packaging problem in Arch Linux so I reported it there. It doesn't sound like a sphinx-doc issue so I guess this can be closed

**Comment by jfbu** [comment]
Ok, thanks for reporting. I will close for now, but feel free to re-open depending on what Arch Linux people say.

**Comment by eli-schwartz** [comment]
Th

> Arch Linux and Parabola GNU/Linux are likely removing non-free components from the official texlive distribution before packaging it.

Arch Linux has no rules against packaging non-free components to anything whatsoever, as long as it is licensed in such a way that permits us to redistribute it.

Arch Linux packages these fonts as part of texlive-core, and the project in question builds correctly for me, therefore as an @archlinux bugwranger I've closed your distribution bug report.

Parabola is an FSDG Libre distro, and as such provides a forked version of texlive-core with the following deviation from Arch Linux: https://git.parabola.nu/abslibre.git/tree/libre/texlive-core/PKGBUILD#n90

```
   # remove nonfree packages
   # MeX licensed packages
   rm -v {cc-pl,cs,ec,mex,pl}.tar.xz
   # public domain, will be relicensed
   rm -v context-{account,algorithmic,letter,ruby}.tar.xz
   # no specific free license
   rm -v euro-ce.tar.xz
```

This includes the ec fonts which your build is failing to pick up, but mine is correctly picking up.

**Comment by alex-tee** [comment]
thanks for clearing this up
