### ISSUE TITLE
Longtable before header has incorrect distance

### ISSUE THREAD

**Issue by jessetan** [sphinx-doc/sphinx#6668]
**Describe the bug**
A longtable before a header produces smaller vertical whitespace than other content before a header

**To Reproduce**

`index.rst`:
```rst
************
Some chapter
************

Header distance
===============

.. list-table:: Long table before text
    :class: longtable

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

This is some content that is not a longtable. bla bla bla bla bla bla

Normal header distance
----------------------

.. list-table:: Long table before not long table
    :class: longtable

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

.. list-table:: Table not longtable

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

Normal header distance again
----------------------------

.. list-table:: Long table before long table
    :class: longtable

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

.. list-table:: Long table before header
    :class: longtable

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

SMALLER HEADER DISTANCE AFTER LONGTABLE
---------------------------------------

foo foo foo foo
```

**Result**

The distance longtable-header == distance longtable-text and the distance text-header == distance table-header.

![Screen Shot 2019-08-22 at 15 23 37](https://user-images.githubusercontent.com/3284111/63518224-dd916800-c4f0-11e9-9c54-170e807c28e1.png)

**Expected behavior**

The distance longtable-header == distance text-header == distance table-header.

**Additional info**

I've tried to work around this by messing with `\sphinxatlongtableend` and `\sphinxtablepost` but did not succeed since this only happens before a header and not in all situations

Possibly related to #3504

**Environment info**
- Python version: 3.7.3
- Sphinx version: 2.2.0

**Comment by jfbu** [comment]
Thanks for catching this and fine test case. I have started debugging this and it looks almost as un upstream LaTeX problem. The different spacing (the one before longtable and next header) comes from the header being typeset in a condition where the LaTeX conditional `\if@nobreak` is true. Add any text (or a non-longtable table) to the contents in-between headers and this turns the `\if@nobreak` to false, then spacing is correct. Thus your problem occurs when two headers are separated **only** by longtables: it can thus not be said to be caused by only one given longtable, but the fact a longtable by itself does not let intervene TeX so-called paragraph mode which would (due to LaTeX customization of  `\par`)  cause the `\if@nobreak` after a header to revert to false (it is true immediately after it).

In this example I separate two headers by one table and one longtable, and you can check that spacing is ok, despite a longtable immediately preceding a header:

```
Some dummy header
-----------------

.. list-table:: table before header

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

Normal header distance again
----------------------------

.. list-table:: table before long table

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

.. list-table:: Long table before header
    :class: longtable

    * - a
      - b
      - c
    * - 1
      - 2
      - 3

NORMAL HEADER DISTANCE AFTER LONGTABLE
--------------------------------------

foo foo foo foo
```

I need to think a bit how to best fix that. A `\@nobreakfalse` [1] added to `\shinxatlongtableend` for example would fix it. Maybe there is better way. Need to ponder this. Thanks!

.. [1]: the `\if@nobreak` is not a regular TeX conditional created by `\newif`, and LaTeX defines directly `\@nobreakfalse` to include a `\global` prefix.

**Comment by jfbu** [comment]
Reported upstream: https://github.com/latex3/latex2e/issues/173

**Comment by jessetan** [comment]
Thanks @jfbu for the analysis. I'll try to workaround for now by moving some text from the caption to a line "The following table shows bla bla".

**Comment by jfbu** [comment]
Fixed at https://github.com/sphinx-doc/sphinx/commit/e944a555170f8320adc3768799fb13bc55fda472
