### ISSUE TITLE
It would be great to be able to create tables the Asciidoctor way

### ISSUE THREAD

**Issue by Nadano** [sphinx-doc/sphinx#6770]
I have been using asciidoctor for a while and now I started to use rst because adoc started to show its limitations.
I was quite surprised of how difficult is to manage tables compared to asciidoctor, list-tables are a big improvement already to creating ascii-art but they are not near as powerful as in asciidoc(tor).

https://asciidoctor.org/docs/user-manual/#tables

Not knowing the internal sphinx architecture, I wonder: Would it be possible to implement this in sphinx or some extension?

**Comment by tk0miya** [comment]
The syntax of reStructuredText has been discussed at docutils project. So please ask this to their project.
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html

IMO, adding another new table syntax is not good. Because two different syntax would confuse people. It is better to add new "directive" to make a table with asciidoc's syntax to me.
