### ISSUE TITLE
autosummary and autodoc-skip-member don't work well together

### ISSUE THREAD

**Issue by kbattocchi** [sphinx-doc/sphinx#6798]
**Describe the bug**
The `autodoc-skip-member` event can be used modify which members are documented by autodoc.  However, those modifications are ignored by `autosummary`, which breaks in two ways:
- If a member is skipped by autodoc-skip-member then the member still shows up in the set of members used by autosummary templates (e.g. a class that is now suppressed in autodoc is still an element of the `classes` collection used by the module.rst template).  This results in broken links in generated tables.
- If a member is included by autodoc-skip-member when it would normally be included, then it does not appear in the set of members used by the autosummary template, which can result in missing entries in the tables generated by the template, even though the documentation itself is generated by the section.  For instance, the `.. automodule::` section of the `module.rst` default template might generate the documentation for a normally hidden class because of `autodoc-skip-member`, but that class won't appear in the `Classes` section that the template creates.

**To Reproduce**

1. Add something like this to the bottom of a conf.py that uses autodoc and autosummary:

        def skip_member(app, what, name, obj, skip, opts):
            # we can document otherwise excluded entities here by returning False
            # or skip otherwise included entities by returning True
            if name == "_something_that_wouldnt_normally_appear":
                return False
            elif name == "something_that_would_appear":
                return True
            return None

        def setup(app):
            app.connect('autodoc-skip-member', skip_member)

2. Run sphinx

**Expected behavior**

There is some straightforward way to get the list of members post-filtering into an autosummary template.

**Actual behavior**

The member table generated by autosummary wrongly contains a broken link to "something_that_would_appear", and wrongly does not contain a link to "_something_that_wouldnt_normally_appear" even though documentation is generated for it.

**Environment info**
- OS: any
- Python version: any
- Sphinx version: 2.2.1
- Sphinx extensions:  sphinx.ext.autodoc, sphinx.ext.autosummary

**Comment by ben-spiller** [comment]
What might be ideal is to refactor the autodoc Documenter.filter_members() method (which calls out to autodoc-skip-member amongst other things) into a standalone function (or perhaps callback?) that can be easily used from autosummary and any other custom extensions - since this functionality is quite valuable for many use cases so makes sense to have in a more reusable form (without having to set up an autodoc Documenter object which is non-trivial). 

Anyway, at a minimum we should avoid autosummary having its own logic (e.g. in generate_autosummary_content) for deciding which members to ignore which behaves differently to the equivalent in autodoc.

**Comment by tk0miya** [comment]
autosummary is designed as a generator of reST code for autodoc. So it does not invoke autodoc extension directly. So it is natural not to call `autodoc-skip-member` event on running autosummary to me. But I agree there are no way to remove them from the output of autosummary.
+1 for improving. I think adding a new event like `autosummary-skip-member` is good.

**Comment by ben-spiller** [comment]
Great, will be good to improve this. autosummary-skip-member is certainly better than nothing but if you don't mind I'd like to sketch out the case for invoking autodoc-skip-member instead of adding a new callback:
a) the documentation already says "Autosummary preprocesses the docstrings and signatures with the same autodoc-process-docstring and autodoc-process-signature hooks as autodoc." (http://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) - and if those two autodoc-* hooks work with autosummary then it would be reasonable expect autodoc-skip-member to do the same for the sake of consistency.

b) the logic for calling XXX-skip-member is closely related to the logic for deciding whether to skip private/special items starting with _ or __ - and it might be more consistent and cleaner to have a common implementation for that filtering that applies to both extensions rather than having subtly different logic in both places (Documenter.filter_members() and generate_autosummary_content)

c) if a user was to set the autodoc-skip-member but not autosummary-skip-member I think you'd get broken links (?), so using a different mechanism seems fragile. In the architecture I get the impression there's 'meant' to be a close relationship between the autodoc extension (for detailed doc of classes/functions etc) and autosummary (for summary tables that link to the autodoc for those items)

**Comment by tk0miya** [comment]
>a) the documentation already says "Autosummary preprocesses the docstrings and signatures with the same autodoc-process-docstring and autodoc-process-signature hooks as autodoc."

Oh, I've forgotten this rule. Indeed, I agree with you. It is better to use `autodoc-skip-member` event on autosummary too (if we can use it).

**Comment by tk0miya** [comment]
I made a PR #6817 for this. Could you try this please?

**Comment by kbattocchi** [comment]
@tk0miya Thanks for the quick response!

This solves half of my problem: it correctly hides things that should be hidden by returning `True` from `autodoc-skip-member`, creating proper summmary tables without broken links.

However, it doesn't quite address the other half, which is making it easier to document things that would normally be hidden but are now exposed by returning `False` from `autodoc-skip-member`.  

To give a concrete example, with the default `module.rst` autosummary template, if I don't add any `autodoc-skip-member`, then:

1. Classes starting with an '_' do not appear in the summary table in the "Classes" section (and if these are the only classes, the "Classes" section is completely omitted).
2. Detailed class documentation for classes starting with an '_' do not appear in the `automodule` content either.
3. Normal classes do appear in the summary table.
4. Detailed class documentation for normal classes do appear in the `automodule` content.

If add an `autodoc-skip-member` that indicates that some normally private class should be documented (by returning `False`), then

* This class still does not appear in the summary table (even after your current modifications)
* However, detailed class documentation for the class does now appear in the `automodule` content.

So from an autodoc perspective, it's like the class is now public, but from an autosummary perspective it is still non-public.

**Comment by ben-spiller** [comment]
Thanks guys great to see some progress on this so soon! I'd add a +1 for @kbattocchi 's point I think... it's weird for autosummary and autodoc to have different behaviour. I think as long as autosummary has its own duplicated and different logic for deciding how to filter members we're going to hit edge cases like the ones mentioned above (and probably others we haven't thought of yet). (aside: for example, I suspect there are some subtle cases around deciding if a data member has a docstring or not (since we need to run the analyzer to pick up docstrings for data members as __doc__ doesn't cut it)). 

It also means if there are future improvements or bug fixes to the member filtering logic in autodoc (e.g. GH-6808) there will again be new issues in autosummary that need fixing separately. 

Looks like an ideal solution would be to have autosummary execute the exact same implementation as autodoc by calling its Documenter.filter_members() method which is where the private member filtering happens (as well as the call to autodoc-skip-member). Sorry I don't have time to put together a proper pull request for this suggestion myself, but I can see the autosummary code can already create an autodoc documenter instance (using the FakeDirective hack :) ), so could make use of the filtering by something like::

		# need this so that attribute docs are found by the analyzer, else filter_members gets confused
		documenter.analyzer = ModuleAnalyzer.for_module(modulename)
		#maybe: attr_docs = documenter.analyzer.find_attr_docs()

		# find out which members are documentable; use __dict__.items() to retain the ordering info, but delegate to 
		# autodoc get_object_members for yes/no decision for its __all__ handling logic
		permittedmembers = set(memberinfo[0] for memberinfo in documenter.get_object_members(want_all=True)[1])
		members = [(mname,m) for mname, m in mod.__dict__.items() if mname in permittedmembers]
		
		for (mname, m, isattr) in documenter.filter_members(members, want_all=True):
			...`

**Comment by ben-spiller** [comment]
btw I think that approach of delegating to autodoc code instead of duplicating similar-ish! logic in autosummary would also automatically solve problems like GH-2021 (and maybe to some extent GH-5379, GH-4534 and associated PR GH-6214)

**Comment by tk0miya** [comment]
@kbattocchi Thank you for confirmation. I just updated my PR now. It allows to document private member forcedly via skip-member handler.

**Comment by tk0miya** [comment]
>btw I think that approach of delegating to autodoc code instead of duplicating similar-ish! 

I agree. We need to refactor them in another time. Let's talk about it in #6829.

**Comment by tk0miya** [comment]
Just merged: #6817. Thank you for reporting!
