### ISSUE TITLE
str, int, dict, list, etc. is thrown as a warning in sphinx-build -n mode

### ISSUE THREAD

**Issue by dvorapa** [sphinx-doc/sphinx#6895]
**Describe the bug**
When I add `-n` parameter to the `sphinx-build` command, I get 2 500 warnings like this:
```
10:57:35 /src/pywikibot/site.py:docstring of scripts.maintenance.cache.APISite.movepage:: WARNING: py:class reference target not found: str
```
Changing str to string does not help. This seems to me like a bug with `-n` function maybe as I can't imagine anything else to write there instead of str or string, int, dict, list, etc.

**To Reproduce**
```
$ git clone https://github.com/wikimedia/pywikibot
$ cd pywikibot
$ pip install -r requirements.txt .[security] -r docs/requirements-py3.txt
$ cd docs
$ sphinx-build -b html . _build -n
see the output
```

**Expected behavior**
Base Python classes should be understood by nitpick mode, right?

**Your project**
https://github.com/wikimedia/pywikibot (just a mirror from https://phabricator.wikimedia.org/diffusion/PWBC/)

**Environment info**
- OS: Debian Linux
- Python version: 3.5
- Sphinx version: 2.2.2
- Sphinx extensions: autodoc, apidoc, rstcheck, epytext, numpydoc or napoleon, alabaster

**Additional context**
For a while, you can see the logs here: https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/7891/console

**Comment by tk0miya** [comment]
At present, Sphinx does not know python basic classes at all. So nitpicky mode warns all references  which are not resolved. You can suppress them with adding python's document to the configuration of intersphinx.

**Comment by ColinKennedy** [comment]
Is there a way to report domains with broken links exclusively? e.g. Just check links such as ``` :func:`foo_module.get_bar` ```. nitpicky throws too many false positives and I really only want to be checking domains that users explicitly requested.

**Comment by tk0miya** [comment]
What do you mean "domain"? If you mean Sphinx's domain, you can ignore warnings via `nitpick_ignore`. But I guess what you meant is python's package. Is this right? If so there are no way to ignore them. But it is acceptable feature to me.

BTW, nowadays type annotations are added into python ecosystem. So we're usually using type-systems in python code. So it would be better to support auto suppressing for built-in types and `typing` types. On the other hand, python contains many "batteries". And they're usually changed on updating. So it would not be good to support them all.

**Comment by ColinKennedy** [comment]
I was referring to Sphinx domains. specifically the "Cross-referencing Python objects" section. https://www.sphinx-doc.org/en/2.0/usage/restructuredtext/domains.html#cross-referencing-python-objects

```
...
:py:class:
:py:meth:
:py:attr:
:py:obj:
...
```

In Python 2, Sphinx 1.8.5

```python
def foo(bar=8):
    """Do something.

    Args:
        bar (int, optional): Some information here.

    """
    pass
```

`nitpicky` returns

```
WARNING: py:class reference target not found: int
WARNING: py:class reference target not found: optional
```

I could theoretically make a big list of every possible thing to ignore. But as you mentioned before, that's not really viable. Plus, sometimes you can't always point to a Python type (C/python bindings), etc.

**Comment by ColinKennedy** [comment]
The ideal outcome is to have **clickable types** in Sphinx so that multiple projects can jump from one to another. Currently, I'm accomplishing this using intersphinx and the ``` :py:class:`foo` ``` syntax mentioned above. But if that's the way I'm supposed to be doing this, I'd like to have a tool that will make sure that these tags will always stay up to date.

`some_module.py`
```python

"""A module that uses :class:`project_b.another_module.TestClass`."""

# ...
```

And this renders as 

![image](https://user-images.githubusercontent.com/10103049/71713547-0854cc80-2dbf-11ea-9eb9-fe96a5eae631.png)

That's a clickable link that goes to the other project. 

## Maybe this is possible to do using only static type hints?
I'm not super familiar with Python 3 so I could be wrong about this next point.

But I built a Python project using Python 3 + static type hints with a custom class. **And then added napoleon + intersphinx** on top of it. The result was this

![image](https://user-images.githubusercontent.com/10103049/71713736-d4c67200-2dbf-11ea-82fa-12cbb0350b2c.png)


```python

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""A module that uses :class:`project_b.another_module.TestClass`."""

from typing import Any, List, Optional
from project_b import another_module


def get_foo(something: List[another_module.TestClass], another: Optional[List[Any]]):
    print('I do something!')


def get_bar(something: List[another_module.TestClass], another: Optional[List[Any]]):
    """Example documented code.

    Args:
        something: Some information here.
        another: More data, here.

    """
    print('I do something!')
```

Even though the module was included in the signature, it didn't create clickable links as I had expected. I was able to get a good result using [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints) but I'm not sure if that is the correct way of doing this kind of thing. Using type-hints would be a better way of working because it removes the need to "check" if the type actually points to a proper Python object. Assuming it has docs.

**Comment by tk0miya** [comment]
I understand our goal is generating documents from typehints. Agreed. But it is too far from current implementation. So we should improve Sphinx step by step.

My understanding for goal of this issue is to suppress built-in python modules, right? If so, we can use intersphinx with python-docs.
```
extensions = ['sphinx.ext.intersphinx']
intersphinx_mapping = {
    'python': ('https://docs.python.org/', None),
}
```

If you would not like to link them to external document, you can use `nitpick_ignore` as a workaround:
```
import builtins
for name in dir(builtins):
    nitpick_ignore = [('py:class', name)]
```
This is not perfect solution. But it almost works fine.


As an idea, it would be better to suppress a nitpicky warnings for specific domain like `nitpick_ignore = [('py:class', '*')]`. Is it helpful for you?

**Comment by tk0miya** [comment]
FYI: We have an another issue #6418 to generate a document from type annotations. It might be almost same as sphinx-autodoc-typehints.

On the other hand, there are no issues to make types in arguments list clickable..

**Comment by shimizukawa** [comment]
I don't think it makes sense to warn about built-in types cannot be referenced.
+1 to suppress built-in types by default in nitpick.
