### ISSUE TITLE
Does Sphinx support markdown with mermaid?

### ISSUE THREAD

**Issue by kathywt** [sphinx-doc/sphinx#6958]
**Describe the bug**
I have a markdown file with mermaid as follows, but when the sphinx is used to generate HTML files, it shows a warning: "WARNING: Pygments lexer name 'mermaid' is not known".
When i change it to rst file, it looks good. But how can I solve this problem with markdown file but not rst file? Thank you.

```
    ```mermaid
       graph LR
          TestBase --> TestA
          TestBase --> TestB
    ```
```

**Environment info**
- OS: [Centos]
- Python version: [3.7.3]
- Sphinx version: [2.2.2]
- Sphinx extensions:  [recommonmark, sphinxcontrib.mermaid]

**Comment by tk0miya** [comment]
Sorry, I don't understand why did you file this as sphinx-core's bug. But it seems this is not a bug of Sphinx. Sphinx does not support both markdown and mermaid as a core feature. Please ask to their project.

IMO, recommonmark would not work well with other extensions. Because markdown does not have syntax like directive in reST.

**Comment by kathywt** [comment]
ok, thank you.

**Comment by Gama11** [comment]
Relevant docs on how to set this up for others that might stumble upon this issue:

https://github.com/mgaitan/sphinxcontrib-mermaid#markdown-support
