### ISSUE TITLE
Make it possible to ignore certain files when searching

### ISSUE THREAD

**Issue by libre-man** [sphinx-doc/sphinx#7025]
**Is your feature request related to a problem? Please describe.**
We use sphinx for both code documentation and user documentation. As the code documentation is used way less then the user documentation, especially when searching, we would like to hide useless results for many of our users, i.e. the code documentation. 

**Describe the solution you'd like**
I would like a new configuration option that would allow me to ignore certain files when creating the search index.

**Describe alternatives you've considered**
I could subclass the search implementation and implement this manually, but I think a configuration option might also be useful.

**Comment by tk0miya** [comment]
Sphinx's search is consist of full text search, title search and term search (object search). IMO, disabling full text search and title search is easy. But disabling term search is difficult. Because it is also used to cross references.
So +1 for disabling full text search and title search for specific documents.
