### ISSUE TITLE
napoleon renders parameter defaults differently depending on whether parameter type is quoted

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#7391]
**Describe the bug**

In napoleon/numpydoc-style docstrings, parameter defaults are rendered differently depending on whether the parameter type is quoted or not.

**To Reproduce**
```
$ sphinx-quickstart -q -m --sep -pfoo -afoo --extensions=sphinx.ext.autodoc,sphinx.ext.napoleon
```
Create `foo.py` with the contents
```python
from enum import Enum


class E(Enum):
    a = 1


def foo(x = 42, y = E.a):
    """
    Parameters
    ----------
    x : int, default: 42
        The x.
    y : `E`, default: `E.a`
        The y.
    """
```
and add to `index.rst`
```rst
.. automodule:: foo
   :members:
```
then build with `PYTHONPATH=. make html`.

**Expected behavior**
The defaults for `x` and `y` are rendered with the same style...

**Screenshots**
... but one actually gets
![Screenshot_20200328_133646](https://user-images.githubusercontent.com/1322974/77823164-4ed57100-70f9-11ea-8380-68b39e6a70aa.png)
(one default is italicized, not the other)

**Environment info**
- OS: linux
- Python version: 3.8.2
- Sphinx version: 2.4.4
- Sphinx extensions:  automodule, napoleon

**Comment by tk0miya** [comment]
This is not related to the napoleon module. It only converts the docstring of `foo()` like this:
```
def foo(x = 42, y = E.a):
    """
    :param x: The x.
    :type x: int, default: 42
    :param y: The y.
    :type y: `E`, default: `E.a`
    """
```

**Comment by tk0miya** [comment]
Please look at the result of conversion. The "default: 42" and "default: `E.a`" are converted to the `:type:` field. It means napoleon considers them as type, not default values.

And default docstring processor, the python domain tries to convert the type-field to a reference. As a result, the type for `x` is converted to italic because failed to find the object named `int` and `default: 42`. On the other hand, the type for `y` parameter is failed to converted because they are marked up manually. So they are not converted at all.

Conclusion: This is not expected usage. Please write a default value to description field:
```
def foo(x = 42, y = E.a):
    """
    Parameters
    ----------
    x : int
        The x. (default: 42)
    y : E
        The y. (default: `E.a`)
    """
```

**Comment by anntzer** [comment]
Fair enough, feel free to close, then.
