### ISSUE TITLE
Mark abstract methods/properties as such

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#744]
It would be useful if autodoc produced special markup for abstract methods and such, as defined by the abc module. Possibly, the "raw" directives in the Python domain should then also support marking something as abstract.

The "obvious" way to mark this up would be to prepend "abstract" in the same way as "class" is prepended to class definitions. This, I recall, is effectively what the sphinx extension for zope.interface does with interfaces. An argument against it might be that "abstract" is neither a keyword nor the way something is marked abstract in Python.

Another idea might be to make it look decorator-like and prepend a line like `[abstract](https://bitbucket.org/abstract)` or somesuch.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/744
- Originally reported by: Dag Odenhall
- Originally created at: 2011-08-04T01:37:19.823

**Comment by shimizukawa** [comment]
_From Dag Odenhall on 2011-08-04 14:08:36+00:00_

> “An argument against it might be that "abstract" is neither a keyword nor the way something is marked abstract in Python.”

I overlooked how Sphinx already does this with classmethod/staticmethod, so a fake "abstract" keyword would be fine.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-22 10:05:49+00:00_

Patches are accepted :)

**Comment by aisthesis** [comment]
+1

**Comment by lukasjuhrich** [comment]
How would one go about representing this in `ReST`?

Classmethods/staticmethods are not a good comparison, because “being abstract” is a supplementary property. You can have abstract methods, classmethods, staticmethods, and even properties – and everything is realized by adding `@abstractmethod` as an innermost decorator. In fact, all it does is to [set the `__isabstractmethod__` attribute](https://github.com/python/cpython/blob/3.7/Lib/abc.py#L23).

To my shame, I've never written any class documentation myself (well, because autodoc exists), so I'm not aware of how one best modifies the syntax.

**Comment by lukasjuhrich** [comment]
I took a quick look at this. Is this a valid assesment of what would have to be done?

- [x] letting autodoc find out whether something is abstract (easy)
- [x] Finding out a good way to put this binary information into `rst` syntax
- [x] When parsing, passing this information to `sphinx.domains.python.PyClassmember` and turning it into something readable.
- [x] Testing, of course.

Would it be an idea to allow for an `:abstract:` option on the classmember directives and read this via the `option_spec` dict?

**Comment by lukasjuhrich** [comment]
> Patches are accepted :)

@birkenfeld I hope that's still true 7½ years later? ;-)

**Comment by tk0miya** [comment]
Added by #6365.
Thanks,
