### ISSUE TITLE
Captions & globbing not working with an autosummary TOC

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#7490]
**Describe the issue**

I am using Sphinx & autosummary to document a large number of submodules, and running into a headache trying to get autosummary to work. Any help would be greatly appreciated.

I would like to have multiple autosummary directives in my index.rst , and have them separated in the nav sidebar with occasional captions. However, I can't find a way to do this. The `caption` option does not seem to be accepted by the autosummary directive.

**To reproduce**

Here is a minimal example, assuming there are four submodules: module1, module2, module3 and module4.

I would like to summarise them with automodule, AND have them grouped them in the nav sidebar by various captions. Here is what I am trying; the "caption" option doesn't seem to work:

```
.. autosummary::
   :toctree: _autosummary
   :caption: Group A submodules

   module1
   module2
   
.. autosummary::
   :toctree: _autosummary
   :caption: Group B submodules

   module3
   module4
   etc
```

**Expected behaviour**

I would expect the captions "Group A modules" and "Group B modules" to appear in the navigation sidebar.

**Environment info**
- OS: Linux
- Python version: 3.7
- Sphinx version:  2.4.1
- Sphinx extensions:  autodoc, autosummary, napoleon

**Comment by tk0miya** [comment]
Good idea. I'll work on this.

I have only one question. Your example contains two `:caption:` options in one `autosummary` directive. Is this intended or typo? In my understanding, it should be only one, right?
```
.. autosummary::
   :toctree: _autosummary
   :caption: Group A submod
   :caption: Group B submodules

   module3
   module4
   etc
```

**Comment by ghost** [comment]
Yes sorry, that was indeed a typo. I've fixed the example. Thanks so much for the fast response!

I wonder, on a related note would it be possible to be able to pass the ‘glob‘ option as well? That would be super helpful for automatic documentation of a large number of modules!

**Comment by tk0miya** [comment]
Sorry, I did not mention about glob option. For now, I'd not like to implement it. Please tell me your situation in detail. How would you like to use if it exists? Anyway, it would be better to make another issue to discuss it.

**Comment by ghost** [comment]
OK, will do..

**Comment by emmanueljordy** [comment]
Dear,

I have a similar problem where I have a file named "module1.rst"  for a module with the following instructions therein

.. currentmodule:: long.path.to.module1

.. autosummary::
   :toctree: _autosummary
   :caption: This module summary
   
  module1

A path to the summary of module 1 appears in the toctree, however, the caption just does not appear anywhere. It is not pleasing visually since the title of the file generated with autosummary is too long e.g. long.path.to.module1.module1. I would like to use a caption to replace the automatic title generated by autosummary. Is there anyway I could do that please?

I have tried using "add_module_names = False" in conf.py, but this does not change the title of the file generated by autosummary, nor does this change the name that appears in the toctree. 

**Expected behaviour**

I would expect the caption "This module summary"  to appear in the navigation sidebar and not long.path.to.module1.module1

Environment info

OS: Windows
Python version: 3.7
Sphinx version: 3.5.4
Sphinx extensions: autodoc, autosummary, napoleon, coverage, viewcode


Thanks for your help!
