### ISSUE TITLE
Reimplement property object description for python

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#7523]
**Is your feature request related to a problem? Please describe.**
In Sphinx-2.1.0, we started to support property objects #6320. At that time, it is implemented as a kind of method. But we have some discussions #6785 and #7068 to change it to a kind of attribute.
Finally, we agreed to implement it as an independent type: property. At same time, it is very similar to attributes. So we also support to refer it as attributes.

**Describe the solution you'd like**

* Allow to describe property object via `py:property` directive.
* Allow to refer a property object via `py:prop` and `py:attr` role.
* The autodoc extension should render properties as `py:property` directive.
* The napoloen extension should render properties as `py:property` directive.
* The intersphinx extension should support to refer remote properties via `py:prop` and `py:attr` role.
* The autosumary extension generate a document that properties and attributes are shown in the same headings by default

**Comment by johann-petrak** [comment]
Not sure if this is the right place, but I think it would be extremely helpful if the generated documentation could not just show THAT something is a property, but also, indicate whether it has got a getter, setter, deleter. 
This is important information for API users and manually documenting this is unnecessary (since it is easy to figure out automatically) and error prone (especially if e.g. a setter is added, since this would need to get documented in the getter, by convention). 
One way to do this would be to show something like property/get/set or property/set/delete in the generate documentation.

**Comment by tk0miya** [comment]
I think indicating a property supports getter, setter and deleter is another topic. So I just made #9087 to support it.

**Comment by tk0miya** [comment]
I think this has been almost implemented. So I will try to confirm it works in the 4.0 later.
