### ISSUE TITLE
Napoleon: Add `Keyword Parameters` section header

### ISSUE THREAD

**Issue by zhustec** [sphinx-doc/sphinx#7609]
For ordinal parameters, there has:

* `Args`
* `Arguments`
* `Parameters`

But for keyword arguments, there only has:

* `Keyword Args`
* `Keyword Arguments`

which `Keyword Parameters` is missing.

**Comment by tk0miya** [comment]
I heard the name for the first time. Is it commonly used?

**Comment by picnixz** [comment]
More generally, I think it could be fine if we had our *own* section headers. Because sometimes, you want a specific section header and you don't want to use, say `.. rubric::`. So having a configuration value for custom section headers would also be an alternative.

**Comment by electric-coder** [comment]
> (...) having a configuration value for custom section headers would also be an alternative.

Now that I remember, there's [`napoleon_custom_sections`][1] and it works reasonably well, except for some cases where the sections are special cased like `Returns:`. As an alias it doesn't always work.

[1]: [napoleon_custom_sections](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#confval-napoleon_custom_sections)

**Comment by picnixz** [comment]
Ah yes, I forgot about this one. Sorry, what I meant (but I didn't say it at all) is to allow users to *automatically* have their own sections. For instance, when you want to write some 'title-like' section, you generally use `.. rubric::` if it's inside the docstring. But I always wanted an option to automatically pick up header-like strings without telling me "it's not a valid section". But that's actually a separate issue so maybe we could close this one since we have a workaround?

**Comment by electric-coder** [comment]
> we could close this one since we have a workaround?

I agree this one can be closed as a workaround has been identified.
