### ISSUE TITLE
introduce directive for type alias

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [sphinx-doc/sphinx#7896]
There's no clear way to document a type alias as distinct from a module-level variable

I suggest adding a `:type:` directive that distinguishes an alias, like
```
DEFAULT_NUMBER_FACTORY = int
""" :var: zero-argument constructor for default numbers. """

Number = int
""" :type: Type used for numbers. """

def foo(a: Number) -> None:
    ...
```

It's possible we could use the fact that [type aliases aren't meant to have annotations themselves](https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases). I'm not sure which is better.

**Comment by tk0miya** [comment]
At present, [PEP-613 (Explicit Type Aliases)](https://www.python.org/dev/peps/pep-0613/) has been discussed. So we should follow the spec in the future.

BTW, the PEP will be introduced since python-3.10 or later (maybe). It means we don't have a way to indicate one variable is a kind of type-alias until then. I understand a need for the workaround to do that.

Pros.
* We can indicate a variable is a type-alias.
* We can indicate it before PEP adopted.

Cons.
* Sphinx adopts a non-standard way as a workaround.
* We need to keep backward compatible for a while even after PEP adopted.

**Comment by joelberkeley-secondmind** [comment]
@tk0miya those are some good points. I assume there will be a desire to keep compatibility with <=3.9 for a long while now, esp since 3.9 isn't released yet. Is it therefore feasible to wait for that PEP?

Can we draw conclusions from sphinx's experience with the `:rtype:` directive, which is no longer needed with full type hinting in 3.6?

**Comment by tk0miya** [comment]
>Is it therefore feasible to wait for that PEP?

This is the first request for type-alias. So nobody in a hurry now as far as I know. So we can wait for the release of the PEP.

In addition, there are no special representation for type-aliases. So we need to consider how Sphinx represent them in output.

>Can we draw conclusions from sphinx's experience with the :rtype: directive, which is no longer needed with full type hinting in 3.6?

If I can design autodoc from scratch now, I'll drop the `:rtype:` field from spec because it is duplicated with the type annotation. (It might be useful for C extensions. So I can't say I'll surely drop it).

**Comment by patrick-nicodemus** [comment]
I would like this and I look forward to seeing it in a future release!
