### ISSUE TITLE
"Include file '...' not found or reading it failed" should be an error, not a warning

### ISSUE THREAD

**Issue by ezyang** [sphinx-doc/sphinx#7929]
**Describe the bug**
When I have an invalid `literalinclude` directive, the error saying that it could not be found is only a warning. It should be an error (or there should be a way to make it an error, without making all other warnings, many of which may be benign, into errors).

**To Reproduce**
Steps to reproduce the behavior: make a rst file with a `.. literainclude:: asfkdjsfkdjafkds`.

**Expected behavior**
Build fails with error

**Comment by tk0miya** [comment]
Sphinx raises an error only if it can't build the document anymore. So it emits a warning when the target file not found on including. It is the same as `image` directive does not found an image file. Please use `-W` option for `sphinx-build` command. It will stop the build immediately when any warnings detected.

**Comment by ezyang** [comment]
I have an existing doc codebase that has a ton of warnings, and I cannot easily fix them all. It would be very helpful to fix incrementally by Werror'ifying only the most major warnings first, and then gradually improving things. For example, https://github.com/sphinx-doc/sphinx/issues/4770 warnings are spurious and yet this would hard block my project from turning on `-W`

**Comment by tk0miya** [comment]
It would be nice if we could promote warnings to some errors with priority. But it's difficult to change the error level of warnings from basic directives of reST because they are implemented in docutils (a base library of Sphinx), not in Sphinx. I know we can change only the error level of `literalinclude` directive because it is Sphinx's. But I don't think it is not worthy to change it only.

Just FYI: You can change the error level of the directive locally via modifying this code to `document.reporter.error(...)`.
https://github.com/sphinx-doc/sphinx/blob/5da54cc035937a03126354d6a50ef75257650719/sphinx/directives/code.py#L467
