### ISSUE TITLE
An uninitialized annotated instance variable is not documented when `:inherited-members:` option given.

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#8030]
**Describe the bug**
An uninitialized annotated instance variable is not documented when `:inherited-members:` option given.

**To Reproduce**

```
# example.py
class Foo:
    """docstring"""

    var1: int
```
```
# index.rst

.. automodule:: example
   :members:
   :undoc-members:
   :inherited-members:
```

Note: When I don't give `:inherited-members:` option, it is shown correctly.

**Expected behavior**
The document is documented even if `:inherited-members:` option is given.

**Your project**
No

**Screenshots**
No

**Environment info**
- OS: Mac
- Python version: 3.8.2
- Sphinx version: 3.x HEAD
- Sphinx extensions: sphinx.ext.autodoc

**Comment by kotval** [comment]
Pull request #8031 does not solve this issue in all cases. In particular, if the type hint is not primitive, but instead modifies the class mro, the fix in that request still does not solve the problem. Cannot disclose code to cause this, but the fix should be uncontroversial as it is to change: [sphinx/ext/autodoc/__init__.py around line: 669](https://github.com/sphinx-doc/sphinx/blob/9cf28264917800534e56a92c1fa5c1196c73e73f/sphinx/ext/autodoc/__init__.py#L669) so that:

```python
def is_filtered_inherited_member(name: str) -> bool:
            if inspect.isclass(self.object):
                for cls in self.object.__mro__:
                    if cls.__name__ == self.options.inherited_members and cls != self.object:
                        # given member is a member of specified *super class*
                        return True
                    elif name in cls.__dict__:
                        return False
                    elif name in self.get_attr(cls, '__annotations__', {}):
                        return False

            return False
```
instead does not rely on a call to `get_attr` that may be mutated by changing the mro. I suggest the following instead:

```python
def is_filtered_inherited_member(name: str) -> bool:
            if inspect.isclass(self.object):
                for cls in self.object.__mro__:
                    if cls.__name__ == self.options.inherited_members and cls != self.object:
                        # given member is a member of specified *super class*
                        return True
                    elif name in cls.__dict__:
                        return False
                    else:
                        try:
                            if name in self.get_attr(cls, '__annotations__', {}):
                                return False
                            else:
                                return True
                        except:
                            return False

            return False
```
I can give more exposition if this seems odd, but it would be somewhat time consuming.

**Comment by tk0miya** [comment]
@kotval Could you make a pull request with a test case? Then I'll merge it.
