### ISSUE TITLE
The :index: role and the glossary generate duplicate entries in the LaTeX index

### ISSUE THREAD

**Issue by ddemange** [sphinx-doc/sphinx#8214]
**Bug**
A document contains both : 
- a glossary with an entry named "term"
- some text, in which I index an occurrence of the word "term" through the role `` :index:`term` ``

The output PDF index contains a duplicate entry for the word "term":
- one entry with a page number of the glossary entry
- one entry with a page number of the occurrence in the text of the document
Below is a snapshot :
![image](https://user-images.githubusercontent.com/12810126/93342206-587d9d00-f82f-11ea-9adc-3498e9547bf1.png)

**Expected behavior**
The index should contain only one entry for the word "term", with 2 page numbers pointing to the occurrences of that word.
Expected output index :
![image](https://user-images.githubusercontent.com/12810126/93342747-fcffdf00-f82f-11ea-930f-af04b4b1607b.png)

**Possible cause**
Looking at the generated `.idx` file:
```
\indexentry{term@\spxentry{term}|hyperpage}{1}
\indexentry{term@\spxentry {term}|hyperindexformat{\spxpagem}}{3}
```
An extra whitespace between the command `\spxentry` and the argument `{term}` is generated from the glossary entry. 
Removing that extra whitespace solves the problem.

**Environment info**
- OS: Mac 10.13.6
- Python version: 3.8.5
- Sphinx version: 3.2.1
- Sphinx extensions:  none
- Extra tools: none

**Comment by ddemange** [comment]
The problem would be due to the `\index` command doing tokenization of its argument.
See: https://tex.stackexchange.com/a/145326

The `:index:` role in the main body of the document is generating 
`\index{term@\spxentry{term}}`

while the glossary entry is generating 
`{term\index{term@\spxentry{term}|spxpagem}\phantomsection\label{\detokenize{glossary:term-term}}}`.

**Comment by jfbu** [comment]
Thanks for reporting and analysis.

Using `latex_use_xindy = True` appears to solve this. There is only one term in the index. If both indexed term and glossary are on the same page, there is only one page link. Else there are two page links.

```rst
An indexed :index:`term` and :index:`another` one.

.. glossary::

   term
      will it generate a duplicate entry?


.. raw:: latex

   \clearpage

.. glossary::

   another
      will it generate a duplicate entry?

```

conf.py:

```
latex_use_xindy = True
```

we will have

```
\indexentry{term@\spxentry{term}}{1}
\indexentry{another@\spxentry{another}}{1}
\indexentry{term@\spxentry {term}|spxpagem}{1}
\indexentry{another@\spxentry {another}|spxpagem}{2}
```

but the extra spaces are fine with xindy.


![Capture d’écran 2021-01-26 à 17 29 59](https://user-images.githubusercontent.com/2589111/105874160-9324ec80-5ffc-11eb-8f82-27138c181a6e.png)


I will investigate if a not too complicated work-around is feasible for the makeindex route, else the fix will be to use xindy as above (testing report welcome).

edit: if testing with then without then with xindy, always do `make clean` because the left-over auxiliary files in latex build repertory break the  build when toggling the config.
