### ISSUE TITLE
make latexpdf fails when using literal-blocks and fancybox package

### ISSUE THREAD

**Issue by zoranbosnjak** [sphinx-doc/sphinx#8339]
**Describe the bug**

`\usepackage{fancybox}`, together with literal block fails to compile with `make latexpdf`.
Each component alone (fancybox or literal block) works fine.

**To Reproduce**

* start new project (all defaults):
```
sphinx-quickstart
```

* add to the end of the `conf.py` this snippet:
```python
latex_elements = {
    'preamble': r'''
\usepackage{fancybox}
'''
}
```

*  add to the end of the `index.rst` this snippet (taken from the manual):

```
This is a normal text paragraph. The next paragraph is a code sample::

   It is not processed in any way, except
   that the indentation is removed.

   It can span multiple lines.

This is a normal text paragraph again.
```

* build project
```
make latexpdf
```

**Expected behavior**
Successfull build.

**Screenshots**
Build fails with the output:
```
...
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.116 \end{sphinxVerbatim}
                          
? 
```

**Environment info**
- OS: Linux ubuntu 20.04 with nix package manager
- Nix package set: release-20.09, rev "cc9ec4dafad5c0c454ce95a2f06b257b762fd688"
- Python version: 3.8.5
- Sphinx version: 3.2.1
- Sphinx extensions:  none
- Extra tools: pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/NixOS.org)

**Additional info**
This problem was not present on old version of sphinx-doc, for example, this combination is OK:
- Python version: 3.6.6
- Sphinx version: 1.7.9
- pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/NixOS.org)

**Comment by jfbu** [comment]
Sorry for late. Thanks for detailed report. I removed the bug label but maybe I will add it again. The problem originates in the fact that `fancybox` has its own definition of Verbatim. The package `fancyvrb` was extracted from `fancybox` (same author originally, this is long time ago more than 15 years). The same code however is named slightly differently in the two packages.

Problem is that Sphinx after loading `fancyvrb`, stores the meaning of two of its crucial macros this way:
```latex
\let\OriginalVerbatim   \Verbatim
\let\endOriginalVerbatim\endVerbatim
```

Then if you add loading of `fancybox` it will have its own definition of `\Verbatim/\endVerbatim` and the original ones do not work anymore because of some changes in some other support macros.

Problem is that in our code we use `\OriginalVerbatim` and `\endOriginalVerbatim`. This is because formerly prior to Sphinx 1.5, Sphinx redefined the `\Verbatim`, which it does not since 1.5, and some extension needed `\OriginalVerbatim` macros for own hacking. So we had to keep using them under these names.


Problem is that fancybox loading resutls into the fact that the old meanings of `\Verbatim/\endVerbatim` now fails and sphinx should really be using `\Verbatim` not `\OriginalVerbatim`.

To fix your issue, you have to thus either play some tricks to load fancybox prior to  sphinx.sty:

```
latex_elements = {
    'passoptionstopackages': r'\usepackage{fancybox}',
#   'preamble': r'''
# \usepackage{fancybox}
# '''
}
```

or to do the `\let` from `sphinx.sty` latex code again after loading `fancybox`:

```
latex_elements = {
#    'passoptionstopackages': r'\usepackage{fancybox}',
    'preamble': r'''
\usepackage{fancybox}
\let\OriginalVerbatim\Verbatim
\let\endOriginalVerbatim\endVerbatim
'''
}
```
(not tested fully, but it worked with your example)

I think we should at next major release stop defining these `\OriginalVerbatim` things and let sphinx.sty  only use `\Verbatim`, `\endVerbatim`.

**Comment by jfbu** [comment]
Related https://github.com/sphinx-doc/sphinx/issues/2698.

Checking now I see no OriginalVerbatim in spatialaudio/nbsphinx, they were removed at https://github.com/spatialaudio/nbsphinx/pull/218

ping @mgeier, can you confirm we can get rid of `\OriginalVerbatim` definition by Sphinx latex code?

there is some interest in the fact that Sphinx uses an alias for `\Verbatim` as it provides a hook point, but as this issue demonstrates it has also a disadvantage. An alternative would be for sphinx.sty to do:

```latex
\def\OriginalVerbatim{\Verbatim}
\def\endOriginalVerbatim{\endVerbatim}
```

This would fix this issue.

On the other hand now looking at the pdf output, I see that loading `fancybox` after `sphinx.sty` ruins all the Pygments syntax high-lighting and the line wrapping, so my advice

```
latex_elements = {
#    'passoptionstopackages': r'\usepackage{fancybox}',
    'preamble': r'''
\usepackage{fancybox}
\let\OriginalVerbatim\Verbatim
\let\endOriginalVerbatim\endVerbatim
'''
}
```

does NOT work (even with `\OriginalVerbatim` defined with `\def` not `\let`), only

```
latex_elements = {
    'passoptionstopackages': r'\usepackage{fancybox}',
#   'preamble': r'''
# \usepackage{fancybox}
# '''
}
```

does work (and workss also with the `\def`).

So one MUST load `fancybox` very early, it is only way even if Sphinx used `\def`.

**Comment by jfbu** [comment]
Finally, this looks to me more like a documentation issue on Sphinx level. I will keep the `\OriginalVerbatim` as hook points, but using `\def` which allows people hacking into `\Verbatim` itself. Will make a PR for 3.x, this is no breaking change.

No using `\def` brings nothing really needed. And did not solve this issue, because there are too many things redefined by `fancybox`. So not changing anything to sphinx.sty LaTeX package macros.

**Comment by mgeier** [comment]
> ping @mgeier, can you confirm we can get rid of `\OriginalVerbatim` definition by Sphinx latex code?

Thanks for the ping! I can confirm that `nbsphinx` doesn't use and doesn't need `\OriginalVerbatim` any more.

I have no opinion on whether it should be removed from Sphinx, I cannot foresee what consequences that might have.

But I'm happy to test any related PRs!

**Comment by jfbu** [comment]
@mgeier thanks for the quick confirmation. I had pinged you in a characteristically too hurried way, because as I discovered later on, leaving `fancybox` decide after sphinx loading what `\Verbatim` did only superficially fixed the issue. Due to other changes caused by `fancybox`, nothing of the Sphinx syntax highlighting and line wrapping survived, so the only way is for `fancybox` to be loaded before `fancyvrb`. As a result I opted for very conservative approach #8724 of not changing anything but our docs... and whether to define `\OriginalVerbatim` with `\let` or `\def` is irrelevant anyhow if the main rationale to keep it is to help potential entrypoints at innermost of sphinxVerbatim without the hacker having to touch `\Verbatim` itself. BIg tempest in a cup of tea here! So we keep as is for time being.

**Comment by jfbu** [comment]
Here is a LaTeX only demo of the incompatibility between fancybox and fancyvrb, for the record. I will report to fancyvrb maintainer in order for documentation to mention it.

```latex
\documentclass{article}

%\usepackage{fancybox}% ok
\usepackage{fancyvrb}
\usepackage{fancybox}% NOT OK : commandchars option ignored

% Copied over directly from fancybox documentation
\newenvironment{FramedVerb}%
       {\VerbatimEnvironment
         \begin{Sbox}\begin{minipage}{5cm}\begin{Verbatim}}%
       {\end{Verbatim}\end{minipage}\end{Sbox}
         \setlength{\fboxsep}{8pt}\fbox{\TheSbox}}

\begin{document}

\begin{FramedVerb}[commandchars=\\\{\}]
  if \textbf{ foo } \textit{ bar } fi
\end{FramedVerb}

\end{document}
```

With fancybox loaded after fancyrvb, there is no highlighting inside the box, everything inclusive of the macro names appear verbatim rather than being executed.
