### ISSUE TITLE
code directive with single backslash character not interpreted as expected

### ISSUE THREAD

**Issue by AmosEgel** [sphinx-doc/sphinx#8396]
I try to display a code directive including only a single backslash character.

When I try

```
:code:`\`
```

the code block is not rendered at all: 
![grafik](https://user-images.githubusercontent.com/16704045/98527958-f152f680-227b-11eb-9607-23820dbdcabb.png)

When I try

```
:code:`\\`
```

I get a code block with two backslashes:
![grafik](https://user-images.githubusercontent.com/16704045/98528026-04fe5d00-227c-11eb-9716-efb4041db834.png)

I don't know if this is a bug or the intended behaviour ... but I'd expect that the first of the above variants should work.

**Screenshots**

**Environment info**
- OS: Windows
- Python version: WinPython 3.7.4
- Sphinx version: 3.0.3

**Comment by kai687** [comment]
Did you try a space between the backslash and the closing backtick? 

`:code:\ ` works. If I enter your version without the space, this is the warning message I see:

```
Inline interpreted text or phrase reference start-string without end-string.
```

The backslash in the directive _escapes_ the character, to prevent the 'special' meaning of the backtick character as beginning and end of an interpreted text role. Otherwise, you would not be able to render the single backtick character inside interpreted text roles.

This role comes from docutils: https://docutils.sourceforge.io/docs/ref/rst/roles.html#code

**Comment by AmosEgel** [comment]
Then, it seems not to be possible to obtain a code block with a single backslash character, right?
Your suggestion with the additional space character works and I can live with that. Thanks!

**Comment by tk0miya** [comment]
Yes, it seems docutils (original reST implementation) does not support a code role with a single backslash character.
```
$ echo ':code:`\\\\`' | rst2html.py
(snip)
<body>
<div class="document">


<p><code>\\</code></p>
</div>
</body>
</html>
```

If you'd like to improve this, please post a patch to docutils project. Thanks :-)

@kai687 Thank you for your help :-)
