### ISSUE TITLE
Newest docutils (v0.17) breaks rendering

### ISSUE THREAD

**Issue by kevinzakka** [sphinx-doc/sphinx#9061]
It seems the newest docutils has broken html rendering in a few places. I'm attaching screenshots showing the output of `make html` with 0.16 and comparing it to 0.17.

**Screenshots**
<img src="https://user-images.githubusercontent.com/10518920/113529642-cfcf1000-9578-11eb-8160-3701d5cc8a59.png" height="200">
<img src="https://user-images.githubusercontent.com/10518920/113529649-d198d380-9578-11eb-8749-94c846bce3fa.png" height="200">

**Your project**
https://github.com/kevinzakka/torchkit

**Environment info**
- OS: [e.g. mac OS]
- Python version: [e.g. 3.8/3.9]
- Sphinx version: [e.g. 3.5.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc]

**Comment by kevinzakka** [comment]
Oops, I missed https://github.com/sphinx-doc/sphinx/pull/9059 .. Closing this for now!

**Comment by mgeier** [comment]
This should fix the issue: #9053.

**Comment by rkdarst** [comment]
list items `li` in unordered lists `ul` is also broken (bullet point ::marker are missing).  docutils!=0.17 also fixes it for me.  I haven't dug much deeper yet.

**Comment by mgeier** [comment]
@rkdarst I cannot reproduce the problem. Can you please create a new issue for this, ideally with example reST code and a screenshot? Please also specify which HTML theme you are using.

**Comment by rkdarst** [comment]
You are right, I could only reproduce it in sphinx_rtd_theme, not the default Sphinx theme.  I filed the issue here: https://github.com/readthedocs/sphinx_rtd_theme/issues/1115  .  Reproducing my issue can be found in that issue.

I haven't dug deeper to see if there could be anything else to do in Sphinx itself, but browsing sphinx_rtd_theme's docs I don't see anything obvious.  I guess there is possibility that each theme needs to update some things, but I know nothing about that so far.
