### ISSUE TITLE
Search engine returns 404 links or is hanging forever for sphinx > 2.4.4 on scikit-image

### ISSUE THREAD

**Issue by sciunto** [sphinx-doc/sphinx#9068]
**Describe the bug**

Some details are available in this issue: https://github.com/scikit-image/scikit-image/issues/4647

For our last released, we banned sphinx version > 2.4.4 because we had failures with the search engine. At that time, the original discussion indicates that we experienced 404 errors on the links returned by the search engine. My last test shows that the search engine is hanging forever, either on our CI tools or on my machine.

I looked in the version changes and also in the bug tracker. An issue caught my attention: https://github.com/sphinx-doc/sphinx/pull/7192 However, it is unclear to me whether this is relevant or not, this is beyond my expertise.

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/scikit-image/scikit-image.git
$ cd scikit-image
$ pip install -r requirements/build.txt
$ pip install -r requirements/default.txt
$ pip install -r requirements/docs.txt
$ cd docs
$ make html
```

**Comment by tk0miya** [comment]
It seems the custom theme of scikit-image does not load `language_data.js`. Please compare these files.
https://github.com/scikit-image/scikit-image/blob/main/doc/source/themes/scikit-image/search.html#L12-L15
https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/search.html#L12-L16

I propose you inherit `search.html` instead of `layout.html` to create a custom `search.html`.

**Comment by sciunto** [comment]
many thanks for helping on this @tk0miya Your help is very appreciated. Our search engine seems to be working with the last version now. I'm closing this issue.
