### ISSUE TITLE
Config to add JS/CSS to all generated HTML pages

### ISSUE THREAD

**Issue by humitos** [sphinx-doc/sphinx#9115]
**Is your feature request related to a problem? Please describe.**

After https://github.com/sphinx-doc/sphinx/pull/8631 was merged, JS/CSS files for MathJax are only added to those pages that contains math formulas. This is not a problem unless you want to embed the content of one of those pages where the JS/CSS are included from a different page.

This problem is clear on my extension [`sphinx-hoverxref`](https://sphinx-hoverxref.readthedocs.io/) that shows a tooltip with the content of the linked page when hovering over a link. Example: if you hover on "tooltip with Mathjax" in https://sphinx-hoverxref.readthedocs.io/en/sphinx-35/usage.html#tooltip-with-mathjax you won't see the MathJax rendered properly inside the tooltip

![Screenshot_2021-04-19_11-02-47](https://user-images.githubusercontent.com/244656/115211436-d96f8080-a0ff-11eb-80dc-ee50e6674bed.png)

and an error in the console "Not triggering MathJax because it is not defined". This is because MathJax is not included in `usage.html` page but it's included in target page (`mathjax.html`)

_Note that I'm mentioning the problem only with MathJax for now since it's a known extension that it's using this new feature, but this applies to all the extension that start including the JS/CSS only on pages where the extension is present_

**Describe the solution you'd like**

I think a config to force the old behavior that includes all the JS/CSS in all the pages could work. I know this has some drawbacks, but as far is optional, I think it's good.

**Describe alternatives you've considered**

1. `sphinx-hoverxref` uses an endpoint from Read the Docs' API to get the content to embed in the tooltip. We are discussing if it's possible to return `"extras": ["mathjax.js", "mathjax.css"]` together with the content to be included so the JS client knows it has to include these assets before rendering the content. See https://github.com/readthedocs/readthedocs.org/pull/8039#discussion_r604449923
2. Another option could be to detect from the Sphinx extension "what are the assets required in the target page and add them into this page as well". Note that this won't work when using intersphinx.

**Additional context**

Reference: https://github.com/sphinx-doc/sphinx/pull/8631#issuecomment-821162722
Downstream issue: https://github.com/readthedocs/sphinx-hoverxref/issues/119

**Comment by tk0miya** [comment]
My thought:

* Only extensions would like to enable JS/CSS in the all pages. Users would not. So it's better to provide an API to switch the behavior instead of a configuration.
* It's difficult to control the behavior by sphinx-core because extensions can control the visibility of the JS/CSS on their code, not sphinx-core.
  Here is an example of mathjax's case. It enables JS entry only if the document contains equations at least one.
  https://github.com/sphinx-doc/sphinx/blob/4e9d1553968653df6699b20afc22b73eb3280185/sphinx/ext/mathjax.py#L82-L98
* So the following mechanism is needed to resolve this problem:
  - A new API like `app.enable_html_assets_in_all_pages()` to enable assets in all pages.
  - Extensions should refer the result of the API to control when they install assets in the specific pages.

**Comment by mgeier** [comment]
BTW, a similar thing happens if there is ``:math:`a+b` `` in a page title, it will *not* be displayed in the TOC of other pages (if those don't use any math on their own).

I'm not sure if this should be a separate issue.
This is something that happens in Sphinx core, without extensions (except for `sphinx.ext.mathjax`).

**Comment by tk0miya** [comment]
It's a different topic. And it was already posted as #8139.

**Comment by humitos** [comment]
Thanks for sharing your thoughts @tk0miya! I think adding something like `app.enable_html_assets_in_all_pages()` is a good path forward. I understand the result of that would be able to be changed by _one_ extension so all the other ones follow that rule, right? I imagine that if any extension defines `enable_html_assets_in_all_pages = True` every other extension will add assets to all the pages _even_ if there is one extension that defines `enable_html_assets_in_all_pages = False`. So, `True` takes precedence.

**Comment by humitos** [comment]
@tk0miya I opened a PR with a proposal. Let's see if that's something similar to what you had in mind. Let me know 😄
