### ISSUE TITLE
svg graphics create error in pdflatex

### ISSUE THREAD

**Issue by craiq** [sphinx-doc/sphinx#9376]
**Describe the bug**
- svg graphics are not found / not supported when compiling with pdflatex
- creating html everything works flawless and svg graphics are visible
- those svg graphics are created with Inkscape
- manual adding usapackage svg did not help

**To Reproduce**
add svg figure in markdown file

````
```{figure} img/file.svg
Description
```
````

**Expected behavior**
Show svg graphic in pdf too

**Screenshots**
```
LaTeX Warning: File `{file}.svg' not found on input line 2219.


! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.2219 ...\sphinxincludegraphics{{file}.svg}

?
```

**Environment info**
- OS: Win 10
- Python version: 3.9.5
- Sphinx version: 4.0.2
- Sphinx extensions:  MyST, sphinx_material
- Extra tools: InkscapePortable 1.1

**Comment by mgeier** [comment]
You could use https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html.
But as noted there, a better option would be to use https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter, which in most cases leads to better image quality (because it doesn't rasterize the given SVG vector graphics).

I normally use `sphinxcontrib.rsvgconverter`. You'll need to install the program `rsvg-convert` for that, which is available via Debian/Ubuntu package `librsvg2-bin` and `conda` package `librsvg`.

**Comment by craiq** [comment]
Thank you very much! 
Setting this up without admin rights and windows I understood why this is not embedded ...

finally this saved me: https://sourceforge.net/projects/tumagcc/files/rsvg-convert-2.40.20.7z/download

**Comment by mgeier** [comment]
Good to know!

It should also be possible to install `conda` without admin rights.

A `librsvg` package seems to be available for Windows (64 bit): https://anaconda.org/conda-forge/librsvg.

But I'm not a Windows user, so I don't know if that actually works.
