### ISSUE TITLE
autosummary extension overrides `typing.TYPE_CHECKING` flag to False after other extensions set it to True

### ISSUE THREAD

**Issue by lmmx** [sphinx-doc/sphinx#9468]
### Describe the bug

The `autosummary` extension will override the `typing.TYPE_CHECKING` to False. I observed this when using the sphinx-autodoc-typehints extension (see [bug report 180](https://github.com/agronholm/sphinx-autodoc-typehints/issues/180))

### How to Reproduce

Add "sphinx.ext.autosummary" to the `extensions` list (before `"sphinx-autodoc-typehints"`) in your docs/conf.py and add a print statement for the `typing.TYPE_CHECKING` flag (compare before and after to see that it is switched off)

- Minimal reproducible repo to show this [here](https://github.com/lmmx/sphinx-type-annotations-demo).

```
git clone https://github.com/lmmx/sphinx-type-annotations-demo
cd sphinx-type-annotations-demo
pip install tox
pip install -e .[docs]
tox -e docs
```

This will build and report "typing.TYPE_CHECKING=True" in the output.

If you edit the extensions list in docs/conf.py to put "sphinx.ext.autosummary" at (the top of) the list, it will report "typing.TYPE_CHECKING=False" in the output, indicating that when Sphinx processes the code (the standard `sphinx-build` call) the constant is not set by the sphinx-autodoc-typehints module.

I can only assume this is because it is being overridden somehow by the autosummary extension, however I can't see the part of the extension which would achieve this. The extension does not import `typing.TYPE_CHECKING`, so it must be some sort of side effect.

- autodoc [does](https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/ext/autodoc/__init__.py) import `typing.TYPE_CHECKING` and autosummary [does](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autosummary/__init__.py) interact with that module, so I can vaguely see how it can happen
- However sphinx-autodoc-typehints does not have trouble alongside autodoc (as the name suggests)

### Expected behavior

When `typing.TYPE_CHECKING` is set to True in the sphinx-autodoc-typehints extension (when docs/conf.py contains `set_check_typing_flag = True`), I expect the `typing.TYPE_CHECKING` flag to be set to True when Sphinx passes over it. This does not happen when `"sphinx.ext.autosummary"` is in the extensions list.

### Your project

https://github.com/lmmx/sphinx-type-annotations-demo

### OS

Linux

### Python version

3.8

### Sphinx version

4.1.1

### Sphinx extensions

"sphinx.ext.autodoc", "sphinx.ext.autosummary", "sphinx_autodoc_typehints",

### Additional context

- Bug reported to `sphinx-autodoc-typehints` maintainer in [issue 180](https://github.com/agronholm/sphinx-autodoc-typehints/issues/180)

**Comment by tk0miya** [comment]
>I can only assume this is because it is being overridden somehow by the autosummary extension, however I can't see the part of the extension which would achieve this.

It's not so. autosummary does not touch `TYPE_CHECKING` at all. Simply, it's invoked before the constant is modified.

Both autosummary and sphinx-autodoc-typehints install handlers for the builder-inited events.
https://github.com/sphinx-doc/sphinx/blob/f9941b9402821de2d60c1e94f9ac5cf0379640d0/sphinx/ext/autosummary/__init__.py#L794
https://github.com/agronholm/sphinx-autodoc-typehints/blob/1b85ff5306f02985ab00c73b41504bb5b17943eb/sphinx_autodoc_typehints.py#L488

And these handlers are invoked in order of the `extensions` configuration. As a result, `set_check_typing_flag` feature of sphinx-autodoc-typhints extension will be invoked after autosummary if you put autosummary extension at the top of the list. As a trial, please put autosummary just after sphinx-autodoc-typehints. I guess everything works well as you expected.

To invoke the handler of sphinx-autodoc-typehints, please specify the priority of the handler. Since v3.0, `Sphinx.connect` API supports `priority` parameter to control the order of the event handlers: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.connect

**Comment by lmmx** [comment]
Ahhh, yes, I did not see any part of autosummary which appeared to touch `TYPE_CHECKING`.

As you suggest, lowering its priority resolves this bug by ensuring it runs first. Is there a suggestion for what this priority ought be? 499 is sufficient but I don't know if there is a recommendation when changing it? I'll suggest 400 would be reasonable.

I will take this back to the sphinx-autodoc-typehints bug tracker now, thanks very much.

**Comment by tk0miya** [comment]
Unfortunately, there is no standard for the priority because the priority system is too young. Only I can say is 1) default priority is 500, 2) the lower number is invoked faster. IMO, 400 is good :-)
