### ISSUE TITLE
Create Graphviz graphs from sphinx-apidoc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#953]
Hi,
I made (more than one month ago) a little patch (against the 24ad0c778dad commit) to implement a new commandline option of apidoc.py:

-G (--graph) will add the needed directives in conf.py and *.rst files to generate the inheritance graphs using graphviz ( 'patch' attached)

I tried to make a queue patch right here, but I think I did something wrong (I can't do a pull request), then I tried to post my patch in the google group (http://is.gd/92whft), but recieved no response.

Hope this helps.

PS: If I need to do something more to make your work easier, just tell me and I'll try to.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/953
- Originally reported by: Mark Caglienzi
- Originally created at: 2012-06-23T14:37:17.559

**Comment by electric-coder** [comment]
@AA-Turner I'm pretty sure this can be closed, because:

1. The simple [`.. inheritance-diagram::`][1] exists and works correctly.
2. Anything more elaborate can be done with [`sphinx.ext.graphviz`][2] and it comes with [`conf.py` options][3].

Reading the OP it doesn't seem like anything is missing. If additional functionality is needed it would be better to open a new FR to put things in the current context.

[1]: https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html#directive-inheritance-diagram
[2]: https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html#module-sphinx.ext.graphviz
[3]: https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html#confval-graphviz_dot
