### ISSUE TITLE
Nested ul list introduces unwanted dl / dt / dd.

### ISSUE THREAD

**Issue by kjcole** [sphinx-doc/sphinx#9766]
### Describe the bug

When attempting to get a nested list, Sphinx introduces a `<dl class="simple">` which messes with the vertical spacing, and a `<dd>` which messes with the horizontal spacing, both introducing unwanted whitespace.

### How to Reproduce

```
* This is the first outer list item
* This is the second outer list item
   * This is an inner list item
   * Another inner list item
* A third outer list item 
```
produces
```
<ul class="simple">
<li><p>This is the first outer list item</p></li>
<li><dl class="simple">
<dt>This is the second outer list item</dt><dd><ul>
<li><p>This is an inner list item</p></li>
<li><p>Another inner list item</p></li>
</ul>
</dd>
</dl>
</li>
<li><p>A third outer list item</p></li>
</ul>
```

### Expected behavior

```
<ul class="simple">
<li>This is the first outer list item</li>
<li>This is the second outer list item<ul>
<li>This is an inner list item</li>
<li>Another inner list item</li>
</ul></li>
<li>A third outer list item</li>
</ul>
```

### Your project

Attached minimal example broken.zip

### OS

Pop! OS 20.04 (approximately Ubuntu Linux 20.04)

### Python version

3.8.10

### Sphinx version

4.1.2

### Additional context

(In the full project, I'm using the cloud-sptheme theme, which makes the above look even more wrong, but it seems that both the paragraph tags and the definition list tags are semantically unwanted, unnecessary cruft -- though there may be some historical reason for having them.)

[broken.zip](https://github.com/sphinx-doc/sphinx/files/7406319/broken.zip)

**Comment by ghost** [comment]
Dear @kjcole

This is not a bug, neither in Sphinx nor in docutils.  (@ maintainer this issue can be closed; explanation of the observed behaviour follows) .

The thing is that your reStructuredText code is "malformed". It is valid reStructuredText code but it is not what you expect.

```
* This is the first outer list item
* This is the second outer list item
   * This is an inner list item
   * Another inner list item
* A third outer list item 
```

First, please note that sublists must be separated by by a blank lines above and below [1].

Also – and this one is important for reStructuredText – your indent must be correct. The indent for the second line must be **two** spaces and not three as in your code. This is because the "This" of "This is the second list item" starts at column 3 (=2 spaces of indent). Thus, for Sphinx/docutils/reStructuredText the second item of the bullet list has the form

```
XXXXX
 YYYYYY
 YYYYYY
```

which indeed is a definition list [2] (follow up lines are indented by some amount of space) and that definition list contains ``YYY...`` which in your example happens to be a (sub)list. This explains the behaviour you are observing.

The correct code for what you want to achieve would be

```
* This is the first outer list item
* This is the second outer list item

  - This is an inner list item
  - Another inner list item

* A third outer list item 
```

or when going into the extremes:

```
*       This is the first outer list item
*       This is the second outer list item

        - This is an inner list item
        - Another inner list item

*       A third outer list item 
```

Note the indent of the inner bulltet list matches up with the outer letters, it is however irrelevant whether it is 2 spaces or 100.
I also used a different bullet indicator, to visually separate the sublist but this is optional.

Bonus:

In the following I did not adjust the indent of the inner bullet list:

```
* This is the first outer list item
* This is the second outer list item

   * This is an inner list item
   * Another inner list item

* A third outer list item 
```

In this case the second item is parsed as

```
XXXXXXX

 YYYYY
 YYYYY

```

which is a paragraph (`XXXXX`) followed by a block quote [3] (the indented part) and the block quote contains the list.
Depending on the theme you are using, you might or might not see the block quote visually peeking out.

HTH

[1] https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#bullet-lists
[2] https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#definition-lists
[3] https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#block-quotes

**Comment by kjcole** [comment]
@latosha-maltba Oops. In the unforgettable words of [Emily Litella](https://en.wikipedia.org/wiki/Emily_Litella):

> _"Oh... Never mind."_

Thanks!
