### ISSUE TITLE
build failed on read the docs

### ISSUE THREAD

**Issue by cirospat** [sphinx-doc/sphinx#9783]
### Describe the bug

hi
this is the report https://readthedocs.org/api/v2/build/15104921.txt 
I received from read the docs (build failed).

I'm not a skylled tech and I'd like to understand what kind of measures it need to be activate in order to solve the problem

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

https://readthedocs.org/projects/cirospat/builds/15104921/

### Screenshots

![image](https://user-images.githubusercontent.com/3757525/139054616-3f1d8173-deaf-45bc-9b55-ca3ea3a62b4d.png)

![image](https://user-images.githubusercontent.com/3757525/139055080-ca3b000b-89cc-4f85-8bb2-856f22cad74a.png)

### OS

Win

### Python version

3.7

### Sphinx version

1.8.5

### Sphinx extensions

import recommonmark from recommonmark.transform 
import AutoStructify

**Comment by joshuacwnewton** [comment]
We've run into this issue too for several projects. Here's a summary of the problem:

* The issue is due to the recent release of `docutils-0.18` (which is incompatible with Sphinx at the moment, see https://github.com/sphinx-doc/sphinx/issues/9777).
* Sphinx pins `docutils<0.18`, so you can avoid auto-installing `docutils-0.18` _if_ your Sphinx installation is up-to-date:
    https://github.com/sphinx-doc/sphinx/blob/2be9d6b092965a2f9354da66b645bf5ea76ce288/setup.py#L26
* However, if you're building on RTD, and your project was created prior to October 2020, _and_ you haven't explicitly specified a version of Sphinx to use, [RTD will default to `sphinx<2`](https://docs.readthedocs.io/en/stable/builds.html?highlight=october%202020#python).
* So, `sphinx<2` + `docutils-0.18` will be installed, causing the error.

You can pin `docutils<0.18`, but since Sphinx is already doing that (and will likely become compatible with 0.18 in the future), the solution we instead settled on was to pin a more recent version of Sphinx in our RTD requirements. Please refer to RTD's ["Reproducible Builds"](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html) page (and specifically the [pinning dependencies](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies) section) for more information on RTD's recommendations here.

----

EDIT: One additional note...

* If your project pins the version of `sphinx` using [`extras_require`](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) keyword in your `setup.py`, _and_
* In RTD you're installing your project via the [`python`](https://docs.readthedocs.io/en/stable/config-file/v2.html#python) keyword of your `.readthedocs.yaml` config file

Then you can also fix the problem by making sure you set [`extra_requirements`](https://docs.readthedocs.io/en/stable/config-file/v2.html#packages) key in your RTD config file.

**Comment by astrojuanlu** [comment]
This is an excellent summary, thanks @joshuacwnewton ! I'm going to copy it over to https://github.com/readthedocs/readthedocs.org/issues/8616

**Comment by astrojuanlu** [comment]
In any case, this is an exact duplicate of #9727
