### ISSUE TITLE
linkcheck reports failure for link to local file if anchor is included

### ISSUE THREAD

**Issue by arporter** [sphinx-doc/sphinx#9790]
### Describe the bug

linkcheck will now successfully check for links to local files, e.g.:

    (           psyir: line  341) ok        /home/me/Projects/PSyclone/doc/reference_guide/build/html/autogenerated/psyclone.psyir.symbols.html

 However, I have links to anchors within those files and if I include those then linkcheck reports a failure:

    (           psyir: line  341) broken    /home/me/Projects/PSyclone/doc/reference_guide/build/html/autogenerated/psyclone.psyir.symbols.html#psyclone.psyir.symbols.UnknownType - 

This link works fine in the generated html documentation.

### How to Reproduce

```
$ git clone https://github.com/stfc/psyclone
$ cd PSyclone
$ git checkout 1398_sphinx_linkcheck
$ pip install .[doc]
$ cd doc/reference_guide
$ make html
$ cd ../userguide
$ make linkcheck
$ Error reported to stdout



### Expected behavior

No errors should be reported by linkcheck.

### Your project

https://github.com/stfc/PSyclone

### Screenshots

_No response_

### OS

Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

4.2.0

### Sphinx extensions

'sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.coverage', 'sphinx.ext.imgmath', 'sphinx.ext.viewcode', 'sphinxcontrib.bibtex', 'psyclone.apilinks'

### Extra tools

_No response_

### Additional context

This is all to do with a chicken-and-egg problem in testing the links in documentation that links to other documentation (e.g. separate reference guide) which is built at the same time but only published to RTD when the PR is merged. Ideally I want a way to check that the links are valid without looking at RTD. To accomplish this I have a configurable link target that can either be RTD or the locally-generated version of the (various parts of the) documentation.

**Comment by francoisfreitag** [comment]
`linkcheck` interprets `/path/to/file#anchor` as a file path. A file could legitimately be named `file#anchor`. In that case, it would be expected that `linkcheck` verifies `file#anchor` exists, not that `file` exists and has `anchor` in its content.

Running `firefox "$(pwd)/file#anchor"` opens URL `file:///home/freitafr/dev/sphinx/file%23anchor`, so the anchor is escaped and not scrolled to. I don’t think `linkcheck` should be modified to check anchors on local filesystem links.

---
About your use case, what about serving the docs on localhost using e.g. the Python builtin webserver and linking to that instead of doing filesystem lookups?

**Comment by arporter** [comment]
Thanks for the response - I can see the problem. I hadn't thought about launching a local webserver but that seems like it might work provided GHA lets me do it. I'll do some investigating...
