### ISSUE TITLE
TypeError: argument to reversed() must be a sequence

### ISSUE THREAD

**Issue by RobH123** [sphinx-doc/sphinx#9811]
### Describe the bug

Build fails with above error when processing a .rst file. I'm a first-time ReadTheDocs user, but I couldn't find any help on where to find the error in my file.

### How to Reproduce

Not sure how long this file is kept for, but it's at https://readthedocs.org/api/v2/build/15164895.txt

### Your project

https://readthedocs.org/projects/gl-manual/builds/

### OS

n/a

### Python version

n/a

### Sphinx version

n/a

**Comment by latacita** [comment]
I get the same error. My project, hosted in Read The Docs, does not work anymore.

**Comment by astrojuanlu** [comment]
Different error message, but same root cause as #9810, #9809, #9727, #9788, readthedocs/readthedocs.org#8616 , readthedocs/readthedocs.org#8618, readthedocs/readthedocs.org#8640, readthedocs/readthedocs.org#8642. You can solve this by capping docutils to `<0.18` in your requirements. More information here: https://blog.readthedocs.com/build-errors-docutils-0-18/
