### ISSUE TITLE
Addind expand/collapse (+) symbol in content section for all sections

### ISSUE THREAD

**Issue by hashimx** [sphinx-doc/sphinx#9863]
Hi ,

In the documentation we have, only the latest viewed section has the expand/collapse (+) symbol, is it possible to have this symbol for all sections by default? 

![image](https://user-images.githubusercontent.com/38165007/142425608-682c7b41-9690-4b06-b3d7-f2c159eca213.png)

**Comment by mgeier** [comment]
This is a question regarding the HTML theme you are using, not about Sphinx itself.

Given the screenshot, I assume you are using https://github.com/readthedocs/sphinx_rtd_theme, so you should look there for answers.

However, I think I happen to know the setting you are looking for (because I've used it myself), just add this to your `conf.py`:

```python
html_theme_options = {
    'collapse_navigation': False,
}
```

See https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-collapse_navigation.

**Comment by hashimx** [comment]
Thank you for the resolution, it works just as I wanted :)
